### ISSUE TITLE
RuntimeError: Expected object of device type cuda but got device type cpu for argument #2 'mat1' in call to _th_addmm

### ISSUE THREAD

**Issue by jctaillandier** [joblib/joblib#1007]
Error saying that specific matrix is not in right device, although that matrix is generated by an object I passed in upstream, that is in cuda.

I am running on remote cluster, so might be a memory issue, but wanted to ask here in case.

```
Traceback (most recent call last):
  File "../gansan/Optimal.py", line 793, in <module>
    all_folds()
  File "../gansan/Optimal.py", line 756, in all_folds
    for fold_id in range(1, p.K_Folds + 1))
  File "/home/jct/.local/lib/python3.6/site-packages/joblib/parallel.py", line 1017, in __call__
    self.retrieve()
  File "/home/jct/.local/lib/python3.6/site-packages/joblib/parallel.py", line 909, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/jct/.local/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 562, in wrap_future_result
    return future.result(timeout=timeout)
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
RuntimeError: Expected object of device type cuda but got device type cpu for argument #2 'mat1' in call to _th_addmm
```
Where print statements confirmed to me that all that was passed in `Optimal.py` is pushed `.to(device)` and `device=cuda:0`.
joblib `v0.14.1`

**Comment by jctaillandier** [comment]
Rookie Mistake; Some variables weren't pushed to device
