### ISSUE TITLE
joblib doesn't propogate correct exception, raises SyntaxError instead

### ISSUE THREAD

**Issue by ariddell** [joblib/joblib#101]
Whereas multiprocessing propagates the RuntimeError: Error during user-specified initialization

joblib generates a very strange SyntaxError -- I have no idea how I could specify an encoding in a compiled extension!

    ======================================================================
    ERROR: test_user_init_unspecified (pystan.tests.test_problems.TestStanfit)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/abr/documents/pystan/pystan-ariddell/pystan/tests/test_problems.py", line 30, in test_user_init_unspecified
        pystan.stan(model_code=model_code, iter=10, chains=1, seed=2, data=data, init=[dict(mu=4)], warmup=0)
      File "/home/abr/documents/pystan/pystan-ariddell/pystan/api.py", line 321, in stan
        n_jobs=n_jobs, **kwargs)
      File "/home/abr/documents/pystan/pystan-ariddell/pystan/model.py", line 650, in sampling
        ret_and_samples = Parallel(n_jobs)(delayed(call_sampler_star)(args) for args in call_sampler_args)
      File "/home/abr/documents/pystan/pystan-ariddell/pystan/external/joblib/parallel.py", line 602, in __call__
        self.retrieve()
      File "/home/abr/documents/pystan/pystan-ariddell/pystan/external/joblib/parallel.py", line 480, in retrieve
        self._output.append(job.get())
      File "/usr/lib/python3.3/multiprocessing/pool.py", line 564, in get
        raise self._value
    nose.proxy.SyntaxError: invalid or missing encoding declaration for '/tmp/tmp5pc7xw/pystan/stanfit4anon_model_652395f2575ceb009e57546b592d498e.cpython-33m.so'

**Comment by lmjohns3** [comment]
I'm seeing a similar error with Python 3.4 and joblib+pandas, but I also don't have a minimal script that produces the error. I'll see whether I can post a small script soon.

**Comment by lmjohns3** [comment]
Here's a pretty simple example:

    import joblib
    import numpy as np
    import pandas as pd

    def remove():
        df = pd.DataFrame(np.random.randn(5, 3), columns=list('abc'))
        del df[['a', 'b']]

    joblib.Parallel(-1)(joblib.delayed(remove)() for _ in range(2))

The error without using joblib is:

```
Traceback (most recent call last):
  File "/tmp/error.py", line 9, in <module>
    remove()
  File "/tmp/error.py", line 7, in remove
    del df[['a', 'b']]
  File "/home/leif/.py/py3/lib/python3.4/site-packages/pandas/core/generic.py", line 1307, in __delitem__
    self._data.delete(key)
  File "/home/leif/.py/py3/lib/python3.4/site-packages/pandas/core/internals.py", line 2907, in delete
    indexer = self.items.get_loc(item)
  File "/home/leif/.py/py3/lib/python3.4/site-packages/pandas/core/index.py", line 1402, in get_loc
    return self._engine.get_loc(_values_from_object(key))
  File "pandas/index.pyx", line 134, in pandas.index.IndexEngine.get_loc (pandas/index.c:3812)
  File "pandas/index.pyx", line 136, in pandas.index.IndexEngine.get_loc (pandas/index.c:3478)
TypeError
```

**Comment by danishabdullah** [comment]
+1. Just ran into this issue with pandas.

**Comment by amueller** [comment]
this looks to be related to https://github.com/scikit-learn/scikit-learn/issues/4664

**Comment by amueller** [comment]
Simple scikit-learn example:
```python
from sklearn.svm import SVC
from sklearn.grid_search import GridSearchCV
from sklearn.datasets import load_iris

iris = load_iris()

tuner = GridSearchCV(estimator=SVC(), 
                     param_grid={"kernel": ["foo"]},
                     scoring="f1",
                     n_jobs=3)

tuner.fit(iris["data"], iris["target"])
```

**Comment by amueller** [comment]
ping @ogrisel @lesteve ?

**Comment by lesteve** [comment]
I can reproduce the problem with @lmjohns3 and @amueller snippets above, I'll try to take a look in the upcoming days.
