### ISSUE TITLE
C++ function cannot be converted to a Python object for pickling

### ISSUE THREAD

**Issue by monchin** [joblib/joblib#1024]
Hello, I tried to use `joblib`, but have got an error.
I have some c++ codes:
```C++
// a.h
# pragma once
class A{
public:
    A() ;
    int a(int, int);
    ~A();
}
```
```C++
// a.cpp
#include "a.h"
A::A() {};
int A::a(int b, int c) { return b + c; }
A::~A() {};
```
And I wrote a python wrapper by Cython following [this tutorial](https://cython.readthedocs.io/en/latest/src/userguide/wrapping_CPlusPlus.html), naming the python class `A_`.
Now, I would like to run `A_.a` function several times parallelly, and I want to use `joblib`, so I write:
```python
# test.py
from A import A_
from joblib import Parallel, delayed
def test():
    res = Parallel(n_job=6)(delayed(A_().a)(1, 2) for _ in range(6))
    return res
if __name__ == "__main__":
    test()
```
Then error occurs:
`TypeError: self.Aclass cannot be converted to a Python object for pickling`
`self.Acalss` is defined in `cdef class A_` in `A.pyx`,  no matter I use `cdef A Aclass` or `cpdef A Aclass`, the same error occured.
So is there any way I can pickle C++ functions wrapped by cython?
Thank you!

**Comment by ogrisel** [comment]
I would have expected joblib (actually its loky backend) to pickle by name, that is reimport the function in the child processes instead of try to pickle it as a dynamically defined function.

Maybe the wrapper does not properly generate the `__qualname__` and  `__module__` attributes where loky would naturally expect them?

Can you please update the description of your issue to include the full traceback? Also can you tell us the values of the `__class__`, `__module__` and `__qualname__` of `A_` and `A_.a` when those attributes are present?

As a workaround, you can either (or both):

- tell Cython to release the GIL when calling the C++ method and then use `Parallel(n_jobs=6, backend="threading")` instead of the default process-based backend: this will the most efficient way to leverage multiple CPU cores on a single machine.
- wrap you native method in a simple Python shim and pass the Python function to `delayed` instead of  `A_.a` directly.

**Comment by monchin** [comment]
> I would have expected joblib (actually its loky backend) to pickle by name, that is reimport the function in the child processes instead of try to pickle it as a dynamically defined function.
> 
> Maybe the wrapper does not properly generate the `__qualname__` and `__module__` attributes where loky would naturally expect them?
> 
> Can you please update the description of your issue to include the full traceback? Also can you tell us the values of the `__class__`, `__module__` and `__qualname__` of `A_` and `A_.a` when those attributes are present?
> 
> As a workaround, you can either (or both):
> 
> * tell Cython to release the GIL when calling the C++ method and then use `Parallel(n_jobs=6, backend="threading")` instead of the default process-based backend: this will the most efficient way to leverage multiple CPU cores on a single machine.
> * wrap you native method in a simple Python shim and pass the Python function to `delayed` instead of  `A_.a` directly.

Thank you for your reply! 

The full traceback is too long, here is some key information:
```
joblib.externals.loky.process_executor._RemoteTraceback:
"""
blahblah
TypeError: self.Aclass cannot be converted to a Python object for pickling
"""
The above exception was the direct cause of the following exception:
blahblah
_pickle.PicklingError: Could not pickle the task to send it to the workers.
```
Here is full traceback:
```
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/mon/nfs/anaconda3/lib/python3.7/site-packages/joblib/externals/loky/backend/queues.py", line 150, in _feed
    obj_ = dumps(obj, reducers=reducers)
  File "/home/mon/nfs/anaconda3/lib/python3.7/site-packages/joblib/externals/loky/backend/reduction.py", line 247, in dumps
    dump(obj, buf, reducers=reducers, protocol=protocol)
  File "/home/mon/nfs/anaconda3/lib/python3.7/site-packages/joblib/externals/loky/backend/reduction.py", line 240, in dump
    _LokyPickler(file, reducers=reducers, protocol=protocol).dump(obj)
  File "/home/mon/nfs/anaconda3/lib/python3.7/site-packages/joblib/externals/cloudpickle/cloudpickle.py", line 482, in dump
    return Pickler.dump(self, obj)
  File "/home/mon/nfs/anaconda3/lib/python3.7/pickle.py", line 437, in dump
    self.save(obj)
  File "/home/mon/nfs/anaconda3/lib/python3.7/pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "/home/mon/nfs/anaconda3/lib/python3.7/pickle.py", line 662, in save_reduce
    save(state)
  File "/home/mon/nfs/anaconda3/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/mon/nfs/anaconda3/lib/python3.7/pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "/home/mon/nfs/anaconda3/lib/python3.7/pickle.py", line 885, in _batch_setitems
    save(v)
  File "/home/mon/nfs/anaconda3/lib/python3.7/pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "/home/mon/nfs/anaconda3/lib/python3.7/pickle.py", line 662, in save_reduce
    save(state)
  File "/home/mon/nfs/anaconda3/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/mon/nfs/anaconda3/lib/python3.7/pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "/home/mon/nfs/anaconda3/lib/python3.7/pickle.py", line 890, in _batch_setitems
    save(v)
  File "/home/mon/nfs/anaconda3/lib/python3.7/pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "/home/mon/nfs/anaconda3/lib/python3.7/pickle.py", line 662, in save_reduce
    save(state)
  File "/home/mon/nfs/anaconda3/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/mon/nfs/anaconda3/lib/python3.7/pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "/home/mon/nfs/anaconda3/lib/python3.7/pickle.py", line 885, in _batch_setitems
    save(v)
  File "/home/mon/nfs/anaconda3/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/mon/nfs/anaconda3/lib/python3.7/pickle.py", line 819, in save_list
    self._batch_appends(obj)
  File "/home/mon/nfs/anaconda3/lib/python3.7/pickle.py", line 846, in _batch_appends
    save(tmp[0])
  File "/home/mon/nfs/anaconda3/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/mon/nfs/anaconda3/lib/python3.7/pickle.py", line 774, in save_tuple
    save(element)
  File "/home/mon/nfs/anaconda3/lib/python3.7/pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "/home/mon/nfs/anaconda3/lib/python3.7/pickle.py", line 638, in save_reduce
    save(args)
  File "/home/mon/nfs/anaconda3/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/mon/nfs/anaconda3/lib/python3.7/pickle.py", line 774, in save_tuple
    save(element)
  File "/home/mon/nfs/anaconda3/lib/python3.7/pickle.py", line 524, in save
    rv = reduce(self.proto)
  File "stringsource", line 2, in A.A_.__reduce_cython__
TypeError: self.Aclass cannot be converted to a Python object for pickling
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test.py", line 7, in <module>
    test()
  File "test.py", line 4, in test
    res = Parallel(n_jobs=6)(delayed(A_().a)(1, 2) for _ in range(6))
  File "/home/mon/nfs/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 1016, in __call__
    self.retrieve()
  File "/home/mon/nfs/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 908, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/mon/nfs/anaconda3/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 554, in wrap_future_result
    return future.result(timeout=timeout)
  File "/home/mon/nfs/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 435, in result
    return self.__get_result()
  File "/home/mon/nfs/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
_pickle.PicklingError: Could not pickle the task to send it to the workers.
```
Here is some information:
```python
In [1]: from A import A_                                                        

In [2]: A_.__class__                                                            
Out[2]: type

In [3]: A_.a.__module__                                                         
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-3e88f8deb93e> in <module>
----> 1 A_.a.__module__

AttributeError: 'method_descriptor' object has no attribute '__module__'

In [4]: A_.a.__qualname__                                                       
Out[4]: 'A_.a'

In [5]: A_().a(1,3)                                                             
Out[5]: 4
```

For now I used `multiprocessing` and have made program run successfully.

**Comment by ogrisel** [comment]
Was is the value of `A_.__module__`?

Can you please give us the code you use to build the example Cython code you reported above? Maybe push all the files into https://gist.github.com so that we can reproduce the failure and investigate ourselves.

**Comment by ogrisel** [comment]
> For now I used multiprocessing and have made program run successfully.

Note that this would not be the case on Windows and other platform and won't be the case anymore in future versions of Python under Linux.

https://discuss.python.org/t/switching-default-multiprocessing-context-to-spawn-on-posix-as-well/21868

Could you please include the Cython source code and the build commands you used?
