### ISSUE TITLE
python 3.7.3 ModuleNotFoundError: No module named '_lzma' with joblib 0.15.0

### ISSUE THREAD

**Issue by xiaozhongtian** [joblib/joblib#1050]
Hello,
New version  joblib 0.15.0 has incompability with python 3.7.3 in centos.
```
>>> import joblib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xiaozho/export_mlbox/mlbox_export/venv/lib/python3.7/site-packages/joblib/__init__.py", line 113, in <module>
    from .memory import Memory, MemorizedResult, register_store_backend
  File "/home/xiaozho/export_mlbox/mlbox_export/venv/lib/python3.7/site-packages/joblib/memory.py", line 33, in <module>
    from ._store_backends import StoreBackendBase, FileSystemStoreBackend
  File "/home/xiaozho/export_mlbox/mlbox_export/venv/lib/python3.7/site-packages/joblib/_store_backends.py", line 17, in <module>
    from . import numpy_pickle
  File "/home/xiaozho/export_mlbox/mlbox_export/venv/lib/python3.7/site-packages/joblib/numpy_pickle.py", line 15, in <module>
    from .compressor import lz4, LZ4_NOT_INSTALLED_ERROR
  File "/home/xiaozho/export_mlbox/mlbox_export/venv/lib/python3.7/site-packages/joblib/compressor.py", line 24, in <module>
    import lzma
  File "/usr/local/python3/lib/python3.7/lzma.py", line 27, in <module>
    from _lzma import *
ModuleNotFoundError: No module named '_lzma'
```

**Comment by ogrisel** [comment]
Maybe when we dropped Python 2 compat we added the implicit requirement that lzma should be present.

**Comment by ogrisel** [comment]
Will work on a fix.

**Comment by ogrisel** [comment]
@xiaozhongtian @andrewsmartin can you please confirm that #1051 fixes the issue for you?

**Comment by xiaozhongtian** [comment]
Waiting for the release version in Pypi to test.
But I haved seen the changes on the branch ogrisel:make_lzma_optional_again. It should be feasible.

**Comment by ogrisel** [comment]
I have tried to use docker image with centos 8 but the python3.6 package that comes with it has the `lzma` module in its standard library by default.

**Comment by ogrisel** [comment]
Actually #1051 was not good it would still break. I deleted the `lzma.py` file from my python distribution to make sure that joblib test would pass without lzma installed.

**Comment by ogrisel** [comment]
0.15.1 is out with your fix.

**Comment by xiaozhongtian** [comment]
fix resovled comfirmed.
