### ISSUE TITLE
ModuleNotFoundError: No module named 'utils'

### ISSUE THREAD

**Issue by Adblu** [joblib/joblib#1073]
On fresh environment, python 3.6 I am trying to import the data that was previously saved:
```
joblib.load(file)
```
Im having following error:

```
>>> a = joblib.load('/home/n/Documents/production_inference/results/2016/16481755_Foto[10]')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/n/anaconda3/lib/python3.7/site-packages/joblib/numpy_pickle.py", line 598, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/home/n/anaconda3/lib/python3.7/site-packages/joblib/numpy_pickle.py", line 526, in _unpickle
    obj = unpickler.load()
  File "/home/n/anaconda3/lib/python3.7/pickle.py", line 1088, in load
    dispatch[key[0]](self)
  File "/home/n/anaconda3/lib/python3.7/pickle.py", line 1376, in load_global
    klass = self.find_class(module, name)
  File "/home/n/anaconda3/lib/python3.7/pickle.py", line 1426, in find_class
    __import__(module, level=0)
ModuleNotFoundError: No module named 'utils'

```

How to fix it ?

**Comment by ogrisel** [comment]
pickled objects are in general not meant to be loaded with different versions of the libraries you use. Regenerate the pickle with the new version of your code and dependencies.
