### ISSUE TITLE
_pickle.PicklingError: Could not pickle the task to send it to the workers.

### ISSUE THREAD

**Issue by floria618** [joblib/joblib#1088]
I encountered the same problem when I ran

Node2Vec(G, dimensions = 64, q = 0.025, p = 4, workers = 4, num_walks = 1, walk_length = 5, weight_key = 'weight')**

Traceback (most recent call last):
File "FluPrediction.py", line 255, in
node2vec_weightedGraph()
File "FluPrediction.py", line 14, in node2vec_weightedGraph
model = Node2Vec(G, dimensions = 64, q = 0.025, p = 4, workers = 4, num_walks = 2, walk_length = 10, weight_key = 'weight').fit(window = 2, min_count = 1, batch_words = 4)
File "D:\Python3.6\lib\site-packages\node2vec\node2vec.py", line 67, in init
self.walks = self._generate_walks()
File "D:\Python3.6\lib\site-packages\node2vec\node2vec.py", line 154, in _generate_walks
in enumerate(num_walks_lists, 1))
File "D:\Python3.6\lib\site-packages\joblib\parallel.py", line 934, in call
self.retrieve()
File "D:\Python3.6\lib\site-packages\joblib\parallel.py", line 833, in retrieve
self._output.extend(job.get(timeout=self.timeout))
File "D:\Python3.6\lib\site-packages\joblib_parallel_backends.py", line 521, in wrap_future_result
return future.result(timeout=timeout)
File "D:\Python3.6\lib\concurrent\futures_base.py", line 432, in result
return self.__get_result()
File "D:\Python3.6\lib\concurrent\futures_base.py", line 384, in __get_result
raise self._exception
_pickle.PicklingError: Could not pickle the task to send it to the workers.

**Comment by floria618** [comment]
joblib.externals.loky.process_executor._RemoteTraceback:
"""
Traceback (most recent call last):
  File "D:\Python3.6\lib\site-packages\joblib\externals\loky\backend\queues.py", line 152, in _feed
    send_bytes(obj_)
  File "D:\Python3.6\lib\multiprocessing\connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "D:\Python3.6\lib\multiprocessing\connection.py", line 280, in _send_bytes
    ov, err = _winapi.WriteFile(self._handle, buf, overlapped=True)
OSError: [WinError 87] 参数错误。
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "FluPrediction.py", line 255, in <module>
    node2vec_weightedGraph()
  File "FluPrediction.py", line 14, in node2vec_weightedGraph
    model = Node2Vec(G, dimensions = 64, q = 0.025, p = 4, workers = 4, num_walks = 2, walk_length = 10, weight_key = 'weight').fit(window = 2, min_count = 1, batch_words = 4)
  File "D:\Python3.6\lib\site-packages\node2vec\node2vec.py", line 67, in __init__
    self.walks = self._generate_walks()
  File "D:\Python3.6\lib\site-packages\node2vec\node2vec.py", line 154, in _generate_walks
    in enumerate(num_walks_lists, 1))
  File "D:\Python3.6\lib\site-packages\joblib\parallel.py", line 934, in __call__
    self.retrieve()
  File "D:\Python3.6\lib\site-packages\joblib\parallel.py", line 833, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "D:\Python3.6\lib\site-packages\joblib\_parallel_backends.py", line 521, in wrap_future_result
    return future.result(timeout=timeout)
  File "D:\Python3.6\lib\concurrent\futures\_base.py", line 432, in result
    return self.__get_result()
  File "D:\Python3.6\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
_pickle.PicklingError: Could not pickle the task to send it to the workers.

**Comment by ogrisel** [comment]
Can you please tel use the exact version number of Python you are running and give us a minimal reproduction script that does not depend on your data? https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

The `[WinError 87]` error you get is very low level. It's unlikely we will be able to help you without being able to reproduce the error on our own machine.

**Comment by ogrisel** [comment]
For reference, I changed the title to be more specific. Is this program a frozen Python executable?
