### ISSUE TITLE
KeyError in resource_tracker (random) when running test_multithreaded_parallel_termination_resource_tracker_silent

### ISSUE THREAD

**Issue by ogrisel** [joblib/joblib#1091]
```
================================== FAILURES ===================================
_______ test_multithreaded_parallel_termination_resource_tracker_silent _______

    @with_numpy

E               File "d:\a\1\s\joblib\externals\loky\reusable_executor.py", line 177, in submit

E                 return super(_ReusablePoolExecutor, self).submit(

E               File "d:\a\1\s\joblib\externals\loky\process_executor.py", line 1104, in submit

E                 raise ShutdownExecutorError(

E             joblib.externals.loky.process_executor.ShutdownExecutorError: cannot schedule new futures after shutdown

E             d:\a\1\s\joblib\externals\loky\backend\resource_tracker.py:303: UserWarning: resource_tracker: C:\Users\VSSADM~1\AppData\Local\Temp\joblib_memmapping_folder_4580_bd4bea4cf12e454fbc25ed9b66ece88c_a4ae259e1d704739bce519131495ebf9\4580-1757708830608-253caf7f02a2426b908a4af1c5f575ac.pkl: FileNotFoundError(2, 'The system cannot find the path specified')

E               warnings.warn(

E             Traceback (most recent call last):

E               File "d:\a\1\s\joblib\externals\loky\backend\resource_tracker.py", line 281, in main

E                 del registry[rtype][name]

E             KeyError: 'C:\\Users\\VSSADM~1\\AppData\\Local\\Temp\\joblib_memmapping_folder_4580_bd4bea4cf12e454fbc25ed9b66ece88c_a4ae259e1d704739bce519131495ebf9\\4580-1757708830608-253caf7f02a2426b908a4af1c5f575ac.pkl'

E             
E           assert b'resource_tracker' not in b'Traceback (most recent call last):\r\n  File "<string>", line 48, in <module>\r\n  File "C:\\Miniconda\\envs\\testen...454fbc25ed9b66ece88c_a4ae259e1d704739bce519131495ebf9\\\\4580-1757708830608-253caf7f02a2426b908a4af1c5f575ac.pkl\'\r\n'

cmd        = 'if 1:\n        import os\n        import numpy as np\n        from joblib import Parallel, delayed\n        from jobl...minate their backend\n        wait([future_1, future_2])\n\n        future_1.result()\n        future_2.result()\n    '
err        = b'Traceback (most recent call last):\r\n  File "<string>", line 48, in <module>\r\n  File "C:\\Miniconda\\envs\\testen...454fbc25ed9b66ece88c_a4ae259e1d704739bce519131495ebf9\\\\4580-1757708830608-253caf7f02a2426b908a4af1c5f575ac.pkl\'\r\n'
f1         = 'parallel_get_filename'
f2         = 'parallel_raise'
functions_and_returncodes = [('parallel_get_filename', 'parallel_get_filename', 0), ('parallel_get_filename', 'parallel_raise', 1), ('parallel_raise', 'parallel_raise', 1)]
out        = b''
p          = <subprocess.Popen object at 0x000001A500C6D9A0>
returncode = 1
```

Observed with Python 3.8 on Windows in this PR: #1090

**Comment by ogrisel** [comment]
This is probably caused by a race condition in loky but I opened an issue here to track the frequency of the problem at the joblib level.

**Comment by ogrisel** [comment]
Similar error (`resource_tracker` in stderr) appears randomly in another run of #1090 in `test_nested_loop_error_in_grandchild_resource_tracker_silent` on Python 3.6 / Linux:

```python-traceback
_________ test_nested_loop_error_in_grandchild_resource_tracker_silent _________

    @with_numpy
    @with_multiprocessing
E           File "<string>", line 11, in nested_loop
E           File "/home/vsts/work/1/s/joblib/parallel.py", line 1042, in __call__
E             self.retrieve()
E           File "/home/vsts/work/1/s/joblib/parallel.py", line 921, in retrieve
E             self._output.extend(job.get(timeout=self.timeout))
E           File "/home/vsts/work/1/s/joblib/_parallel_backends.py", line 542, in wrap_future_result
E             return future.result(timeout=timeout)
E           File "/usr/share/miniconda/envs/testenv/lib/python3.6/concurrent/futures/_base.py", line 432, in result
E             return self.__get_result()
E           File "/usr/share/miniconda/envs/testenv/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
E             raise self._exception
E         ValueError
E         """
E         
E         The above exception was the direct cause of the following exception:
E         
E         Traceback (most recent call last):
E           File "<string>", line 17, in <module>
E           File "/home/vsts/work/1/s/joblib/parallel.py", line 1042, in __call__
E             self.retrieve()
E           File "/home/vsts/work/1/s/joblib/parallel.py", line 921, in retrieve
E             self._output.extend(job.get(timeout=self.timeout))
E           File "/home/vsts/work/1/s/joblib/_parallel_backends.py", line 542, in wrap_future_result
E             return future.result(timeout=timeout)
E           File "/usr/share/miniconda/envs/testenv/lib/python3.6/concurrent/futures/_base.py", line 432, in result
E             return self.__get_result()
E           File "/usr/share/miniconda/envs/testenv/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
E             raise self._exception
E         ValueError
E         /home/vsts/work/1/s/joblib/externals/loky/backend/resource_tracker.py:320: UserWarning: resource_tracker: There appear to be 3 leaked semlock objects to clean up at shutdown
E           (len(rtype_registry), rtype))
E         
E       assert b'resource_tracker' not in b'joblib.externals.loky.process_executor._RemoteTraceback: \n"""\njoblib.externals.loky.process_executor._RemoteTraceb...source_tracker: There appear to be 3 leaked semlock objects to clean up at shutdown\n  (len(rtype_registry), rtype))\n'

cmd        = 'if 1:\n        from joblib import Parallel, delayed\n\n\n        def raise_error(i):\n            raise ValueError\n\...(backend="loky", n_jobs=2)(\n                delayed(nested_loop)(func) for func in [raise_error]\n            )\n    '
err        = b'joblib.externals.loky.process_executor._RemoteTraceback: \n"""\njoblib.externals.loky.process_executor._RemoteTraceb...source_tracker: There appear to be 3 leaked semlock objects to clean up at shutdown\n  (len(rtype_registry), rtype))\n'
out        = b''
p          = <subprocess.Popen object at 0x7fa8e5118f98>

```

**Comment by dPys** [comment]
@ogrisel -- Are the following warnings at all related to this issue?

```
/usr/local/anaconda3/lib/python3.7/site-packages/joblib/externals/loky/backend/resource_tracker.py:320: UserWarning: resource_tracker: There appear to be 6 leaked folder objects to clean up at shutdown
  (len(rtype_registry), rtype))
/usr/local/anaconda3/lib/python3.7/site-packages/joblib/externals/loky/backend/resource_tracker.py:333: UserWarning: resource_tracker: /var/folders/r1/p8kclf5j3v74m4l5l4__jty00000gn/T/tmpsdw45tqe/joblib_memmapping_folder_75608_e933daacf30d402e94665b6325255fdd_36da637f0b904debb76eedc6a00adad4: FileNotFoundError(2, 'No such file or directory')
  warnings.warn('resource_tracker: %s: %r' % (name, e))
/usr/local/anaconda3/lib/python3.7/site-packages/joblib/externals/loky/backend/resource_tracker.py:333: UserWarning: resource_tracker: /var/folders/r1/p8kclf5j3v74m4l5l4__jty00000gn/T/tmpsdw45tqe/joblib_memmapping_folder_75608_9bb34772fbbe4055abd8388041e22dc8_19fc9cfb400446c3b5bce39152a7091d: FileNotFoundError(2, 'No such file or directory')
  warnings.warn('resource_tracker: %s: %r' % (name, e))
/usr/local/anaconda3/lib/python3.7/site-packages/joblib/externals/loky/backend/resource_tracker.py:333: UserWarning: resource_tracker: /var/folders/r1/p8kclf5j3v74m4l5l4__jty00000gn/T/tmpsdw45tqe/joblib_memmapping_folder_75608_fb552d07e669434ea203427c94bfe3d2_bfae29fea4d74433a70a91fa1f11de0e: FileNotFoundError(2, 'No such file or directory')
  warnings.warn('resource_tracker: %s: %r' % (name, e))
/usr/local/anaconda3/lib/python3.7/site-packages/joblib/externals/loky/backend/resource_tracker.py:333: UserWarning: resource_tracker: /var/folders/r1/p8kclf5j3v74m4l5l4__jty00000gn/T/tmpsdw45tqe/joblib_memmapping_folder_75608_62ec0949a80043b594804a1d968e4ca9_7dd48befbb674a058d0b7dc35f1dc386: FileNotFoundError(2, 'No such file or directory')
  warnings.warn('resource_tracker: %s: %r' % (name, e))
/usr/local/anaconda3/lib/python3.7/site-packages/joblib/externals/loky/backend/resource_tracker.py:333: UserWarning: resource_tracker: /var/folders/r1/p8kclf5j3v74m4l5l4__jty00000gn/T/tmpsdw45tqe/joblib_memmapping_folder_75608_79a968924ce241118f8d2965b62fc0e6_3764391c11fe43848ce82648c15c1d3a: FileNotFoundError(2, 'No such file or directory')
  warnings.warn('resource_tracker: %s: %r' % (name, e))
/usr/local/anaconda3/lib/python3.7/site-packages/joblib/externals/loky/backend/resource_tracker.py:333: UserWarning: resource_tracker: /var/folders/r1/p8kclf5j3v74m4l5l4__jty00000gn/T/tmpsdw45tqe/joblib_memmapping_folder_75608_e756834f31fa4e2b8676fef165606a62_decd76209a264ff4a7bc79782b2d825c: FileNotFoundError(2, 'No such file or directory')
  warnings.warn('resource_tracker: %s: %r' % (name, e))
/usr/local/anaconda3/lib/python3.7/site-packages/joblib/externals/loky/backend/resource_tracker.py:320: UserWarning: resource_tracker: There appear to be 7 leaked folder objects to clean up at shutdown
  (len(rtype_registry), rtype))
/usr/local/anaconda3/lib/python3.7/site-packages/joblib/externals/loky/backend/resource_tracker.py:333: UserWarning: resource_tracker: /var/folders/r1/p8kclf5j3v74m4l5l4__jty00000gn/T/tmpi2tkczin/joblib_memmapping_folder_75605_5b0d6a5817ae48499fca8e09e520474c_16a547cfed054ea985c5eccaaa55b4d6: FileNotFoundError(2, 'No such file or directory')
  warnings.warn('resource_tracker: %s: %r' % (name, e))
/usr/local/anaconda3/lib/python3.7/site-packages/joblib/externals/loky/backend/resource_tracker.py:333: UserWarning: resource_tracker: /var/folders/r1/p8kclf5j3v74m4l5l4__jty00000gn/T/tmpi2tkczin/joblib_memmapping_folder_75605_5a22b37028124987af6b2d090b58672c_e517e950f34c41b6b6c0b0d4f1887810: FileNotFoundError(2, 'No such file or directory')
  warnings.warn('resource_tracker: %s: %r' % (name, e))
/usr/local/anaconda3/lib/python3.7/site-packages/joblib/externals/loky/backend/resource_tracker.py:333: UserWarning: resource_tracker: /var/folders/r1/p8kclf5j3v74m4l5l4__jty00000gn/T/tmpi2tkczin/joblib_memmapping_folder_75605_d0e1a3223c024bd58c160c5e0598ce03_92618c0ad6b248ae99992ef78d8ecde9: FileNotFoundError(2, 'No such file or directory')
  warnings.warn('resource_tracker: %s: %r' % (name, e))
/usr/local/anaconda3/lib/python3.7/site-packages/joblib/externals/loky/backend/resource_tracker.py:333: UserWarning: resource_tracker: /var/folders/r1/p8kclf5j3v74m4l5l4__jty00000gn/T/tmpi2tkczin/joblib_memmapping_folder_75605_99969424f1f04965930e42ed3f733968_229aaf213023464cac37dc19df29b169: FileNotFoundError(2, 'No such file or directory')
  warnings.warn('resource_tracker: %s: %r' % (name, e))
/usr/local/anaconda3/lib/python3.7/site-packages/joblib/externals/loky/backend/resource_tracker.py:333: UserWarning: resource_tracker: /var/folders/r1/p8kclf5j3v74m4l5l4__jty00000gn/T/tmpi2tkczin/joblib_memmapping_folder_75605_da5a6a818161438588c5038ad82e4207_f7e83ef0279f4440ab843b699e4ae6d1: FileNotFoundError(2, 'No such file or directory')
  warnings.warn('resource_tracker: %s: %r' % (name, e))
/usr/local/anaconda3/lib/python3.7/site-packages/joblib/externals/loky/backend/resource_tracker.py:333: UserWarning: resource_tracker: /var/folders/r1/p8kclf5j3v74m4l5l4__jty00000gn/T/tmpi2tkczin/joblib_memmapping_folder_75605_36664caf74a24a3ab86e087f39117bde_634776b021db49c5b0afc94733238a9e: FileNotFoundError(2, 'No such file or directory')
  warnings.warn('resource_tracker: %s: %r' % (name, e))
/usr/local/anaconda3/lib/python3.7/site-packages/joblib/externals/loky/backend/resource_tracker.py:333: UserWarning: resource_tracker: /var/folders/r1/p8kclf5j3v74m4l5l4__jty00000gn/T/tmpi2tkczin/joblib_memmapping_folder_75605_b543c47a79544a6ba9680577db6469e0_be3d6b29173a42d4825aa065145ededb: FileNotFoundError(2, 'No such file or directory')
  warnings.warn('resource_tracker: %s: %r' % (name, e))
```

If not, I can open a separate issue.

@dPys
