### ISSUE TITLE
 Joblib fails when used concurrently with multiple workers in PyTorch's DataLoader

### ISSUE THREAD

**Issue by gerardsn** [joblib/joblib#1104]
## 🐛 Bug

Joblib fails when used concurrently with multiple workers in PyTorch's DataLoader

## To Reproduce

```python
import os, sys
import torch, torch.nn as nn, torch.nn.functional as F
from torch.utils.data import DataLoader
from torchvision import transforms, datasets
from joblib import Parallel, delayed

class Model(nn.Module):
    def __init__(self):
        super().__init__()
        self.l1 = torch.nn.Linear(28 * 28, 10)

    def forward(self, x):
        return torch.relu(self.l1(x.view(x.size(0), -1)))

def main(num_workers, lr):
    data_set = datasets.MNIST(os.getcwd(), download=True, train=True, transform=transforms.ToTensor())
    data_loader = DataLoader(data_set, batch_size=64, num_workers=num_workers)
    model = Model()
    optim = torch.optim.Adam(model.parameters(), lr=lr)

    for batch in data_loader:
        x, y = batch
        y_hat = model(x)
        loss = F.cross_entropy(y_hat, y)
    print(f'completed {lr}')

if __name__ == '__main__':
    num_workers = int(sys.argv[1])
    Parallel(n_jobs=3, backend='loky')(delayed(main)(num_workers, lr) for lr in [1e-4, 1e-3, 1e-2])
```

This works:
```commandline
python code.py 0
```

This fails:
```commandline
python code.py 1
```

with error:

```commandline
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/opt/.virtualenvs/l2r/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 431, in _process_worker
    r = call_item()
  File "/opt/.virtualenvs/l2r/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 285, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/opt/.virtualenvs/l2r/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "/opt/.virtualenvs/l2r/lib/python3.7/site-packages/joblib/parallel.py", line 253, in __call__
    for func, args, kwargs in self.items]
  File "/opt/.virtualenvs/l2r/lib/python3.7/site-packages/joblib/parallel.py", line 253, in <listcomp>
    for func, args, kwargs in self.items]
  File "code.py", line 21, in main
    for batch in data_loader:
  File "/opt/.virtualenvs/l2r/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 291, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "/opt/.virtualenvs/l2r/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 737, in __init__
    w.start()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.7/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/opt/.virtualenvs/l2r/lib/python3.7/site-packages/joblib/externals/loky/backend/process.py", line 39, in _Popen
    return Popen(process_obj)
  File "/opt/.virtualenvs/l2r/lib/python3.7/site-packages/joblib/externals/loky/backend/popen_loky_posix.py", line 52, in __init__
    self._launch(process_obj)
  File "/opt/.virtualenvs/l2r/lib/python3.7/site-packages/joblib/externals/loky/backend/popen_loky_posix.py", line 157, in _launch
    pid = fork_exec(cmd_python, self._fds, env=process_obj.env)
AttributeError: 'Process' object has no attribute 'env'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "code.py", line 29, in <module>
    Parallel(n_jobs=3, backend='loky')(delayed(main)(num_workers, lr) for lr in [1e-4, 1e-3, 1e-2])
  File "/opt/.virtualenvs/l2r/lib/python3.7/site-packages/joblib/parallel.py", line 1042, in __call__
    self.retrieve()
  File "/opt/.virtualenvs/l2r/lib/python3.7/site-packages/joblib/parallel.py", line 921, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/opt/.virtualenvs/l2r/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 435, in result
    return self.__get_result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
AttributeError: 'Process' object has no attribute 'env'
/opt/.virtualenvs/l2r/lib/python3.7/site-packages/joblib/externals/loky/backend/resource_tracker.py:320: UserWarning: resource_tracker: There appear to be 33 leaked semlock objects to clean up at shutdown
  (len(rtype_registry), rtype))

```

## Expected behavior

Being able to use joblib for running multiple PyTorch training jobs with num_workers>0 in the DataLoader. 

## Environment

OS: Ubuntu 18.04.5 LTS (x86_64)
Python version: 3.7 (64-bit runtime)

Versions of relevant libraries:
[pip3] joblib==0.16.0
[pip3] torch==1.6.0
[pip3] torchvision==0.7.0

## Additional context

Same issue on GPU and CPU, and there are plenty of cores available for this to work.

**Comment by gerardsn** [comment]
@omry

**Comment by jjerphan** [comment]
This should be fixed upstream by https://github.com/pytorch/pytorch/pull/81862.
