### ISSUE TITLE
struct.error when each process sending back a large object

### ISSUE THREAD

**Issue by AaronX121** [joblib/joblib#1113]
Hi, I met a problem when using Joblib to parallelize the learning process of my learning model. 

The basic workflow is to send the training data to each process (~180MB), and each process is required to send back the trained model. Finally, models returned by all processes are aggregated as a final model. The workflow is very similar to `_parallel_build_trees` from the `_forest.py` in Scikit-Learn ([Link](https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/ensemble/_forest.py#L387)), despite each model in my case is quite large, its size may be several GBs in the memory.

The traceback information is as follows:
```
joblib.externals.loky.process_executor._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/anaconda3/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 357, in _sendback_result
    exception=exception))
  File "/home/anaconda3/lib/python3.7/site-packages/joblib/externals/loky/backend/queues.py", line 244, in put
    self._writer.send_bytes(obj)
  File "/home/anaconda3/lib/python3.7/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/home/anaconda3/lib/python3.7/multiprocessing/connection.py", line 393, in _send_bytes
    header = struct.pack("!i", n)
struct.error: 'i' format requires -2147483648 <= number <= 2147483647
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test_forest.py", line 60, in <module>
    model.fit(X_train, y_train)
  File "../model.py", line 248, in fit
    X_aug_train = layer_.fit_transform(X_train, y)
  File "../_layer.py", line 174, in fit_transform
    for idx, estimator in self.estimators_.items())
  File "/home/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 1042, in __call__
    self.retrieve()
  File "/home/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 921, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/anaconda3/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/home/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 435, in result
    return self.__get_result()
  File "/home/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
struct.error: 'i' format requires -2147483648 <= number <= 2147483647
```

I find that the similar problem is mentioned in issue #731. Since it is two years from now, I am wondering that whether this is fixed in the current version, or there is a better solution than dumping the model on the disk (slow because of the reading speed)? Thanks !

Package Info:
Python==3.8.3
Joblib==0.16.0

**Comment by tomMoral** [comment]
It seems to be an issue with the `Connection` before `python3.8`: python/cpython#10305

Could you test your script in a `conda` env with python3.8 to confirm this fix your issue?

In the mean time, I will try to see if the python fix can be backported in the `loky` backend.

**Comment by AaronX121** [comment]
I am sorry for my carelessness. Yes, the traceback above was reported by a python3.7 environment. I took your suggestions and the program works fine under python3.8. 

If the issue behind is already fixed in python3.8, I think this issue can be safely closed. Thanks!

**Comment by tomMoral** [comment]
Great that it is working!
We will see if we can  also make it work in `loky`, thanks for the report anyway.
