### ISSUE TITLE
Cannot close close memmap in Windows

### ISSUE THREAD

**Issue by parkournerd** [joblib/joblib#1119]
**Issue:**
Hey there!

I can't close memmapped joblibs in Windows with Python 3.8. Below shows that the numpy arrays are correctly mem-mapped, but cannot be closed so I cannot rewrite them.

Additionally (separate isseus):
1. I am able to delete the files using my script, but still cannot access
2. Using the "with" operator, you end up with ndarrays instead of mem-maps

**Script:**
import pandas
import joblib
import numpy
import gc

# create and save example numpy array
arr = numpy.array([1, 2, 3, 4, 5])
joblib.dump(arr, "arr.joblib")

# load (memmap works but cannot close)
arr = joblib.load("arr.joblib", mmap_mode = "r")
print(type(arr))

# delete
del arr
gc.collect()

# try to load again
arr = joblib.load("arr.joblib", mmap_mode = "r")
print(type(arr))

# try to save over the file
joblib.dump(arr, "arr.joblib")

**Output: **
<class 'numpy.memmap'>
<class 'numpy.memmap'>
Traceback (most recent call last):
  File ".\testjoblib.py", line 23, in <module>
    joblib.dump(arr, "arr.joblib")
  File "C:\Users\TinDucVo\.virtualenvs\usnnperiodic-fMPrPz_m\lib\site-packages\joblib\numpy_pickle.py", line 479, in dum
p
    with open(filename, 'wb') as f:
OSError: [Errno 22] Invalid argument: 'arr.joblib'

**Comment by parkournerd** [comment]
Please close. I dun-goof't and forgot to close the mmap.  The "with" operator issue is still valid though
