### ISSUE TITLE
queue.Empty error when n_jobs is numpy.int64

### ISSUE THREAD

**Issue by auderson** [joblib/joblib#1122]
`>>> Parallel(span // 2)(read_file(fp) for fp in file_paths)`

```
Traceback (most recent call last):
  File "/home/auderson/.local/lib/python3.6/site-packages/joblib/parallel.py", line 827, in dispatch_one_batch
    tasks = self._ready_batches.get(block=False)
  File "/usr/lib/python3.6/queue.py", line 161, in get
    raise Empty
queue.Empty
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-6-41b859bf228e>", line 1, in <module>
    Parallel(span // 2)(read_factor(fp) for fp in file_paths)
  File "/home/auderson/.local/lib/python3.6/site-packages/joblib/parallel.py", line 1048, in __call__
    if self.dispatch_one_batch(iterator):
  File "/home/auderson/.local/lib/python3.6/site-packages/joblib/parallel.py", line 838, in dispatch_one_batch
    islice = list(itertools.islice(iterator, big_batch_size))
ValueError: Stop argument for islice() must be None or an integer: 0 <= x <= sys.maxsize.
```
`>>> span // 2`

`5`

`>>> type(span // 2)`

`numpy.int64`

works fine if add `int` outside:

`>>> Parallel(int(span // 2))(read_file(fp) for fp in file_paths)`

**Comment by auderson** [comment]
a reproducible example:


```
import numpy as np
from joblib import Parallel, delayed


@delayed
def test():
    pass


>>> type(np.array(10) // 3)
numpy.int64
>>> type(np.max([1, 2, 10]) // 3)
numpy.int64
>>> type(10 // 3)
int
>>> Parallel(np.max([1, 2, 10]) // 3)(test() for i in range(100))
Traceback (most recent call last):
  File "/home/auderson/.local/lib/python3.6/site-packages/joblib/parallel.py", line 827, in dispatch_one_batch
    tasks = self._ready_batches.get(block=False)
  File "/usr/lib/python3.6/queue.py", line 161, in get
    raise Empty
queue.Empty
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-13-f24a7eb0a600>", line 1, in <module>
    Parallel(np.array(10) // 3)(test() for i in range(100))
  File "/home/auderson/.local/lib/python3.6/site-packages/joblib/parallel.py", line 1048, in __call__
    if self.dispatch_one_batch(iterator):
  File "/home/auderson/.local/lib/python3.6/site-packages/joblib/parallel.py", line 838, in dispatch_one_batch
    islice = list(itertools.islice(iterator, big_batch_size))
ValueError: Stop argument for islice() must be None or an integer: 0 <= x <= sys.maxsize.
```

**Comment by auderson** [comment]
I guess it's a problem with numpy array. In my initial post, `span = np.max(...some number)`, so maybe it is a 0-dim np.ndarray?
