### ISSUE TITLE
Pandas DataFrame with Extension fails using `LokyBackend` but succeeds using `MultiprocessingBackend`

### ISSUE THREAD

**Issue by ianozsvald** [joblib/joblib#1163]
Passing a Pandas DataFrame that has a registered Extension (https://pandas.pydata.org/docs/development/extending.html) fails using the `joblib` `Parallel` default with `LokyBackend`, if instead we use `Parallel(backend='multiprocessing')` then the job succeeds.

Below I provide working code and a copy of the output. If I call `Parallel` with a function (`my_fn`) which takes a DataFrame I get several success/failure combinations:
* `my_fn` calls a standard DataFrame function (e.g. `.sum()`) with either `MultiprocessingBackend` or `LokyBackend` - success
* `my_fn` calls a user-defined extension with `LokyBackend` - failure
* `my_fn` calls a user-defined extension with `MultiprocessingBackend` - success

In the following code I provide two extension methods - one as a property, one as a function - both cause the same failure (i.e. there's no behaviour difference). 

I'm using a fresh Anaconda install with Python 3.8, I have version notes at the end.

```
"""Cause joblib+Loky to fail on a Pandas Extension, where joblib+multiprocessing succeeds"""
import pandas as pd

# Example code adapted from
# https://pandas.pydata.org/docs/development/extending.html
@pd.api.extensions.register_dataframe_accessor("extn")
class ExtnAccessor:
    def __init__(self, pandas_obj):
        self._validate(pandas_obj)
        self._obj = pandas_obj

    @staticmethod
    def _validate(obj):
        """Check for the mandatory columns"""
        if "numbers" not in obj.columns: 
            raise AttributeError("Must have 'numbers' series.")

    @property
    def double_if_positive_property(self):
        """Example extension as a property"""
        mask = self._obj['numbers'] <= 0
        return self._obj.where(mask, other=self._obj.numbers * 2, axis=0)

    def double_if_positive_function(self):
        """Example extension as a function"""
        mask = self._obj['numbers'] <= 0
        return self._obj.where(mask, other=self._obj.numbers * 2, axis=0)

# We can define 3 variants of my_fn - 2 using the Pandas Extension
# which both fail and 1 using a regular Pandas function which succeeds

#def my_fn(df):
#    # if we call the extension property then we get the failure
#    return df.extn.double_if_positive_property

def my_fn(df):
    # if we call the extension function then we also get the failure
    return df.extn.double_if_positive_function()

#def my_fn(df):
#    # if my_fn calls a regular pd function rather than
#    # an Extension then both joblib backends are happy
#    return df.sum()


if __name__ == "__main__":
    df = pd.DataFrame({'numbers': [-5, -1, 0, 1, 5]})
    # note that double_if_positive_property is a property, so no need for () brackets
    # we verify that the property and function variants both provide the same answer
    df_expected_property = df.extn.double_if_positive_property
    df_expected_function = df.extn.double_if_positive_function()
    pd.testing.assert_frame_equal(df_expected_property, df_expected_function)
    from IPython.display import display
    print("We expect negatives to be unchanged and positives to double")
    display(df_expected_property)

    # Next we'll call the DataFrame with a function in a 2-iteration loop using
    # joblib with multiprocessing or Loky, expecting that Loky fails
    # with extensions

    # calling joblib with n_jobs > 1 and multiprocessing works fine for 
    # the ExtenAccessor `extn` 
    from joblib import Parallel, delayed
    results = Parallel(n_jobs=2, backend='multiprocessing', verbose=1)(delayed(my_fn)(df,) for n in range(2))
    print(f"Result from using multiprocessing:", results)

    # calling joblib the same way with Loky causes a failure with
    # and we can use either the property or function based extension to get the same failure
    #[Parallel(n_jobs=2)]: Using backend LokyBackend with 2 concurrent workers.
    #[Parallel(n_jobs=2)]: Done   2 out of   2 | elapsed:    0.5s remaining:    0.0s
    #---------------------------------------------------------------------------
    #_RemoteTraceback                          Traceback (most recent call last)
    #_RemoteTraceback: 
    #"""
    #Traceback (most recent call last):
    #  File "/home/ian/miniconda3/envs/trial_loky_pandas_extension/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py", line 431, in _process_worker
    #    r = call_item()
    #  File "/home/ian/miniconda3/envs/trial_loky_pandas_extension/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py", line 285, in __call__
    #    return self.fn(*self.args, **self.kwargs)
    #  File "/home/ian/miniconda3/envs/trial_loky_pandas_extension/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 595, in __call__
    #    return self.func(*args, **kwargs)
    #  File "/home/ian/miniconda3/envs/trial_loky_pandas_extension/lib/python3.8/site-packages/joblib/parallel.py", line 262, in __call__
    #    return [func(*args, **kwargs)
    #  File "/home/ian/miniconda3/envs/trial_loky_pandas_extension/lib/python3.8/site-packages/joblib/parallel.py", line 262, in <listcomp>
    #    return [func(*args, **kwargs)
    #  File "/home/ian/workspace/scratch/trial_loky_pandas_extension/extn_trial.py", line 24, in my_fn
    #    return df.extn.double_if_positive_function
    #  File "/home/ian/miniconda3/envs/trial_loky_pandas_extension/lib/python3.8/site-packages/pandas/core/generic.py", line 5465, in __getattr__
    #    return object.__getattribute__(self, name)
    #AttributeError: 'DataFrame' object has no attribute 'extn'
    #"""   
    results = Parallel(n_jobs=2, backend='loky', verbose=1)(delayed(my_fn)(df,) for n in range(2))
    print(f"Result from using Loky:", results) # we never get here due to the AttributeError
```

Output:

```
In [26]: %run extn_trial.py
/home/ian/workspace/scratch/trial_loky_pandas_extension/extn_trial.py:7: UserWarning: registration of accessor <class '__main__.ExtnAccessor'> under name 'extn' for type <class 'pandas.core.frame.DataFrame'> is overriding a preexisting attribute with the same name.
  self._obj = pandas_obj
We expect negatives to be unchanged and positives to double
   numbers
0       -5
1       -1
2        0
3        2
4       10
[Parallel(n_jobs=2)]: Using backend MultiprocessingBackend with 2 concurrent workers.
[Parallel(n_jobs=2)]: Done   2 out of   2 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=2)]: Done   2 out of   2 | elapsed:    0.0s finished
Result from using multiprocessing: [   numbers
0       -5
1       -1
2        0
3        2
4       10,    numbers
0       -5
1       -1
2        0
3        2
4       10]
[Parallel(n_jobs=2)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=2)]: Done   2 out of   2 | elapsed:    0.5s remaining:    0.0s
---------------------------------------------------------------------------
_RemoteTraceback                          Traceback (most recent call last)
_RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/ian/miniconda3/envs/trial_loky_pandas_extension/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py", line 431, in _process_worker
    r = call_item()
  File "/home/ian/miniconda3/envs/trial_loky_pandas_extension/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py", line 285, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/home/ian/miniconda3/envs/trial_loky_pandas_extension/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "/home/ian/miniconda3/envs/trial_loky_pandas_extension/lib/python3.8/site-packages/joblib/parallel.py", line 262, in __call__
    return [func(*args, **kwargs)
  File "/home/ian/miniconda3/envs/trial_loky_pandas_extension/lib/python3.8/site-packages/joblib/parallel.py", line 262, in <listcomp>
    return [func(*args, **kwargs)
  File "/home/ian/workspace/scratch/trial_loky_pandas_extension/extn_trial.py", line 38, in my_fn
    return df.extn.double_if_positive_function()
  File "/home/ian/miniconda3/envs/trial_loky_pandas_extension/lib/python3.8/site-packages/pandas/core/generic.py", line 5465, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'extn'
"""

The above exception was the direct cause of the following exception:

AttributeError                            Traceback (most recent call last)
~/workspace/scratch/trial_loky_pandas_extension/extn_trial.py in <module>
     90     #AttributeError: 'DataFrame' object has no attribute 'extn'
     91     #"""
---> 92     results = Parallel(n_jobs=2, backend='loky', verbose=1)(delayed(my_fn)(df,) for n in range(2))
     93     print(f"Result from using Loky:", results) # we never get here due to the AttributeError

~/miniconda3/envs/trial_loky_pandas_extension/lib/python3.8/site-packages/joblib/parallel.py in __call__(self, iterable)
   1052 
   1053             with self._backend.retrieval_context():
-> 1054                 self.retrieve()
   1055             # Make sure that we get a last message telling us we are done
   1056             elapsed_time = time.time() - self._start_time

~/miniconda3/envs/trial_loky_pandas_extension/lib/python3.8/site-packages/joblib/parallel.py in retrieve(self)
    931             try:
    932                 if getattr(self._backend, 'supports_timeout', False):
--> 933                     self._output.extend(job.get(timeout=self.timeout))
    934                 else:
    935                     self._output.extend(job.get())

~/miniconda3/envs/trial_loky_pandas_extension/lib/python3.8/site-packages/joblib/_parallel_backends.py in wrap_future_result(future, timeout)
    540         AsyncResults.get from multiprocessing."""
    541         try:
--> 542             return future.result(timeout=timeout)
    543         except CfTimeoutError as e:
    544             raise TimeoutError from e

~/miniconda3/envs/trial_loky_pandas_extension/lib/python3.8/concurrent/futures/_base.py in result(self, timeout)
    437                 raise CancelledError()
    438             elif self._state == FINISHED:
--> 439                 return self.__get_result()
    440             else:
    441                 raise TimeoutError()

~/miniconda3/envs/trial_loky_pandas_extension/lib/python3.8/concurrent/futures/_base.py in __get_result(self)
    386     def __get_result(self):
    387         if self._exception:
--> 388             raise self._exception
    389         else:
    390             return self._result

AttributeError: 'DataFrame' object has no attribute 'extn'

```

```
In [31]: joblib.__version__
Out[31]: '1.0.1'

In [32]: pd.show_versions()

INSTALLED VERSIONS
------------------
commit           : f2c8480af2f25efdbd803218b9d87980f416563e
python           : 3.8.8.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.4.0-65-generic
Version          : #73-Ubuntu SMP Mon Jan 18 17:25:17 UTC 2021
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_GB.UTF-8
LOCALE           : en_GB.UTF-8

pandas           : 1.2.3
numpy            : 1.20.1
pytz             : 2021.1
dateutil         : 2.8.1
pip              : 21.0.1
setuptools       : 49.6.0.post20210108
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : 7.21.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None
```

**Comment by ianozsvald** [comment]
I checked the installed `cloudpickle` and it seems that it pickles up the extended DataFrame just fine:

```
In [43]: from joblib.externals import cloudpickle

In [44]: df_dumped = cloudpickle.dumps(df)

In [45]: dir(cloudpickle.loads(df_dumped).extn.double_if_positive_function)
Out[45]: 
['__call__',
... # all the expected methods are present
```

I'm not sure how Loky uses `cloudpickle` (maybe not with the default arguments?) so I'm not sure what would need to be investigated next, I'm happy to hear ideas.
