### ISSUE TITLE
Pickle5 error with scikit-learn loky backend on Linux with Python<3.8  

### ISSUE THREAD

**Issue by rikturr** [joblib/joblib#1186]
Hello! I was getting the following error when training a scikit-learn model with n_jobs=-1, and I see that its been mentioned before on different issues in related packages [here](https://github.com/scikit-learn-contrib/skope-rules/issues/18) and #827.

Example code (happens for several estimators):
```python
X, y = ...
clf = LogisticRegression(C=0.1, n_jobs=-1)
clf.fit(X, y)
```

Error:
```
TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.
```

Upon digging into my environment further, I realized that the issue (at least in my case) is due to pickle5 being used because my env is on Python 3.7. Here is a way to replicate:

Setup environment:
```bash
conda create -n working -c conda-forge python==3.7 scikit-learn==0.24.0 joblib==1.0.1 pickle5
conda activate working
```

Python code:
```python
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression

X, y = make_classification(
    n_samples=10,
    n_features=20,
)
clf = LogisticRegression(C=0.1, n_jobs=-1)
clf.fit(X, y)
print(clf)
```

<details>
<summary>This should be the stack trace</summary>
RecursionError: maximum recursion depth exceeded while calling a Python object

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/envs/working/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py", line 1416, in fit
    for class_, warm_start_coef_ in zip(classes_, warm_start_coef))
  File "/opt/conda/envs/working/lib/python3.7/site-packages/joblib/parallel.py", line 1041, in __call__
    if self.dispatch_one_batch(iterator):
  File "/opt/conda/envs/working/lib/python3.7/site-packages/joblib/parallel.py", line 859, in dispatch_one_batch
    self._dispatch(tasks)
  File "/opt/conda/envs/working/lib/python3.7/site-packages/joblib/parallel.py", line 777, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/opt/conda/envs/working/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 531, in apply_async
    future = self._workers.submit(SafeFunction(func))
  File "/opt/conda/envs/working/lib/python3.7/site-packages/joblib/externals/loky/reusable_executor.py", line 178, in submit
    fn, *args, **kwargs)
  File "/opt/conda/envs/working/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 1122, in submit
    self._ensure_executor_running()
  File "/opt/conda/envs/working/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 1096, in _ensure_executor_running
    self._adjust_process_count()
  File "/opt/conda/envs/working/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 1087, in _adjust_process_count
    p.start()
  File "/opt/conda/envs/working/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/opt/conda/envs/working/lib/python3.7/site-packages/joblib/externals/loky/backend/process.py", line 39, in _Popen
    return Popen(process_obj)
  File "/opt/conda/envs/working/lib/python3.7/site-packages/joblib/externals/loky/backend/popen_loky_posix.py", line 52, in __init__
    self._launch(process_obj)
  File "/opt/conda/envs/working/lib/python3.7/site-packages/joblib/externals/loky/backend/popen_loky_posix.py", line 132, in _launch
    reduction.dump(prep_data, fp)
  File "/opt/conda/envs/working/lib/python3.7/site-packages/joblib/externals/loky/backend/reduction.py", line 264, in dump
    _LokyPickler(file, reducers=reducers, protocol=protocol).dump(obj)
  File "/opt/conda/envs/working/lib/python3.7/site-packages/joblib/externals/cloudpickle/cloudpickle_fast.py", line 570, in dump
    raise pickle.PicklingError(msg) from e
pickle5.pickle.PicklingError: Could not pickle object as excessively deep recursion required.
</details>

There are a few workarounds here:
- Use `multiprocessing` backend 
```python
with joblib.parallel_backend('multiprocessing'):
    clf.fit(X, y)
```
- Upgrade to Python>=3.8
- Remove pickle5 
 
In the env I'm working with pickle5 is required because it also utilizes RAPIDS, which [requires pickle5 for Python<3.8](https://github.com/rapidsai/integration/blob/526fba70b3758bbed1e0bf4ae0d2b7241ad7229b/conda/recipes/rapids/meta.yaml#L45).

I'm opening an issue here in the hopes that someone searching this error can reference one of the above workarounds, or if there could be a fix made to joblib to handle this case.

**Comment by sandipde** [comment]
I ran into this exact same issue today. removing pickle5 was the solution that I had to resort for now.
