### ISSUE TITLE
I still face Issues with all the requirements satisfied.

### ISSUE THREAD

**Issue by Carlos1729** [joblib/joblib#1193]
I still face Issues with all the requirements satisfied.

Traceback (most recent call last):
  File "/anaconda3/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/anaconda3/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/anaconda3/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Projectfolder/predict_risk/views.py", line 31, in PredictRisk
    standard_scalar = GetStandardScalarForHeart()
  File "/Projectfolder/predict_risk/data_provider.py", line 32, in GetStandardScalarForHeart
    return GetPickleFile(config['heart']['scalar_file'])
  File "/projectfolder/predict_risk/data_provider.py", line 27, in GetPickleFile
    return pickle.load(open(os.path.join(dir, filepath), "rb"))
  File "/anaconda3/lib/python3.8/site-packages/sklearn/__init__.py", line 65, in <module>
    from .utils._show_versions import show_versions
  File "/anaconda3/lib/python3.8/site-packages/sklearn/utils/__init__.py", line 13, in <module>
    from .validation import (as_float_array,
  File "/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py", line 27, in <module>
    from ..utils._joblib import Memory
  File "/anaconda3/lib/python3.8/site-packages/sklearn/utils/_joblib.py", line 18, in <module>
    from ..externals.joblib import __all__   # noqa
  File "/anaconda3/lib/python3.8/site-packages/sklearn/externals/joblib/__init__.py", line 119, in <module>
    from .parallel import Parallel
  File "/anaconda3/lib/python3.8/site-packages/sklearn/externals/joblib/parallel.py", line 32, in <module>
    from .externals.cloudpickle import dumps, loads
  File "/anaconda3/lib/python3.8/site-packages/sklearn/externals/joblib/externals/cloudpickle/__init__.py", line 3, in <module>
    from .cloudpickle import *
  File "/anaconda3/lib/python3.8/site-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py", line 150, in <module>
    _cell_set_template_code = _make_cell_set_template_code()
  File "/anaconda3/lib/python3.8/site-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py", line 131, in _make_cell_set_template_code
    return types.CodeType(
TypeError: an integer is required (got type bytes)

@ogrisel

_Originally posted by @Carlos1729 in https://github.com/joblib/joblib/issues/917#issuecomment-863135660_

**Comment by Carlos1729** [comment]
Resolved

**Comment by Carlos1729** [comment]
It still doesn't work
