### ISSUE TITLE
Dask parallel backend throws error when iterating over items with more than 1 worker node; works fine with 1 worker node

### ISSUE THREAD

**Issue by SimplicityGuy** [joblib/joblib#1201]
Python: `Python 3.7.3` (on Linux), `Python 3.9.6` (on Mac)
Version: `joblib==1.0.1`
Pandas: `pandas==1.3.0`
Numpy: `numpy==1.21.0`
Dask: `dask==2021.6.2`, `distributed==2021.6.2`

I have the following code, which works fine when there's only 1 worker in my Dask cluster:
```python3
with parallel_backend("dask"):
    results = Parallel(n_jobs=-1, verbose=10)(
        delayed(match)(fn, vectorizer, tf_idf_matrix, values, n)
        for fn in files["c.file"]
        if len(fn) != 0
    )
```

However, as soon as I add a second node to the Dask cluster, this code stops working. Here's the output of the app running:
```python3
[Parallel(n_jobs=-1)]: Using backend DaskDistributedBackend with 14 concurrent workers.
[Parallel(n_jobs=-1)]: Done   4 tasks      | elapsed:   21.0s
[Parallel(n_jobs=-1)]: Done  13 tasks      | elapsed:   21.0s
[Parallel(n_jobs=-1)]: Done  22 tasks      | elapsed:   21.0s
Traceback (most recent call last):
  File "alt.py", line 207, in <module>
    for fn in files["c.file"]
  File "/home/datum/.local/lib/python3.7/site-packages/joblib/parallel.py", line 1054, in __call__
    self.retrieve()
  File "/home/datum/.local/lib/python3.7/site-packages/joblib/parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
TypeError: 'CancelledError' object is not iterable
```

There have been reports of this issue going back to 2018. Some references: https://github.com/joblib/joblib/issues/959, https://github.com/scikit-learn/scikit-learn/issues/12315, https://github.com/scikit-learn/scikit-learn/issues/15383.

Any ideas as to what's causing this?

**Comment by DiptoChakrabarty** [comment]
I am also facing the same error , only difference is I am using dask version 2021.5.0 with same joblib version . Would like to know how to fix it.

**Comment by SimplicityGuy** [comment]
Here is a very simple repro of this when I have 2 workers in my Dask cluster.
```python3
import json
from itertools import chain

import numpy as np
import pandas as pd
from dask.distributed import Client
from joblib import Parallel, delayed, parallel_backend
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.neighbors import NearestNeighbors


def get_top_n_match(row, n=2):
    row_count = row.getnnz()
    if row_count == 0:
        return None
    elif row_count <= n:
        result = zip(row.indices, row.data)
    else:
        arg_idx = np.argpartition(row.data, -n)[-n:]
        result = zip(row.indices[arg_idx], row.data[arg_idx])
    return sorted(result, key=(lambda x: -x[1]))


def match_name(input_name, vectorizer, name_vectors, name_df, n=2):
    input_name_vector = vectorizer.transform([input_name])
    result_vector = input_name_vector.dot(name_vectors.T)
    matched_data = [get_top_n_match(row, n) for row in result_vector]
    flat_matched_data = [
        tup for data_row in matched_data if data_row is not None for tup in data_row
    ]
    if len(flat_matched_data) == 0:
        return []
    lkp_idx, lkp_sim = zip(*flat_matched_data)
    nr_matches = len(lkp_idx)
    matched_names = [None] * nr_matches
    for i in range(nr_matches):
        matched_names[i] = {
            "match": name_df["name"].iloc[lkp_idx[i]],
            "score": lkp_sim[i] * 100,
            "c.file": input_name,
        }
    return matched_names


def ngrams(string, n=3):
    fraction = 1 / 3
    limit = int(len(string) * fraction)
    string = f" {string[0:limit]} {string} "
    return ["".join(ngram) for ngram in zip(*[string[i:] for i in range(n)])]


print(f"Dask cluster starting...")
client = Client("localhost:8786")
values = pd.DataFrame(np.random.rand(5000, 2), columns=["id", "name"])
values["name"] = values["name"].astype(str)
files = pd.DataFrame(np.random.rand(750, 2), columns=["file", "c.file"])
files["file"] = files["file"].astype(str)
files["c.file"] = files["c.file"].astype(str)
print(f"... values shape {values.shape}")
print(f"... files shape {files.shape}")


vectorizer = TfidfVectorizer(
    analyzer=ngrams, encoding="ascii", stop_words="english", strip_accents="ascii"
)
tf_idf_matrix = vectorizer.fit_transform(values["name"])
print(f"... tf-idf shape {tf_idf_matrix.shape}")

n = 2
with parallel_backend("dask"):
    results = Parallel(n_jobs=-1, verbose=10)(
        delayed(match_name)(fn, vectorizer, tf_idf_matrix, values, n)
        for fn in files["c.file"]
        if len(fn) != 0
    )

matches = pd.DataFrame(list(chain(*results)))
print(f"... matches shape {matches.shape}")

matched = pd.merge(files, matches)
print(f"... matched shape {matched.shape}")
```

The output is:
```python3
... values shape (5000, 2)
... files shape (750, 2)
... tf-idf shape (5000, 1221)
[Parallel(n_jobs=-1)]: Using backend DaskDistributedBackend with 14 concurrent workers.
[Parallel(n_jobs=-1)]: Done   4 tasks      | elapsed:    0.3s
[Parallel(n_jobs=-1)]: Done  13 tasks      | elapsed:    0.3s
[Parallel(n_jobs=-1)]: Done  22 tasks      | elapsed:    0.3s
Traceback (most recent call last):
  File "repro.py", line 73, in <module>
    for fn in files["c.file"]
  File "/home/datum/.local/lib/python3.7/site-packages/joblib/parallel.py", line 1054, in __call__
    self.retrieve()
  File "/home/datum/.local/lib/python3.7/site-packages/joblib/parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
TypeError: 'CancelledError' object is not iterable
```

**Comment by drfraser** [comment]
I am trying to track down something similar in my code (a segfault) though I was getting CancelledError sometimes.  Is the setup with 2 workers using up all possible threads/cores? Is there any lower level parallelization somewhere you are not aware of? I ended up concluding my CancelledErrors was a problem with a lack of resources.

Another thing is to put a try/except in match_name() and catch any exceptions. To deal with the problem of being in a child process, I explicitly opened a file with os.open and wrote the exception message etc to that. I also used faulthandler.dump_traceback to dump its output to that file descriptor. It ended up being an exception in scikit-learn/joblib, but that info doesn't get passed back to you, just CancelledError or a message about a segfault.

**Comment by hamedhsn** [comment]
I have the same problem. want to test my training on dask cluster in Kubernetes. this code runs in a pod in Kubernetes. 
am using `daskdev/dask` image for everything.  
```
 python sklearn-dist.py
Fitting 2 folds for each of 1 candidates, totalling 2 fits
Traceback (most recent call last):
  File "sklearn-dist.py", line 25, in <module>
    search.fit(digits.data, digits.target)
  File "/opt/conda/lib/python3.8/site-packages/sklearn/utils/validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/sklearn/model_selection/_search.py", line 841, in fit
    self._run_search(evaluate_candidates)
  File "/opt/conda/lib/python3.8/site-packages/sklearn/model_selection/_search.py", line 1633, in _run_search
    evaluate_candidates(ParameterSampler(
  File "/opt/conda/lib/python3.8/site-packages/sklearn/model_selection/_search.py", line 795, in evaluate_candidates
    out = parallel(delayed(_fit_and_score)(clone(base_estimator),
  File "/opt/conda/lib/python3.8/site-packages/joblib/parallel.py", line 1054, in __call__
    self.retrieve()
  File "/opt/conda/lib/python3.8/site-packages/joblib/parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
TypeError: 'CancelledError' object is not iterable
```
this is my code:
```
cat sklearn-dist.py
import numpy as np
from dask.distributed import Client

from sklearn.datasets import load_digits
from sklearn.model_selection import RandomizedSearchCV
from sklearn.svm import SVC

client = Client("dask-cluster-scheduler:8786")

digits = load_digits()

param_space = {
    'C': np.logspace(-6, 6, 13),
    'gamma': np.logspace(-8, 8, 17),
    'tol': np.logspace(-4, -1, 4),
    'class_weight': [None, 'balanced'],
}

model = SVC(kernel='rbf')
search = RandomizedSearchCV(model, param_space, cv=2, n_iter=1, verbose=10)

import joblib
with joblib.parallel_backend('dask'):
    search.fit(digits.data, digits.target)
```

**Comment by Artimi** [comment]
I'd add that this error is very cryptic. Basically we should not try to extend with something that might not be an iterable.
```
 self._output.extend(job.get(timeout=self.timeout))
```
I think it would make sense the `CancelledError` directly, not the exception that was caused by `CancelledError`.

**Comment by AndreasPrev** [comment]
I have run into the same issue scaling up scikit-learn using dask parallel backend:

```
  File "/home/anp22022/miniconda3/envs/winter_identification/Lib_v1_parallel_dask_HPC.py", line 141, in train_rf
    `rf_model.fit(train_df.iloc[:,` :-1], train_df.iloc[:, -1])
  File "/home/anp22022/miniconda3/envs/winter_identification/lib/python3.11/site-packages/daal4py/sklearn/_device_offload.py", line 88, in wrapper_with_self
    return wrapper_impl(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anp22022/miniconda3/envs/winter_identification/lib/python3.11/site-packages/daal4py/sklearn/_device_offload.py", line 74, in wrapper_impl
    result = _run_on_device(func, q, obj, *hostargs, **hostkwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anp22022/miniconda3/envs/winter_identification/lib/python3.11/site-packages/daal4py/sklearn/_device_offload.py", line 65, in _run_on_device
    return dispatch_by_obj(obj, func, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anp22022/miniconda3/envs/winter_identification/lib/python3.11/site-packages/daal4py/sklearn/_device_offload.py", line 53, in dispatch_by_obj
    return func(obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anp22022/miniconda3/envs/winter_identification/lib/python3.11/site-packages/daal4py/sklearn/ensemble/_forest.py", line 453, in fit
    return super().fit(X, y, sample_weight=sample_weight)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anp22022/miniconda3/envs/winter_identification/lib/python3.11/site-packages/sklearn/base.py", line 1151, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anp22022/miniconda3/envs/winter_identification/lib/python3.11/site-packages/sklearn/ensemble/_forest.py", line 456, in fit
    trees = Parallel(
            ^^^^^^^^^
  File "/home/anp22022/miniconda3/envs/winter_identification/lib/python3.11/site-packages/sklearn/utils/parallel.py", line 65, in __call__
    return super().__call__(iterable_with_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anp22022/miniconda3/envs/winter_identification/lib/python3.11/site-packages/joblib/parallel.py", line 1944, in __call__
    return output if self.return_generator else list(output)
                                                ^^^^^^^^^^^^
  File "/home/anp22022/miniconda3/envs/winter_identification/lib/python3.11/site-packages/joblib/parallel.py", line 1587, in _get_outputs
    yield from self._retrieve()
  File "/home/anp22022/miniconda3/envs/winter_identification/lib/python3.11/site-packages/joblib/parallel.py", line 1710, in _retrieve
    for result in batched_results:
TypeError: 'CancelledError' object is not iterable

```
It does not matter whether it is a .fit call to an estimator or a GridSearchCV object. The same issue comes up. I am just mentioning that this .fit call is inside a for loop while a call to joblib's Parallel is also present.

**Comment by tbugfinder** [comment]
any workarounds - sort of?

**Comment by tbugfinder** [comment]
I swtiched from dask backend to the ray backend and got rid of the issue and finally have a working environment.
https://docs.ray.io/en/latest/ray-more-libs/joblib.html
