### ISSUE TITLE
Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1 warning with scikit-learn

### ISSUE THREAD

**Issue by troehling** [joblib/joblib#1204]
I am getting a very similar warning as described in #978 when running with multiiprocessing: `Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1`. I use scikit-learn's DBSCAN algorithm with n_jobs > 1. Is this message intended? I assume that the computation is running only on a single core in this case. Is there any possibility how I could get this to work or do I have to either launch the algorithm in the main process of implement multiprocessing myself?

@tomMoral suggested to use multiprocessing.set_start_method('loky') but it does not seem to be working for me.

_Originally posted by @troehling in https://github.com/joblib/joblib/issues/978#issuecomment-881266514_

**Comment by tomMoral** [comment]
Do you have a minimal reproducible working example, so I can better understand what you are trying to do?
Also, when you say it is not working, does it throws an error or do you see the same warning?

**Comment by troehling** [comment]
Right now the example is more or less the opposite of minimal but I am trying to create a minimal example right now. To give a very brief overview: I have a process (which is not the main process) that receives data continuously and should execute DBSCAN with the data it receives. I will update you when I have a minimal reproducible example. 

I am still getting the same warning as before.

**Comment by troehling** [comment]
I have observed that `multiprocessing.set_start_method('loky')` does not seem to have any impact as `multiprocessing.get_start_method()` still returns `fork`. Do I have to somehow initialise loky before? The main application is based on pyqt, could this be the problem?

**Comment by tomMoral** [comment]
This is weird. On my computer, I get:
![image](https://user-images.githubusercontent.com/3321081/125940592-ff7f100a-a8cd-41ca-9fd9-eae5c6b8e974.png)

**Comment by troehling** [comment]
I did something very similar:
```
import multiprocessing
from PyQt5.QtWidgets import *
import sklearn  # Library that imports joblib and loky in my case

def main():
    print(multiprocessing.get_start_method())

    app = QApplication([])
    label = QLabel('Hello World!')
    label.show()
    app.exec_()


if __name__ == "__main__":
    multiprocessing.set_start_method('loky')
    main()
```

I checked this first without all the instructions from qt and added those later to check whether this could be an issue. Still this example works. Ich will try to get it closer to my actual version, to see where it breaks.

**Comment by troehling** [comment]
I do not exactly know what changed but when i call the program directly I can now see a different error message in my programm:

```
Traceback (most recent call last):
  File "pymepix-viewer/pymepixviewer/main.py", line 582, in <module>
    multiprocessing.set_start_method('loky')
  File "/usr/lib/python3.7/multiprocessing/context.py", line 242, in set_start_method
    raise RuntimeError('context has already been set')
RuntimeError: context has already been set
```

If i set `force=True` for `set_start_method` there seem to be conflicts with loky for other threads/processes:
```
  File "/usr/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.7/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/lib/python3/dist-packages/joblib/externals/loky/backend/process.py", line 37, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3/dist-packages/joblib/externals/loky/backend/popen_loky_posix.py", line 52, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3/dist-packages/joblib/externals/loky/backend/popen_loky_posix.py", line 133, in _launch
    reduction.dump(process_obj, fp)
  File "/usr/lib/python3/dist-packages/joblib/externals/loky/backend/reduction.py", line 236, in dump
    _LokyPickler(file, reducers=reducers, protocol=protocol).dump(obj)
  File "/usr/lib/python3/dist-packages/joblib/externals/cloudpickle/cloudpickle.py", line 284, in dump
    return Pickler.dump(self, obj)
  File "/usr/lib/python3.7/pickle.py", line 437, in dump
    self.save(obj)
  File "/usr/lib/python3.7/pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python3.7/pickle.py", line 662, in save_reduce
    save(state)
  File "/usr/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.7/pickle.py", line 856, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.7/pickle.py", line 882, in _batch_setitems
    save(v)
  File "/usr/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.7/pickle.py", line 856, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.7/pickle.py", line 882, in _batch_setitems
    save(v)
  File "/usr/lib/python3.7/pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python3.7/pickle.py", line 638, in save_reduce
    save(args)
  File "/usr/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.7/pickle.py", line 771, in save_tuple
    save(element)
  File "/usr/lib/python3.7/pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python3.7/pickle.py", line 638, in save_reduce
    save(args)
  File "/usr/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.7/pickle.py", line 771, in save_tuple
    save(element)
  File "/usr/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.7/pickle.py", line 771, in save_tuple
    save(element)
  File "/usr/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.7/pickle.py", line 856, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.7/pickle.py", line 887, in _batch_setitems
    save(v)
  File "/usr/lib/python3.7/pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python3.7/pickle.py", line 662, in save_reduce
    save(state)
  File "/usr/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.7/pickle.py", line 856, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.7/pickle.py", line 887, in _batch_setitems
    save(v)
  File "/usr/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.7/pickle.py", line 771, in save_tuple
    save(element)
  File "/usr/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.7/pickle.py", line 771, in save_tuple
    save(element)
  File "/usr/lib/python3.7/pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python3.7/pickle.py", line 662, in save_reduce
    save(state)
  File "/usr/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.7/pickle.py", line 856, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.7/pickle.py", line 882, in _batch_setitems
    save(v)
  File "/usr/lib/python3.7/pickle.py", line 524, in save
    rv = reduce(self.proto)
TypeError: can't pickle mmap.mmap objects
```

**Comment by troehling** [comment]
The issue seems to be definitely on my side. There is a library that I use (https://github.com/CFEL-CMI/pymepix) that seems to be the cause for the issues I have. No matter which file of this library I include in my minimal example it breaks and I get this error when executing `set_start_method`.
```
Traceback (most recent call last):
  File "loky_issue_example.py", line 27, in <module>
    multiprocessing.set_start_method('loky')
  File "/usr/lib/python3.7/multiprocessing/context.py", line 242, in set_start_method
    raise RuntimeError('context has already been set')
RuntimeError: context has already been set

```

I know this problem is probably not on your side of thing but if you do have any idea what happens there or how I could fix this I would greatly appreciate it as I am totally clueless myself at this point.

My example to reproduce the issue is this right now. No matter which one of the imports I use, it breaks. Even though some are only enums.
```
import multiprocessing

# from pymepix.timepixdef import PacketType
# from pymepix.timepixdef import Polarity
# from pymepix.timepixdef import OperationMode
# from pymepix.timepixdef import GrayCounter
# from pymepix.timepixdef import TestPulse
# from pymepix.timepixdef import SuperPixel
# from pymepix.timepixdef import TimerOverflow
# from pymepix.timepixdef import TestPulseDigAnalog
# from pymepix.timepixdef import TestPulseGenerator
# from pymepix.timepixdef import TimeofArrivalClock
# from pymepix.timepixdef import DacRegisterCodes
from pymepix.core.log import PymepixLogger

from my_enum import PacketType


import sklearn


def main():
    print(multiprocessing.get_start_method())


if __name__ == "__main__":
    multiprocessing.set_start_method('loky')
    main()
```

**Comment by troehling** [comment]
This minimal reproducible example is working on my system:
```
import multiprocessing

import sklearn


_proc_log_queue = multiprocessing.Queue()


def main():
    print(multiprocessing.get_start_method())


if __name__ == "__main__":
    multiprocessing.set_start_method('loky')
    main()
```

Then I do get this error:
```
Traceback (most recent call last):
  File "loky_issue_example.py", line 13, in <module>
    multiprocessing.set_start_method('loky')
  File "/usr/lib/python3.7/multiprocessing/context.py", line 242, in set_start_method
    raise RuntimeError('context has already been set')
RuntimeError: context has already been set
```

**Comment by GaelVaroquaux** [comment]
What if you import multiprocessing after sklearn? Does it change
anything?

**Comment by troehling** [comment]
I tried and sadly changing the order of the imports does not change anything. The error is still the same.

**Comment by tomMoral** [comment]
Actually, when you instantiate `multiprocessing.Queue`, under the hood this sets the default context.
So you should actually move `set_start_method`

```python
import multiprocessing
import sklearn

multiprocessing.set_start_method('loky')
_proc_log_queue = multiprocessing.Queue()

def main():
    print(multiprocessing.get_start_method())

if __name__ == "__main__":
    main()
```

**Comment by tomMoral** [comment]
This is to prevent you from creating a `multiprocessing.Queue` with the fork context and then launching processes with `loky` context.
This is also what causes the large traceback when you run the method with `force`, as the context qbetween the queue and the process do not match I guess.

**Comment by troehling** [comment]
Ohh yes at least in my example I can do it this way. Still the error I have already had with `force=True` exists if I shift the `set_start_method`-call above the creation of the queue. If you have an idea right now what might cause this I'd appreciate  it. I will take a closer look into it myself and try to make adjustments in my example to make it reproducible.

> I do not exactly know what changed but when i call the program directly I can now see a different error message in my programm:
> 
> ```
> Traceback (most recent call last):
>   File "pymepix-viewer/pymepixviewer/main.py", line 582, in <module>
>     multiprocessing.set_start_method('loky')
>   File "/usr/lib/python3.7/multiprocessing/context.py", line 242, in set_start_method
>     raise RuntimeError('context has already been set')
> RuntimeError: context has already been set
> ```
> 
> If i set `force=True` for `set_start_method` there seem to be conflicts with loky for other threads/processes:
> 
> ```
>   File "/usr/lib/python3.7/multiprocessing/process.py", line 112, in start
>     self._popen = self._Popen(self)
>   File "/usr/lib/python3.7/multiprocessing/context.py", line 223, in _Popen
>     return _default_context.get_context().Process._Popen(process_obj)
>   File "/usr/lib/python3/dist-packages/joblib/externals/loky/backend/process.py", line 37, in _Popen
>     return Popen(process_obj)
>   File "/usr/lib/python3/dist-packages/joblib/externals/loky/backend/popen_loky_posix.py", line 52, in __init__
>     self._launch(process_obj)
>   File "/usr/lib/python3/dist-packages/joblib/externals/loky/backend/popen_loky_posix.py", line 133, in _launch
>     reduction.dump(process_obj, fp)
>   File "/usr/lib/python3/dist-packages/joblib/externals/loky/backend/reduction.py", line 236, in dump
>     _LokyPickler(file, reducers=reducers, protocol=protocol).dump(obj)
>   File "/usr/lib/python3/dist-packages/joblib/externals/cloudpickle/cloudpickle.py", line 284, in dump
>     return Pickler.dump(self, obj)
>   File "/usr/lib/python3.7/pickle.py", line 437, in dump
>     self.save(obj)
>   File "/usr/lib/python3.7/pickle.py", line 549, in save
>     self.save_reduce(obj=obj, *rv)
>   File "/usr/lib/python3.7/pickle.py", line 662, in save_reduce
>     save(state)
>   File "/usr/lib/python3.7/pickle.py", line 504, in save
>     f(self, obj) # Call unbound method with explicit self
>   File "/usr/lib/python3.7/pickle.py", line 856, in save_dict
>     self._batch_setitems(obj.items())
>   File "/usr/lib/python3.7/pickle.py", line 882, in _batch_setitems
>     save(v)
>   File "/usr/lib/python3.7/pickle.py", line 504, in save
>     f(self, obj) # Call unbound method with explicit self
>   File "/usr/lib/python3.7/pickle.py", line 856, in save_dict
>     self._batch_setitems(obj.items())
>   File "/usr/lib/python3.7/pickle.py", line 882, in _batch_setitems
>     save(v)
>   File "/usr/lib/python3.7/pickle.py", line 549, in save
>     self.save_reduce(obj=obj, *rv)
>   File "/usr/lib/python3.7/pickle.py", line 638, in save_reduce
>     save(args)
>   File "/usr/lib/python3.7/pickle.py", line 504, in save
>     f(self, obj) # Call unbound method with explicit self
>   File "/usr/lib/python3.7/pickle.py", line 771, in save_tuple
>     save(element)
>   File "/usr/lib/python3.7/pickle.py", line 549, in save
>     self.save_reduce(obj=obj, *rv)
>   File "/usr/lib/python3.7/pickle.py", line 638, in save_reduce
>     save(args)
>   File "/usr/lib/python3.7/pickle.py", line 504, in save
>     f(self, obj) # Call unbound method with explicit self
>   File "/usr/lib/python3.7/pickle.py", line 771, in save_tuple
>     save(element)
>   File "/usr/lib/python3.7/pickle.py", line 504, in save
>     f(self, obj) # Call unbound method with explicit self
>   File "/usr/lib/python3.7/pickle.py", line 771, in save_tuple
>     save(element)
>   File "/usr/lib/python3.7/pickle.py", line 504, in save
>     f(self, obj) # Call unbound method with explicit self
>   File "/usr/lib/python3.7/pickle.py", line 856, in save_dict
>     self._batch_setitems(obj.items())
>   File "/usr/lib/python3.7/pickle.py", line 887, in _batch_setitems
>     save(v)
>   File "/usr/lib/python3.7/pickle.py", line 549, in save
>     self.save_reduce(obj=obj, *rv)
>   File "/usr/lib/python3.7/pickle.py", line 662, in save_reduce
>     save(state)
>   File "/usr/lib/python3.7/pickle.py", line 504, in save
>     f(self, obj) # Call unbound method with explicit self
>   File "/usr/lib/python3.7/pickle.py", line 856, in save_dict
>     self._batch_setitems(obj.items())
>   File "/usr/lib/python3.7/pickle.py", line 887, in _batch_setitems
>     save(v)
>   File "/usr/lib/python3.7/pickle.py", line 504, in save
>     f(self, obj) # Call unbound method with explicit self
>   File "/usr/lib/python3.7/pickle.py", line 771, in save_tuple
>     save(element)
>   File "/usr/lib/python3.7/pickle.py", line 504, in save
>     f(self, obj) # Call unbound method with explicit self
>   File "/usr/lib/python3.7/pickle.py", line 771, in save_tuple
>     save(element)
>   File "/usr/lib/python3.7/pickle.py", line 549, in save
>     self.save_reduce(obj=obj, *rv)
>   File "/usr/lib/python3.7/pickle.py", line 662, in save_reduce
>     save(state)
>   File "/usr/lib/python3.7/pickle.py", line 504, in save
>     f(self, obj) # Call unbound method with explicit self
>   File "/usr/lib/python3.7/pickle.py", line 856, in save_dict
>     self._batch_setitems(obj.items())
>   File "/usr/lib/python3.7/pickle.py", line 882, in _batch_setitems
>     save(v)
>   File "/usr/lib/python3.7/pickle.py", line 524, in save
>     rv = reduce(self.proto)
> TypeError: can't pickle mmap.mmap objects
> ```
> 
> I am still trying to create a minimum working example but thus far I my example does not yield the error/ warning. There must be some component I am still missing that causes the issue.

**Comment by troehling** [comment]
I was finally able to create a minimal example for this issue:
```
import multiprocessing

import loky
multiprocessing.set_start_method('loky')

import ctypes
import time
from multiprocessing.sharedctypes import Value

# _proc_log_queue = multiprocessing.Queue()

class Processor(multiprocessing.Process):

    def __init__(self):
        super(multiprocessing.Process, self).__init__()
        self._record = Value(ctypes.c_bool, False) # required for inter process communication

    def run(self):
        for i in range(10):
            time.sleep(.5)
            print('running...')

def main():
    print(multiprocessing.get_start_method())

    sampler = Processor()
    sampler.start()


if __name__ == "__main__":
    main()
```

The `Value` object is required for communication with other processes and if the corresponding line is removed or commented out it seems to work (better). Instead of the very long error trace, another error occurs:
```
Traceback (most recent call last):
  File "loky_issue_example.py", line 31, in <module>
    main()
  File "loky_issue_example.py", line 27, in main
    sampler.start()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.7/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/home/cfelcmi/.local/lib/python3.7/site-packages/loky/backend/process.py", line 39, in _Popen
    return Popen(process_obj)
  File "/home/cfelcmi/.local/lib/python3.7/site-packages/loky/backend/popen_loky_posix.py", line 52, in __init__
    self._launch(process_obj)
  File "/home/cfelcmi/.local/lib/python3.7/site-packages/loky/backend/popen_loky_posix.py", line 157, in _launch
    pid = fork_exec(cmd_python, self._fds, env=process_obj.env)
AttributeError: 'Processor' object has no attribute 'env'
```

Maybe I should create a new (or maybe two) issue in the loky repository?

**Comment by R-N** [comment]
> I am getting a very similar warning as described in #978 when running with multiiprocessing: `Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1`. I use scikit-learn's DBSCAN algorithm with `n_jobs > 1`. Is this message intended? I assume that the computation is running only on a single core in this case. Is there any possibility how I could get this to work or do I have to either launch the algorithm in the main process of implement multiprocessing myself?
> 
> @tomMoral suggested to use `multiprocessing.set_start_method('loky')` but it does not seem to be working for me.
> 
> _Originally posted by @troehling in [#978 (comment)](https://github.com/joblib/joblib/issues/978#issuecomment-881266514)_

Hello, I tried to set start method to loky but I'm getting ValueError: cannot find context for 'loky'. Am I missing something?

**Comment by ogrisel** [comment]
@R-N this seems like a problem unrelated to @troehling's report. Can you please open a dedicated issue with information about the versions of Python and loky (and joblib if you use it) and a minimal reproducing example code snippet for your problem?

If your problem does not involve joblib, please open the issue on the loky github repository instead.

**Comment by ogrisel** [comment]
@troehling I just tried your reproducer with Python 3.11 and the current loky version on macOS and I get:

```python-traceback
Traceback (most recent call last):
  File "/Users/ogrisel/tmp/loky_start_method.py", line 31, in <module>
    main()
  File "/Users/ogrisel/tmp/loky_start_method.py", line 27, in main
    sampler.start()
  File "/Users/ogrisel/miniforge3/envs/dev/lib/python3.11/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
  File "/Users/ogrisel/miniforge3/envs/dev/lib/python3.11/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ogrisel/code/loky/loky/backend/process.py", line 45, in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/ogrisel/code/loky/loky/backend/popen_loky_posix.py", line 48, in __init__
    self._launch(process_obj)
  File "/Users/ogrisel/code/loky/loky/backend/popen_loky_posix.py", line 104, in _launch
    reduction.dump(process_obj, fp)
  File "/Users/ogrisel/code/loky/loky/backend/reduction.py", line 208, in dump
    _LokyPickler(file, reducers=reducers, protocol=protocol).dump(obj)
  File "/Users/ogrisel/code/cloudpickle/cloudpickle/cloudpickle.py", line 1245, in dump
    return super().dump(obj)
           ^^^^^^^^^^^^^^^^^
TypeError: cannot pickle 'mmap.mmap' object
```

instead of the error your report.

Note that the `set_start_method` should better be moved at the beginning of the `main` function.

I don't think we support using `multiprocessing.sharedctypes` constructs in loky. Note that they do not seem to work with the `spawn` start method which the `loky` start method extends.

It might be possible to extend the `_LokyPickler` to reconstruct such `mmap` instances `multiprocessing.sharedctypes` all use that under the hood for all operating systems but this sounds like non trivial work to do (and properly test) to add official support.

Feel free to open an feature request in loky for this (and ideally a PR).
