### ISSUE TITLE
Nested parallel loops causing errors

### ISSUE THREAD

**Issue by experiencedft** [joblib/joblib#1205]
I was testing the concept of nested parallel loops in preparation for a large simulation that would require them. Consider this minimal working example: 

```python
import numpy as np 
from joblib import Parallel, delayed
import time 

def makeExp(x):
    return np.exp(x)

def func(ar):
    results = Parallel(n_jobs=-1, backend="loky")(delayed(makeExp)(elem) for elem in ar)
    return results

array_of_arrays = [np.linspace(0, 10, 10).tolist() for i in range(10)]

results = [0 for i in range(len(array_of_arrays))]
for i in range(len(array_of_arrays)): 
    results[i] = func(array_of_arrays[i])

print(results)
```

This code works perfectly well and returns an array of array of numbers to which have been applied the exponential function.

Now consider the following modification to the code, the goal being to test nested parallel loops with the Loky backend. 

```python
import numpy as np 
from joblib import Parallel, delayed
import time 

def makeExp(x):
    return np.exp(x)

def func(ar):
    results = Parallel(n_jobs=-1, backend="loky")(delayed(makeExp)(elem) for elem in ar)
    return results

array_of_arrays = [np.linspace(0, 10, 10).tolist() for i in range(10)]

results = Parallel(n_jobs=-1, verbose = 0, backend='loky')(delayed(func)(array) for array in array_of_arrays)

print(results)
```

This seems to work, the two prints return identical arrays. However, in the case of the second code snippet, after the execution of the print command, I am greeted with a long sequence of error messages all similar to this one:

```
--------------------------------------------------------------------------------
LokyProcess-13:10 failed with traceback: 
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/neptu/.local/lib/python3.9/site-packages/joblib/externals/loky/backend/popen_loky_posix.py", line 199, in <module>
    process_obj = pickle.load(from_parent)
  File "/home/neptu/.local/lib/python3.9/site-packages/joblib/externals/loky/backend/synchronize.py", line 116, in __setstate__
    self._semlock = _SemLock._rebuild(*state)
FileNotFoundError: [Errno 2] No such file or directory
```

It is my first time using Joblib and I don't understand what is going on here. There is a long sequence of such error messages, and then the program keeps running without seemingly doing anything until I forcibly terminate it with keyboard interrupt. 

What could be the cause of this issue?

**Comment by jeremyfix** [comment]
Tested your code on joblib 1.4.2 with python 3.10.12 ; The second snippet is not returning any error in my case.

Can this be due to a version of job lib ? There seems to be issue for example with joblib < 1.2.0 ; see #1247

**Comment by lesteve** [comment]
Thanks @jeremyfix. It seems very similar to #1247 indeed, let's close this one.
