### ISSUE TITLE
BrokenProcessPool: A task has failed to un-serialize.

### ISSUE THREAD

**Issue by ginward** [joblib/joblib#1225]
This issue is related to [this one here](https://github.com/scikit-learn-contrib/hdbscan/issues/494#issuecomment-932359617). 

It seems that when [calling Joblib on a large numpy array in Cython](https://github.com/scikit-learn-contrib/hdbscan/blob/d9464decd6a07162d72e20020b263f8c8589c414/hdbscan/_hdbscan_boruvka.pyx#L426), the following error arises: 
```

---------------------------------------------------------------------------
_RemoteTraceback                          Traceback (most recent call last)
_RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/rds/user/jw983/hpc-work/pytorch-env2/lib/python3.9/site-packages/joblib/externals/loky/process_executor.py", line 404, in _process_worker
    call_item = call_queue.get(block=True, timeout=timeout)
  File "/usr/local/software/spack/spack-git/opt/spack/linux-rhel7-broadwell/gcc-5.4.0/python-3.9.6-sbr552hsx3zanhgi3ekdjp4rsn6o6ejq/lib/python3.9/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
  File "sklearn/neighbors/_binary_tree.pxi", line 1057, in sklearn.neighbors._kd_tree.BinaryTree.__setstate__
  File "sklearn/neighbors/_binary_tree.pxi", line 999, in sklearn.neighbors._kd_tree.BinaryTree._update_memviews
  File "stringsource", line 658, in View.MemoryView.memoryview_cwrapper
  File "stringsource", line 349, in View.MemoryView.memoryview.__cinit__
ValueError: buffer source array is read-only
"""

The above exception was the direct cause of the following exception:

BrokenProcessPool                         Traceback (most recent call last)
/tmp/ipykernel_53757/3427515298.py in <module>
----> 1 test=hdbscan_model.fit_predict(embeddings_init)

/rds/user/jw983/hpc-work/pytorch-env2/lib/python3.9/site-packages/hdbscan/hdbscan_.py in fit_predict(self, X, y)
    956             cluster labels
    957         """
--> 958         self.fit(X)
    959         return self.labels_
    960 

/rds/user/jw983/hpc-work/pytorch-env2/lib/python3.9/site-packages/hdbscan/hdbscan_.py in fit(self, X, y)
    934          self._condensed_tree,
    935          self._single_linkage_tree,
--> 936          self._min_spanning_tree) = hdbscan(X, **kwargs)
    937 
    938         if self.prediction_data:

/rds/user/jw983/hpc-work/pytorch-env2/lib/python3.9/site-packages/hdbscan/hdbscan_.py in hdbscan(X, min_cluster_size, min_samples, alpha, cluster_selection_epsilon, max_cluster_size, metric, p, leaf_size, algorithm, memory, approx_min_span_tree, gen_min_span_tree, core_dist_n_jobs, cluster_selection_method, allow_single_cluster, match_reference_implementation, **kwargs)
    622                                            gen_min_span_tree, **kwargs)
    623             else:
--> 624                 (single_linkage_tree, result_min_span_tree) = memory.cache(
    625                     _hdbscan_boruvka_kdtree)(X, min_samples, alpha,
    626                                              metric, p, leaf_size,

/rds/user/jw983/hpc-work/pytorch-env2/lib/python3.9/site-packages/joblib/memory.py in __call__(self, *args, **kwargs)
    350 
    351     def __call__(self, *args, **kwargs):
--> 352         return self.func(*args, **kwargs)
    353 
    354     def call_and_shelve(self, *args, **kwargs):

/rds/user/jw983/hpc-work/pytorch-env2/lib/python3.9/site-packages/hdbscan/hdbscan_.py in _hdbscan_boruvka_kdtree(X, min_samples, alpha, metric, p, leaf_size, approx_min_span_tree, gen_min_span_tree, core_dist_n_jobs, **kwargs)
    275 
    276     tree = KDTree(X, metric=metric, leaf_size=leaf_size, **kwargs)
--> 277     alg = KDTreeBoruvkaAlgorithm(tree, min_samples, metric=metric,
    278                                  leaf_size=leaf_size // 3,
    279                                  approx_min_span_tree=approx_min_span_tree,

hdbscan/_hdbscan_boruvka.pyx in hdbscan._hdbscan_boruvka.KDTreeBoruvkaAlgorithm.__init__()

hdbscan/_hdbscan_boruvka.pyx in hdbscan._hdbscan_boruvka.KDTreeBoruvkaAlgorithm._compute_bounds()

/rds/user/jw983/hpc-work/pytorch-env2/lib/python3.9/site-packages/joblib/parallel.py in __call__(self, iterable)
   1052 
   1053             with self._backend.retrieval_context():
-> 1054                 self.retrieve()
   1055             # Make sure that we get a last message telling us we are done
   1056             elapsed_time = time.time() - self._start_time

/rds/user/jw983/hpc-work/pytorch-env2/lib/python3.9/site-packages/joblib/parallel.py in retrieve(self)
    931             try:
    932                 if getattr(self._backend, 'supports_timeout', False):
--> 933                     self._output.extend(job.get(timeout=self.timeout))
    934                 else:
    935                     self._output.extend(job.get())

/rds/user/jw983/hpc-work/pytorch-env2/lib/python3.9/site-packages/joblib/_parallel_backends.py in wrap_future_result(future, timeout)
    540         AsyncResults.get from multiprocessing."""
    541         try:
--> 542             return future.result(timeout=timeout)
    543         except CfTimeoutError as e:
    544             raise TimeoutError from e

/usr/local/software/spack/spack-git/opt/spack/linux-rhel7-broadwell/gcc-5.4.0/python-3.9.6-sbr552hsx3zanhgi3ekdjp4rsn6o6ejq/lib/python3.9/concurrent/futures/_base.py in result(self, timeout)
    443                     raise CancelledError()
    444                 elif self._state == FINISHED:
--> 445                     return self.__get_result()
    446                 else:
    447                     raise TimeoutError()

/usr/local/software/spack/spack-git/opt/spack/linux-rhel7-broadwell/gcc-5.4.0/python-3.9.6-sbr552hsx3zanhgi3ekdjp4rsn6o6ejq/lib/python3.9/concurrent/futures/_base.py in __get_result(self)
    388         if self._exception:
    389             try:
--> 390                 raise self._exception
    391             finally:
    392                 # Break a reference cycle with the exception in self._exception

BrokenProcessPool: A task has failed to un-serialize. Please ensure that the arguments of the function are all picklable.
```

I have tried using the multiprocessing backend and locky backend but to not avail. It seems that problem only occurs if I have a numpy array of the shape above (140000, 5). If the array size is smaller than (130000, 5), the code runs with no issue. 

You can replicate the problem with the code here: 

```

import pandas as pd

from sklearn.decomposition import PCA

import numpy as np

from hdbscan import HDBSCAN

embeddings_ = np.random.rand(140000,5)

pca = PCA(n_components=5)
embeddings_pca = pca.fit_transform(embeddings_)



scale = np.std(embeddings_pca, axis=0)/1e-4
embeddings_init=((embeddings_pca - np.mean(embeddings_pca, axis=0))/scale)



# Setting HDBSCAN model
hdbscan_model = HDBSCAN(min_cluster_size=10, metric='euclidean', cluster_selection_method='eom', prediction_data=True, core_dist_n_jobs=2)



test=hdbscan_model.fit_predict(embeddings_init)
```

If you change the number of rows to below 130000, the problem disappears. 

Any idea why?

**Comment by drtobybrown** [comment]
Is this fixed? I'm still finding is issue in 1.3.2.
