### ISSUE TITLE
 The sklearn.linear_model.logistic module is  deprecated

### ISSUE THREAD

**Issue by loretoparisi** [joblib/joblib#1233]
Installing the latest version of `joblib` I get this error

```
Traceback (most recent call last):
  File "/usr/local/bin/explicitly", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/explicitly/__init__.py", line 112, in main
    process_args(args)
  File "/usr/local/lib/python3.7/dist-packages/explicitly/__init__.py", line 64, in process_args
    classifier = joblib.load(os.path.join(DATA_PATH,'explicit_lyrics_classifier/logistic_regression_explicitness.jl'))
  File "/usr/local/lib/python3.7/dist-packages/joblib/numpy_pickle.py", line 587, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/usr/local/lib/python3.7/dist-packages/joblib/numpy_pickle.py", line 506, in _unpickle
    obj = unpickler.load()
  File "/usr/lib/python3.7/pickle.py", line 1088, in load
    dispatch[key[0]](self)
  File "/usr/lib/python3.7/pickle.py", line 1376, in load_global
    klass = self.find_class(module, name)
  File "/usr/lib/python3.7/pickle.py", line 1426, in find_class
    __import__(module, level=0)
ModuleNotFoundError: No module named 'sklearn.linear_model.logistic'
```

to fix it I had to force the `sklearn` version to:

```
Cython
scikit-learn==0.22.1
joblib
```

**Comment by jjerphan** [comment]
`joblib.load` is only guaranteed to work when using the same version of the libraries used for `joblib.dump` — the versions look like they have changed.

**Comment by jjerphan** [comment]
For more information about models' persistence using `pickle`, you can check [scikit-learn's security & maintainability limitations for model persistence](https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations).

**Comment by ogrisel** [comment]
I agree with @jjerphan's analysis. Closing.

**Comment by nicklu666** [comment]
so. what is the solution?
