### ISSUE TITLE
Process terminated without finishing

### ISSUE THREAD

**Issue by LukeHankey** [joblib/joblib#1251]
For an unexpected reason, one of my processes terminates before completing and not just at the end but nearer to the start of the function being executed.

I run 6 jobs in parallel which all iterate over another function 200 times and returns some result from those 200 iterations. All other 5 jobs run to completion, that is all 200 iterations are ran and results are returned but one of the processes ends around iteration 15 and I'm not sure why when all others are fine.

**Comment by LukeHankey** [comment]
Having resolved this, I found that at the end of the last process to finish, the error is raised. Not so great in my case, especially where the function runs for 12 hours or so. It would be great if there was a fail fast option to raise any errors in any processes and then kill all. Having to wait 12 hours or so to not get any results is painful.

**Comment by ogrisel** [comment]
This should be the default behavior. If you could provide us with a minimal reproducer we can investigate.

Here is a minimal example that does **not** reproduce your problem:

```python
from joblib import Parallel, delayed
from time import sleep


def failing_func(i):
    print(f"starting {i}")
    sleep(0.3)
    if i == 3:
        raise ValueError(f"I don't like {i}")
    print(f"done with {i}")


Parallel(n_jobs=4)(delayed(failing_func)(i) for i in range(1000))
```

the output is:

```
starting 0
starting 1
starting 2
starting 3
done with 0
starting 4
done with 1
done with 2
starting 5
starting 6
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/ogrisel/code/joblib/joblib/externals/loky/process_executor.py", line 436, in _process_worker
    r = call_item()
  File "/Users/ogrisel/code/joblib/joblib/externals/loky/process_executor.py", line 288, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/Users/ogrisel/code/joblib/joblib/_parallel_backends.py", line 620, in __call__
    return self.func(*args, **kwargs)
  File "/Users/ogrisel/code/joblib/joblib/parallel.py", line 287, in __call__
    return [func(*args, **kwargs)
  File "/Users/ogrisel/code/joblib/joblib/parallel.py", line 287, in <listcomp>
    return [func(*args, **kwargs)
  File "/private/tmp/debug_joblib.py", line 9, in failing_func
    raise ValueError(f"I don't like {i}")
ValueError: I don't like 3
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/private/tmp/debug_joblib.py", line 13, in <module>
    Parallel(n_jobs=4)(delayed(failing_func)(i) for i in range(1000))
  File "/Users/ogrisel/code/joblib/joblib/parallel.py", line 1093, in __call__
    self.retrieve()
  File "/Users/ogrisel/code/joblib/joblib/parallel.py", line 972, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/Users/ogrisel/code/joblib/joblib/_parallel_backends.py", line 567, in wrap_future_result
    return future.result(timeout=timeout)
  File "/Users/ogrisel/mambaforge/envs/dev/lib/python3.9/concurrent/futures/_base.py", line 438, in result
    return self.__get_result()
  File "/Users/ogrisel/mambaforge/envs/dev/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
ValueError: I don't like 3
```

as you can see it fails fast and does not wait for all the 1000 jobs to complete.

**Comment by ogrisel** [comment]
I think in your case you have nested parallel loops? Is this right? I am not sure because English is ambiguous. If you can provide us with minimal Python code to illustrate the problem on a toy case that runs fast, what you observe and what you would have expected instead, that would help.

**Comment by tomMoral** [comment]
From what I understood, the problem is that you have 2 tasks, the first one is long (10s) while the second error immediatly, you  need 10s to get the error:

```python
import time


def func(x, t_start):
    if x == 1:
         print(f"Raise error after {time.time() - t_start:.1f}s")
         raise ValueError()
    time.sleep(10)
    return x
 
 
from joblib import Parallel, delayed

t_start = time.time()
try:
    Parallel(n_jobs=2)(delayed(func)(x, t_start) for x in range(2))
except:
    print(f"Got error after: {time.time() - t_start:.1f}s")
```
```
Raise error after 0.2s
Got error after: 10.3s
```

We the work we are doing in #588, we intend to change this behavior. On the `return_generator` branch, the same code gives:
```
Raise error after 0.2s
Got error after: 0.3s
```

As the results cannot be retrieved in this case, I agree that it makes sense to exit early. But @ogrisel if you think the expected behavior is not this one, we can discuss this.

**Comment by ogrisel** [comment]
Thanks for the clarification. I am fine with the new behavior, I am not sure if all backends will be able to return early in case of error: for instance on a threading or dask backend, the already scheduled long running tasks will still run in the background even if there results will be discarded. So CPU resources will still be used in workers threads, so if the exception is caught in the main process thread and a new parallel call issued afterwards, one will probably still need to wait for  the previously scheduled work to terminate before being able to schedule new calls.

**Comment by ogrisel** [comment]
I tried some interactive tests with https://github.com/joblib/joblib/pull/588 and, surprisingly, the call to `p._backend.terminate()` does not seem to block for long as I would have expected for some magical reason.

**Comment by tomMoral** [comment]
Yes, because in this case, we call terminate on the `ThreadPool` but this is non-blocking as we do not terminate the threads  nor join them. The computations continues in background even after we call `close` and `terminate`, as it is the case in `abort_everything` for the threading backend
A simple example to show this:

```python
import time
from multiprocessing.pool import ThreadPool

pool = ThreadPool()
r = pool.apply_async(time.sleep, (100,))
time.sleep(0.2)
pool.close()
pool.terminate()
time.sleep(0.2)
print("Running threads:", sum([p.is_alive() for p in pool._pool]))

```

Gives `Running threads: 1`.

**Comment by ogrisel** [comment]
Thanks. I am not sure if this behavior is good or bad, but trying to interrupt thread execution is probably going to be challenging to achieve in a safe and robust manner so maybe the current behavior is ok.

**Comment by LukeHankey** [comment]
> I think in your case you have nested parallel loops? Is this right? I am not sure because English is ambiguous. If you can provide us with minimal Python code to illustrate the problem on a toy case that runs fast, what you observe and what you would have expected instead, that would help.

Hi, sorry for the long delay. There are nested loops, yes. We use the skrebate package for MultiSURF which uses joblib under the hood. As part of our machine learning app, the number of features were reduced to 0 on the 14/200 iteration which was picked up by sklearn further down the line where we actually fit our model. In this case, it was the random forest classifier which also uses joblib under the hood, I believe.
