### ISSUE TITLE
ipython>=8.0 crashes when there is an exception in joblib parallel process

### ISSUE THREAD

**Issue by mityakrylov** [joblib/joblib#1252]
I found that in jupyterlab with ipython>=8.0 no error from joblib child process is shown in notebook. 

Way to reproduce:
```
pip install jupyterlab joblib
```

In jupyter notebook:
```
from joblib import Parallel, delayed

def my_func(a):
    if a == 7:
        raise ValueError(f'wrong input: {a}')
    return a ** 2

items = list(range(1, 10))
with Parallel(n_jobs=8) as parallel:
    res = parallel(delayed(my_func)(item) for item in items)
```

There is no error from joblib shown in notebook (and there is a strange warning about history logging): 
<img width="1069" alt="joblib_ipython8" src="https://user-images.githubusercontent.com/1423550/151557650-11c20af0-7170-42cf-b210-1d3a33e9286d.png">

Instead there is an error in jupyterlab logs:
```
[IPKernelApp] ERROR | Exception in message handler:
joblib.externals.loky.process_executor._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/dmkrylov/envs/jupyter/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py", line 436, in _process_worker
    r = call_item()
  File "/home/dmkrylov/envs/jupyter/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py", line 288, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/home/dmkrylov/envs/jupyter/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "/home/dmkrylov/envs/jupyter/lib/python3.8/site-packages/joblib/parallel.py", line 262, in __call__
    return [func(*args, **kwargs)
  File "/home/dmkrylov/envs/jupyter/lib/python3.8/site-packages/joblib/parallel.py", line 262, in <listcomp>
    return [func(*args, **kwargs)
  File "/home/dmkrylov/tmp/ipykernel_22235/1264567453.py", line 6, in my_func
ValueError: wrong input: 7
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dmkrylov/envs/jupyter/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3251, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/home/dmkrylov/tmp/ipykernel_22235/1264567453.py", line 12, in <module>
    res = parallel(delayed(my_func)(item) for item in items)
  File "/home/dmkrylov/envs/jupyter/lib/python3.8/site-packages/joblib/parallel.py", line 1056, in __call__
    self.retrieve()
  File "/home/dmkrylov/envs/jupyter/lib/python3.8/site-packages/joblib/parallel.py", line 935, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/dmkrylov/envs/jupyter/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
ValueError: wrong input: 7

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dmkrylov/envs/jupyter/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 1934, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'ValueError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dmkrylov/envs/jupyter/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3191, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/home/dmkrylov/envs/jupyter/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3268, in run_code
    self.showtraceback(running_compiled_code=True)
  File "/home/dmkrylov/envs/jupyter/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 1936, in showtraceback
    stb = self.InteractiveTB.structured_traceback(etype,
  File "/home/dmkrylov/envs/jupyter/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1105, in structured_traceback
    return FormattedTB.structured_traceback(
  File "/home/dmkrylov/envs/jupyter/lib/python3.8/site-packages/IPython/core/ultratb.py", line 999, in structured_traceback
    return VerboseTB.structured_traceback(
  File "/home/dmkrylov/envs/jupyter/lib/python3.8/site-packages/IPython/core/ultratb.py", line 871, in structured_traceback
    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,
  File "/home/dmkrylov/envs/jupyter/lib/python3.8/site-packages/IPython/core/ultratb.py", line 775, in format_exception_as_a_whole
    assert etb is not None
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dmkrylov/envs/jupyter/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 1934, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'AssertionError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dmkrylov/envs/jupyter/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 2814, in _run_cell
    return runner(coro)
  File "/home/dmkrylov/envs/jupyter/lib/python3.8/site-packages/IPython/core/async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "/home/dmkrylov/envs/jupyter/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3012, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/home/dmkrylov/envs/jupyter/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3210, in run_ast_nodes
    self.showtraceback()
  File "/home/dmkrylov/envs/jupyter/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 1936, in showtraceback
    stb = self.InteractiveTB.structured_traceback(etype,
  File "/home/dmkrylov/envs/jupyter/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1105, in structured_traceback
    return FormattedTB.structured_traceback(
  File "/home/dmkrylov/envs/jupyter/lib/python3.8/site-packages/IPython/core/ultratb.py", line 999, in structured_traceback
    return VerboseTB.structured_traceback(
  File "/home/dmkrylov/envs/jupyter/lib/python3.8/site-packages/IPython/core/ultratb.py", line 871, in structured_traceback
    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,
  File "/home/dmkrylov/envs/jupyter/lib/python3.8/site-packages/IPython/core/ultratb.py", line 775, in format_exception_as_a_whole
    assert etb is not None
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dmkrylov/envs/jupyter/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 1934, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'AssertionError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dmkrylov/envs/jupyter/lib/python3.8/site-packages/ipykernel/kernelbase.py", line 357, in dispatch_shell
    await result
  File "/home/dmkrylov/envs/jupyter/lib/python3.8/site-packages/ipykernel/kernelbase.py", line 652, in execute_request
    reply_content = await reply_content
  File "/home/dmkrylov/envs/jupyter/lib/python3.8/site-packages/ipykernel/ipkernel.py", line 353, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/home/dmkrylov/envs/jupyter/lib/python3.8/site-packages/ipykernel/zmqshell.py", line 532, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/home/dmkrylov/envs/jupyter/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 2768, in run_cell
    result = self._run_cell(
  File "/home/dmkrylov/envs/jupyter/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 2819, in _run_cell
    self.showtraceback(running_compiled_code=True)
  File "/home/dmkrylov/envs/jupyter/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 1936, in showtraceback
    stb = self.InteractiveTB.structured_traceback(etype,
  File "/home/dmkrylov/envs/jupyter/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1105, in structured_traceback
    return FormattedTB.structured_traceback(
  File "/home/dmkrylov/envs/jupyter/lib/python3.8/site-packages/IPython/core/ultratb.py", line 999, in structured_traceback
    return VerboseTB.structured_traceback(
  File "/home/dmkrylov/envs/jupyter/lib/python3.8/site-packages/IPython/core/ultratb.py", line 871, in structured_traceback
    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,
  File "/home/dmkrylov/envs/jupyter/lib/python3.8/site-packages/IPython/core/ultratb.py", line 775, in format_exception_as_a_whole
    assert etb is not None
AssertionError
```

Python version 3.8.9, pip list:
```
Package              Version
-------------------- ---------
anyio                3.5.0
argon2-cffi          21.3.0
argon2-cffi-bindings 21.2.0
asttokens            2.0.5
attrs                21.4.0
Babel                2.9.1
backcall             0.2.0
black                21.12b0
bleach               4.1.0
certifi              2021.10.8
cffi                 1.15.0
charset-normalizer   2.0.10
click                8.0.3
debugpy              1.5.1
decorator            5.1.1
defusedxml           0.7.1
entrypoints          0.3
executing            0.8.2
idna                 3.3
importlib-resources  5.4.0
ipykernel            6.7.0
ipython              8.0.1
ipython-genutils     0.2.0
jedi                 0.18.1
Jinja2               3.0.3
joblib               1.1.0
json5                0.9.6
jsonschema           4.4.0
jupyter-client       7.1.2
jupyter-core         4.9.1
jupyter-server       1.13.4
jupyterlab           3.2.8
jupyterlab-pygments  0.1.2
jupyterlab-server    2.10.3
MarkupSafe           2.0.1
matplotlib-inline    0.1.3
mistune              0.8.4
mypy-extensions      0.4.3
nbclassic            0.3.5
nbclient             0.5.10
nbconvert            6.4.1
nbformat             5.1.3
nest-asyncio         1.5.4
notebook             6.4.8
packaging            21.3
pandocfilters        1.5.0
parso                0.8.3
pathspec             0.9.0
pexpect              4.8.0
pickleshare          0.7.5
pip                  21.3.1
platformdirs         2.4.1
prometheus-client    0.13.0
prompt-toolkit       3.0.26
ptyprocess           0.7.0
pure-eval            0.2.2
pycparser            2.21
Pygments             2.11.2
pyparsing            3.0.7
pyrsistent           0.18.1
python-dateutil      2.8.2
pytz                 2021.3
pyzmq                22.3.0
requests             2.27.1
Send2Trash           1.8.0
setuptools           60.2.0
six                  1.16.0
sniffio              1.2.0
stack-data           0.1.4
terminado            0.13.1
testpath             0.5.0
tomli                1.2.3
tornado              6.1
traitlets            5.1.1
typing_extensions    4.0.1
urllib3              1.26.8
wcwidth              0.2.5
webencodings         0.5.1
websocket-client     1.2.3
wheel                0.37.1
zipp                 3.7.0
```

After installing latest ipython7 `pip install ipyhon==7.31.1` error is shown as expected:
<img width="1072" alt="joblib_ipython7" src="https://user-images.githubusercontent.com/1423550/151558273-51a52f78-059a-464e-ab89-d9c0b00b14cb.png">

Can it can be somehow related to [traceback improvements](https://ipython.readthedocs.io/en/stable/whatsnew/version8.html#traceback-improvements) in ipython8? Is there something that can be done on joblib side or should I report this to ipython issues?

**Comment by lesteve** [comment]
I can get a similar error with `multiprocessing.Pool` so it seems like an issue with `IPython` 8 and not joblib. It would be great if you can report this problem to the IPython developers.

```py
import math

from multiprocessing import Pool

pool = Pool(1)

pool.apply(math.sqrt, -1)
```

Full output within IPython 8:
```
Python 3.9.5 | packaged by conda-forge | (default, Jun 19 2021, 00:32:32) 
Type 'copyright', 'credits' or 'license' for more information
IPython 8.0.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import math
   ...: 
   ...: from multiprocessing import Pool
   ...: 
   ...: pool = Pool(1)
   ...: 
   ...: pool.apply(math.sqrt, -1)
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/lesteve/miniconda3/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
TypeError: math.sqrt() argument after * must be an iterable, not int
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lesteve/miniconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3251, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-1-2d4056f56556>", line 7, in <module>
    pool.apply(math.sqrt, -1)
  File "/home/lesteve/miniconda3/lib/python3.9/multiprocessing/pool.py", line 357, in apply
    return self.apply_async(func, args, kwds).get()
  File "/home/lesteve/miniconda3/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
TypeError: math.sqrt() argument after * must be an iterable, not int

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lesteve/miniconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 1934, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'TypeError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lesteve/miniconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3191, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/home/lesteve/miniconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3268, in run_code
    self.showtraceback(running_compiled_code=True)
  File "/home/lesteve/miniconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 1936, in showtraceback
    stb = self.InteractiveTB.structured_traceback(etype,
  File "/home/lesteve/miniconda3/lib/python3.9/site-packages/IPython/core/ultratb.py", line 1105, in structured_traceback
    return FormattedTB.structured_traceback(
  File "/home/lesteve/miniconda3/lib/python3.9/site-packages/IPython/core/ultratb.py", line 999, in structured_traceback
    return VerboseTB.structured_traceback(
  File "/home/lesteve/miniconda3/lib/python3.9/site-packages/IPython/core/ultratb.py", line 871, in structured_traceback
    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,
  File "/home/lesteve/miniconda3/lib/python3.9/site-packages/IPython/core/ultratb.py", line 775, in format_exception_as_a_whole
    assert etb is not None
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lesteve/miniconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 1934, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'AssertionError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lesteve/miniconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 2814, in _run_cell
    return runner(coro)
  File "/home/lesteve/miniconda3/lib/python3.9/site-packages/IPython/core/async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "/home/lesteve/miniconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3012, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/home/lesteve/miniconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3210, in run_ast_nodes
    self.showtraceback()
  File "/home/lesteve/miniconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 1936, in showtraceback
    stb = self.InteractiveTB.structured_traceback(etype,
  File "/home/lesteve/miniconda3/lib/python3.9/site-packages/IPython/core/ultratb.py", line 1105, in structured_traceback
    return FormattedTB.structured_traceback(
  File "/home/lesteve/miniconda3/lib/python3.9/site-packages/IPython/core/ultratb.py", line 999, in structured_traceback
    return VerboseTB.structured_traceback(
  File "/home/lesteve/miniconda3/lib/python3.9/site-packages/IPython/core/ultratb.py", line 871, in structured_traceback
    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,
  File "/home/lesteve/miniconda3/lib/python3.9/site-packages/IPython/core/ultratb.py", line 775, in format_exception_as_a_whole
    assert etb is not None
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lesteve/miniconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 1934, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'AssertionError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lesteve/miniconda3/bin/ipython", line 11, in <module>
    sys.exit(start_ipython())
  File "/home/lesteve/miniconda3/lib/python3.9/site-packages/IPython/__init__.py", line 123, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/home/lesteve/miniconda3/lib/python3.9/site-packages/traitlets/config/application.py", line 846, in launch_instance
    app.start()
  File "/home/lesteve/miniconda3/lib/python3.9/site-packages/IPython/terminal/ipapp.py", line 316, in start
    self.shell.mainloop()
  File "/home/lesteve/miniconda3/lib/python3.9/site-packages/IPython/terminal/interactiveshell.py", line 611, in mainloop
    self.interact()
  File "/home/lesteve/miniconda3/lib/python3.9/site-packages/IPython/terminal/interactiveshell.py", line 604, in interact
    self.run_cell(code, store_history=True)
  File "/home/lesteve/miniconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 2768, in run_cell
    result = self._run_cell(
  File "/home/lesteve/miniconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 2819, in _run_cell
    self.showtraceback(running_compiled_code=True)
  File "/home/lesteve/miniconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 1936, in showtraceback
    stb = self.InteractiveTB.structured_traceback(etype,
  File "/home/lesteve/miniconda3/lib/python3.9/site-packages/IPython/core/ultratb.py", line 1105, in structured_traceback
    return FormattedTB.structured_traceback(
  File "/home/lesteve/miniconda3/lib/python3.9/site-packages/IPython/core/ultratb.py", line 999, in structured_traceback
    return VerboseTB.structured_traceback(
  File "/home/lesteve/miniconda3/lib/python3.9/site-packages/IPython/core/ultratb.py", line 871, in structured_traceback
    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,
  File "/home/lesteve/miniconda3/lib/python3.9/site-packages/IPython/core/ultratb.py", line 775, in format_exception_as_a_whole
    assert etb is not None
AssertionError

If you suspect this is an IPython 8.0.1 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True
```

**Comment by lesteve** [comment]
I am closing this for now, but don't hesitate to reopen if I was wrong in my analysis of the problem.

**Comment by lesteve** [comment]
Actually I looked in the IPython issue tracker and the problem reported here is very similar to https://github.com/ipython/ipython/issues/12467.
