### ISSUE TITLE
issue with Parallel and pandas series backend interaction with large datasets

### ISSUE THREAD

**Issue by ariannalong** [joblib/joblib#1284]
Hi there,

I'm using Parallel on my function "make_masses". I'm only asking it to loop 100 times, but the data that goes into the function has about 1.5 million rows (and two columns). Parallel works perfectly fine on smaller slices of this data set (I've tested up to 5k rows) but when I ask it to run on the full 1.5M, it throws the following error:

```
---------------------------------------------------------------------------
_RemoteTraceback                          Traceback (most recent call last)
_RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/series.py", line 1062, in __setitem__
    self._set_with_engine(key, value)
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/series.py", line 1095, in _set_with_engine
    loc = self.index._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 82, in pandas._libs.index.IndexEngine.get_loc
TypeError: '[ 624204  375707  904524 ...  839086  229595 1213560]' is an invalid key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.9/site-packages/joblib/externals/loky/process_executor.py", line 436, in _process_worker
    r = call_item()
  File "/opt/anaconda3/lib/python3.9/site-packages/joblib/externals/loky/process_executor.py", line 288, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/joblib/_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/joblib/parallel.py", line 262, in __call__
    return [func(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/joblib/parallel.py", line 262, in <listcomp>
    return [func(*args, **kwargs)
  File "/var/folders/9m/58ctzpdj30v5n2q5c6llkmsx6hn1lb/T/ipykernel_17538/2503849451.py", line 35, in make_masses
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/series.py", line 1088, in __setitem__
    self._set_with(key, value)
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/series.py", line 1123, in _set_with
    self._set_labels(key, value)
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/series.py", line 1135, in _set_labels
    self._set_values(indexer, value)
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/series.py", line 1141, in _set_values
    self._mgr = self._mgr.setitem(indexer=key, value=value)
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/internals/managers.py", line 355, in setitem
    return self.apply("setitem", indexer=indexer, value=value)
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/internals/managers.py", line 327, in apply
    applied = getattr(b, f)(**kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/internals/blocks.py", line 983, in setitem
    values[indexer] = value
ValueError: assignment destination is read-only
"""

The above exception was the direct cause of the following exception:

ValueError                                Traceback (most recent call last)
/var/folders/9m/58ctzpdj30v5n2q5c6llkmsx6hn1lb/T/ipykernel_17538/813242355.py in <module>
     47 
     48     perc_sb = r
---> 49     mock_masses = Parallel(n_jobs=num_cores)(delayed(make_masses)(mocks['z'], mocks['l']) for i in range(100))
     50     masses.append(mock_masses)
     51 

/opt/anaconda3/lib/python3.9/site-packages/joblib/parallel.py in __call__(self, iterable)
   1054 
   1055             with self._backend.retrieval_context():
-> 1056                 self.retrieve()
   1057             # Make sure that we get a last message telling us we are done
   1058             elapsed_time = time.time() - self._start_time

/opt/anaconda3/lib/python3.9/site-packages/joblib/parallel.py in retrieve(self)
    933             try:
    934                 if getattr(self._backend, 'supports_timeout', False):
--> 935                     self._output.extend(job.get(timeout=self.timeout))
    936                 else:
    937                     self._output.extend(job.get())

/opt/anaconda3/lib/python3.9/site-packages/joblib/_parallel_backends.py in wrap_future_result(future, timeout)
    540         AsyncResults.get from multiprocessing."""
    541         try:
--> 542             return future.result(timeout=timeout)
    543         except CfTimeoutError as e:
    544             raise TimeoutError from e

/opt/anaconda3/lib/python3.9/concurrent/futures/_base.py in result(self, timeout)
    443                     raise CancelledError()
    444                 elif self._state == FINISHED:
--> 445                     return self.__get_result()
    446                 else:
    447                     raise TimeoutError()

/opt/anaconda3/lib/python3.9/concurrent/futures/_base.py in __get_result(self)
    388         if self._exception:
    389             try:
--> 390                 raise self._exception
    391             finally:
    392                 # Break a reference cycle with the exception in self._exception

ValueError: assignment destination is read-only
```

I thought it was perhaps related to [this issue](https://github.com/scikit-learn/scikit-learn/issues/5956) (where the solution is to increase the 'max_nbytes' in joblib/parallel.py), but if I do increase 'max_nbytes' to e.g. 1000M, I get this issue (which is seems similar to the first one):

```
---------------------------------------------------------------------------
_RemoteTraceback                          Traceback (most recent call last)
_RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/series.py", line 1062, in __setitem__
    self._set_with_engine(key, value)
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/series.py", line 1095, in _set_with_engine
    loc = self.index._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 82, in pandas._libs.index.IndexEngine.get_loc
TypeError: '1377263' is an invalid key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.9/site-packages/joblib/externals/loky/process_executor.py", line 436, in _process_worker
    r = call_item()
  File "/opt/anaconda3/lib/python3.9/site-packages/joblib/externals/loky/process_executor.py", line 288, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/joblib/_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/joblib/parallel.py", line 262, in __call__
    return [func(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/joblib/parallel.py", line 262, in <listcomp>
    return [func(*args, **kwargs)
  File "/var/folders/9m/58ctzpdj30v5n2q5c6llkmsx6hn1lb/T/ipykernel_17811/2503849451.py", line 44, in make_masses
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/series.py", line 1088, in __setitem__
    self._set_with(key, value)
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/series.py", line 1123, in _set_with
    self._set_labels(key, value)
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/series.py", line 1131, in _set_labels
    indexer: np.ndarray = self.index.get_indexer(key)
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3486, in get_indexer
    return self._get_indexer(target, method, limit, tolerance)
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/indexes/range.py", line 418, in _get_indexer
    locs[~valid] = -1
TypeError: 'numpy.int64' object does not support item assignment
"""

The above exception was the direct cause of the following exception:

TypeError                                 Traceback (most recent call last)
/var/folders/9m/58ctzpdj30v5n2q5c6llkmsx6hn1lb/T/ipykernel_17811/813242355.py in <module>
     47 
     48     perc_sb = r
---> 49     mock_masses = Parallel(n_jobs=num_cores)(delayed(make_masses)(mocks['z'], mocks['l']) for i in range(100))
     50     masses.append(mock_masses)
     51 

/opt/anaconda3/lib/python3.9/site-packages/joblib/parallel.py in __call__(self, iterable)
   1054 
   1055             with self._backend.retrieval_context():
-> 1056                 self.retrieve()
   1057             # Make sure that we get a last message telling us we are done
   1058             elapsed_time = time.time() - self._start_time

/opt/anaconda3/lib/python3.9/site-packages/joblib/parallel.py in retrieve(self)
    933             try:
    934                 if getattr(self._backend, 'supports_timeout', False):
--> 935                     self._output.extend(job.get(timeout=self.timeout))
    936                 else:
    937                     self._output.extend(job.get())

/opt/anaconda3/lib/python3.9/site-packages/joblib/_parallel_backends.py in wrap_future_result(future, timeout)
    540         AsyncResults.get from multiprocessing."""
    541         try:
--> 542             return future.result(timeout=timeout)
    543         except CfTimeoutError as e:
    544             raise TimeoutError from e

/opt/anaconda3/lib/python3.9/concurrent/futures/_base.py in result(self, timeout)
    443                     raise CancelledError()
    444                 elif self._state == FINISHED:
--> 445                     return self.__get_result()
    446                 else:
    447                     raise TimeoutError()

/opt/anaconda3/lib/python3.9/concurrent/futures/_base.py in __get_result(self)
    388         if self._exception:
    389             try:
--> 390                 raise self._exception
    391             finally:
    392                 # Break a reference cycle with the exception in self._exception

TypeError: 'numpy.int64' object does not support item assignment
```

It seems the underlying issue has to do with how Parallel interacts with pandas on the backend, but I'm not entirely sure how to fix it. Any suggestions? Right now I'm running it in batches to cope, but would appreciate a more permanent solution.

**Comment by ariannalong** [comment]
Update: even when running in batches of ~14k, I get the following error (which again appears to relate:

'''
---------------------------------------------------------------------------
_RemoteTraceback                          Traceback (most recent call last)
_RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.9/site-packages/joblib/externals/loky/process_executor.py", line 436, in _process_worker
    r = call_item()
  File "/opt/anaconda3/lib/python3.9/site-packages/joblib/externals/loky/process_executor.py", line 288, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/joblib/_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/joblib/parallel.py", line 262, in __call__
    return [func(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/joblib/parallel.py", line 262, in <listcomp>
    return [func(*args, **kwargs)
  File "/var/folders/9m/58ctzpdj30v5n2q5c6llkmsx6hn1lb/T/ipykernel_17811/2503849451.py", line 35, in make_masses
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/series.py", line 966, in __getitem__
    return self._get_with(key)
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/series.py", line 1001, in _get_with
    return self.loc[key]
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/indexing.py", line 931, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/indexing.py", line 1153, in _getitem_axis
    return self._getitem_iterable(key, axis=axis)
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/indexing.py", line 1093, in _getitem_iterable
    keyarr, indexer = self._get_listlike_indexer(key, axis)
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/indexing.py", line 1314, in _get_listlike_indexer
    self._validate_read_indexer(keyarr, indexer, axis)
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/indexing.py", line 1374, in _validate_read_indexer
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")
KeyError: "None of [Int64Index([9880, 3155, 3072, 3144, 3304, 9579, 9739, 3460, 3592, 3560, 9110,\n            9212, 9267, 9572, 3221, 9651, 3022, 3520, 3082, 3253, 9484, 9228,\n            3618, 2984, 3676, 9792, 3623, 3393, 9483, 9331, 9744, 9758, 9065,\n            9706, 9762, 3223, 9223, 3012, 9247, 9008, 2936, 9451, 3402, 3686,\n            9887, 3669, 9770, 8992, 9892, 9879, 9296, 8984, 9150, 9463, 3209,\n            9434, 9234, 3490, 9263, 3360, 9466, 9016, 9859, 3262, 9626, 3644,\n            9357, 9829],\n           dtype='int64')] are in the [index]"
"""

The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
/var/folders/9m/58ctzpdj30v5n2q5c6llkmsx6hn1lb/T/ipykernel_17811/694243436.py in <module>
     51         if i < 99:
     52             # print(i, i*chunk, ((i+1)*chunk)-1)
---> 53             mock_masses = Parallel(n_jobs=num_cores)(delayed(make_masses)(mocks['z'][i*chunk:((i+1)*chunk)-1], mocks['l'][i*chunk:((i+1)*chunk)-1]) for k in range(100))
     54             masses.append(mock_masses)
     55         else:

/opt/anaconda3/lib/python3.9/site-packages/joblib/parallel.py in __call__(self, iterable)
   1054 
   1055             with self._backend.retrieval_context():
-> 1056                 self.retrieve()
   1057             # Make sure that we get a last message telling us we are done
   1058             elapsed_time = time.time() - self._start_time

/opt/anaconda3/lib/python3.9/site-packages/joblib/parallel.py in retrieve(self)
    933             try:
    934                 if getattr(self._backend, 'supports_timeout', False):
--> 935                     self._output.extend(job.get(timeout=self.timeout))
    936                 else:
    937                     self._output.extend(job.get())

/opt/anaconda3/lib/python3.9/site-packages/joblib/_parallel_backends.py in wrap_future_result(future, timeout)
    540         AsyncResults.get from multiprocessing."""
    541         try:
--> 542             return future.result(timeout=timeout)
    543         except CfTimeoutError as e:
    544             raise TimeoutError from e

/opt/anaconda3/lib/python3.9/concurrent/futures/_base.py in result(self, timeout)
    443                     raise CancelledError()
    444                 elif self._state == FINISHED:
--> 445                     return self.__get_result()
    446                 else:
    447                     raise TimeoutError()

/opt/anaconda3/lib/python3.9/concurrent/futures/_base.py in __get_result(self)
    388         if self._exception:
    389             try:
--> 390                 raise self._exception
    391             finally:
    392                 # Break a reference cycle with the exception in self._exception

KeyError: "None of [Int64Index([9880, 3155, 3072, 3144, 3304, 9579, 9739, 3460, 3592, 3560, 9110,\n            9212, 9267, 9572, 3221, 9651, 3022, 3520, 3082, 3253, 9484, 9228,\n            3618, 2984, 3676, 9792, 3623, 3393, 9483, 9331, 9744, 9758, 9065,\n            9706, 9762, 3223, 9223, 3012, 9247, 9008, 2936, 9451, 3402, 3686,\n            9887, 3669, 9770, 8992, 9892, 9879, 9296, 8984, 9150, 9463, 3209,\n            9434, 9234, 3490, 9263, 3360, 9466, 9016, 9859, 3262, 9626, 3644,\n            9357, 9829],\n           dtype='int64')] are in the [index]"
'''

**Comment by ariannalong** [comment]
Ugh it was a bug in my code. Sorry for bothering.
