### ISSUE TITLE
Terminated worker memory issue

### ISSUE THREAD

**Issue by erwanPl** [joblib/joblib#1292]
Hi, I've come accross an error that I can't explain, solve or force:

Traceback (most recent call last):
  File "reservoir comp like optimised.py", line 333, in <module>
    para(delayed(simulation)(x,i,j,k) for x in super_list)
  File "C:\Users\Admin-CNRS\.conda\envs\Erwan_Pytorch_test\lib\site-packages\joblib\parallel.py", line 1056, in __call__
    self.retrieve()
  File "C:\Users\Admin-CNRS\.conda\envs\Erwan_Pytorch_test\lib\site-packages\joblib\parallel.py", line 935, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "C:\Users\Admin-CNRS\.conda\envs\Erwan_Pytorch_test\lib\site-packages\joblib\_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "C:\Users\Admin-CNRS\.conda\envs\Erwan_Pytorch_test\lib\concurrent\futures\_base.py", line 444, in result
    return self.__get_result()
  File "C:\Users\Admin-CNRS\.conda\envs\Erwan_Pytorch_test\lib\concurrent\futures\_base.py", line 389, in __get_result
    raise self._exception
joblib.externals.loky.process_executor.TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.

My code is below with simulation being a big function using pytorch

if __name__=='__main__':
	nbsimu=12
	with Parallel(n_jobs = nbsimu,max_nbytes=10000) as para:
		for k in [2]:
			for j in [1000]:
				for i in [0.05]:
					for h in range(0,1):
						shift=12*h
						super_list=[k for k in range(shift,3*nbsimu+shift)]
						para(delayed(simulation)(x,i,j,k) for x in super_list)
	
I'm  a bit puzzled as I monitored the RAM used and it wasn't exceeding 30%, I have 32 giga. My joblib version is 1.0.1 and python 3.8.12. The error is happening randomly when the function simulation try to save some data with pickle or some .png 
My processor is a Z690 Phantom gaming 4/D5 2.03

**Comment by inkarar** [comment]
Hey, have you found the solution to this issue? Can you please help me solve this issue?
 I am getting the same error. It's frustrating. 

I tried to simplify the function and avoid nesting as much as possible. I tried different backends and tweaking parameters of the Parallel function but to no avail! 

I am running my script on an EC2 instance with 8 CPU, 16 GB ram, 512 GB SSD, (upgraded from 8 GB ram to  16 GB ram)

**Comment by erwanPl** [comment]
Hello, yes I found where was the problem for me, one of my RAM block had some defectuous slots so I removed it and it worked nicely, so maybe you can test your RAM with OCCT https://www.lesnumeriques.com/telecharger/occt-20084.

Else you could test with the package multiprocessing in python
