### ISSUE TITLE
memmapping folders eatup too much space

### ISSUE THREAD

**Issue by RichardErkhov** [joblib/joblib#1310]
joblib_memmapping_folder_*_* all together eat >95 gb. 
windows 10 64 bit
python 3.10.6
```
joblib.externals.loky.process_executor._RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\joblib\externals\loky\backend\queues.py", line 153, in _feed
    obj_ = dumps(obj, reducers=reducers)
  File "C:\Python310\lib\site-packages\joblib\externals\loky\backend\reduction.py", line 271, in dumps
    dump(obj, buf, reducers=reducers, protocol=protocol)
  File "C:\Python310\lib\site-packages\joblib\externals\loky\backend\reduction.py", line 264, in dump
    _LokyPickler(file, reducers=reducers, protocol=protocol).dump(obj)
  File "C:\Python310\lib\site-packages\joblib\externals\cloudpickle\cloudpickle_fast.py", line 602, in dump
    return Pickler.dump(self, obj)
  File "C:\Python310\lib\site-packages\joblib\_memmapping_reducer.py", line 442, in __call__
    for dumped_filename in dump(a, filename):
  File "C:\Python310\lib\site-packages\joblib\numpy_pickle.py", line 482, in dump
    NumpyPickler(f, protocol=protocol).dump(value)
  File "C:\Python310\lib\pickle.py", line 487, in dump
    self.save(obj)
  File "C:\Python310\lib\site-packages\joblib\numpy_pickle.py", line 281, in save
    wrapper.write_array(obj, self)
  File "C:\Python310\lib\site-packages\joblib\numpy_pickle.py", line 104, in write_array
    pickler.file_handle.write(chunk.tobytes('C'))
OSError: [Errno 28] No space left on device
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "G:\3dengine\Python-Raytracer-master\animation.py", line 60, in <module>
    create_animation(scene = Sc,
  File "G:\3dengine\Python-Raytracer-master\sightpy\animation.py", line 42, in create_animation
    Parallel(n_jobs=max_threads)(delayed(x)(copy.deepcopy(scene), i, name, samples_per_pixel, dt, update_scene) for i in range(0, number_of_frames) )
  File "C:\Python310\lib\site-packages\joblib\parallel.py", line 1056, in __call__
    self.retrieve()
  File "C:\Python310\lib\site-packages\joblib\parallel.py", line 935, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "C:\Python310\lib\site-packages\joblib\_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "C:\Python310\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "C:\Python310\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
_pickle.PicklingError: Could not pickle the task to send it to the workers.
```

**Comment by RichardErkhov** [comment]
when trying to "Parallel(n_jobs=max_threads, mmap_mode=None)"
getting:
```
joblib.externals.loky.process_executor._RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\joblib\externals\loky\process_executor.py", line 407, in _process_worker
    call_item = call_queue.get(block=True, timeout=timeout)
  File "C:\Python310\lib\multiprocessing\queues.py", line 122, in get
    return _ForkingPickler.loads(res)
  File "C:\Python310\lib\site-packages\joblib\numpy_pickle.py", line 527, in load_temporary_memmap
    JOBLIB_MMAPS.add(obj.filename)
AttributeError: 'numpy.ndarray' object has no attribute 'filename'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "G:\3dengine\Python-Raytracer-master\animation.py", line 60, in <module>
    create_animation(scene = Sc,
  File "G:\3dengine\Python-Raytracer-master\sightpy\animation.py", line 42, in create_animation
    Parallel(n_jobs=max_threads, mmap_mode=None)(delayed(x)(copy.deepcopy(scene), i, name, samples_per_pixel, dt, update_scene) for i in range(0, number_of_frames) )
  File "C:\Python310\lib\site-packages\joblib\parallel.py", line 1056, in __call__
    self.retrieve()
  File "C:\Python310\lib\site-packages\joblib\parallel.py", line 935, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "C:\Python310\lib\site-packages\joblib\_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "C:\Python310\lib\concurrent\futures\_base.py", line 446, in result
    return self.__get_result()
  File "C:\Python310\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
joblib.externals.loky.process_executor.BrokenProcessPool: A task has failed to un-serialize. Please ensure that the arguments of the function are all picklable.
```

**Comment by RichardErkhov** [comment]
> when trying to "Parallel(n_jobs=max_threads, mmap_mode=None)" getting:
> 
> ```
> joblib.externals.loky.process_executor._RemoteTraceback:
> """
> Traceback (most recent call last):
>   File "C:\Python310\lib\site-packages\joblib\externals\loky\process_executor.py", line 407, in _process_worker
>     call_item = call_queue.get(block=True, timeout=timeout)
>   File "C:\Python310\lib\multiprocessing\queues.py", line 122, in get
>     return _ForkingPickler.loads(res)
>   File "C:\Python310\lib\site-packages\joblib\numpy_pickle.py", line 527, in load_temporary_memmap
>     JOBLIB_MMAPS.add(obj.filename)
> AttributeError: 'numpy.ndarray' object has no attribute 'filename'
> """
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "G:\3dengine\Python-Raytracer-master\animation.py", line 60, in <module>
>     create_animation(scene = Sc,
>   File "G:\3dengine\Python-Raytracer-master\sightpy\animation.py", line 42, in create_animation
>     Parallel(n_jobs=max_threads, mmap_mode=None)(delayed(x)(copy.deepcopy(scene), i, name, samples_per_pixel, dt, update_scene) for i in range(0, number_of_frames) )
>   File "C:\Python310\lib\site-packages\joblib\parallel.py", line 1056, in __call__
>     self.retrieve()
>   File "C:\Python310\lib\site-packages\joblib\parallel.py", line 935, in retrieve
>     self._output.extend(job.get(timeout=self.timeout))
>   File "C:\Python310\lib\site-packages\joblib\_parallel_backends.py", line 542, in wrap_future_result
>     return future.result(timeout=timeout)
>   File "C:\Python310\lib\concurrent\futures\_base.py", line 446, in result
>     return self.__get_result()
>   File "C:\Python310\lib\concurrent\futures\_base.py", line 391, in __get_result
>     raise self._exception
> joblib.externals.loky.process_executor.BrokenProcessPool: A task has failed to un-serialize. Please ensure that the arguments of the function are all picklable.
> ```
added max_nbytes=None to fix it
