### ISSUE TITLE
argument max_nbytes is not disabled when mmap_mode is set to None

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [joblib/joblib#1315]
Hi,

I was trying to disable memory mapping on my algorithm and after reading [the doc](https://joblib.readthedocs.io/en/latest/generated/joblib.Parallel.html) I thought that simply setting 'mmap_mode' to None would disable it:
* from max_nbytes doc: `Use None to disable memmapping of large arrays.`
* from memmap_mode doc: `None will disable memmapping`

However, it appears that setting 'mmap_mode' to 'None' does not make sure that 'max_nbytes' is ignored.  The other way around is True.

I put together an example script:

```
import joblib
import numpy as np
import seaborn as sns
import time

# load data
ar = sns.load_dataset("diamonds")[["x", "y", "z"]]

# make it bigger
ar = np.concatenate([ar for repeat in range(10)])

# make an iterator
iterator = [ar * i for i in range(10)]

def func(ar):
    return ar**2

parallel = joblib.Parallel(backend="multiprocessing",
                           n_jobs=5,
                           mmap_mode="r",
                           max_nbytes="1K",
                           verbose=0)
out = parallel(joblib.delayed(func)(ar=ar) for ar in iterator)
print("Works OK with mmap_mode and max_nbytes both ON")
time.sleep(3)

parallel = joblib.Parallel(backend="multiprocessing",
                           n_jobs=5,
                           mmap_mode=None,
                           max_nbytes=None,
                           verbose=0)
out = parallel(joblib.delayed(func)(ar=ar) for ar in iterator)
print("Works OK with mmap_mode and max_nbytes both OFF")
time.sleep(3)

parallel = joblib.Parallel(backend="loky",  # also the case with "multiprocessing"
                           n_jobs=5,
                           mmap_mode="r",
                           max_nbytes=None,
                           verbose=0)
out = parallel(joblib.delayed(func)(ar=ar) for ar in iterator)
print("Works OK with mmap_mode ON and max_nbytes OFF")
time.sleep(3)

parallel = joblib.Parallel(backend="loky",
                           n_jobs=5,
                           mmap_mode=None,
                           #max_nbytes="1K",
                           verbose=0)
out = parallel(joblib.delayed(func)(ar=ar) for ar in iterator)
print("Works not OK with mmap_mode OFF and max_nbytes ON")
time.sleep(3)

```

Here's the output:
```
Works OK with mmap_mode and max_nbytes both ON
Works OK with mmap_mode and max_nbytes both OFF
Works OK with mmap_mode ON and max_nbytes OFF
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/USER/.local/lib/python3.9/site-packages/joblib/externals/loky/process_executor.py", line 407, in _process_worker
    call_item = call_queue.get(block=True, timeout=timeout)
  File "/usr/local/lib/python3.9/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
  File "/home/USER/.local/lib/python3.9/site-packages/joblib/numpy_pickle.py", line 527, in load_temporary_memmap
    JOBLIB_MMAPS.add(obj.filename)
AttributeError: 'numpy.ndarray' object has no attribute 'filename'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/USER/Downloads/./joblib_test.py", line 58, in <module>
    out = parallel(joblib.delayed(func)(ar=ar) for ar in iterator)
  File "/home/USER/.local/lib/python3.9/site-packages/joblib/parallel.py", line 1056, in __call__
    self.retrieve()
  File "/home/USER/.local/lib/python3.9/site-packages/joblib/parallel.py", line 935, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/USER/.local/lib/python3.9/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 440, in result
    return self.__get_result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
joblib.externals.loky.process_executor.BrokenProcessPool: A task has failed to un-serialize. Please ensure that the arguments of the function are all picklable.
```

This is somewhat caused #1310 but was closed 

Suggestions:
* make sure that disabling either mmap_moded or max_nbytes turns memory mapping off
* clarify the documentation to explain the proper way to disable memory mapping. Ideally while explaining the pros and cons to the user. (Am I right in thinking that disabling memory mapping will increase initial overhead but speed up each job at the risk of getting out of memory arror?)

```
joblib version: 1.1.0
python version: 3.9.0
```

And thank you for this wonderful library that gains us all so much time :)

**Comment by ogrisel** [comment]
I would be in favor of implementing your first suggestion: make sure the code does what the doc says instead of the reverse.

Would you be interested in submitting a PR?

**Comment by thiswillbeyourgithub** [comment]
Hi! Thanks for the reply.

I made a minimal draft. It works on the script test I mentionned above. Opinion?
