### ISSUE TITLE
Parallel not working on python 3.7.2

### ISSUE THREAD

**Issue by manuel-lincbiotech** [joblib/joblib#1349]
Hello,
I'm having some issues when running Parallel on Python 3.7.2.
Using Windows 10 with a venv, joblib  1.1  (64 bit). 

Code example to test:

```
from joblib import Parallel, delayed, cpu_count

def operations(n1,n2):
    return n1+n2

n1 = range(0,1000)
n2 = range(1000,2000)
results = Parallel(n_jobs=cpu_count()-2, verbose=1)(delayed(operations)(i,j) for i,j in zip(n1,n2))
```

The error I get: 

> [Parallel(n_jobs=14)]: Using backend LokyBackend with 14 concurrent workers.
exception calling callback for <Future at 0x20e6c6e2588 state=finished raised BrokenProcessPool>
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\multiprocessing\queues.py", line 109, in get
    self._sem.release()
OSError: [WinError 6] Controlador no válido
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\User\Desktop\lincbiotech\venv\lib\site-packages\joblib\externals\loky\process_executor.py", line 407, in _process_worker
    call_item = call_queue.get(block=True, timeout=timeout)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\multiprocessing\queues.py", line 111, in get
    self._rlock.release()
OSError: [WinError 6] Controlador no válido
"""
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "C:\Users\User\Desktop\lincbiotech\venv\lib\site-packages\joblib\externals\loky\_base.py", line 625, in _invoke_callbacks
    callback(self)
  File "C:\Users\User\Desktop\lincbiotech\venv\lib\site-packages\joblib\parallel.py", line 359, in __call__
    self.parallel.dispatch_next()
  File "C:\Users\User\Desktop\lincbiotech\venv\lib\site-packages\joblib\parallel.py", line 794, in dispatch_next
    if not self.dispatch_one_batch(self._original_iterator):
  File "C:\Users\User\Desktop\lincbiotech\venv\lib\site-packages\joblib\parallel.py", line 861, in dispatch_one_batch
    self._dispatch(tasks)
  File "C:\Users\User\Desktop\lincbiotech\venv\lib\site-packages\joblib\parallel.py", line 779, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "C:\Users\User\Desktop\lincbiotech\venv\lib\site-packages\joblib\_parallel_backends.py", line 531, in apply_async
    future = self._workers.submit(SafeFunction(func))
  File "C:\Users\User\Desktop\lincbiotech\venv\lib\site-packages\joblib\externals\loky\reusable_executor.py", line 178, in submit
    fn, *args, **kwargs)
  File "C:\Users\User\Desktop\lincbiotech\venv\lib\site-packages\joblib\externals\loky\process_executor.py", line 1115, in submit
    raise self._flags.broken
joblib.externals.loky.process_executor.BrokenProcessPool: A task has failed to un-serialize. Please ensure that the arguments of the function are all picklable.
ERROR: no se encontr� el proceso "516".
ERROR: no se encontr� el proceso "19028".
ERROR: no se encontr� el proceso "16196".
ERROR: no se encontr� el proceso "21440".
ERROR: no se encontr� el proceso "10060".
ERROR: no se encontr� el proceso "20604".
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\multiprocessing\queues.py", line 109, in get
    self._sem.release()
OSError: [WinError 6] Controlador no válido
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\User\Desktop\lincbiotech\venv\lib\site-packages\joblib\externals\loky\process_executor.py", line 407, in _process_worker
    call_item = call_queue.get(block=True, timeout=timeout)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\multiprocessing\queues.py", line 111, in get
    self._rlock.release()
OSError: [WinError 6] Controlador no válido
"""
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 10, in <module>
  File "C:\Users\User\Desktop\lincbiotech\venv\lib\site-packages\joblib\parallel.py", line 1056, in __call__
    self.retrieve()
  File "C:\Users\User\Desktop\lincbiotech\venv\lib\site-packages\joblib\parallel.py", line 935, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "C:\Users\User\Desktop\lincbiotech\venv\lib\site-packages\joblib\_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\_base.py", line 432, in result
    return self.__get_result()
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
  File "C:\Users\User\Desktop\lincbiotech\venv\lib\site-packages\joblib\externals\loky\_base.py", line 625, in _invoke_callbacks
    callback(self)
  File "C:\Users\User\Desktop\lincbiotech\venv\lib\site-packages\joblib\parallel.py", line 359, in __call__
    self.parallel.dispatch_next()
  File "C:\Users\User\Desktop\lincbiotech\venv\lib\site-packages\joblib\parallel.py", line 794, in dispatch_next
    if not self.dispatch_one_batch(self._original_iterator):
  File "C:\Users\User\Desktop\lincbiotech\venv\lib\site-packages\joblib\parallel.py", line 861, in dispatch_one_batch
    self._dispatch(tasks)
  File "C:\Users\User\Desktop\lincbiotech\venv\lib\site-packages\joblib\parallel.py", line 779, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "C:\Users\User\Desktop\lincbiotech\venv\lib\site-packages\joblib\_parallel_backends.py", line 531, in apply_async
    future = self._workers.submit(SafeFunction(func))
  File "C:\Users\User\Desktop\lincbiotech\venv\lib\site-packages\joblib\externals\loky\reusable_executor.py", line 178, in submit
    fn, *args, **kwargs)
  File "C:\Users\User\Desktop\lincbiotech\venv\lib\site-packages\joblib\externals\loky\process_executor.py", line 1115, in submit
    raise self._flags.broken
joblib.externals.loky.process_executor.BrokenProcessPool: A task has failed to un-serialize. Please ensure that the arguments of the function are all picklable.

Since my system language is in Spanish notice that 

> OSError: [WinError 6] Controlador no válido

is the same as 

> OSError: [WinError 6] The handle is invalid

The code example with the same joblib version (and with more complex functions to parrallelize) works perfectly when using python 3.9.13 and 3.8.13 (haven´t tried it with other version). I must note that in these two cases I was using conda evironment. Still I refer to this other closed issue https://github.com/joblib/joblib/issues/901 that seemed to describe the exact same problem (or very similar) but was supposedly solved. 

I could work with Python 3.8 (not 3.9 for my current project) but that would mean a very big migration since there is a lot already done in python 3.7.2, if it's possible I would prefer to stick with 3.7.2 even if it's with some workaround for the time being.

Thnak in advance

**Comment by lesteve** [comment]
Sorry for the lack of response, this is not relevant anymore since we don't support Python 3.7, so I am going to close this one.
