### ISSUE TITLE
Missing __cause__ of the exception in the subprocess

### ISSUE THREAD

**Issue by GianlucaFicarelli** [joblib/joblib#1369]
When using joblib (with loky and cloudpickle) and an exception is raised in a subprocess, the original traceback is usually transmitted to the main process and it can be printed if desired.
However, I encountered a particular setup where the original `__cause__` is lost.

To reproduce the issue, in a fresh virtualenv execute:
```
pip install joblib xarray distributed
# dask and tblib are automatically installed
```

Then execute this script:
```
from functools import partial
from joblib import Parallel, delayed

def run_parallel(tasks, jobs=2, backend="loky", verbose=10):
    parallel = Parallel(n_jobs=jobs, backend=backend, verbose=verbose)
    return parallel(delayed(task)(i=i) for i, task in enumerate(tasks))

def func(d, i):
    import xarray
    _ = d["missing"]  # raise KeyError

def main():
    myfunc = partial(func, d={})
    run_parallel([myfunc, myfunc])

if __name__ == "__main__":
    main()
```

The result is: (using python 3.11)
```
[Parallel(n_jobs=2)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=2)]: Done   2 out of   2 | elapsed:    8.6s remaining:    0.0s
Traceback (most recent call last):
  File "/private/tmp/try_ex.py", line 17, in <module>
    main()
  File "/private/tmp/try_ex.py", line 14, in main
    run_parallel([myfunc, myfunc])
  File "/private/tmp/try_ex.py", line 6, in run_parallel
    return parallel(delayed(task)(i=i) for i, task in enumerate(tasks))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/tmp/venv/lib/python3.11/site-packages/joblib/parallel.py", line 1098, in __call__
    self.retrieve()
  File "/private/tmp/venv/lib/python3.11/site-packages/joblib/parallel.py", line 975, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/tmp/venv/lib/python3.11/site-packages/joblib/_parallel_backends.py", line 567, in wrap_future_result
    return future.result(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/.pyenv/versions/3.11.0/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/user/.pyenv/versions/3.11.0/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
KeyError: 'missing'
```

but if tblib is uninstalled:
```
pip uninstall tblib distributed
```
then, using the same script above, the result includes the original exception as expected:
```
[Parallel(n_jobs=2)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=2)]: Done   2 out of   2 | elapsed:    1.2s remaining:    0.0s
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/private/tmp/venv/lib/python3.11/site-packages/joblib/externals/loky/process_executor.py", line 428, in _process_worker
    r = call_item()
        ^^^^^^^^^^^
  File "/private/tmp/venv/lib/python3.11/site-packages/joblib/externals/loky/process_executor.py", line 275, in __call__
    return self.fn(*self.args, **self.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/tmp/venv/lib/python3.11/site-packages/joblib/_parallel_backends.py", line 620, in __call__
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/tmp/venv/lib/python3.11/site-packages/joblib/parallel.py", line 288, in __call__
    return [func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/private/tmp/venv/lib/python3.11/site-packages/joblib/parallel.py", line 288, in <listcomp>
    return [func(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/private/tmp/try_ex.py", line 10, in func
    _ = d["missing"]  # raise KeyError
        ~^^^^^^^^^^^
KeyError: 'missing'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/private/tmp/try_ex.py", line 17, in <module>
    main()
  File "/private/tmp/try_ex.py", line 14, in main
    run_parallel([myfunc, myfunc])
  File "/private/tmp/try_ex.py", line 6, in run_parallel
    return parallel(delayed(task)(i=i) for i, task in enumerate(tasks))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/tmp/venv/lib/python3.11/site-packages/joblib/parallel.py", line 1098, in __call__
    self.retrieve()
  File "/private/tmp/venv/lib/python3.11/site-packages/joblib/parallel.py", line 975, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/tmp/venv/lib/python3.11/site-packages/joblib/_parallel_backends.py", line 567, in wrap_future_result
    return future.result(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/.pyenv/versions/3.11.0/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/user/.pyenv/versions/3.11.0/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
KeyError: 'missing'
```

After a first investigation:
- xarray imports dask (if available) [here](https://github.com/pydata/xarray/blob/690d3ce298e1f1032397c873bad101e6510b582f/xarray/backends/locks.py#L8-L12)
- that imports tblib (if available) and calls `tblib.pickling_support.install()` [here](https://github.com/dask/dask/blob/c2556fb3a574feaeee5be3a8aebae7e229abe28f/dask/multiprocessing.py#L97-L99)
- that calls `copyreg.pickle()` for any subclass of BaseException [here](https://github.com/ionelmc/python-tblib/blob/6f769cf6e0728ed0f60cb3c4cbde6c02e351eada/src/tblib/pickling_support.py#L69-L70)
- if `copyreg.pickle()` is skipped or commented out, the original `__cause__` is not lost.

I wonder if it's possible to get the full original traceback in such virtual environment, or if there is any known limitation.
Thanks.

**Comment by lesteve** [comment]
Thanks a lot for the detailed issue and investigation. I can reproduce this.

Not sure where it is coming and whether from but I noticed two things:
- the problem does not happen with `backend="multiprocessing"`, so it seems Loky specific I am wondering whether this could be related to https://github.com/joblib/loky/pull/255
- the problem does not happen if `import xarray` is outside the function that gets run on the worker. Maybe that is a workable work-around for your use case?

**Comment by GianlucaFicarelli** [comment]
@lesteve I just resumed the investigation on this issue and I confirm that the traceback is displayed correctly after applying the change in the linked PR, i.e. replacing:
```python
class _ExceptionWithTraceback(BaseException):
```
with 
```python
class _ExceptionWithTraceback:
```
because in this way tblib doesn't apply `copyreg.pickle` in https://github.com/ionelmc/python-tblib/blob/6f769cf6e0728ed0f60cb3c4cbde6c02e351eada/src/tblib/pickling_support.py#L69-L70.

This change would make the definition similar to what is at https://github.com/python/cpython/blob/c00eb1eae6af3ee5b7e314add4606da4521bb8c5/Lib/concurrent/futures/process.py#L124 (original commit: https://github.com/python/cpython/commit/1285c9b7829a6ae3a1267e7676b1bc2c5ce11f96)

I don't see a clear reason to keep `_ExceptionWithTraceback` inheriting from `BaseException`.
Do you think it can be changed?

Side note: in my case it's not possible to import xarray outside the function as a workaround, because in the original code the function to be executed in a subprocess is defined in a different file.

**Comment by lesteve** [comment]
OK thanks for investigating! I am going to close this issue and will try to push https://github.com/joblib/loky/pull/255 instead.
