### ISSUE TITLE
joblib.backports.make_memmap should not be used if numpy is not installed.

### ISSUE THREAD

**Issue by donatoaz** [joblib/joblib#1407]
I'm trying to use `Parallel` and `delayed` on an AWS Lambda function.

```python
    def create_in_zoom_frame(w, h):
        # extract a rectangle centered on the needle's center, with (w,h) size
        y, x = int(needle_h / 2), int(needle_w / 2)
        y1, x1 = round(y - h / 2), round(x - w / 2)
        y2, x2 = round(y1 + h), round(x1 + w)

        # copy and crop original image
        frame = matched_needle.copy()
        frame = frame[y1:y2, x1:x2]

        # Resize frame to final video size
        frame = cv2.resize(
            frame, (video_width, video_height), interpolation=cv2.INTER_AREA
        )

        return frame

    in_zoom_frames = Parallel(n_jobs=4)(delayed(create_in_zoom_frame)(w, h) for (w, h) in in_zoom_frame_sizes)
```

I do have numpy installed, however I get the following error:

```
[ERROR] 2023-03-14T21:26:14.221Z        cbbda2f4-325d-494a-94a5-8dd5c94c9f14    exception calling callback for <Future at 0x4023486310 state=finished raised BrokenProcessPool>
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/var/task/joblib/externals/loky/process_executor.py", line 407, in _process_worker
    call_item = call_queue.get(block=True, timeout=timeout)
  File "/var/lang/lib/python3.9/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
  File "/var/task/joblib/numpy_pickle.py", line 526, in load_temporary_memmap
    obj = load(filename, mmap_mode)
  File "/var/task/joblib/numpy_pickle.py", line 587, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/var/task/joblib/numpy_pickle.py", line 506, in _unpickle
    obj = unpickler.load()
  File "/var/lang/lib/python3.9/pickle.py", line 1212, in load
    dispatch[key[0]](self)
  File "/var/task/joblib/numpy_pickle.py", line 344, in load_build
    self.stack.append(array_wrapper.read(self))
  File "/var/task/joblib/numpy_pickle.py", line 187, in read
    array = self.read_mmap(unpickler)
  File "/var/task/joblib/numpy_pickle.py", line 160, in read_mmap
    marray = make_memmap(unpickler.filename,
  File "/var/task/joblib/backports.py", line 45, in make_memmap
    raise NotImplementedError(
NotImplementedError: 'joblib.backports.make_memmap' should not be used if numpy is not installed.
"""
```

I also tried instantiating `Parallel` with `mmap_mode=None` and the error just changed to:

```
[ERROR] 2023-03-14T21:34:54.312Z        8f2c7df7-9f32-4f90-a6dd-4b1d198b1733    exception calling callback for <Future at 0x4023484370 state=finished raised BrokenProcessPool>
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/var/task/joblib/externals/loky/process_executor.py", line 407, in _process_worker
    call_item = call_queue.get(block=True, timeout=timeout)
  File "/var/lang/lib/python3.9/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
  File "/var/task/joblib/numpy_pickle.py", line 527, in load_temporary_memmap
    JOBLIB_MMAPS.add(obj.filename)
AttributeError: 'numpy.ndarray' object has no attribute 'filename'
"""
```

**Comment by lesteve** [comment]
Not enough information to reproduce unfortunately, let's close this one.
