### ISSUE TITLE
Issue defining a custom backend

### ISSUE THREAD

**Issue by MaximeSongIdris** [joblib/joblib#1429]
Hi,

I'm trying to define a custom backend using StarPU (https://starpu.gitlabpages.inria.fr/) by taking example of the loky implementation (using Future as the return of the submitted task), but I've met some problems.

Here is the code I am using :
```
import starpu
import numpy as np
from joblib._parallel_backends import AutoBatchingMixin, ParallelBackendBase
from joblib import register_parallel_backend, parallel_backend
from joblib import Parallel, delayed
from concurrent.futures._base import TimeoutError as CfTimeoutError

                
class StarpuBackendHandle(AutoBatchingMixin, ParallelBackendBase):
    
    def effective_n_jobs(self, n_jobs):
        """Determine the number of jobs which are going to run in parallel"""
        if n_jobs < 0:
            return max(cpu_count() + 1 + n_jobs, 1)
        return n_jobs
    
    def apply_async(self, func, callback=None):
        """Schedule a func to be run
        
        func : a joblib.parallel.BatchedCalls object
        """
        future = starpu.task_submit()(func)
        # define the get method (get is the method used by joblib to retrieve task results)
        future.get = functools.partial(self.wrap_future_result, future)
        if callback is not None:
            future.add_done_callback(callback)
        return future

    @staticmethod
    def wrap_future_result(future, timeout=None):
        """Wrapper for Future.result to implement the same behaviour as
        AsyncResults.get from multiprocessing."""
        try:
            return future.result(timeout=timeout)
        except CfTimeoutError as e:
            raise TimeoutError from e


register_parallel_backend('StarpuBackendHandle', StarpuBackendHandle)

# ------------------------------------------------------------------------------
def main():
    
    starpu.init()
    
    def increment_5(x):
        print(x+5)
        return x+5

    X = np.random.default_rng().normal(0., 1., size=(1000))

    with parallel_backend('StarpuBackendHandle'):
        Parallel(n_jobs=2)(delayed(increment_5)(x) for x in X)
        
    starpu.shutdown()

if __name__ == "__main__":
    main()
```

I get the following error when running my code :
```
[starpu][starpu_initialize] Initialisation finished
Traceback (most recent call last):
  File "backend_starpu_future.py", line 70, in <module>
    main()
  File "backend_starpu_future.py", line 65, in main
    Parallel(n_jobs=1)(delayed(increment_5)(x) for x in X)
  File "/gpfswork/idris/sos/ssos027/sklearn/.local/lib/python3.8/site-packages/joblib/parallel.py", line 1089, in __call__
    if self.dispatch_one_batch(iterator):
  File "/gpfswork/idris/sos/ssos027/sklearn/.local/lib/python3.8/site-packages/joblib/parallel.py", line 901, in dispatch_one_batch
    self._dispatch(tasks)
  File "/gpfswork/idris/sos/ssos027/sklearn/.local/lib/python3.8/site-packages/joblib/parallel.py", line 819, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "backend_starpu_future.py", line 34, in apply_async
    future = starpu.task_submit()(func)
  File "/gpfsdswork/projects/idris/sos/commun/STARPU/starpu1.4_mpi_cuda_py/install/lib/python3.8/site-packages/starpu/intermedia.py", line 80, in call_task_submit
    res=starpupy._task_submit(f, *args, kwargs)
starpupy.error: Can't find asyncio module (try to add "-m asyncio" when starting Python interpreter)
```

Asyncio seems to be necessary here, yet in Loky, there was no mention of asyncio. Is there anything I am missing here ?

**Comment by tomMoral** [comment]
Hello,

Thanks for the report.
`joblib` does not depend on `asyncio`, so it seems to be an error on how
you use `starpu`.
The traceback seems to mention running the script with `python -m asyncio
script.py`, have you tried this?

**Comment by MaximeSongIdris** [comment]
Yes, running `python -m asyncio my_script.py` will open an interactive session without executing `my_script.py`

**Comment by tomMoral** [comment]
As I don't know starPU, I cannot really help here.
But in a script, if you run `starpu.task_submit()(func)`, does this work?

**Comment by MaximeSongIdris** [comment]
It's not working, I need asyncio, but I don't know if it is due to the Future object, or due to StarPU

**Comment by sthibaul** [comment]
by default, `ret_fut=True` in the `task_submit` parameters, so that would want to return a future

**Comment by MaximeSongIdris** [comment]
Found this https://stackoverflow.com/questions/29902908/what-is-the-difference-between-concurrent-futures-and-asyncio-futures
Seems like StarPU use asyncio.Future which need asyncio to work, while concurrent.Future works without it

**Comment by tomMoral** [comment]
For the custom backend, `joblib` does not really care about the internals so you can use any return object type to track the computation in the backend. The problem seems to be with the way you use `asyncio.Future` that require a event loop to be running I guess? you probably need to wrap the future in an object that mimic the `concurrent.futures` API, with a `get` that would await the results once it is done.
