### ISSUE TITLE
Joblib fails when using pandas.DataFrame.itertuples, Parallel, and Memory

### ISSUE THREAD

**Issue by holmescharles** [joblib/joblib#1431]
I would like to process a dataframe row by row. I have some logic that will take a named tuple (from itertuples) and do some data scrapping based on the column values in that row. Thus, I am trying to cache the results of a function that takes a named tuple with type "pandas.core.frame.Pandas". However, when I run my code, I get an error that reads "Can't pickle <class 'pandas.core.frame.Pandas'>: it's not found as pandas.core.frame.Pandas".

I think I've boiled the logic down to a minimal example here:

```python
# foo.py

import pandas as pd
import numpy as np
import joblib
import time

mem = joblib.Memory("cache_dir")

@mem.cache
def foo(x):
  # time.sleep(1)
  return x.a + x.b

df = pd.DataFrame({"a": list(range(100)), "b": list(range(100, 200))})
y = joblib.Parallel(n_jobs=1)(joblib.delayed(foo)(x) for x in df.itertuples())
```

When run, the code above produces this error:

```
Traceback (most recent call last):
  File "/home/chuck/foo.py", line 14, in <module>
    y = joblib.Parallel(n_jobs=1)(joblib.delayed(foo)(x) for x in df.itertuples())
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chuck/.miniconda3/envs/main/lib/python3.11/site-packages/joblib/parallel.py", line 1085, in __call__
    if self.dispatch_one_batch(iterator):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chuck/.miniconda3/envs/main/lib/python3.11/site-packages/joblib/parallel.py", line 901, in dispatch_one_batch
    self._dispatch(tasks)
  File "/home/chuck/.miniconda3/envs/main/lib/python3.11/site-packages/joblib/parallel.py", line 819, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chuck/.miniconda3/envs/main/lib/python3.11/site-packages/joblib/_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/chuck/.miniconda3/envs/main/lib/python3.11/site-packages/joblib/_parallel_backends.py", line 597, in __init__
    self.results = batch()
                   ^^^^^^^
  File "/home/chuck/.miniconda3/envs/main/lib/python3.11/site-packages/joblib/parallel.py", line 288, in __call__
    return [func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chuck/.miniconda3/envs/main/lib/python3.11/site-packages/joblib/parallel.py", line 288, in <listcomp>
    return [func(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/home/chuck/.miniconda3/envs/main/lib/python3.11/site-packages/joblib/memory.py", line 594, in __call__
    return self._cached_call(args, kwargs)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chuck/.miniconda3/envs/main/lib/python3.11/site-packages/joblib/memory.py", line 486, in _cached_call
    func_id, args_id = self._get_output_identifiers(*args, **kwargs)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chuck/.miniconda3/envs/main/lib/python3.11/site-packages/joblib/memory.py", line 638, in _get_output_identifiers
    argument_hash = self._get_argument_hash(*args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chuck/.miniconda3/envs/main/lib/python3.11/site-packages/joblib/memory.py", line 632, in _get_argument_hash
    return hashing.hash(filter_args(self.func, self.ignore, args, kwargs),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chuck/.miniconda3/envs/main/lib/python3.11/site-packages/joblib/hashing.py", line 266, in hash
    return hasher.hash(obj)
           ^^^^^^^^^^^^^^^^
  File "/home/chuck/.miniconda3/envs/main/lib/python3.11/site-packages/joblib/hashing.py", line 63, in hash
    self.dump(obj)
  File "/home/chuck/.miniconda3/envs/main/lib/python3.11/pickle.py", line 487, in dump
    self.save(obj)
  File "/home/chuck/.miniconda3/envs/main/lib/python3.11/site-packages/joblib/hashing.py", line 241, in save
    Hasher.save(self, obj)
  File "/home/chuck/.miniconda3/envs/main/lib/python3.11/site-packages/joblib/hashing.py", line 89, in save
    Pickler.save(self, obj)
  File "/home/chuck/.miniconda3/envs/main/lib/python3.11/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
    ^^^^^^^^^^^^
  File "/home/chuck/.miniconda3/envs/main/lib/python3.11/pickle.py", line 972, in save_dict
    self._batch_setitems(obj.items())
  File "/home/chuck/.miniconda3/envs/main/lib/python3.11/site-packages/joblib/hashing.py", line 140, in _batch_setitems
    Pickler._batch_setitems(self, iter(sorted(items)))
  File "/home/chuck/.miniconda3/envs/main/lib/python3.11/pickle.py", line 1003, in _batch_setitems
    save(v)
  File "/home/chuck/.miniconda3/envs/main/lib/python3.11/site-packages/joblib/hashing.py", line 241, in save
    Hasher.save(self, obj)
  File "/home/chuck/.miniconda3/envs/main/lib/python3.11/site-packages/joblib/hashing.py", line 89, in save
    Pickler.save(self, obj)
  File "/home/chuck/.miniconda3/envs/main/lib/python3.11/pickle.py", line 603, in save
    self.save_reduce(obj=obj, *rv)
  File "/home/chuck/.miniconda3/envs/main/lib/python3.11/pickle.py", line 687, in save_reduce
    save(cls)
  File "/home/chuck/.miniconda3/envs/main/lib/python3.11/site-packages/joblib/hashing.py", line 241, in save
    Hasher.save(self, obj)
  File "/home/chuck/.miniconda3/envs/main/lib/python3.11/site-packages/joblib/hashing.py", line 89, in save
    Pickler.save(self, obj)
  File "/home/chuck/.miniconda3/envs/main/lib/python3.11/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
    ^^^^^^^^^^^^
  File "/home/chuck/.miniconda3/envs/main/lib/python3.11/site-packages/joblib/hashing.py", line 111, in save_global
    Pickler.save_global(self, obj, **kwargs)
  File "/home/chuck/.miniconda3/envs/main/lib/python3.11/pickle.py", line 1071, in save_global
    raise PicklingError(
_pickle.PicklingError: ("Can't pickle <class 'pandas.core.frame.Pandas'>: it's not found as pandas.core.frame.Pandas", 'PicklingError while hashing {\'x\': Pandas(Index=0, a=0, b=100)}: PicklingError("Can\'t pickle <class \'pandas.core.frame.Pandas\'>: it\'s not found as pandas.core.frame.Pandas")')

chuck in 🌐 conception in ~ via 🐍 v3.11.0 via 🅒  main
zsh ❯ python foo.py
Traceback (most recent call last):
  File "/home/chuck/foo.py", line 14, in <module>
    y = joblib.Parallel(n_jobs=1)(joblib.delayed(foo)(x) for x in df.itertuples())
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chuck/.miniconda3/envs/main/lib/python3.11/site-packages/joblib/parallel.py", line 1085, in __call__
    if self.dispatch_one_batch(iterator):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chuck/.miniconda3/envs/main/lib/python3.11/site-packages/joblib/parallel.py", line 901, in dispatch_one_batch
    self._dispatch(tasks)
  File "/home/chuck/.miniconda3/envs/main/lib/python3.11/site-packages/joblib/parallel.py", line 819, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chuck/.miniconda3/envs/main/lib/python3.11/site-packages/joblib/_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/chuck/.miniconda3/envs/main/lib/python3.11/site-packages/joblib/_parallel_backends.py", line 597, in __init__
    self.results = batch()
                   ^^^^^^^
  File "/home/chuck/.miniconda3/envs/main/lib/python3.11/site-packages/joblib/parallel.py", line 288, in __call__
    return [func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chuck/.miniconda3/envs/main/lib/python3.11/site-packages/joblib/parallel.py", line 288, in <listcomp>
    return [func(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/home/chuck/.miniconda3/envs/main/lib/python3.11/site-packages/joblib/memory.py", line 594, in __call__
    return self._cached_call(args, kwargs)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chuck/.miniconda3/envs/main/lib/python3.11/site-packages/joblib/memory.py", line 486, in _cached_call
    func_id, args_id = self._get_output_identifiers(*args, **kwargs)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chuck/.miniconda3/envs/main/lib/python3.11/site-packages/joblib/memory.py", line 638, in _get_output_identifiers
    argument_hash = self._get_argument_hash(*args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chuck/.miniconda3/envs/main/lib/python3.11/site-packages/joblib/memory.py", line 632, in _get_argument_hash
    return hashing.hash(filter_args(self.func, self.ignore, args, kwargs),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chuck/.miniconda3/envs/main/lib/python3.11/site-packages/joblib/hashing.py", line 266, in hash
    return hasher.hash(obj)
           ^^^^^^^^^^^^^^^^
  File "/home/chuck/.miniconda3/envs/main/lib/python3.11/site-packages/joblib/hashing.py", line 63, in hash
    self.dump(obj)
  File "/home/chuck/.miniconda3/envs/main/lib/python3.11/pickle.py", line 487, in dump
    self.save(obj)
  File "/home/chuck/.miniconda3/envs/main/lib/python3.11/site-packages/joblib/hashing.py", line 241, in save
    Hasher.save(self, obj)
  File "/home/chuck/.miniconda3/envs/main/lib/python3.11/site-packages/joblib/hashing.py", line 89, in save
    Pickler.save(self, obj)
  File "/home/chuck/.miniconda3/envs/main/lib/python3.11/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
    ^^^^^^^^^^^^
  File "/home/chuck/.miniconda3/envs/main/lib/python3.11/pickle.py", line 972, in save_dict
    self._batch_setitems(obj.items())
  File "/home/chuck/.miniconda3/envs/main/lib/python3.11/site-packages/joblib/hashing.py", line 140, in _batch_setitems
    Pickler._batch_setitems(self, iter(sorted(items)))
  File "/home/chuck/.miniconda3/envs/main/lib/python3.11/pickle.py", line 1003, in _batch_setitems
    save(v)
  File "/home/chuck/.miniconda3/envs/main/lib/python3.11/site-packages/joblib/hashing.py", line 241, in save
    Hasher.save(self, obj)
  File "/home/chuck/.miniconda3/envs/main/lib/python3.11/site-packages/joblib/hashing.py", line 89, in save
    Pickler.save(self, obj)
  File "/home/chuck/.miniconda3/envs/main/lib/python3.11/pickle.py", line 603, in save
    self.save_reduce(obj=obj, *rv)
  File "/home/chuck/.miniconda3/envs/main/lib/python3.11/pickle.py", line 687, in save_reduce
    save(cls)
  File "/home/chuck/.miniconda3/envs/main/lib/python3.11/site-packages/joblib/hashing.py", line 241, in save
    Hasher.save(self, obj)
  File "/home/chuck/.miniconda3/envs/main/lib/python3.11/site-packages/joblib/hashing.py", line 89, in save
    Pickler.save(self, obj)
  File "/home/chuck/.miniconda3/envs/main/lib/python3.11/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
    ^^^^^^^^^^^^
  File "/home/chuck/.miniconda3/envs/main/lib/python3.11/site-packages/joblib/hashing.py", line 111, in save_global
    Pickler.save_global(self, obj, **kwargs)
  File "/home/chuck/.miniconda3/envs/main/lib/python3.11/pickle.py", line 1071, in save_global
    raise PicklingError(
_pickle.PicklingError: ("Can't pickle <class 'pandas.core.frame.Pandas'>: it's not found as pandas.core.frame.Pandas", 'PicklingError while hashing {\'x\': Pandas(Index=0, a=0, b=100)}: PicklingError("Can\'t pickle <class \'pandas.core.frame.Pandas\'>: it\'s not found as pandas.core.frame.Pandas")')
```

Does anyone know how to handle or fix this? Or can someone explain to me what the issue is? Thanks!

**Comment by tomMoral** [comment]
Hello,

I can reproduce the issue, which seems to be linked to this one: pandas-dev/pandas#11791
They propose multiple solutions on the linked issue, the main one being using `itertuples(name=False)` to avoid having namedtuple which are not picklable.
But the core issue seems to be that `cloudpickle` does not handle the case of namedtuple, which seems strange.
It might be worth reporting on the `cloudpickle` tracker to see if they want to add the support for those.
