### ISSUE TITLE
`byte_bounds` is deprecated in numpy dev

### ISSUE THREAD

**Issue by ogrisel** [joblib/joblib#1454]
```python-traceback
Traceback (most recent call last):
  File "/usr/share/miniconda/envs/testvenv/lib/python3.11/site-packages/joblib/externals/loky/backend/queues.py", line 159, in _feed
    obj_ = dumps(obj, reducers=reducers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/miniconda/envs/testvenv/lib/python3.11/site-packages/joblib/externals/loky/backend/reduction.py", line 215, in dumps
    dump(obj, buf, reducers=reducers, protocol=protocol)
  File "/usr/share/miniconda/envs/testvenv/lib/python3.11/site-packages/joblib/externals/loky/backend/reduction.py", line 208, in dump
    _LokyPickler(file, reducers=reducers, protocol=protocol).dump(obj)
  File "/usr/share/miniconda/envs/testvenv/lib/python3.11/site-packages/joblib/externals/cloudpickle/cloudpickle_fast.py", line 632, in dump
    return Pickler.dump(self, obj)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/miniconda/envs/testvenv/lib/python3.11/site-packages/joblib/_memmapping_reducer.py", line 385, in __call__
    return _reduce_memmap_backed(a, m)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/miniconda/envs/testvenv/lib/python3.11/site-packages/joblib/_memmapping_reducer.py", line 269, in _reduce_memmap_backed
    a_start, a_end = np.byte_bounds(a)
                     ^^^^^^^^^^^^^^^^^
  File "/usr/share/miniconda/envs/testvenv/lib/python3.11/site-packages/numpy/lib/utils.py", line 143, in newfunc
    warnings.warn(depdoc, DeprecationWarning, stacklevel=2)
DeprecationWarning:     `byte_bounds` is deprecated!
```

from the scikit-learn nightly build CI against numpy dev.

**Comment by ogrisel** [comment]
See: https://github.com/scikit-learn/scikit-learn/pull/26646

**Comment by lesteve** [comment]
I have commented in https://github.com/numpy/numpy/pull/23830#issuecomment-1629208691 to get feed-back from Numpy on this.

**Comment by seberg** [comment]
If you are probing of two numpy arrays overlap, `np.may_share_memory` is the replacement.

**Comment by lesteve** [comment]
I don't think `np.may_share_memory` is enough for what we are doing (see below), but this needs a closer look.

https://github.com/joblib/joblib/blob/0c57c18c906b60002b394d91600e6189d98c0caa/joblib/_memmapping_reducer.py#L259-L295

We can always implement `byte_bounds` in joblib if needed.

**Comment by seberg** [comment]
Ah, I think I looked at some earlier point in the code maybe.  Here you do indeed need more to calculate the `offset` and `total_buffer_len`.

While agree that `byte_bounds` is pretty niche, I am also OK to reinstate it if you prefer. 

I would love to put it into soemthing like `np.lib.<something>.byte_bounds`.  It would really be helpful to figure out a naming scheme for a future where `np.lib.<submodule>` is generally used for extended truly public functionality (and not a weird mix of public things and implementation detail).

**Comment by mtsokol** [comment]
Hi @lesteve!
I'm working on deprecations/Python API cleanup - I can revert that deprecation (or move `byte_bounds` to a more specific module) if agreed.

**Comment by ogrisel** [comment]
I think it can be useful to other projects, so better keep this in numpy, possibly not in the top level namespace.

**Comment by lesteve** [comment]
Our code was adapted in #1501.
