### ISSUE TITLE
TypeError: Cannot enter `np.errstate` twice on numpy dev

### ISSUE THREAD

**Issue by ogrisel** [joblib/joblib#1455]
```python-traceback
Traceback (most recent call last):
  File "/usr/share/miniconda/envs/testvenv/lib/python3.11/site-packages/joblib/_parallel_backends.py", line 272, in _wrap_func_call
    return func()
           ^^^^^^
  File "/usr/share/miniconda/envs/testvenv/lib/python3.11/site-packages/joblib/parallel.py", line 580, in __call__
    return [func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/miniconda/envs/testvenv/lib/python3.11/site-packages/joblib/parallel.py", line 580, in <listcomp>
    return [func(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/home/vsts/work/1/s/sklearn/utils/parallel.py", line 127, in __call__
    return self.function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vsts/work/1/s/sklearn/ensemble/_forest.py", line 173, in _parallel_build_trees
    indices = _generate_sample_indices(
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vsts/work/1/s/sklearn/ensemble/_forest.py", line 129, in _generate_sample_indices
    random_instance = check_random_state(random_state)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vsts/work/1/s/sklearn/utils/validation.py", line 1274, in check_random_state
    return np.random.RandomState(seed)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "numpy/random/mtrand.pyx", line 184, in numpy.random.mtrand.RandomState.__init__
  File "_mt19937.pyx", line 130, in numpy.random._mt19937.MT19937.__init__
  File "/usr/share/miniconda/envs/testvenv/lib/python3.11/contextlib.py", line 80, in inner
    with self._recreate_cm():
  File "/usr/share/miniconda/envs/testvenv/lib/python3.11/site-packages/numpy/core/_ufunc_config.py", line 406, in __enter__
    raise TypeError("Cannot enter `np.errstate` twice.")
TypeError: Cannot enter `np.errstate` twice.
```
from a failure of the scikit-learn CI on scipy-dev:

https://dev.azure.com/scikit-learn/scikit-learn/_build/results?buildId=56067&view=logs&j=dfe99b15-50db-5d7b-b1e9-4105c42527cf&t=ef785ae2-496b-5b02-9f0e-07a6c3ab3081&l=1596

For context here is the PR that introduced the change in numpy:
- https://github.com/numpy/numpy/pull/23936

**Comment by ogrisel** [comment]
Actually the problem happens with the threading-backend in `RandomForestClassifier.fit`:

```python
    def test_parallel_train():
        rng = check_random_state(12321)
        n_samples, n_features = 80, 30
        X_train = rng.randn(n_samples, n_features)
        y_train = rng.randint(0, 2, n_samples)
    
>       clfs = [
            RandomForestClassifier(n_estimators=20, n_jobs=n_jobs, random_state=12345).fit(
                X_train, y_train
            )
            for n_jobs in [1, 2, 3, 8, 16, 32]
        ]
```
