### ISSUE TITLE
TypeError when using joblib to make requests to multiprocessing.Manager

### ISSUE THREAD

**Issue by uchenily** [joblib/joblib#1467]
I got "'NoneType' object cannot be interpreted as an integer" error when using joblib.
here is reproduce code:

```shell
$ cat /tmp/1.py
from multiprocessing import Manager
from joblib import Parallel, delayed
from queue import Empty

proxy_manager = Manager()
queue = proxy_manager.Queue()

def func1():
    for i in range(100):
        try:
            queue.get(block=False)
        except Empty:
            pass
        except TypeError as e:
            print(type(e), e)

Parallel(n_jobs=2, backend="loky")((delayed(func1)() for _ in range(32)))
$ python /tmp/1.py
<class 'TypeError'> 'NoneType' object cannot be interpreted as an integer
<class 'TypeError'> 'NoneType' object cannot be interpreted as an integer
<class 'TypeError'> 'NoneType' object cannot be interpreted as an integer
$ python -V
Python 3.10.11
$ python -c 'import joblib; print(joblib.__version__)'
1.2.0
```

this issue seems to be related to the resource cleanup or fd close in multiprocessing + joblib

```python
  File "/root/venv/lib/python3.10/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
TypeError: 'NoneType' object cannot be interpreted as an integer
```

**Comment by ogrisel** [comment]
Here is a variant of the script with the full traceback:

```python
In [1]: from multiprocessing import Manager
   ...: from joblib import Parallel, delayed
   ...: from queue import Empty
   ...: 
   ...: proxy_manager = Manager()
   ...: queue = proxy_manager.Queue()
   ...: 
   ...: def func1():
   ...:     for i in range(100):
   ...:         try:
   ...:             queue.get(block=False)
   ...:         except Empty:
   ...:             pass
   ...: 
   ...: 
   ...: Parallel(n_jobs=2, backend="loky")((delayed(func1)() for _ in range(32)))

---------------------------------------------------------------------------
_RemoteTraceback                          Traceback (most recent call last)
_RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/ogrisel/code/joblib/joblib/externals/loky/process_executor.py", line 463, in _process_worker
    r = call_item()
        ^^^^^^^^^^^
  File "/Users/ogrisel/code/joblib/joblib/externals/loky/process_executor.py", line 291, in __call__
    return self.fn(*self.args, **self.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ogrisel/code/joblib/joblib/parallel.py", line 588, in __call__
    return [func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ogrisel/code/joblib/joblib/parallel.py", line 588, in <listcomp>
    return [func(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^
  File "<ipython-input-1-1559f532f2cb>", line 11, in func1
  File "<string>", line 2, in get
  File "/Users/ogrisel/mambaforge/envs/dev/lib/python3.11/multiprocessing/managers.py", line 821, in _callmethod
    conn.send((self._id, methodname, args, kwds))
  File "/Users/ogrisel/mambaforge/envs/dev/lib/python3.11/multiprocessing/connection.py", line 205, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/Users/ogrisel/mambaforge/envs/dev/lib/python3.11/multiprocessing/connection.py", line 410, in _send_bytes
    self._send(header + buf)
  File "/Users/ogrisel/mambaforge/envs/dev/lib/python3.11/multiprocessing/connection.py", line 367, in _send
    n = write(self._handle, buf)
        ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object cannot be interpreted as an integer
"""

The above exception was the direct cause of the following exception:

TypeError                                 Traceback (most recent call last)
Cell In[1], line 16
     12         except Empty:
     13             pass
---> 16 Parallel(n_jobs=2, backend="loky")((delayed(func1)() for _ in range(32)))

File ~/code/joblib/joblib/parallel.py:1930, in Parallel.__call__(self, iterable)
   1924 # The first item from the output is blank, but it makes the interpreter
   1925 # progress until it enters the Try/Except block of the generator and
   1926 # reach the first `yield` statement. This starts the aynchronous
   1927 # dispatch of the tasks to the workers.
   1928 next(output)
-> 1930 return output if self.return_generator else list(output)

File ~/code/joblib/joblib/parallel.py:1573, in Parallel._get_outputs(self, iterator, pre_dispatch)
   1570     yield
   1572     with self._backend.retrieval_context():
-> 1573         yield from self._retrieve()
   1575 except GeneratorExit:
   1576     # The generator has been garbage collected before being fully
   1577     # consumed. This aborts the remaining tasks if possible and warn
   1578     # the user if necessary.
   1579     self._exception = True

File ~/code/joblib/joblib/parallel.py:1677, in Parallel._retrieve(self)
   1670 while self._wait_retrieval():
   1671 
   1672     # If the callback thread of a worker has signaled that its task
   1673     # triggerd an exception, or if the retrieval loop has raised an
   1674     # exception (e.g. `GeneratorExit`), exit the loop and surface the
   1675     # worker traceback.
   1676     if self._aborting:
-> 1677         self._raise_error_fast()
   1678         break
   1680     # If the next job is not ready for retrieval yet, we just wait for
   1681     # async callbacks to progress.

File ~/code/joblib/joblib/parallel.py:1712, in Parallel._raise_error_fast(self)
   1708 # If this error job exists, immediatly raise the error by
   1709 # calling get_result. This job might not exists if abort has been
   1710 # called directly or if the generator is gc'ed.
   1711 if error_job is not None:
-> 1712     error_job.get_result(self.timeout)

File ~/code/joblib/joblib/parallel.py:735, in BatchCompletionCallBack.get_result(self, timeout)
    729 backend = self.parallel._backend
    731 if backend.supports_retrieve_callback:
    732     # We assume that the result has already been retrieved by the
    733     # callback thread, and is stored internally. It's just waiting to
    734     # be returned.
--> 735     return self._return_or_raise()
    737 # For other backends, the main thread needs to run the retrieval step.
    738 try:

File ~/code/joblib/joblib/parallel.py:753, in BatchCompletionCallBack._return_or_raise(self)
    751 try:
    752     if self.status == TASK_ERROR:
--> 753         raise self._result
    754     return self._result
    755 finally:

TypeError: 'NoneType' object cannot be interpreted as an integer
```

**Comment by ogrisel** [comment]
I replicated the problem with loky directly using a `Queue` instance derived from a `Manager` instance from the "loky" context and I get the same result:

```python
In [8]: from multiprocessing import get_context
   ...: import loky

In [9]: loky_ctx = get_context("loky")

In [10]: manager = loky_ctx.Manager()

In [11]: queue = manager.Queue()

In [12]: def func1(*ignored):
    ...:     for i in range(100):
    ...:         try:
    ...:             queue.get(block=False)
    ...:         except Empty:
    ...:             pass
    ...: 

In [13]: e = loky.get_reusable_executor()

In [14]: list(e.map(func1, range(32)))
---------------------------------------------------------------------------
_RemoteTraceback                          Traceback (most recent call last)
_RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/ogrisel/code/loky/loky/process_executor.py", line 463, in _process_worker
    r = call_item()
        ^^^^^^^^^^^
  File "/Users/ogrisel/code/loky/loky/process_executor.py", line 291, in __call__
    return self.fn(*self.args, **self.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ogrisel/code/loky/loky/process_executor.py", line 364, in _process_chunk
    return [fn(*args) for args in chunk]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ogrisel/code/loky/loky/process_executor.py", line 364, in <listcomp>
    return [fn(*args) for args in chunk]
            ^^^^^^^^^
  File "<ipython-input-12-922edc546506>", line 4, in func1
  File "<string>", line 2, in get
  File "/Users/ogrisel/mambaforge/envs/dev/lib/python3.11/multiprocessing/managers.py", line 821, in _callmethod
    conn.send((self._id, methodname, args, kwds))
  File "/Users/ogrisel/mambaforge/envs/dev/lib/python3.11/multiprocessing/connection.py", line 205, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/Users/ogrisel/mambaforge/envs/dev/lib/python3.11/multiprocessing/connection.py", line 410, in _send_bytes
    self._send(header + buf)
  File "/Users/ogrisel/mambaforge/envs/dev/lib/python3.11/multiprocessing/connection.py", line 367, in _send
    n = write(self._handle, buf)
        ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object cannot be interpreted as an integer
"""

The above exception was the direct cause of the following exception:

TypeError                                 Traceback (most recent call last)
Cell In[14], line 1
----> 1 list(e.map(func1, range(32)))

File ~/code/loky/loky/process_executor.py:967, in _chain_from_iterable_of_lists(iterable)
    961 def _chain_from_iterable_of_lists(iterable):
    962     """
    963     Specialized implementation of itertools.chain.from_iterable.
    964     Each item in *iterable* should be a list.  This function is
    965     careful not to keep references to yielded objects.
    966     """
--> 967     for element in iterable:
    968         element.reverse()
    969         while element:

File ~/mambaforge/envs/dev/lib/python3.11/concurrent/futures/_base.py:619, in Executor.map.<locals>.result_iterator()
    616 while fs:
    617     # Careful not to keep a reference to the popped future
    618     if timeout is None:
--> 619         yield _result_or_cancel(fs.pop())
    620     else:
    621         yield _result_or_cancel(fs.pop(), end_time - time.monotonic())

File ~/mambaforge/envs/dev/lib/python3.11/concurrent/futures/_base.py:317, in _result_or_cancel(***failed resolving arguments***)
    315 try:
    316     try:
--> 317         return fut.result(timeout)
    318     finally:
    319         fut.cancel()

File ~/mambaforge/envs/dev/lib/python3.11/concurrent/futures/_base.py:456, in Future.result(self, timeout)
    454     raise CancelledError()
    455 elif self._state == FINISHED:
--> 456     return self.__get_result()
    457 else:
    458     raise TimeoutError()

File ~/mambaforge/envs/dev/lib/python3.11/concurrent/futures/_base.py:401, in Future.__get_result(self)
    399 if self._exception:
    400     try:
--> 401         raise self._exception
    402     finally:
    403         # Break a reference cycle with the exception in self._exception
    404         self = None

TypeError: 'NoneType' object cannot be interpreted as an integer
```

So it seems that there is actually a bug in the `Manager` implementation from the loky backend. I will open a dedicated issue for this on the upstream repo. However I don't think I will have time to investigate more myself, but feel free to open a PR there if find a solution.
