### ISSUE TITLE
Crash when running high number of parallel jobs

### ISSUE THREAD

**Issue by dakaidan** [joblib/joblib#1486]
We are fuzzing machine learning libraries to improve their reliability and hit a bug in the `RandomForestClassifier` of  `scikit-learn`, which is originating from `joblib`.

When running with a high number of threads a crash occurs, I initially reported this [here](https://github.com/scikit-learn/scikit-learn/issues/26905) as it was found through fuzzing `scikit-learn`.  

This can be reproduced with `scikit-learn` with the following:
```
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_jobs=32067)
model.fit([[1]], [[1, 2]])
```

Producing
```
Traceback (most recent call last):
  File "/share/Work/RandomForestClassifierThread.py", line 6, in <module>
    model.fit([[1]], [[1, 2]])
  File "/usr/local/lib/python3.9/site-packages/sklearn/base.py", line 1151, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/sklearn/ensemble/_forest.py", line 456, in fit
    trees = Parallel(
  File "/usr/local/lib/python3.9/site-packages/sklearn/utils/parallel.py", line 65, in __call__
    return super().__call__(iterable_with_config)
  File "/usr/local/lib/python3.9/site-packages/joblib/parallel.py", line 1927, in __call__
    iterator = itertools.islice(iterator, self._pre_dispatch_amount)
ValueError: Stop argument for islice() must be None or an integer: 0 <= x <= sys.maxsize.
```

The job number appears to be very system sensitive, `32067` was the lowest I could go on my system while still consistently getting a crash. while you could go much higher to around `4611686018427387905` before `joblib` throws an error.

I'd suggest when given high number of jobs which can cause a crash it should be treated as a `-1` as I mentioned in the original bug report.

**Comment by lesteve** [comment]
So I don't think this is likely to be at the top of our priority list in the foreseeable future, I am going to close this one.
