### ISSUE TITLE
KeyError in loky backend

### ISSUE THREAD

**Issue by Okroshiashvili** [joblib/joblib#1595]
Today, I was training some anomaly detection models using [PyOd](https://github.com/yzhao062/pyod) and [SUOD](https://github.com/yzhao062/suod) and got the following KeyError. I use [Pixi](https://github.com/prefix-dev/pixi)
 to manage dependencies

```
KeyError: '/var/folders/mz/3thvm62j52l8lpr5sllrt6rh0000gn/T/joblib_memmapping_folder_50524_96bd540c7f034a23b41d88ee1abf23b8_ff7b7b615ed44a9f98bfadc1ad848e5d/50524-6115774864-9cb066ed558b4639a4c2ca81c268d9c1.pkl'
Traceback (most recent call last):
  File "/Users/*****/Desktop/task/.pixi/envs/default/lib/python3.12/site-packages/joblib/externals/loky/backend/resource_tracker.py", line 281, in main
    registry[rtype][name] -= 1
```

When I tried [this example](https://github.com/yzhao062/pyod/blob/master/examples/suod_example.py) there were no error. However, when tried my data got the above error.

**Comment by miohtama** [comment]
I can confirm this error 

- Running Jupyter Notebook on Datalore 
- The notebook is using joblib for background multirocessing

```
 File "/opt/python/envs/minimal/lib/python3.11/site-packages/joblib/externals/loky/backend/resource_tracker.py", line 281, in main
    registry[rtype][name] -= 1
    ~~~~~~~~~~~~~~~^^^^^^
KeyError: '/tmp/joblib_memmapping_folder_10171_f0478ff659324e6ea2882b6d38a6c510_1a62ea928e664013a186bffb98f5957e/10171-140348080872016-ffbe66388ea044fe985c2f5e604377d5.pkl'
```

**Comment by chenyangkang** [comment]
Same here

**Comment by lesteve** [comment]
I know it's likely quite some work, but it would be super useful if someone manages to put together a stand-alone snippet that reproduces the error.

This would help a lot trying to debug this issue. Without a stand-alone snippet, there is not much we can do but wild-guessing ...

**Comment by chenyangkang** [comment]
For me, it turns out to be a stupid mistake that I made

```bash
Traceback (most recent call last):
  File "/my_path/my_file.py", line 438, in <module>
    memory_use = memory_usage((run_model, (sp1, sp2, output_name, n_name, )), interval=60)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mypath/micromamba/lib/python3.12/site-packages/memory_profiler.py", line 379, in memory_usage
    returned = f(*args, **kw)
               ^^^^^^^^^^^^^^
  File "/my_path/my_file.py", line 321, in run_model
    res = predict_each_date(date0)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/my_path/my_file.py", line 273, in predict_each_date
    ensemble_pred_transformed[2][:,col_index] = np.log(prob1/(1-prob1))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^
KeyError: 2
Traceback (most recent call last):
  File "/my_path/micromamba/lib/python3.12/site-packages/joblib/externals/loky/backend/resource_tracker.py", line 274, in main
    del registry[rtype][name]
        ~~~~~~~~~~~~~~~^^^^^^
KeyError: '/loky-1096322-5wqstp36'
```

I missed the real error line `ensemble_pred_transformed[2][:,col_index] = np.log(prob1/(1-prob1))` caused by my code because there are huge amount of trace back mentioning joblib. So I think I solved it.

**Comment by lesteve** [comment]
According to https://github.com/joblib/joblib/issues/1243#issuecomment-990660813, this shouldn't affect the execution of the script only the cleaning up of memmapped files.

I am going to close this one since it seems a duplicate of https://github.com/joblib/joblib/issues/1243.
