### ISSUE TITLE
pickle errors with Python 2.7.8 win32

### ISSUE THREAD

**Issue by pombredanne** [joblib/joblib#160]
using the memory cache decorator with a function that returns an object of about 200MB once pickled I get the error. In fairness I get the same error when I try to use cPickle directly possibly because of http://bugs.python.org/issue13555 yet it should have been fixed....

```
Traceback (most recent call last):
  File "c:\w421\scripts\eggs\joblib-0.8.2-py2.7.egg\joblib\memory.py", line 481, in __call__
    depending from it.
  File "c:\w421\scripts\eggs\joblib-0.8.2-py2.7.egg\joblib\memory.py", line 428, in _cached_call
    out = _load_output(output_dir, _get_func_fullname(self.func),
  File "c:\w421\scripts\eggs\joblib-0.8.2-py2.7.egg\joblib\memory.py", line 674, in call
    if self._verbose > 0:
  File "c:\w421\scripts\eggs\joblib-0.8.2-py2.7.egg\joblib\memory.py", line 691, in _persist_output
    " Race condition in the creation of the directory "
  File "c:\w421\scripts\eggs\joblib-0.8.2-py2.7.egg\joblib\numpy_pickle.py", line 368, in dump
    pickler.dump(value)
  File "c:\Python27\Lib\pickle.py", line 224, in dump
    self.save(obj)
  File "c:\w421\scripts\eggs\joblib-0.8.2-py2.7.egg\joblib\numpy_pickle.py", line 248, in save
    return Pickler.save(self, obj)
  File "c:\Python27\Lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "c:\Python27\Lib\pickle.py", line 419, in save_reduce
    save(state)
  File "c:\w421\scripts\eggs\joblib-0.8.2-py2.7.egg\joblib\numpy_pickle.py", line 248, in save
    return Pickler.save(self, obj)
  File "c:\Python27\Lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "c:\Python27\Lib\pickle.py", line 649, in save_dict
    self._batch_setitems(obj.iteritems())
  File "c:\Python27\Lib\pickle.py", line 681, in _batch_setitems
    save(v)
  File "c:\w421\scripts\eggs\joblib-0.8.2-py2.7.egg\joblib\numpy_pickle.py", line 248, in save
    return Pickler.save(self, obj)
  File "c:\Python27\Lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "c:\Python27\Lib\pickle.py", line 649, in save_dict
    self._batch_setitems(obj.iteritems())
  File "c:\Python27\Lib\pickle.py", line 681, in _batch_setitems
    save(v)
  File "c:\w421\scripts\eggs\joblib-0.8.2-py2.7.egg\joblib\numpy_pickle.py", line 248, in save
    return Pickler.save(self, obj)
  File "c:\Python27\Lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "c:\Python27\Lib\pickle.py", line 419, in save_reduce
    save(state)
  File "c:\w421\scripts\eggs\joblib-0.8.2-py2.7.egg\joblib\numpy_pickle.py", line 248, in save
    return Pickler.save(self, obj)
  File "c:\Python27\Lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "c:\Python27\Lib\pickle.py", line 649, in save_dict
    self._batch_setitems(obj.iteritems())
  File "c:\Python27\Lib\pickle.py", line 681, in _batch_setitems
    save(v)
  File "c:\w421\scripts\eggs\joblib-0.8.2-py2.7.egg\joblib\numpy_pickle.py", line 248, in save
    return Pickler.save(self, obj)
  File "c:\Python27\Lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "c:\Python27\Lib\pickle.py", line 401, in save_reduce
    save(args)
  File "c:\w421\scripts\eggs\joblib-0.8.2-py2.7.egg\joblib\numpy_pickle.py", line 248, in save
    return Pickler.save(self, obj)
  File "c:\Python27\Lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "c:\Python27\Lib\pickle.py", line 548, in save_tuple
    save(element)
  File "c:\w421\scripts\eggs\joblib-0.8.2-py2.7.egg\joblib\numpy_pickle.py", line 248, in save
    return Pickler.save(self, obj)
  File "c:\Python27\Lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "c:\Python27\Lib\pickle.py", line 600, in save_list
    self._batch_appends(iter(obj))
  File "c:\Python27\Lib\pickle.py", line 633, in _batch_appends
    save(x)
  File "c:\w421\scripts\eggs\joblib-0.8.2-py2.7.egg\joblib\numpy_pickle.py", line 248, in save
    return Pickler.save(self, obj)
  File "c:\Python27\Lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "c:\Python27\Lib\pickle.py", line 600, in save_list
    self._batch_appends(iter(obj))
  File "c:\Python27\Lib\pickle.py", line 633, in _batch_appends
    save(x)
  File "c:\w421\scripts\eggs\joblib-0.8.2-py2.7.egg\joblib\numpy_pickle.py", line 248, in save
    return Pickler.save(self, obj)
  File "c:\Python27\Lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "c:\Python27\Lib\pickle.py", line 405, in save_reduce
    self.memoize(obj)
  File "c:\Python27\Lib\pickle.py", line 247, in memoize
    self.memo[id(obj)] = memo_len, obj
MemoryError
``
```

**Comment by jeremiedbb** [comment]
This issue is very old and the error has only been reported on python 2.7 which is not supported. Let's close
