### ISSUE TITLE
ValueError: array is not writeable

### ISSUE THREAD

**Issue by giospud** [joblib/joblib#1627]
Dear All
I am trying to use joblib on some workstation (physical in my office and some AWS machines)
Anyway when I try to use it with nproc>1 I get tthe following error:

```
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/ubuntu/opt/miniforge3/envs/meteocean/lib/python3.13/site-packages/joblib/externals/loky/process_executor.py", line 463, in _process_worker
    r = call_item()
  File "/home/ubuntu/opt/miniforge3/envs/meteocean/lib/python3.13/site-packages/joblib/externals/loky/process_executor.py", line 291, in __call__
    return self.fn(*self.args, **self.kwargs)
           ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/opt/miniforge3/envs/meteocean/lib/python3.13/site-packages/joblib/parallel.py", line 598, in __call__
    return [func(*args, **kwargs)
            ~~~~^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/wwiii_post-proc/pltUnstrWWIII_all.py", line 259, in _plot_map_var
    data.map_var(vari, iitt=timei, dir_out=dir_out, cmap=cmap_v[vari])
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/wwiii_post-proc/pltUnstrWWIII_all.py", line 195, in map_var
    ctrf = axs.tricontourf(self.triangm, var_data, levels=lvls, cmap=cmap)
  File "/home/ubuntu/opt/miniforge3/envs/meteocean/lib/python3.13/site-packages/matplotlib/tri/_tricontour.py", line 270, in tricontourf
    return TriContourSet(ax, *args, **kwargs)
  File "/home/ubuntu/opt/miniforge3/envs/meteocean/lib/python3.13/site-packages/matplotlib/tri/_tricontour.py", line 29, in __init__
    super().__init__(ax, *args, **kwargs)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/opt/miniforge3/envs/meteocean/lib/python3.13/site-packages/matplotlib/contour.py", line 813, in __init__
    kwargs = self._process_args(*args, **kwargs)
  File "/home/ubuntu/opt/miniforge3/envs/meteocean/lib/python3.13/site-packages/matplotlib/tri/_tricontour.py", line 46, in _process_args
    C = _tri.TriContourGenerator(tri.get_cpp_triangulation(), z)
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/ubuntu/opt/miniforge3/envs/meteocean/lib/python3.13/site-packages/matplotlib/tri/_triangulation.py", line 124, in get_cpp_triangulation
    self._cpp_triangulation = _tri.Triangulation(
                              ~~~~~~~~~~~~~~~~~~^
        # For unset arrays use empty tuple which has size of zero.
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
        self._neighbors if self._neighbors is not None else (),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        not self.is_delaunay)
        ^^^^^^^^^^^^^^^^^^^^^
ValueError: array is not writeable
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/wwiii_post-proc/pltUnstrWWIII_all.py", line 281, in <module>
    Parallel(n_jobs=npj)(delayed(_plot_map_var)(data, var_i, time_i, dir_pics, extent=area) for time_i in range(0, data.ntime))
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/opt/miniforge3/envs/meteocean/lib/python3.13/site-packages/joblib/parallel.py", line 2007, in __call__
    return output if self.return_generator else list(output)
                                                ~~~~^^^^^^^^
  File "/home/ubuntu/opt/miniforge3/envs/meteocean/lib/python3.13/site-packages/joblib/parallel.py", line 1650, in _get_outputs
    yield from self._retrieve()
  File "/home/ubuntu/opt/miniforge3/envs/meteocean/lib/python3.13/site-packages/joblib/parallel.py", line 1754, in _retrieve
    self._raise_error_fast()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/ubuntu/opt/miniforge3/envs/meteocean/lib/python3.13/site-packages/joblib/parallel.py", line 1789, in _raise_error_fast
    error_job.get_result(self.timeout)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/ubuntu/opt/miniforge3/envs/meteocean/lib/python3.13/site-packages/joblib/parallel.py", line 745, in get_result
    return self._return_or_raise()
           ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/ubuntu/opt/miniforge3/envs/meteocean/lib/python3.13/site-packages/joblib/parallel.py", line 763, in _return_or_raise
    raise self._result
ValueError: array is not writeable
```

I really do not understand which is the problem here 

The packages installed in the Mamba ENV are the following:
```
_# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
blosc                     1.21.6               hef167b5_0    conda-forge
brotli                    1.1.0                hb9d3cd8_2    conda-forge
brotli-bin                1.1.0                hb9d3cd8_2    conda-forge
bzip2                     1.0.8                h4bc722e_7    conda-forge
c-ares                    1.34.3               hb9d3cd8_1    conda-forge
ca-certificates           2024.8.30            hbcca054_0    conda-forge
cartopy                   0.24.0          py313ha87cce1_0    conda-forge
certifi                   2024.8.30          pyhd8ed1ab_0    conda-forge
cftime                    1.6.4           py313ha014f3b_1    conda-forge
cmocean                   4.0.3              pyhd8ed1ab_0    conda-forge
colorspacious             1.1.2              pyh24bf2e0_0    conda-forge
conda-pack                0.8.1              pyhff2d567_0    conda-forge
contourpy                 1.3.1           py313h33d0bda_0    conda-forge
cpp-expected              1.1.0                hf52228f_0    conda-forge
cycler                    0.12.1             pyhd8ed1ab_0    conda-forge
fmt                       11.0.2               h434a139_0    conda-forge
fonttools                 4.55.0          py313h8060acc_0    conda-forge
freetype                  2.12.1               h267a509_2    conda-forge
geos                      3.13.0               h5888daf_0    conda-forge
hdf4                      4.2.15               h2a13503_7    conda-forge
hdf5                      1.14.4          nompi_h2d575fe_103    conda-forge
joblib                    1.4.2              pyhd8ed1ab_0    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.4.7           py313h33d0bda_0    conda-forge
krb5                      1.21.3               h659f571_0    conda-forge
lcms2                     2.16                 hb7c19ff_0    conda-forge
ld_impl_linux-64          2.43                 h712a8e2_2    conda-forge
lerc                      4.0.0                h27087fc_0    conda-forge
libaec                    1.1.3                h59595ed_0    conda-forge
libarchive                3.7.4                hfca40fe_0    conda-forge
libblas                   3.9.0           25_linux64_openblas    conda-forge
libbrotlicommon           1.1.0                hb9d3cd8_2    conda-forge
libbrotlidec              1.1.0                hb9d3cd8_2    conda-forge
libbrotlienc              1.1.0                hb9d3cd8_2    conda-forge
libcblas                  3.9.0           25_linux64_openblas    conda-forge
libcurl                   8.10.1               hbbe4b11_0    conda-forge
libdeflate                1.22                 hb9d3cd8_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 hd590300_2    conda-forge
libexpat                  2.6.4                h5888daf_0    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc                    14.2.0               h77fa898_1    conda-forge
libgcc-ng                 14.2.0               h69a702a_1    conda-forge
libgfortran               14.2.0               h69a702a_1    conda-forge
libgfortran5              14.2.0               hd5240d6_1    conda-forge
libgomp                   14.2.0               h77fa898_1    conda-forge
libiconv                  1.17                 hd590300_2    conda-forge
libjpeg-turbo             3.0.0                hd590300_1    conda-forge
liblapack                 3.9.0           25_linux64_openblas    conda-forge
libmamba                  2.0.4                hf72d635_0    conda-forge
libmpdec                  4.0.0                h4bc722e_0    conda-forge
libnetcdf                 4.9.2           nompi_h2564987_115    conda-forge
libnghttp2                1.64.0               h161d5f1_0    conda-forge
libopenblas               0.3.28          pthreads_h94d23a6_1    conda-forge
libpng                    1.6.44               hadc24fc_0    conda-forge
libsolv                   0.7.30               h3509ff9_0    conda-forge
libsqlite                 3.47.0               hadc24fc_1    conda-forge
libssh2                   1.11.1               hf672d98_0    conda-forge
libstdcxx                 14.2.0               hc0a3c3a_1    conda-forge
libstdcxx-ng              14.2.0               h4852527_1    conda-forge
libtiff                   4.7.0                he137b08_1    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libwebp-base              1.4.0                hd590300_0    conda-forge
libxcb                    1.17.0               h8a09558_0    conda-forge
libxml2                   2.13.5               h064dc61_0    conda-forge
libzip                    1.11.2               h6991a6a_0    conda-forge
libzlib                   1.3.1                hb9d3cd8_2    conda-forge
lz4-c                     1.9.4                hcb278e6_0    conda-forge
lzo                       2.10              hd590300_1001    conda-forge
mamba                     2.0.4                hfdd0a45_0    conda-forge
matplotlib-base           3.9.2           py313h129903b_2    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
ncurses                   6.5                  he02047a_1    conda-forge
netcdf4                   1.7.2           nompi_py313h1dd084c_100    conda-forge
nlohmann_json             3.11.3               he02047a_1    conda-forge
numpy                     2.1.3           py313h4bf6692_0    conda-forge
openjpeg                  2.5.2                h488ebb8_0    conda-forge
openssl                   3.4.0                hb9d3cd8_0    conda-forge
packaging                 24.2               pyhff2d567_1    conda-forge
pandas                    2.2.3           py313ha87cce1_1    conda-forge
pillow                    11.0.0          py313h2d7ed13_0    conda-forge
pip                       24.3.1             pyh145f28c_0    conda-forge
proj                      9.5.0                h12925eb_0    conda-forge
pthread-stubs             0.4               hb9d3cd8_1002    conda-forge
pyparsing                 3.2.0              pyhd8ed1ab_1    conda-forge
pyproj                    3.7.0           py313hdb96ca5_0    conda-forge
pyshp                     2.3.1              pyhd8ed1ab_0    conda-forge
python                    3.13.0          h9ebbce0_100_cp313    conda-forge
python-dateutil           2.9.0.post0        pyhff2d567_0    conda-forge
python-tzdata             2024.2             pyhd8ed1ab_0    conda-forge
python_abi                3.13                    5_cp313    conda-forge
pytz                      2024.1             pyhd8ed1ab_0    conda-forge
qhull                     2020.2               h434a139_5    conda-forge
readline                  8.2                  h8228510_1    conda-forge
reproc                    14.2.5.post0         hb9d3cd8_0    conda-forge
reproc-cpp                14.2.5.post0         h5888daf_0    conda-forge
scipy                     1.14.1          py313h27c5614_1    conda-forge
setuptools                75.6.0             pyhff2d567_0    conda-forge
shapely                   2.0.6           py313h3f71f02_2    conda-forge
simdjson                  3.10.1               h84d6215_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.2.1                ha2e4443_0    conda-forge
spdlog                    1.14.1               hed91bc2_1    conda-forge
sqlite                    3.47.0               h9eae976_1    conda-forge
tk                        8.6.13          noxft_h4845f30_101    conda-forge
tzdata                    2024b                hc8b5060_0    conda-forge
xarray                    2024.10.0          pyhd8ed1ab_0    conda-forge
xorg-libxau               1.0.11               hb9d3cd8_1    conda-forge
xorg-libxdmcp             1.1.5                hb9d3cd8_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
yaml-cpp                  0.8.0                h59595ed_0    conda-forge
zlib                      1.3.1                hb9d3cd8_2    conda-forge
zstd                      1.5.6                ha6fb4c9_0    conda-forge_

```

**Comment by lesteve** [comment]
Without a snippet to reproduce it's very hard to help ... 

Wild guess, if you control the argument passed to `Parallel` try to use `Parallel(max_nbytes=None, ...)` to turn-off auto-memmapping?

**Comment by lesteve** [comment]
probably one work-around is to turn off the auto memmaping with using `parallel_config(max_nbytes=None):
```py
from joblib import parallel_config


with parallel_config(max_nbytes=None):
   code_that_uses_joblib_parallel_goes_here(...)
```
