### ISSUE TITLE
AttributeError: Can't get local attribute 

### ISSUE THREAD

**Issue by sciunto** [joblib/joblib#166]
Hi,

I made this minimal code:

```
from joblib import Parallel, delayed


def preprocess_fluo_args(im, **args):
    im = im * im
    c = args['c']
    return im + c


def all_args(func, **params):
    def wrapper(im):
        return func(im, **params)
    return wrapper

def loop(t_id, preprocess_fluo=None):
    res = 0
    if preprocess_fluo is not None:
        res = preprocess_fluo(t_id)
    return res


if __name__ == '__main__':

    preprocess_fluo = all_args(preprocess_fluo_args,
                               c=10)
    print('for loop')
    res = [loop(i, preprocess_fluo) for i in range(0, 3, 1)]
    print(res)
    print('joblib')
    res = Parallel(n_jobs=3)(delayed(loop)(i, preprocess_fluo) for i in range(0, 3, 1))
    print(res)

```

For which I have the following backtrace.

```
for loop
[10, 11, 14]
joblib
Traceback (most recent call last):
  File "/usr/lib/python3.4/pickle.py", line 909, in save_global
    obj2 = _getattribute(module, name, allow_qualname=self.proto >= 4)
  File "/usr/lib/python3.4/pickle.py", line 270, in _getattribute
    .format(name, obj))
AttributeError: Can't get local attribute 'all_args.<locals>.wrapper' on <function all_args at 0x7fb2830fd378>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./track.py", line 34, in <module>
    res = Parallel(n_jobs=3)(delayed(loop)(i, preprocess_fluo) for i in range(0, 3, 1))
  File "/usr/lib/python3.4/site-packages/joblib/parallel.py", line 651, in __call__
    self.retrieve()
  File "/usr/lib/python3.4/site-packages/joblib/parallel.py", line 503, in retrieve
    self._output.append(job.get())
  File "/usr/lib/python3.4/multiprocessing/pool.py", line 599, in get
    raise self._value
  File "/usr/lib/python3.4/multiprocessing/pool.py", line 383, in _handle_tasks
    put(task)
  File "/usr/lib/python3.4/site-packages/joblib/pool.py", line 350, in send
    CustomizablePickler(buffer, self._reducers).dump(obj)
  File "/usr/lib/python3.4/pickle.py", line 410, in dump
    self.save(obj)
  File "/usr/lib/python3.4/pickle.py", line 477, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.4/pickle.py", line 742, in save_tuple
    save(element)
  File "/usr/lib/python3.4/pickle.py", line 477, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.4/pickle.py", line 727, in save_tuple
    save(element)
  File "/usr/lib/python3.4/pickle.py", line 477, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.4/pickle.py", line 913, in save_global
    (obj, module_name, name))
_pickle.PicklingError: Can't pickle <function all_args.<locals>.wrapper at 0x7fb27dd76f28>: it's not found as __main__.all_args.<locals>.wrapper

```

I use python3.4 (but also reproducible with python 2.7), and joblib 0.8.2. To me, it seems to be a problem on the namespace, but I'm not sure to know how to solve that.

Thank you!

**Comment by soupault** [comment]
Hello @GaelVaroquaux ! Is there any progress on `Dill` support?

**Comment by lesteve** [comment]
We use cloudpickle (which has similar functionalities to dill)  in joblib master but not in the latest joblib release. Note there seem to be a similar error  in the snippet from https://github.com/joblib/joblib/issues/166#issue-42723278 on joblib master although cloudpickle can pickle (dumps/save) `preprocess_fluo` fine.

Maybe a bug in the loky integration of joblib? ping @ogrisel @tomMoral.

Side-comment : by setting the `LOKY_PICKLER=joblib.externals.cloudpickle` I can go a bit further but still get an error:

<details>

```
---------------------------------------------------------------------------
_RemoteTraceback                          Traceback (most recent call last)
_RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/lesteve/miniconda3/lib/python3.6/pickle.py", line 918, in save_global
    obj2, parent = _getattribute(module, name)
  File "/home/lesteve/miniconda3/lib/python3.6/pickle.py", line 266, in _getattribute
    .format(name, obj))
AttributeError: Can't get local attribute 'all_args.<locals>.wrapper' on <function all_args at 0x7f2322431f28>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lesteve/dev/joblib/joblib/externals/loky/backend/queues.py", line 150, in _feed
    obj, reducers=reducers)
  File "/home/lesteve/dev/joblib/joblib/externals/loky/backend/reduction.py", line 145, in dumps
    p.dump(obj)
  File "/home/lesteve/miniconda3/lib/python3.6/pickle.py", line 409, in dump
    self.save(obj)
  File "/home/lesteve/miniconda3/lib/python3.6/pickle.py", line 521, in save
    self.save_reduce(obj=obj, *rv)
  File "/home/lesteve/miniconda3/lib/python3.6/pickle.py", line 634, in save_reduce
    save(state)
  File "/home/lesteve/miniconda3/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/lesteve/miniconda3/lib/python3.6/pickle.py", line 821, in save_dict
    self._batch_setitems(obj.items())
  File "/home/lesteve/miniconda3/lib/python3.6/pickle.py", line 847, in _batch_setitems
    save(v)
  File "/home/lesteve/miniconda3/lib/python3.6/pickle.py", line 521, in save
    self.save_reduce(obj=obj, *rv)
  File "/home/lesteve/miniconda3/lib/python3.6/pickle.py", line 634, in save_reduce
    save(state)
  File "/home/lesteve/miniconda3/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/lesteve/miniconda3/lib/python3.6/pickle.py", line 821, in save_dict
    self._batch_setitems(obj.items())
  File "/home/lesteve/miniconda3/lib/python3.6/pickle.py", line 852, in _batch_setitems
    save(v)
  File "/home/lesteve/miniconda3/lib/python3.6/pickle.py", line 521, in save
    self.save_reduce(obj=obj, *rv)
  File "/home/lesteve/miniconda3/lib/python3.6/pickle.py", line 634, in save_reduce
    save(state)
  File "/home/lesteve/miniconda3/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/lesteve/miniconda3/lib/python3.6/pickle.py", line 736, in save_tuple
    save(element)
  File "/home/lesteve/miniconda3/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/lesteve/miniconda3/lib/python3.6/pickle.py", line 781, in save_list
    self._batch_appends(obj)
  File "/home/lesteve/miniconda3/lib/python3.6/pickle.py", line 808, in _batch_appends
    save(tmp[0])
  File "/home/lesteve/miniconda3/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/lesteve/miniconda3/lib/python3.6/pickle.py", line 736, in save_tuple
    save(element)
  File "/home/lesteve/miniconda3/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/lesteve/miniconda3/lib/python3.6/pickle.py", line 736, in save_tuple
    save(element)
  File "/home/lesteve/miniconda3/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/lesteve/miniconda3/lib/python3.6/pickle.py", line 922, in save_global
    (obj, module_name, name))
_pickle.PicklingError: Can't pickle <function all_args.<locals>.wrapper at 0x7f2320804048>: it's not found as __main__.all_args.<locals>.wrapper
"""

The above exception was the direct cause of the following exception:

PicklingError                             Traceback (most recent call last)
/tmp/test-parallel.py in <module>()
     28     print(res)
     29     print('joblib')
---> 30     res = Parallel(n_jobs=3)(delayed(loop)(i, preprocess_fluo) for i in range(0, 3, 1))
     31     print(res)

~/dev/joblib/joblib/parallel.py in __call__(self, iterable)
    806                 self._iterating = False
    807 
--> 808             self.retrieve()
    809             # Make sure that we get a last message telling us we are done
    810             elapsed_time = time.time() - self._start_time

~/dev/joblib/joblib/parallel.py in retrieve(self)
    708             try:
    709                 if getattr(self._backend, 'supports_timeout', False):
--> 710                     self._output.extend(job.get(timeout=self.timeout))
    711                 else:
    712                     self._output.extend(job.get())

~/dev/joblib/joblib/_parallel_backends.py in wrap_future_result(future, timeout)
    416         AsyncResults.get from multiprocessing."""
    417         try:
--> 418             return future.result(timeout=timeout)
    419         except LokyTimeoutError:
    420             raise TimeoutError()

~/dev/joblib/joblib/externals/loky/_base.py in result(self, timeout)
    422                 raise CancelledError()
    423             elif self._state == FINISHED:
--> 424                 return self.__get_result()
    425 
    426             self._condition.wait(timeout)

~/dev/joblib/joblib/externals/loky/_base.py in __get_result(self)
    380     def __get_result(self):
    381         if self._exception:
--> 382             raise self._exception
    383         else:
    384             return self._result

~/dev/joblib/joblib/externals/loky/backend/queues.py in _feed(buffer, notempty, send_bytes, writelock, close, reducers, ignore_epipe, onerror)                                                                      
    148                         # serialize the data before acquiring the lock
    149                         obj = CustomizableLokyPickler.dumps(
--> 150                             obj, reducers=reducers)
    151                         if wacquire is None:
    152                             send_bytes(obj)

~/dev/joblib/joblib/externals/loky/backend/reduction.py in dumps(cls, obj, reducers, protocol)
    143         buf = io.BytesIO()
    144         p = cls(buf, reducers=reducers, protocol=protocol)
--> 145         p.dump(obj)
    146         if sys.version_info < (3, 3):
    147             return buf.getvalue()

~/miniconda3/lib/python3.6/pickle.py in dump(self, obj)
    407         if self.proto >= 4:
    408             self.framer.start_framing()
--> 409         self.save(obj)
    410         self.write(STOP)
    411         self.framer.end_framing()

~/miniconda3/lib/python3.6/pickle.py in save(self, obj, save_persistent_id)
    519 
    520         # Save the reduce() output and finally memoize the object
--> 521         self.save_reduce(obj=obj, *rv)
    522 
    523     def persistent_id(self, obj):

~/miniconda3/lib/python3.6/pickle.py in save_reduce(self, func, args, state, listitems, dictitems, obj)
    632 
    633         if state is not None:
--> 634             save(state)
    635             write(BUILD)
    636 

~/miniconda3/lib/python3.6/pickle.py in save(self, obj, save_persistent_id)
    474         f = self.dispatch.get(t)
    475         if f is not None:
--> 476             f(self, obj) # Call unbound method with explicit self
    477             return
    478 

~/miniconda3/lib/python3.6/pickle.py in save_dict(self, obj)
    819 
    820         self.memoize(obj)
--> 821         self._batch_setitems(obj.items())
    822 
    823     dispatch[dict] = save_dict

~/miniconda3/lib/python3.6/pickle.py in _batch_setitems(self, items)
    845                 for k, v in tmp:
    846                     save(k)
--> 847                     save(v)
    848                 write(SETITEMS)
    849             elif n:

~/miniconda3/lib/python3.6/pickle.py in save(self, obj, save_persistent_id)
    519 
    520         # Save the reduce() output and finally memoize the object
--> 521         self.save_reduce(obj=obj, *rv)
    522 
    523     def persistent_id(self, obj):

~/miniconda3/lib/python3.6/pickle.py in save_reduce(self, func, args, state, listitems, dictitems, obj)
    632 
    633         if state is not None:
--> 634             save(state)
    635             write(BUILD)
    636 

~/miniconda3/lib/python3.6/pickle.py in save(self, obj, save_persistent_id)
    474         f = self.dispatch.get(t)
    475         if f is not None:
--> 476             f(self, obj) # Call unbound method with explicit self
    477             return
    478 

~/miniconda3/lib/python3.6/pickle.py in save_dict(self, obj)
    819 
    820         self.memoize(obj)
--> 821         self._batch_setitems(obj.items())
    822 
    823     dispatch[dict] = save_dict

~/miniconda3/lib/python3.6/pickle.py in _batch_setitems(self, items)
    850                 k, v = tmp[0]
    851                 save(k)
--> 852                 save(v)
    853                 write(SETITEM)
    854             # else tmp is empty, and we're done

~/miniconda3/lib/python3.6/pickle.py in save(self, obj, save_persistent_id)
    519 
    520         # Save the reduce() output and finally memoize the object
--> 521         self.save_reduce(obj=obj, *rv)
    522 
    523     def persistent_id(self, obj):

~/miniconda3/lib/python3.6/pickle.py in save_reduce(self, func, args, state, listitems, dictitems, obj)
    632 
    633         if state is not None:
--> 634             save(state)
    635             write(BUILD)
    636 

~/miniconda3/lib/python3.6/pickle.py in save(self, obj, save_persistent_id)
    474         f = self.dispatch.get(t)
    475         if f is not None:
--> 476             f(self, obj) # Call unbound method with explicit self
    477             return
    478 

~/miniconda3/lib/python3.6/pickle.py in save_tuple(self, obj)
    734         if n <= 3 and self.proto >= 2:
    735             for element in obj:
--> 736                 save(element)
    737             # Subtle.  Same as in the big comment below.
    738             if id(obj) in memo:

~/miniconda3/lib/python3.6/pickle.py in save(self, obj, save_persistent_id)
    474         f = self.dispatch.get(t)
    475         if f is not None:
--> 476             f(self, obj) # Call unbound method with explicit self
    477             return
    478 

~/miniconda3/lib/python3.6/pickle.py in save_list(self, obj)
    779 
    780         self.memoize(obj)
--> 781         self._batch_appends(obj)
    782 
    783     dispatch[list] = save_list

~/miniconda3/lib/python3.6/pickle.py in _batch_appends(self, items)
    806                 write(APPENDS)
    807             elif n:
--> 808                 save(tmp[0])
    809                 write(APPEND)
    810             # else tmp is empty, and we're done

~/miniconda3/lib/python3.6/pickle.py in save(self, obj, save_persistent_id)
    474         f = self.dispatch.get(t)
    475         if f is not None:
--> 476             f(self, obj) # Call unbound method with explicit self
    477             return
    478 

~/miniconda3/lib/python3.6/pickle.py in save_tuple(self, obj)
    734         if n <= 3 and self.proto >= 2:
    735             for element in obj:
--> 736                 save(element)
    737             # Subtle.  Same as in the big comment below.
    738             if id(obj) in memo:

~/miniconda3/lib/python3.6/pickle.py in save(self, obj, save_persistent_id)
    474         f = self.dispatch.get(t)
    475         if f is not None:
--> 476             f(self, obj) # Call unbound method with explicit self
    477             return
    478 

~/miniconda3/lib/python3.6/pickle.py in save_tuple(self, obj)
    734         if n <= 3 and self.proto >= 2:
    735             for element in obj:
--> 736                 save(element)
    737             # Subtle.  Same as in the big comment below.
    738             if id(obj) in memo:

~/miniconda3/lib/python3.6/pickle.py in save(self, obj, save_persistent_id)
    474         f = self.dispatch.get(t)
    475         if f is not None:
--> 476             f(self, obj) # Call unbound method with explicit self
    477             return
    478 

~/miniconda3/lib/python3.6/pickle.py in save_global(self, obj, name)
    920             raise PicklingError(
    921                 "Can't pickle %r: it's not found as %s.%s" %
--> 922                 (obj, module_name, name))
    923         else:
    924             if obj2 is not obj:

PicklingError: Can't pickle <function all_args.<locals>.wrapper at 0x7f2320804048>: it's not found as __main__.all_args.<locals>.wrapper
```

</details>
