### ISSUE TITLE
 joblib: gracefully handle KeyboardInterrupt

### ISSUE THREAD

**Issue by amueller** [joblib/joblib#181]
From https://github.com/scikit-learn/scikit-learn/issues/2913

It would be nice if I could easily abort something like a grid search with a KeyboardInterrupt. Currently joblib seems to require holding down Ctrl-C until all PoolWorkers are killed off.

**Comment by GaelVaroquaux** [comment]
+1

**Comment by andrewbolster** [comment]
+1

**Comment by endrebak** [comment]
Is this a similar issue: [If starting unix pipe with Parallel command, pipe commands complain after cntrl-c](http://stackoverflow.com/questions/32426332/if-starting-unix-pipe-with-parallel-command-pipe-commands-complain-after-cntrl) ? Or is it worth its own issue (if it is worth an issue at all?)

**Comment by GaelVaroquaux** [comment]
I have been thinking about this problem. 

Maybe it can be fixed by special casing the KeyboardInterrupt in the part of the code that retrieves the results to kill the pool immediately.

**Comment by Motorrat** [comment]
I can not kill the pool jobs even if I hold Ctrl-C. The stacktrace is below. 
When using Pool with the similar code I have learned that it does abort the subprocesses if the pool is closed like this
```
if __name__ == '__main__':
    pool = Pool(max_pool_size) 
    time.sleep(10)
    pool.map(spawn_classifier, [i for i in range(max_pool_size)])
**    pool.close()
    pool.join()
    pool.terminate()**
```
Excuse me if this is a naive suggestion, I am not an experienced Python coder but the above worked for me.

```
    self._target(*self._args, **self._kwargs)
  File "/home/ekobylkin/anaconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
  File "/home/ekobylkin/anaconda2/lib/python2.7/multiprocessing/pool.py", line 102, in worker
    self._target(*self._args, **self._kwargs)
  File "/home/ekobylkin/anaconda2/lib/python2.7/multiprocessing/pool.py", line 102, in worker
  File "/home/ekobylkin/anaconda2/lib/python2.7/multiprocessing/pool.py", line 102, in worker
    self._target(*self._args, **self._kwargs)
  File "/home/ekobylkin/anaconda2/lib/python2.7/multiprocessing/pool.py", line 102, in worker
  File "/home/ekobylkin/anaconda2/lib/python2.7/multiprocessing/pool.py", line 102, in worker
    task = get()
    task = get()
  File "/home/ekobylkin/anaconda2/lib/python2.7/site-packages/joblib/pool.py", line 357, in get
    task = get()
    task = get()
  File "/home/ekobylkin/anaconda2/lib/python2.7/site-packages/joblib/pool.py", line 357, in get
  File "/home/ekobylkin/anaconda2/lib/python2.7/site-packages/joblib/pool.py", line 357, in get
  File "/home/ekobylkin/anaconda2/lib/python2.7/site-packages/joblib/pool.py", line 357, in get
    task = get()
  File "/home/ekobylkin/anaconda2/lib/python2.7/site-packages/joblib/pool.py", line 357, in get
    racquire()
    racquire()
    racquire()
    racquire()
    racquire()
KeyboardInterrupt
KeyboardInterrupt
KeyboardInterrupt
KeyboardInterrupt
KeyboardInterrupt
Process PoolWorker-1479:
Traceback (most recent call last):
  File "/home/ekobylkin/anaconda2/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Process PoolWorker-1480:
    self.run()
  File "/home/ekobylkin/anaconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
Traceback (most recent call last):
  File "/home/ekobylkin/anaconda2/lib/python2.7/multiprocessing/pool.py", line 102, in worker
  File "/home/ekobylkin/anaconda2/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    task = get()
  File "/home/ekobylkin/anaconda2/lib/python2.7/site-packages/joblib/pool.py", line 357, in get
    self.run()
  File "/home/ekobylkin/anaconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ekobylkin/anaconda2/lib/python2.7/multiprocessing/pool.py", line 102, in worker
    racquire()
KeyboardInterrupt
    task = get()
  File "/home/ekobylkin/anaconda2/lib/python2.7/site-packages/joblib/pool.py", line 357, in get
    racquire()
KeyboardInterrupt
```

**Comment by ybdesire** [comment]
+1

**Comment by Motorrat** [comment]
here is how I kill all python processes on Linux `
for pid in $(ps -ef| grep -v "grep" |grep python|tr -s '[:blank:]'|cut -d' ' -f2); do kill $pid $pid; done; ps -ef
`

**Comment by lsc64** [comment]
> here is how I kill all python processes on Linux `for pid in $(ps -ef| grep -v "grep" |grep python|tr -s '[:blank:]'|cut -d' ' -f2); do kill $pid $pid; done; ps -ef`

For anyone stumbling into this issue 7 years later (like me):
Beware you might close a lot of other stuff using Python, therefore I check specifically for Parallel Processes from joblib. They are invoked as `python -m joblib.externals.loky.backend.popen_loky_posix --process-name LokyProcess-` followed by some number indicating which process it is. To make sure you kill a parallel process, you could kill them specifically using
`pkill -f LokyProcess`
If you really want to kill all python, use
`pkill -f python`
