### ISSUE TITLE
joblib files not cleaned up from /dev/shm

### ISSUE THREAD

**Issue by dave1g** [joblib/joblib#198]
I incorrectly reported this to scikit https://github.com/scikit-learn/scikit-learn/issues/4430 first as that was the code I was most directly making use of.

Basically I kicked of a multiprocesses script that ended up copying lots of data around, that data eventually filled up /dev/shm and no further copying was possible, the python processes locked up. I killed them, attempted to restart and /dev/shm was left in a bad state with all these large files sitting there (Is it possible to make sure they don't live longer than the process that created them?)

$ ls -lrt /dev/shm/joblib
/dev/shm/joblib_memmaping_pool_64060_189405392:
total 13528188
-rw------- 1 general 13852862624 Mar 20 09:09 64060-190150864-190138048-0.pkl_01.npy
-rw------- 1 general 152 Mar 20 09:09 64060-190150864-190138048-0.pkl

4 or 5 similar files/directories were present

If nothing can be done about this situation. It would at least be nice for the exception that gets thrown to be more informative.

Traceback (most recent call last):
File ".../python/linux/lib/python2.6/site-packages/sklearn/externals/joblib/numpy_pickle.py", line 240, in save
obj, filename = self._write_array(obj, filename)
File ".../python/linux/lib/python2.6/site-packages/sklearn/externals/joblib/numpy_pickle.py", line 203, in _write_array
self.np.save(filename, array)
File ".../python/linux/lib/python2.6/site-packages/numpy/lib/npyio.py", line 453, in save
format.write_array(fid, arr)
File ".../python2.6/site-packages/numpy/lib/format.py", line 521, in write_array
array.tofile(fp)
IOError: 1731607818 requested and 502 written

**Comment by ogrisel** [comment]
We already register a garbage collection callback to be executed when the process exits:

https://github.com/joblib/joblib/blob/master/joblib/pool.py#L555

However this won't be executed if the process is killed with `kill -9`.

**Comment by ogrisel** [comment]
What we could do is when we run a new parallel job, we can check if there are folders that match the `joblib_memmaping_pool_{pid}_{thread_id}` pattern and if the pid does not match any running process on the host, we could delete the folder.

We should add the hostname in case the temp folder used for memmaping is a shared folder (which should not be the case by default BTW as it's either `/dev/shm` or `/tmp` if `/dev/shm` does not exists.
