### ISSUE TITLE
Test failure with numpy 1.8

### ISSUE THREAD

**Issue by NelleV** [joblib/joblib#236]
I just installed 0.9.0b4 on our cluster, and one test is failing.
I have not investigated.
I am running python2.7

```
======================================================================
ERROR: joblib.test.test_numpy_pickle.test_compressed_pickle_python_2_3_compatibility
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/cbio/donnees/nvaroquaux/.local/lib/python2.7/site-packages/nose-1.1.2-py2.7.egg/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/cbio/donnees/nvaroquaux/tarball/joblib-0.9.0b4/joblib/test/test_numpy_pickle.py", line 324, in test_compressed_pickle_python_2_3_compatibility
    result_list = numpy_pickle.load(fname)
  File "/cbio/donnees/nvaroquaux/tarball/joblib-0.9.0b4/joblib/numpy_pickle.py", line 524, in load
    obj = unpickler.load()
  File "/cbio/donnees/nvaroquaux/.local/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/cbio/donnees/nvaroquaux/tarball/joblib-0.9.0b4/joblib/numpy_pickle.py", line 384, in load_build
    Unpickler.load_build(self)
  File "/cbio/donnees/nvaroquaux/.local/lib/python2.7/pickle.py", line 1217, in load_build
    setstate(state)
TypeError: must be char, not unicode
```

**Comment by lesteve** [comment]
Weird since this works on Travis. Which version of numpy are you using ?

**Comment by NelleV** [comment]
1.9.2

**Comment by NelleV** [comment]
Mmh… It is possible that at the time I ran the tests, I was using an older version of numpy… I recently updated everything.

**Comment by lesteve** [comment]
Do you still get the same test failure with numpy 1.9.2 ?

**Comment by lesteve** [comment]
I can actually reproduce your error with numpy 1.8.

**Comment by NelleV** [comment]
It works fine.

Sorry…

**Comment by NelleV** [comment]
So, I just noticed that I had written the previous numpy version in the title (numpy 1.8.2). It might be worth investigating this. Numpy 1.8 is still fairly recent.

Cheers,
N

**Comment by lesteve** [comment]
This is being investigated indeed, since joblib is meant to support at the very least the same numpy versions as scikit-learn. README.rst even says numpy > 1.3 at the moment.

There is an open PR about this issue but we are probably going to go another way on this.

**Comment by ogrisel** [comment]
We should support only numpy > 1.6.1 (Ubuntun 12.04) I think. numpy 1.3 is really really old.
