### ISSUE TITLE
test failure archlinux - python 3.5

### ISSUE THREAD

**Issue by sciunto** [joblib/joblib#248]
Hi,

I'm updating toward python 3.5 and I'm packaging the beta version.

````

======================================================================
ERROR: Failure: UnicodeDecodeError ('ascii' codec can't decode byte 0xc3 in position 683: ordinal not in range(128))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/usr/lib/python3.5/site-packages/nose/plugins/manager.py", line 154, in generate
    for r in result:
  File "/usr/lib/python3.5/site-packages/nose/plugins/doctests.py", line 264, in loadTestsFromFile
    doc = dh.read()
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 683: ordinal not in range(128)

======================================================================
ERROR: Check that pmap captures the errors when it is passed an object
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/fr/aur4/python-joblib/src/joblib-0.9.0b4/joblib/test/test_parallel.py", line 204, in test_parallel_pickling
    assert_raises(PickleError, Parallel(), (delayed(g)(x) for x in range(10)))
  File "/usr/lib/python3.5/unittest/case.py", line 724, in assertRaises
    return context.handle('assertRaises', args, kwargs)
  File "/usr/lib/python3.5/unittest/case.py", line 176, in handle
    callable_obj(*args, **kwargs)
  File "/home/fr/aur4/python-joblib/src/joblib-0.9.0b4/joblib/parallel.py", line 805, in __call__
    while self.dispatch_one_batch(iterator):
  File "/home/fr/aur4/python-joblib/src/joblib-0.9.0b4/joblib/parallel.py", line 658, in dispatch_one_batch
    tasks = BatchedCalls(itertools.islice(iterator, batch_size))
  File "/home/fr/aur4/python-joblib/src/joblib-0.9.0b4/joblib/parallel.py", line 69, in __init__
    self.items = list(iterator_slice)
  File "/home/fr/aur4/python-joblib/src/joblib-0.9.0b4/joblib/test/test_parallel.py", line 204, in <genexpr>
    assert_raises(PickleError, Parallel(), (delayed(g)(x) for x in range(10)))
  File "/home/fr/aur4/python-joblib/src/joblib-0.9.0b4/joblib/parallel.py", line 162, in delayed
    pickle.dumps(function)
AttributeError: Can't pickle local object 'test_parallel_pickling.<locals>.g'

======================================================================
FAIL: Check that name collisions with functions will raise warnings
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
AssertionError: 7 != 1
    '7 != 1' = '%s != %s' % _common_shorten_repr(7, 1)
    '7 != 1' = self._formatMessage('7 != 1', '7 != 1')
>>  raise self.failureException('7 != 1')
    

======================================================================
FAIL: Check that name collisions with functions will raise warnings
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
AssertionError: False is not true
    'False is not true' = self._formatMessage('False is not true', "%s is not true" % safe_repr(False))
>>  raise self.failureException('False is not true')
    

======================================================================
FAIL: joblib.test.test_memory.test_memory_warning_lambda_collisions
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/fr/aur4/python-joblib/src/joblib-0.9.0b4/joblib/test/test_memory.py", line 254, in test_memory_warning_lambda_collisions
    nose.tools.assert_equal(len(w), 4)
AssertionError: 13 != 4
    '13 != 4' = '%s != %s' % _common_shorten_repr(13, 4)
    '13 != 4' = self._formatMessage('13 != 4', '13 != 4')
>>  raise self.failureException('13 != 4')
    
-------------------- >> begin captured logging << --------------------
root: WARNING: [Memory(cachedir='/tmp/tmpzyo28oxv/joblib')]: Flushing completely the cache
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: joblib.test.test_memory.test_memory_warning_collision_detection(11, 2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
AssertionError: 11 != 2
    '11 != 2' = '%s != %s' % _common_shorten_repr(11, 2)
    '11 != 2' = self._formatMessage('11 != 2', '11 != 2')
>>  raise self.failureException('11 != 2')
    
-------------------- >> begin captured logging << --------------------
root: WARNING: [Memory(cachedir='/tmp/tmpzyo28oxv/joblib')]: Flushing completely the cache
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: joblib.test.test_memory.test_memory_warning_collision_detection(False,)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
AssertionError: False is not true
    'False is not true' = self._formatMessage('False is not true', "%s is not true" % safe_repr(False))
>>  raise self.failureException('False is not true')
    

Name                                 Stmts   Miss  Cover   Missing
------------------------------------------------------------------
joblib.py                               10      0   100%   
joblib/_compat.py                        4      0   100%   
joblib/_memory_helpers.py               65     63     3%   5-105
joblib/_multiprocessing_helpers.py      22      8    64%   18-19, 27-29, 37-40
joblib/disk.py                          51     11    78%   28, 84-88, 94, 103-107
joblib/format_stack.py                 227     47    79%   34-35, 50, 55, 63, 67-70, 133-135, 146, 148, 168-173, 193-197, 201-205, 208, 215-224, 246-247, 282-286, 299-300, 323, 345-346, 363-367, 372-375, 400, 405, 412
joblib/func_inspect.py                 153     20    87%   80, 109-113, 120-121, 129, 136, 145-146, 150-151, 154-155, 199, 238, 242, 282, 284
joblib/hashing.py                       96     16    83%   20, 54-55, 74, 91-102, 145, 208
joblib/logger.py                        76     12    84%   29, 42, 53, 81, 86, 98, 103, 119, 125, 142-143, 150
joblib/memory.py                       355     17    95%   65, 120, 253, 299, 389, 554, 583-585, 648-649, 659, 696, 729-730, 740, 871, 896
joblib/my_exceptions.py                 48      6    88%   29, 47, 83-84, 92-96
joblib/numpy_pickle.py                 219     36    84%   33-35, 225-226, 272-275, 290, 321-322, 333-371, 387, 397
joblib/parallel.py                     318     22    93%   62, 86, 104, 136, 142, 168, 435, 478, 482, 502-507, 519, 548, 568, 628, 638-640, 724-725, 767
joblib/pool.py                         224     30    87%   29, 50-51, 218, 238, 246, 248, 257, 290, 294, 306-309, 335, 346-348, 351, 358-362, 373, 376, 412, 414, 536-539, 542, 559
------------------------------------------------------------------
TOTAL                                 1868    288    85%   
----------------------------------------------------------------------
Ran 611 tests in 67.832s

FAILED (errors=2, failures=5)
==> ERROR: A failure occurred in check().
    Aborting...



````

**Comment by lesteve** [comment]
There is some overlap with #244 which has been fixed in master. Do you mind trying with master and reporting back ?

**Comment by sciunto** [comment]
master looks good. So, we just need a new beta version or a bugfix release of the stable version, so I can package it for archlinux. :)

Thanks!

**Comment by lesteve** [comment]
Good to hear. Yeah we are planning a joblib release in the very near future. It should be something like a few days.

**Comment by sciunto** [comment]
sounds perfect!

**Comment by lesteve** [comment]
0.9.2 has been released. Closing, let us know if you find any problems with it.

**Comment by sciunto** [comment]
@lesteve Looks like another failure appeared for me. (py2.7 and 3.5)

```
======================================================================
FAIL: Doctest: parallel_numpy.rst
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/doctest.py", line 2226, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for parallel_numpy.rst
  File "/home/fr/aur4/python2-joblib/src/joblib-0.9.2/doc/parallel_numpy.rst", line 0

----------------------------------------------------------------------
File "/home/fr/aur4/python2-joblib/src/joblib-0.9.2/doc/parallel_numpy.rst", line 80, in parallel_numpy.rst
Failed example:
    np.allclose(large_array, large_memmap)
Expected:
    True
Got:
    memmap(True, dtype=bool)

>>  raise self.failureException(self.format_failure(<StringIO.StringIO instance at 0x7f5ae91f31b8>.getvalue()))
```

**Comment by lesteve** [comment]
Thanks for testing it so quickly!

It does ring a bell actually, I probably saw it and forgot about it because it is a doctest. I think this is a documentation issue more than a real bug but I'll investigate more closely to make sure.

**Comment by lesteve** [comment]
This seems to be a change in numpy 1.10, see https://github.com/numpy/numpy/issues/6475.

In any case, I don't think this is a problem as far as joblib 0.9.2 is concerned. 

Not really familiar with packaging in general, can you live with an error like this on your side or do you need perfectly clean tests? It's super easy to create a patch for parallel_numpy.rst to make the doctest pass if you need one.

**Comment by lesteve** [comment]
Closing this one, @sciunto let me know if you need a patch to get the doctest to pass.
