### ISSUE TITLE
joblib.Parallel crashes on interactively defined functions

### ISSUE THREAD

**Issue by fjanoos** [joblib/joblib#263]
Hello,

I'm trying to parallelize an operation on the columns of pandas dataframe using joblib, using this logic:

`parallel =  Parallel(n_jobs=-1, backend='multiprocessing', verbose=12);`
`joblist  =  [delayed(myfunc)( df[col] )  for col in columns ];`
`retlist  =  parallel( joblist );`

where myfunc takes a column and returns a column. This code used to work fine until a few ago, before I did a conda update of pandas and joblib (and some other libraries). After the update, however, the following error gets thrown:

`File "<string>", line unknown`
`SyntaxError: invalid or missing encoding declaration for '/home/firdaus/local/software/anaconda/lib/python3.4/site-packages/pandas/lib.cpython-34m.so'`

Any suggestions would be appreciated.

thanks.

**Comment by fjanoos** [comment]
Just to clarify, I'm using the following versions:
Python: 3.4.3 |Anaconda 2.3.0 (64-bit)
Pandas: '0.17.0'
joblib: '0.9.0b4'

**Comment by lesteve** [comment]
Thanks for the bug report. It would be great if you could put together a minimal reproducable example.

Note: this will probably not fix your problem but you should not use joblib 0.9.0b4 since 0.9.2 has been released.

**Comment by fjanoos** [comment]
Actually, I was trying to test the bug on the following mre, but now joblib isn't returning at all - the call to parallel(joblist) just hangs with no errors or messages. I can terminate it with Ctrl-C - but again, no error message is thrown. I upgraded to 9.2.

from pandas import DataFrame, concat, Series
from joblib import Parallel, delayed
from pylab import *
parallel =  Parallel(n_jobs=-1, backend='multiprocessing', verbose=12);
df = DataFrame(randn(10000,10))
def my_func(d):
    return d**2
joblist = [ delayed(my_func)( df[col] ) for col in df.columns];
retlist  =  parallel( joblist );

**Comment by fjanoos** [comment]
This works only when I set n_jobs=1. Any value of n_jobs > 1 causes the call to parallel to hang.

**Comment by fjanoos** [comment]
I think the lack of error messages was because I was running the code in jupyter. Running it from the command line, I get this:

In [8]: retlist  =  parallel( joblist );

Process ForkServerPoolWorker-3:
Traceback (most recent call last):
  File "/home/firdaus/local/software/anaconda/lib/python3.4/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/home/firdaus/local/software/anaconda/lib/python3.4/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/firdaus/local/software/anaconda/lib/python3.4/multiprocessing/pool.py", line 108, in worker
    task = get()
  File "/srv/local/1/tmp/joblib-0.9.2/joblib/pool.py", line 360, in get
    return recv()
Process ForkServerPoolWorker-9:
Traceback (most recent call last):
  File "/home/firdaus/local/software/anaconda/lib/python3.4/multiprocessing/connection.py", line 251, in recv
    return ForkingPickler.loads(buf.getbuffer())
AttributeError: Can't get attribute 'my_func' on <module '__main__' (built-in)>
  File "/home/firdaus/local/software/anaconda/lib/python3.4/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/home/firdaus/local/software/anaconda/lib/python3.4/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/firdaus/local/software/anaconda/lib/python3.4/multiprocessing/pool.py", line 108, in worker
    task = get()
  File "/srv/local/1/tmp/joblib-0.9.2/joblib/pool.py", line 360, in get
    return recv()
  File "/home/firdaus/local/software/anaconda/lib/python3.4/multiprocessing/connection.py", line 251, in recv
    return ForkingPickler.loads(buf.getbuffer())
AttributeError: Can't get attribute 'my_func' on <module '__main__' (built-in)>
Process ForkServerPoolWorker-7:
Traceback (most recent call last):
  File "/home/firdaus/local/software/anaconda/lib/python3.4/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/home/firdaus/local/software/anaconda/lib/python3.4/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/firdaus/local/software/anaconda/lib/python3.4/multiprocessing/pool.py", line 108, in worker
    task = get()
  File "/srv/local/1/tmp/joblib-0.9.2/joblib/pool.py", line 360, in get
    return recv()
  File "/home/firdaus/local/software/anaconda/lib/python3.4/multiprocessing/connection.py", line 251, in recv
    return ForkingPickler.loads(buf.getbuffer())
AttributeError: Can't get attribute 'my_func' on <module '__main__' (built-in)>

**Comment by lesteve** [comment]
I can reproduce in joblib 0.9.2 and master by copying and pasting your code inside an IPython session.

It seems like a regression because it does work with joblib 0.8.4. I would need to look at it more but I probably won't get around to doing it before next week. Something else I noticed is that it works fine with Python 2 for some reason.

A possible work-around is to define your helper function (my_func in your snippet) in an external module rather than in your IPython session.

Also it does look like this error is not exactly the same as the one in your original post. Let me know if you can reproduce the original error.

**Comment by fjanoos** [comment]
Hi,

I tried a few other variations on this:


`from pandas import DataFrame, concat, Series`
`from joblib import Parallel, delayed`
`from numba import jit`
`import numpy as np`
`from numpy.random import randn`
`from fjpy.stats import timeseries as fjts`
`parallel =  Parallel(n_jobs=-1, backend='multiprocessing', verbose=12);`
`df = DataFrame(randn(10000,10))`
`@jit(nogil=True, nopython=True)`
`def jit_func(d):`
`    return d**2`
`joblist = [ delayed(jit_func)( df[col].as_matrix() ) for col in df.columns];`
`retlist  =  parallel( joblist );`
`def no_jit_func(d):`
`    return d**2`
`joblist = [ delayed(no_jit_func)( df[col].as_matrix() ) for col in df.columns];`
`retlist  =  parallel( joblist );`



For this sequence of code:

'joblist = [ delayed(jit_func)( df[col].as_matrix() ) for col in df.columns];

In [16]: retlist  =  parallel( joblist );`

The output is:

[Parallel(n_jobs=-1)]: Done   1 tasks      | elapsed:    0.4s
[Parallel(n_jobs=-1)]: Done  11 out of  10 | elapsed:    0.6s remaining:   -0.1s
[Parallel(n_jobs=-1)]: Done  11 out of  10 | elapsed:    0.9s remaining:   -0.1s
[Parallel(n_jobs=-1)]: Done  11 out of  10 | elapsed:    1.1s remaining:   -0.1s
[Parallel(n_jobs=-1)]: Done  11 out of  10 | elapsed:    1.3s remaining:   -0.1s
[Parallel(n_jobs=-1)]: Done  11 out of  10 | elapsed:    1.5s remaining:   -0.1s
[Parallel(n_jobs=-1)]: Done  11 out of  10 | elapsed:    1.7s remaining:   -0.2s
[Parallel(n_jobs=-1)]: Done  11 out of  10 | elapsed:    1.9s remaining:   -0.2s
[Parallel(n_jobs=-1)]: Done  11 out of  10 | elapsed:    2.1s remaining:   -0.2s
[Parallel(n_jobs=-1)]: Done  11 out of  10 | elapsed:    2.3s remaining:   -0.2s
[Parallel(n_jobs=-1)]: Done  10 out of  10 | elapsed:    2.3s finished


but for this: 

In [17]: joblist = [ delayed(no_jit_func)( df[col].as_matrix() ) for col in df.columns];

In [18]: retlist  =  parallel( joblist );


the result is:

Process ForkServerPoolWorker-28:
Traceback (most recent call last):
  File "/home/firdaus/local/software/anaconda/lib/python3.4/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/home/firdaus/local/software/anaconda/lib/python3.4/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/firdaus/local/software/anaconda/lib/python3.4/multiprocessing/pool.py", line 108, in worker
    task = get()
  File "/home/firdaus/local/software/anaconda/lib/python3.4/site-packages/joblib-0.9.2-py3.4.egg/joblib/pool.py", line 360, in get
    return recv()
  File "/home/firdaus/local/software/anaconda/lib/python3.4/multiprocessing/connection.py", line 251, in recv
    return ForkingPickler.loads(buf.getbuffer())
AttributeError: Can't get attribute 'no_jit_func' on <module '__main__' (built-in)>
Process ForkServerPoolWorker-21:
Traceback (most recent call last):
  File "/home/firdaus/local/software/anaconda/lib/python3.4/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/home/firdaus/local/software/anaconda/lib/python3.4/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/firdaus/local/software/anaconda/lib/python3.4/multiprocessing/pool.py", line 108, in worker
    task = get()
  File "/home/firdaus/local/software/anaconda/lib/python3.4/site-packages/joblib-0.9.2-py3.4.egg/joblib/pool.py", line 360, in get
    return recv()
  File "/home/firdaus/local/software/anaconda/lib/python3.4/multiprocessing/connection.py", line 251, in recv
    return ForkingPickler.loads(buf.getbuffer())
AttributeError: Can't get attribute 'no_jit_func' on <module '__main__' (built-in)>
Process ForkServerPoolWorker-18:
Traceback (most recent call last):
  File "/home/firdaus/local/software/anaconda/lib/python3.4/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/home/firdaus/local/software/anaconda/lib/python3.4/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
Process ForkServerPoolWorker-17:
Traceback (most recent call last):
  File "/home/firdaus/local/software/anaconda/lib/python3.4/multiprocessing/pool.py", line 108, in worker
    task = get()
  File "/home/firdaus/local/software/anaconda/lib/python3.4/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/home/firdaus/local/software/anaconda/lib/python3.4/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/firdaus/local/software/anaconda/lib/python3.4/site-packages/joblib-0.9.2-py3.4.egg/joblib/pool.py", line 360, in get
    return recv()
  File "/home/firdaus/local/software/anaconda/lib/python3.4/multiprocessing/pool.py", line 108, in worker
    task = get()
  File "/home/firdaus/local/software/anaconda/lib/python3.4/site-packages/joblib-0.9.2-py3.4.egg/joblib/pool.py", line 360, in get
    return recv()
  File "/home/firdaus/local/software/anaconda/lib/python3.4/multiprocessing/connection.py", line 251, in recv
    return ForkingPickler.loads(buf.getbuffer())
AttributeError: Can't get attribute 'no_jit_func' on <module '__main__' (built-in)>
  File "/home/firdaus/local/software/anaconda/lib/python3.4/multiprocessing/connection.py", line 251, in recv
    return ForkingPickler.loads(buf.getbuffer())

**Comment by lesteve** [comment]
Could you please use markdown to format your previous post? That would make it a lot easier to read.

Look at [syntax highlighting](https://help.github.com/articles/github-flavored-markdown/#syntax-highlighting) and [fenced blocks](https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks) for more details.

**Comment by fjanoos** [comment]
I don't have an easy way to reproduce the first error without encountering the second error.

But, I just reverted to joblib 0.8.4 and both the original error and this other one have gone. 

Do you recommend just sticking to 0.8.4 in the future ?

thanks.

**Comment by lesteve** [comment]
> Do you recommend just sticking to 0.8.4 in the future ?

The short story: I would recommend to not use interactively defined functions inside a joblib.Parallel object. Put them in a module somewhere and everything will work fine.

I am actually amazed that defining a function interactively and using it inside a joblib.Parallel object actually works in 0.8.4. Is it an intended feature @ogrisel @GaelVaroquaux ?

I was assuming that because an interactively defined function is not picklable that something would break in the worker processes but apparently not.

For the record, the reason I can get it to work with Python 3 and joblib 0.9.2 by setting the default start method to 'fork' instead of the new default 'forkserver'.

**Comment by GaelVaroquaux** [comment]
> I am actually amazed that defining a function interactively and using
> it inside a joblib.Parallel object actually works in 0.8.4. Is it an
> intended feature @ogrisel @GaelVaroquaux ?

Yes, as much as possible. People will naturally define functions in an
IPython notebook, and expect things to work.

> For the record, the reason I can get it to work with Python 3 and joblib 0.9.2
> by setting the default start method to 'fork' instead of the new default
> 'forkserver'.

OK, that's a bit what I expected :(. I know the rational behind the
forksever, but it's a regression on many aspects (more fragile to
pickling problems, and more time-consuming).

The only way out of this regression is probably to use dill. That not an
easy task.

If it were up to me, I would favor pull out of forkserver by default,
before we can make sure that such patterns work.

Other option is to try to release a version of joblib with embedded dill
(or cloudpickle) soon.

**Comment by lesteve** [comment]
> Yes, as much as possible. People will naturally define functions in an
IPython notebook, and expect things to work.

> If it were up to me, I would favor pull out of forkserver by default, before we can make sure that such patterns work. 

I see, any opinions @ogrisel ?

**Comment by ogrisel** [comment]
Sorry for not having caught that earlier. The problem is not related to notebooks, it impacts any function defined interactively in `__main__` (be it a shell or a script). We could definitely write a non-regression test launching a script in a subprocess.

In the mean time, +1 for disabling forkserver by default in 0.9.1 as a stop gap for this regression. Once we will have dill integration (in 0.10) we can revisit this decision.

I feel that this is a blocker issue for scikit-learn 0.17 as well.

**Comment by ksurya** [comment]
I am able to reproduce this bug with the following script:

```
from joblib import Parallel, delayed
def f(x): return x**2
Parallel(n_jobs=3)(delayed(f)(i) for i in range(10))
```

Environment:

joblib: 0.11
Python: 3.6.1 Anaconda

**Comment by jsnowacki** [comment]
I have the same issue with using `GridSearchCV` with a analyzer defined as a function in `__main__` (i.e. Jupyter notebook cell). 

Is there any workaround apart from usign `n_jobs=1`?

Environment:

joblib: 0.11 (via `sklearn.externals`)
Python 3.6.2 Anaconda 
scikit-learn: 0.19.0
Jupyter Notebook

**Comment by ogrisel** [comment]
joblib with the new loky backend has not been included in scikit-learn yet unfortunately. I need to get that done at some point.

**Comment by jtromans** [comment]
I am also able to reproduce this bug with the following script:

```
from joblib import Parallel, delayed
def f(x): return x**2
Parallel(n_jobs=3)(delayed(f)(i) for i in range(10))
```

Environment:

joblib: 0.11
Python: 3.6.1 Anaconda
Jupyter Notebook
