### ISSUE TITLE
test_joblib_pickle_across_python_versions fails on sparc

### ISSUE THREAD

**Issue by yarikoptic** [joblib/joblib#279]
was trying to catch that possible race condition leading to a stalled test on 64bit sparc -- only ran into this failing test so far

```
======================================================================
FAIL: joblib.test.test_numpy_pickle.test_joblib_pickle_across_python_versions
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/yoh/deb/gits/joblib/joblib/test/test_numpy_pickle.py", line 360, in test_joblib_pickle_across_python_versions
    _check_pickle(fname, expected_list)
  File "/home/yoh/deb/gits/joblib/joblib/test/test_numpy_pickle.py", line 312, in _check_pickle
    nose.tools.assert_equal(result.dtype, expected.dtype)
AssertionError: dtype('<i8') != dtype('int64')
    "dtype('<i8') != dtype('int64')" = '%s != %s' % (safe_repr(dtype('<i8')), safe_repr(dtype('int64')))
    "dtype('<i8') != dtype('int64')" = self._formatMessage("dtype('<i8') != dtype('int64')", "dtype('<i8') != dtype('int64')")
>>  raise self.failureException("dtype('<i8') != dtype('int64')")
```

happens with 0.9.2 and 0.9.3-20-g1b751b2 (apparently I have missed a release)

Cheers

**Comment by lesteve** [comment]
I am guessing this is because sparc is big-endian and the pickles were generated on a little-endian machine. The fix is to be more specific about dtypes in this test ...

**Comment by yarikoptic** [comment]
So I guess it better skips on BE platforms... Or ideally has two sets of files to test on?

**Comment by lesteve** [comment]
I am hoping that one set of files with an explicit dtype for arrays in `expected_list` in test_joblib_pickle_across_python_versions is enough. I just pushed such a fix in 756053f, let me know if that doesn't fix your failure.

**Comment by yarikoptic** [comment]
unfortunately with that fix getting two failures:
```
FAIL: joblib.test.test_numpy_pickle.test_compressed_pickle_dump_and_load
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/yoh/deb/gits/joblib/joblib/test/test_numpy_pickle.py", line 283, in test_compressed_pickle_dump_and_load
    nose.tools.assert_equal(result.dtype, expected.dtype)
AssertionError: dtype('int64') != dtype('<i8')
    "dtype('int64') != dtype('<i8')" = '%s != %s' % (safe_repr(dtype('int64')), safe_repr(dtype('<i8')))
    "dtype('int64') != dtype('<i8')" = self._formatMessage("dtype('int64') != dtype('<i8')", "dtype('int64') != dtype('<i8')")
>>  raise self.failureException("dtype('int64') != dtype('<i8')")
    

======================================================================
FAIL: joblib.test.test_numpy_pickle.test_joblib_pickle_across_python_versions
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/yoh/deb/gits/joblib/joblib/test/test_numpy_pickle.py", line 364, in test_joblib_pickle_across_python_versions
    _check_pickle(fname, expected_list)
  File "/home/yoh/deb/gits/joblib/joblib/test/test_numpy_pickle.py", line 312, in _check_pickle
    nose.tools.assert_equal(result.dtype, expected.dtype)
AssertionError: dtype('int64') != dtype('<i8')
    "dtype('int64') != dtype('<i8')" = '%s != %s' % (safe_repr(dtype('int64')), safe_repr(dtype('<i8')))
    "dtype('int64') != dtype('<i8')" = self._formatMessage("dtype('int64') != dtype('<i8')", "dtype('int64') != dtype('<i8')")
>>  raise self.failureException("dtype('int64') != dtype('<i8')")
    
```

**Comment by lesteve** [comment]
Hmmm that doesn't make much sense to me. I'll try to get a Solaris running in a VM to investigate more.

**Comment by lesteve** [comment]
Ah maybe an hypothesis, the compressed pickles seem to lose the the endianness of the dtype:

```python
import numpy as np
import joblib

arr = np.ones(10, dtype='>i8')
print('dtype before pickle: ', arr.dtype.descr)
filename = '/tmp/test.pkl'
joblib.dump(arr, filename, compress=True)
print('dtype after pickle: ', joblib.load(filename).dtype.descr)
```

Output (on a little-endian machine):
```
dtype before pickle:  [('', '>i8')]
dtype after pickle:  [('', '<i8')]
```

Not sure why this is happening to be perfectly honest.

**Comment by lesteve** [comment]
I just pushed a commit that skips this two tests on non little-endian machines as  a stop-gap solution. It is quite likely that I won't have time to look into the issue before next week. 

@aabadie can you make sure that you don't have this problem in #260? I am reasonably confident that it is not going to be the case since we use np.load/np.save rather than some some custom code in the compressed case but it is still worth double-checking.

**Comment by aabadie** [comment]
> can you make sure that you don't have this problem in #260?

As commented in #280, this problem is fixed in #260. To me, the problem comes from the call __setstate__ which doesn't set the dtype correctly.

**Comment by aabadie** [comment]
@yarikoptic, we recently merged some code that should fix the initial issue you mention. Can you confirm it works on spark 64bits ?

**Comment by yarikoptic** [comment]
Seems to be the same... also note that recent release tags weren't annotated:
```
$> git clean -dfx
(git)/home/yoh/deb/gits/joblib:[master]

$> git describe
0.8.2-261-gb64d57a

*$> git describe --tags
0.9.4-37-gb64d57a

$> nosetests -s -v joblib/test/test_numpy_pickle.py:test_joblib_pickle_across_python_versions
nose.config: INFO: Ignoring files matching ['^\\.', '^_', '^setup\\.py$']
nose.plugins.cover: ERROR: Coverage not available: unable to import coverage module
________________________________________________________________________________
setup numpy_pickle
________________________________________________________________________________
joblib.test.test_numpy_pickle.test_joblib_pickle_across_python_versions ... FAIL
________________________________________________________________________________
teardown numpy_pickle
________________________________________________________________________________

======================================================================
FAIL: joblib.test.test_numpy_pickle.test_joblib_pickle_across_python_versions
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/yoh/deb/gits/joblib/joblib/test/test_numpy_pickle.py", line 517, in test_joblib_pickle_across_python_versions
    _check_pickle(fname, expected_list)
  File "/home/yoh/deb/gits/joblib/joblib/test/test_numpy_pickle.py", line 461, in _check_pickle
    nose.tools.assert_equal(result.dtype, expected.dtype)
AssertionError: dtype('int64') != dtype('<i8')
    "dtype('int64') != dtype('<i8')" = '%s != %s' % (safe_repr(dtype('int64')), safe_repr(dtype('<i8')))
    "dtype('int64') != dtype('<i8')" = self._formatMessage("dtype('int64') != dtype('<i8')", "dtype('int64') != dtype('<i8')")
>>  raise self.failureException("dtype('int64') != dtype('<i8')")
    

----------------------------------------------------------------------
Ran 1 test in 0.109s

FAILED (failures=1)
```

**Comment by aabadie** [comment]
@yarikoptic thanks for testing again. But AFAICS, you are still trying with 0.9.4 which doesn't contain the fix. Can you run the following git commands (assuming you have a fork and already setup `joblib` as a remote on the main repository):
```
git fetch joblib
git checkout master
git merge joblib/master
```
and then re-run nosetests ?

**Comment by lesteve** [comment]
@aabadie if you look carefully at the `git describe` output, you'll realise that @yarikoptic did update his master (the commit he tested is b64d57a12be278c5caa161f41ded8067a3182ab3).

Hmmm not sure why we still see this problem, maybe worth investigating more then.

**Comment by aishgrt1** [comment]
I am facing an issue while training and pickling the model in a little endian system and loading it in a big endian system. Any suggestions how to resolve this ?

**Comment by lesteve** [comment]
I would try this if I were you:
1. can you pickle.dump a numpy array and pickle.load it on a system with a different endianness
2. can you use joblib.dump/joblib.load to do the same thing

If you can do 1. but not 2. this is a problem inside joblib. In this case, please create a new issue with a minimal reproducible example and the full stack-trace.

**Comment by mgorny** [comment]
I suppose I'm a tad late to the party but I seem to have the ~same test failure on ppc64.  Can I help somehow to debug it?

```pytb
==================================================================== FAILURES =====================================================================
____________________________________________________ test_joblib_pickle_across_python_versions ____________________________________________________

    @with_numpy
    def test_joblib_pickle_across_python_versions():
        # We need to be specific about dtypes in particular endianness
        # because the pickles can be generated on one architecture and
        # the tests run on another one. See
        # https://github.com/joblib/joblib/issues/279.
        expected_list = [np.arange(5, dtype=np.dtype('<i8')),
                         np.arange(5, dtype=np.dtype('<f8')),
                         np.array([1, 'abc', {'a': 1, 'b': 2}], dtype='O'),
                         np.arange(256, dtype=np.uint8).tobytes(),
                         # np.matrix is a subclass of np.ndarray, here we want
                         # to verify this type of object is correctly unpickled
                         # among versions.
                         np.matrix([0, 1, 2], dtype=np.dtype('<i8')),
                         u"C'est l'\xe9t\xe9 !"]
    
        # Testing all the compressed and non compressed
        # pickles in joblib/test/data. These pickles were generated by
        # the joblib/test/data/create_numpy_pickle.py script for the
        # relevant python, joblib and numpy versions.
        test_data_dir = os.path.dirname(os.path.abspath(data.__file__))
    
        pickle_extensions = ('.pkl', '.gz', '.gzip', '.bz2', 'lz4')
        if lzma is not None:
            pickle_extensions += ('.xz', '.lzma')
        pickle_filenames = [os.path.join(test_data_dir, fn)
                            for fn in os.listdir(test_data_dir)
                            if any(fn.endswith(ext) for ext in pickle_extensions)]
    
        for fname in pickle_filenames:
>           _check_pickle(fname, expected_list)

joblib/test/test_numpy_pickle.py:457: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

filename = '/home/mgorny/joblib/joblib/test/data/joblib_0.9.2_compressed_pickle_py34_np19.gz'
expected_list = [array([0, 1, 2, 3, 4]), array([0., 1., 2., 3., 4.]), array([1, 'abc', {'a': 1, 'b': 2}], dtype=object), b'\x00\x01\x0...xec\xed\xee\xef\xf0\xf1\xf2\xf3\xf4\xf5\xf6\xf7\xf8\xf9\xfa\xfb\xfc\xfd\xfe\xff', matrix([[0, 1, 2]]), "C'est l'été !"]

    def _check_pickle(filename, expected_list):
        """Helper function to test joblib pickle content.
    
        Note: currently only pickles containing an iterable are supported
        by this function.
        """
        version_match = re.match(r'.+py(\d)(\d).+', filename)
        py_version_used_for_writing = int(version_match.group(1))
    
        py_version_to_default_pickle_protocol = {2: 2, 3: 3}
        pickle_reading_protocol = py_version_to_default_pickle_protocol.get(3, 4)
        pickle_writing_protocol = py_version_to_default_pickle_protocol.get(
            py_version_used_for_writing, 4)
        if pickle_reading_protocol >= pickle_writing_protocol:
            try:
                with warns(None) as warninfo:
                    warnings.simplefilter('always')
                    warnings.filterwarnings(
                        'ignore', module='numpy',
                        message='The compiler package is deprecated')
                    result_list = numpy_pickle.load(filename)
                filename_base = os.path.basename(filename)
                expected_nb_warnings = 1 if ("_0.9" in filename_base or
                                             "_0.8.4" in filename_base) else 0
                assert len(warninfo) == expected_nb_warnings
                for w in warninfo:
                    assert w.category == DeprecationWarning
                    assert (str(w.message) ==
                            "The file '{0}' has been generated with a joblib "
                            "version less than 0.10. Please regenerate this "
                            "pickle file.".format(filename))
                for result, expected in zip(result_list, expected_list):
                    if isinstance(expected, np.ndarray):
>                       assert result.dtype == expected.dtype
E                       AssertionError: assert dtype('int64') == dtype('<i8')
E                        +  where dtype('int64') = array([0, 1, 2, 3, 4]).dtype
E                        +  and   dtype('<i8') = array([0, 1, 2, 3, 4]).dtype

joblib/test/test_numpy_pickle.py:397: AssertionError
-------------------------------------------------------------- Captured stderr call ---------------------------------------------------------------
/home/mgorny/joblib/joblib/test/test_numpy_pickle.py:440: PendingDeprecationWarning: the matrix subclass is not the recommended way to represent matrices or deal with linear algebra (see https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html). Please adjust your code to use regular ndarray.
  np.matrix([0, 1, 2], dtype=np.dtype('<i8')),
============================================================= short test summary info =============================================================
```

**Comment by cmarmo** [comment]
The test is still failing on joblib 1.2.0 on s390x (big endian)
```
>                       assert result.dtype == expected.dtype
E                       AssertionError: assert dtype('<i8') == dtype('int64')
E                        +  where dtype('<i8') = memmap([0, 1, 2, 3, 4]).dtype
E                        +  and   dtype('int64') = array([0, 1, 2, 3, 4]).dtype
```
