### ISSUE TITLE
AssertionError: Incorrect data length while decompressing in Memory/numpy_pickle.py

### ISSUE THREAD

**Issue by hrez** [joblib/joblib#287]
It may be similar to https://github.com/joblib/joblib/issues/220 which mentions `cache_size` as a workaround but it doesn't exist for Memory class.
`joblib==0.9.3`

The code is rather simple:

```
from joblib import Memory
mem = Memory(cachedir='/home/user/tmp/joblib', compress=True, verbose=0)

@mem.cache()
def pandas_parse_csv(csv_file_name, service):
   <skipped>
```
It raises exception on same calls depending on result size if it's already cached.
```
2015-12-23 17:22:07,634 - logger.py - WARNING - [MemorizedFunc(func=<function pandas_parse_csv at 0x7f84b1875578>, cachedir='/home/user/tmp/joblib/joblib')]: Exception while loading results for (args=('/tmp/12.csv.zip', 'ab'), kwargs={})
 Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/joblib/memory.py", line 444, in _cached_call
    verbose=self._verbose)
  File "/usr/local/lib/python2.7/dist-packages/joblib/memory.py", line 133, in _load_output
    return numpy_pickle.load(filename, mmap_mode=mmap_mode)
  File "/usr/local/lib/python2.7/dist-packages/joblib/numpy_pickle.py", line 462, in load
    obj = unpickler.load()
  File "/usr/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/usr/local/lib/python2.7/dist-packages/joblib/numpy_pickle.py", line 325, in load_build
    array = nd_array_wrapper.read(self)
  File "/usr/local/lib/python2.7/dist-packages/joblib/numpy_pickle.py", line 186, in read
    data = read_zfile(f)
  File "/usr/local/lib/python2.7/dist-packages/joblib/numpy_pickle.py", line 97, in read_zfile
    "The file could be corrupted." % file_handle)
AssertionError: Incorrect data length while decompressing <open file '/home/user/tmp/joblib/joblib/__main__--home-user-src-test1/pandas_parse_csv-alias/ab445ac52cde63ef3b2ca96955d3503a/output.pkl_01.npy.z', mode 'rb' at 0x7f84b1cd2930>.The file could be corrupted.
```

The cache dir content before above exception:
```
-rw-rw-r-- 1 user user  178 Dec 23 17:10 metadata.json
-rw-rw-r-- 1 user user  11M Dec 23 17:10 output.pkl
-rw-rw-r-- 1 user user  18M Dec 23 17:09 output.pkl_01.npy.z
-rw-rw-r-- 1 user user  18M Dec 23 17:10 output.pkl_02.npy.z
```

**Comment by lesteve** [comment]
This may have been fixed in master, can you double-check ? Otherwise could you provide a stand-alone example reproducing the problem ?

**Comment by hrez** [comment]
No, still the same.

```
$git show HEAD
commit a8dd1191d9087f2f96b81d8e90efb675a7e81a0d
Author: Loic Esteve <loic.esteve@ymail.com>
Date:   Thu Jan 7 11:25:10 2016 +0100

    Add section in CHANGES.rst
    
    about #262 fix
```

**Comment by lesteve** [comment]
Sorry I should have said: you need to delete your cache folder. The problem that was fixed has to do with joblib.dump.

```
rm -rf /home/user/tmp/joblib/joblib/__main__--home-user-src-test1/pandas_parse_csv-alias
```

If that still doesn't work it would help a lot if you could provide a stand-alone example reproducing the problem.

**Comment by hrez** [comment]
Thanks. Wiping cache actually makes master work.
In fact 0.9.3 can also read cache created by master.
Please update PyPI with a fixed version.

**Comment by lesteve** [comment]
> Thanks. Wiping cache actually makes master work.
In fact 0.9.3 can also read cache created by master.
Please update PyPI with a fixed version.

OK that's what I thought, glad to hear that. As I said the underlying issue happens in joblib.dump not joblib.load.

We are planning a release soonish with a fix for https://github.com/scikit-learn/scikit-learn/issues/6063 but I am not sure when it is going to happen. @ogrisel any thoughts about that ?
