### ISSUE TITLE
joblib crashes with specific Python env

### ISSUE THREAD

**Issue by cle1109** [joblib/joblib#314]
When running an example script from our toolbox (https://github.com/scot-dev/scot/pull/30), Python crashes in line 570 of `parallel.py`:

    job = self._pool.apply_async(SafeFunction(batch), callback=cb)

Any ideas how I could track down the problem? The strange thing is that this only happens in my Python 3.5.1 environment installed via Homebrew (all packages installed via pip, all packages up to date). It doesn't happen in my Anaconda Python 3.5.1 env. The latest joblib version is 0.9.4, Anaconda's version is 0.8.4. If I install 0.8.4 in my Homebrew env, it still crashes, but later in the script (but assumedly in the same joblib line).

**Comment by GaelVaroquaux** [comment]
Could you please give us the full traceback.

**Comment by cle1109** [comment]
How can I get a traceback when Python crashes?

**Comment by GaelVaroquaux** [comment]
> How can I get a traceback when Python crashes?

It's printed on the console.

**Comment by cle1109** [comment]
```
^CProcess ForkPoolWorker-7:
Process ForkPoolWorker-9:
Process ForkPoolWorker-6:
Process ForkPoolWorker-11:
Process ForkPoolWorker-8:
Process ForkPoolWorker-10:
Process ForkPoolWorker-12:
Process ForkPoolWorker-5:
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/pool.py", line 108, in worker
    task = get()
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwTraceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/pool.py", line 108, in worker
    task = get()
  File "/usr/local/lib/python3.5/site-packages/joblib/pool.py", line 357, in get
    racquire()
args)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/pool.py", line 108, in worker
    task = get()
  File "/usr/local/lib/python3.5/site-packages/joblib/pool.py", line 357, in get
    racquire()
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
KeyboardInterrupt
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/process.py", line   File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/pool.py", line 108, in worker
    task = get()
254, in _bootstrap
    self.run()
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.5/site-packages/joblib/pool.py", line 357, in get
    racquire()
KeyboardInterrupt
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.5/site-packages/joblib/pool.py", line 357, in get
    racquire()
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/pool.py", line 108, in worker
    task = get()
  File "/usr/local/lib/python3.5/site-packages/joblib/pool.py", line 357, in get
    racquire()
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/pool.py", line 108, in worker
    task = get()
  File "/usr/local/lib/python3.5/site-packages/joblib/pool.py", line 357, in get
    racquire()
KeyboardInterrupt
KeyboardInterrupt
KeyboardInterrupt
KeyboardInterrupt
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/pool.py", line 108, in worker
    task = get()
  File "/usr/local/lib/python3.5/site-packages/joblib/pool.py", line 357, in get
    racquire()
KeyboardInterrupt
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/pool.py", line 108, in worker
    task = get()
  File "/usr/local/lib/python3.5/site-packages/joblib/pool.py", line 359, in get
    return recv()
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
KeyboardInterrupt
Traceback (most recent call last):
  File "examples/misc/parallelization.py", line 57, in <module>
    var.optimize_order(data, min_p=1, max_p=8)
  File "/Users/clemens/Repositories/scot/scot/var.py", line 118, in optimize_order
    for p_ in range(p, p + npar))
  File "/usr/local/lib/python3.5/site-packages/joblib/parallel.py", line 810, in __call__
    self.retrieve()
  File "/usr/local/lib/python3.5/site-packages/joblib/parallel.py", line 757, in retrieve
    raise exception
  File "/usr/local/lib/python3.5/site-packages/joblib/parallel.py", line 727, in retrieve
    self._output.extend(job.get())
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/pool.py", line 602, in get
    self.wait(timeout)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/pool.py", line 599, in wait
    self._event.wait(timeout)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 549, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 293, in wait
    waiter.acquire()
KeyboardInterrupt
```

**Comment by GaelVaroquaux** [comment]
That traceback is full of 'KeyboardInterrupt', it looks like you have
interrupted the code with 'ctrl-C'. Isn't it the case?

**Comment by cle1109** [comment]
Yes - but only after I received a dialog window saying that Python quit unexpectedly (= crashed).

<img width="433" alt="untitled" src="https://cloud.githubusercontent.com/assets/4377312/13176669/35d58a24-d714-11e5-91ee-6e3a87d25e0b.png">

**Comment by ogrisel** [comment]
I suspect your are using numpy? This is probably caused by a bad interaction between multiprocessing and apple accelerate (with recent anaconda, BLAS calls are passed to MKL instead):

https://pythonhosted.org/joblib/parallel.html#bad-interaction-of-multiprocessing-and-third-party-libraries

Please feel free to reopen if the solutions presented in that doc do not fix your issue.

**Comment by cle1109** [comment]
Nice, thanks @ogrisel, this solved the problem!
