### ISSUE TITLE
Error in thread allocate but joblib didn't throw the exception

### ISSUE THREAD

**Issue by chengguangnan** [joblib/joblib#336]
Some of the joblib workers run out of memory but didn't throw any exception for me to handle it. 

I think I need a way to get notified in the code when a thread failed to allow memory. Any thoughts? 

```
Exception in thread Thread-13:
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/root/anaconda3/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/root/anaconda3/lib/python3.5/multiprocessing/pool.py", line 366, in _handle_workers
    pool._maintain_pool()
  File "/root/anaconda3/lib/python3.5/multiprocessing/pool.py", line 240, in _maintain_pool
    self._repopulate_pool()
  File "/root/anaconda3/lib/python3.5/multiprocessing/pool.py", line 233, in _repopulate_pool
    w.start()
  File "/root/anaconda3/lib/python3.5/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/root/anaconda3/lib/python3.5/multiprocessing/context.py", line 267, in _Popen
    return Popen(process_obj)
  File "/root/anaconda3/lib/python3.5/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/root/anaconda3/lib/python3.5/multiprocessing/popen_fork.py", line 67, in _launch
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory

Exception in thread Thread-15:
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/root/anaconda3/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/root/anaconda3/lib/python3.5/multiprocessing/pool.py", line 429, in _handle_results
    task = get()
  File "/root/anaconda3/lib/python3.5/multiprocessing/connection.py", line 251, in recv
    return ForkingPickler.loads(buf.getbuffer())
MemoryError
```

**Comment by lesteve** [comment]
It would be great to have a stand-alone snippet so that we can try if we can reproduce the problem.

> Note that the process didn't exist.

You mean didn't exit right?
