### ISSUE TITLE
GridsearchCV failing with Assertion errors in joblib and multiprocessing

### ISSUE THREAD

**Issue by krishnateja614** [joblib/joblib#360]
I'm currently running a gridsearch on a Azure VM with 16 cores and 116GB Ram, while everything was working fine until 2-3 days ago (I didn't update any packages during the time), I'm running into the following error during grid search (n_jobs=-1).

```
Exception in thread Thread-4:
Traceback (most recent call last):
  File "C:\Users\Preston\Anaconda2\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Users\Preston\Anaconda2\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Users\Preston\Anaconda2\lib\multiprocessing\pool.py", line 421, in _handle_results
    cache[job]._set(i, obj)
  File "C:\Users\Preston\Anaconda2\lib\multiprocessing\pool.py", line 572, in _set
    self._callback(self._value)
  File "C:\Users\Preston\Anaconda2\lib\site-packages\sklearn\externals\joblib\parallel.py", line 224, in __call__
    self.parallel.dispatch_next()
  File "C:\Users\Preston\Anaconda2\lib\site-packages\sklearn\externals\joblib\parallel.py", line 592, in dispatch_next
    if not self.dispatch_one_batch(self._original_iterator):
  File "C:\Users\Preston\Anaconda2\lib\site-packages\sklearn\externals\joblib\parallel.py", line 658, in dispatch_one_batch
    self._dispatch(tasks)
  File "C:\Users\Preston\Anaconda2\lib\site-packages\sklearn\externals\joblib\parallel.py", line 579, in _dispatch
    job = self._pool.apply_async(SafeFunction(batch), callback=cb)
  File "C:\Users\Preston\Anaconda2\lib\multiprocessing\pool.py", line 293, in apply_async
    assert self._state == RUN
AssertionError

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Preston\Anaconda2\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 699, in runfile
    execfile(filename, namespace)
  File "C:\Users\Preston\Anaconda2\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 74, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)
  File "C:/Users/Preston/Documents/Python Scripts/xgboost_version_4_full_data_anon.py", line 139, in <module>
    clf.fit(x_train,y_train)
  File "C:\Users\Preston\Anaconda2\lib\site-packages\sklearn\grid_search.py", line 804, in fit
    return self._fit(X, y, ParameterGrid(self.param_grid))
  File "C:\Users\Preston\Anaconda2\lib\site-packages\sklearn\grid_search.py", line 553, in _fit
    for parameters in parameter_iterable
  File "C:\Users\Preston\Anaconda2\lib\site-packages\sklearn\externals\joblib\parallel.py", line 818, in __call__
    self._terminate_pool()
  File "C:\Users\Preston\Anaconda2\lib\site-packages\sklearn\externals\joblib\parallel.py", line 549, in _terminate_pool
    self._pool.terminate()  # terminate does a join()
  File "C:\Users\Preston\Anaconda2\lib\site-packages\sklearn\externals\joblib\pool.py", line 583, in terminate
    super(MemmapingPool, self).terminate()
  File "C:\Users\Preston\Anaconda2\lib\multiprocessing\pool.py", line 465, in terminate
    self._terminate()
  File "C:\Users\Preston\Anaconda2\lib\multiprocessing\util.py", line 207, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "C:\Users\Preston\Anaconda2\lib\multiprocessing\pool.py", line 497, in _terminate_pool
    assert result_handler.is_alive() or len(cache) == 0
AssertionError
```

Can anyone help me how to resolve this issue.I tried running the same code 3 times and always ran into  the same error on the same thread number. The dataset size is 800000*210.

**Comment by lesteve** [comment]
Readability counts, a lot! Please use triple back-quotes aka [fenced code blocks](https://help.github.com/articles/creating-and-highlighting-code-blocks/) to format error messages and code snippets.

I edited your previous post accordingly, but try to remember it for next time.

**Comment by lesteve** [comment]
> I'm currently running a gridsearch on a Azure VM with 16 cores and 116GB Ram, while everything was working fine until 2-3 days ago (I didn't update any packages during the time)

Weird, could it not be a Azure problem? It looks like the error happens rather deep in the multiprocessing module.

**Comment by krishnateja614** [comment]
It was working fine until 3 days ago, I used it several times on the same VM over the past month but this error only occurred now.
