### ISSUE TITLE
max_nbytes='1M' makes my job hang, max_nbytes=None fixes it, want to understand why

### ISSUE THREAD

**Issue by chengguangnan** [joblib/joblib#394]
I found that my program hangs at a certain step, and it's related to the size of input. Small inputs okay, larger inputs no. I think it stuck at `self._output.extend(job.get())`

I found that I can fix this problem by setting `max_nbytes=None`.

Given those symptom, I want to understand why `max_nbytes` would cause such an issue?

I'm not clear about the use of `max_nbytes`. So it's about the data that we passed to each worker? I assume each worker will have a different array to work on, what's the use of memory mapping here?

**Comment by chengguangnan** [comment]
- Ubuntu 16.04.1 LTS
- Python 3.5.1 :: Anaconda 2.5.0 (64-bit)
- joblib (0.9.4)

I'm not sure if I can re-produce it. It's a many step pipeline and many step are paralleled. The problem only happens on a certain step which I don't see any special of it. 

The input is about 800MB in pickle file (contains numbers and strings) and the program takes about 10GB of ram, meanwhile the machine as 32GB of ram.

Here is the stack I got upon first Control+C while the program is stuck. 

```
^CProcess ForkPoolWorker-84:
Process ForkPoolWorker-77:
Process ForkPoolWorker-81:
Process ForkPoolWorker-75:
Process ForkPoolWorker-79:
Process ForkPoolWorker-76:
Process ForkPoolWorker-83:
Process ForkPoolWorker-82:
Process ForkPoolWorker-74:
Process ForkPoolWorker-80:
Process ForkPoolWorker-73:
Process ForkPoolWorker-72:
Traceback (most recent call last):
  File "/home/chengguangnan/anaconda3/lib/python3.5/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/home/chengguangnan/anaconda3/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/chengguangnan/anaconda3/lib/python3.5/multiprocessing/pool.py", line 108, in worker
    task = get()
  File "/home/chengguangnan/anaconda3/lib/python3.5/site-packages/joblib-0.9.4-py3.5.egg/joblib/pool.py", line 357, in get
    racquire()
KeyboardInterrupt
Process ForkPoolWorker-71:
Process ForkPoolWorker-78:
Traceback (most recent call last):
  File "/home/chengguangnan/anaconda3/lib/python3.5/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/home/chengguangnan/anaconda3/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/chengguangnan/anaconda3/lib/python3.5/multiprocessing/pool.py", line 108, in worker
    task = get()
  File "/home/chengguangnan/anaconda3/lib/python3.5/site-packages/joblib-0.9.4-py3.5.egg/joblib/pool.py", line 357, in get
    racquire()
KeyboardInterrupt
Traceback (most recent call last):
  File "/home/chengguangnan/anaconda3/lib/python3.5/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/home/chengguangnan/anaconda3/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/chengguangnan/anaconda3/lib/python3.5/multiprocessing/pool.py", line 108, in worker
    task = get()
  File "/home/chengguangnan/anaconda3/lib/python3.5/site-packages/joblib-0.9.4-py3.5.egg/joblib/pool.py", line 357, in get
    racquire()
KeyboardInterrupt
Traceback (most recent call last):
  File "/home/chengguangnan/anaconda3/lib/python3.5/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
Traceback (most recent call last):
  File "/home/chengguangnan/anaconda3/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/chengguangnan/anaconda3/lib/python3.5/multiprocessing/pool.py", line 108, in worker
    task = get()
  File "/home/chengguangnan/anaconda3/lib/python3.5/site-packages/joblib-0.9.4-py3.5.egg/joblib/pool.py", line 357, in get
    racquire()
KeyboardInterrupt
  File "/home/chengguangnan/anaconda3/lib/python3.5/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/home/chengguangnan/anaconda3/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/chengguangnan/anaconda3/lib/python3.5/multiprocessing/pool.py", line 108, in worker
    task = get()
  File "/home/chengguangnan/anaconda3/lib/python3.5/site-packages/joblib-0.9.4-py3.5.egg/joblib/pool.py", line 357, in get
    racquire()
KeyboardInterrupt
Traceback (most recent call last):
  File "/home/chengguangnan/anaconda3/lib/python3.5/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
Traceback (most recent call last):
  File "/home/chengguangnan/anaconda3/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/chengguangnan/anaconda3/lib/python3.5/multiprocessing/pool.py", line 108, in worker
    task = get()
  File "/home/chengguangnan/anaconda3/lib/python3.5/site-packages/joblib-0.9.4-py3.5.egg/joblib/pool.py", line 357, in get
    racquire()
  File "/home/chengguangnan/anaconda3/lib/python3.5/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
KeyboardInterrupt
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/chengguangnan/anaconda3/lib/python3.5/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/home/chengguangnan/anaconda3/lib/python3.5/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/home/chengguangnan/anaconda3/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/chengguangnan/anaconda3/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/chengguangnan/anaconda3/lib/python3.5/multiprocessing/pool.py", line 108, in worker
    task = get()
  File "/home/chengguangnan/anaconda3/lib/python3.5/multiprocessing/pool.py", line 108, in worker
    task = get()
  File "/home/chengguangnan/anaconda3/lib/python3.5/site-packages/joblib-0.9.4-py3.5.egg/joblib/pool.py", line 357, in get
    racquire()
  File "/home/chengguangnan/anaconda3/lib/python3.5/site-packages/joblib-0.9.4-py3.5.egg/joblib/pool.py", line 357, in get
    racquire()
KeyboardInterrupt
KeyboardInterrupt
Traceback (most recent call last):
  File "/home/chengguangnan/anaconda3/lib/python3.5/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/home/chengguangnan/anaconda3/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/chengguangnan/anaconda3/lib/python3.5/multiprocessing/pool.py", line 108, in worker
    task = get()
  File "/home/chengguangnan/anaconda3/lib/python3.5/site-packages/joblib-0.9.4-py3.5.egg/joblib/pool.py", line 357, in get
    racquire()
KeyboardInterrupt
Traceback (most recent call last):
  File "/home/chengguangnan/anaconda3/lib/python3.5/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/home/chengguangnan/anaconda3/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/chengguangnan/anaconda3/lib/python3.5/multiprocessing/pool.py", line 108, in worker
    task = get()
  File "/home/chengguangnan/anaconda3/lib/python3.5/site-packages/joblib-0.9.4-py3.5.egg/joblib/pool.py", line 357, in get
    racquire()
KeyboardInterrupt
Traceback (most recent call last):
  File "/home/chengguangnan/anaconda3/lib/python3.5/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/home/chengguangnan/anaconda3/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/chengguangnan/anaconda3/lib/python3.5/multiprocessing/pool.py", line 108, in worker
    task = get()
  File "/home/chengguangnan/anaconda3/lib/python3.5/site-packages/joblib-0.9.4-py3.5.egg/joblib/pool.py", line 357, in get
    racquire()
KeyboardInterrupt
  File "/home/chengguangnan/anaconda3/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/chengguangnan/anaconda3/lib/python3.5/multiprocessing/pool.py", line 108, in worker
    task = get()
  File "/home/chengguangnan/anaconda3/lib/python3.5/site-packages/joblib-0.9.4-py3.5.egg/joblib/pool.py", line 357, in get
    racquire()
KeyboardInterrupt
Traceback (most recent call last):
  File "/home/chengguangnan/anaconda3/lib/python3.5/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/home/chengguangnan/anaconda3/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/chengguangnan/anaconda3/lib/python3.5/multiprocessing/pool.py", line 108, in worker
    task = get()
  File "/home/chengguangnan/anaconda3/lib/python3.5/site-packages/joblib-0.9.4-py3.5.egg/joblib/pool.py", line 357, in get
    racquire()
KeyboardInterrupt
Traceback (most recent call last):
  File "/home/chengguangnan/anaconda3/lib/python3.5/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/home/chengguangnan/anaconda3/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/chengguangnan/anaconda3/lib/python3.5/multiprocessing/pool.py", line 108, in worker
    task = get()
  File "/home/chengguangnan/anaconda3/lib/python3.5/site-packages/joblib-0.9.4-py3.5.egg/joblib/pool.py", line 359, in get
    return recv()
  File "/home/chengguangnan/anaconda3/lib/python3.5/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/home/chengguangnan/anaconda3/lib/python3.5/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/home/chengguangnan/anaconda3/lib/python3.5/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
KeyboardInterrupt

```

Second Control+C to actually quit. 
```
 File "/home/chengguangnan/anaconda3/lib/python3.5/site-packages/joblib-0.9.4-py3.5.egg/joblib/parallel.py", line 810, in __call__
    self.retrieve()
  File "/home/chengguangnan/anaconda3/lib/python3.5/site-packages/joblib-0.9.4-py3.5.egg/joblib/parallel.py", line 750, in retrieve
    self._terminate_pool()
  File "/home/chengguangnan/anaconda3/lib/python3.5/site-packages/joblib-0.9.4-py3.5.egg/joblib/parallel.py", line 549, in _terminate_pool
    self._pool.terminate()  # terminate does a join()
  File "/home/chengguangnan/anaconda3/lib/python3.5/site-packages/joblib-0.9.4-py3.5.egg/joblib/pool.py", line 583, in terminate
    super(MemmapingPool, self).terminate()
  File "/home/chengguangnan/anaconda3/lib/python3.5/multiprocessing/pool.py", line 505, in terminate
    self._terminate()
  File "/home/chengguangnan/anaconda3/lib/python3.5/multiprocessing/util.py", line 185, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/home/chengguangnan/anaconda3/lib/python3.5/multiprocessing/pool.py", line 535, in _terminate_pool
    cls._help_stuff_finish(inqueue, task_handler, len(pool))
  File "/home/chengguangnan/anaconda3/lib/python3.5/multiprocessing/pool.py", line 520, in _help_stuff_finish
    inqueue._rlock.acquire()
KeyboardInterrupt
```

**Comment by ogrisel** [comment]
Can you try to check it that still happens with the latest version of joblib 0.10.2? You can pip install it in a new conda environment if you don't want to mix anaconda provided packages with pip-installed ones in your main environment.

**Comment by ogrisel** [comment]
Can you please also check the number of multiprocessing workers still alive when that happens? You can use "ps aux | grep python" to list of the running python programs on your system.

Please also have a look at the content of joblib folders in `/dev/shm` and see if there are large files using much of the shared memory of the system.

**Comment by chengguangnan** [comment]
Err, I can't reproduce it now. 

I've restarted the machine, and maybe also changed some code.

**Comment by lesteve** [comment]
OK I am going to close this one. Feel free to reopen if you bump into it again.
