### ISSUE TITLE
test_joblib_pickle_across_python_versions ERRORs on Debian with lzma 0.5.3

### ISSUE THREAD

**Issue by yarikoptic** [joblib/joblib#403]
```
======================================================================
ERROR: joblib.test.test_numpy_pickle.test_joblib_pickle_across_python_versions
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/yoh/deb/gits/build-area/joblib-0.10.2/joblib/test/test_numpy_pickle.py", line 535, in test_joblib_pickle_across_python_versions
    _check_pickle(fname, expected_list)
  File "/home/yoh/deb/gits/build-area/joblib-0.10.2/joblib/test/test_numpy_pickle.py", line 446, in _check_pickle
    numpy_pickle.load, filename)
  File "/usr/lib/python2.7/unittest/case.py", line 473, in assertRaises
    callableObj(*args, **kwargs)
  File "/home/yoh/deb/gits/build-area/joblib-0.10.2/joblib/numpy_pickle.py", line 568, in load
    with _read_fileobject(f, filename, mmap_mode) as fobj:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/home/yoh/deb/gits/build-area/joblib-0.10.2/joblib/numpy_pickle_utils.py", line 202, in _read_fileobject
    yield _buffered_read_file(lzma.LZMAFile(fileobj, 'rb'))
TypeError: coercing to Unicode: need string or buffer, file found
```
some detail:
```shell
$> nosetests -s -v --pdb /home/yoh/deb/gits/build-area/joblib-0.10.2/joblib/test/test_numpy_pickle.py:test_joblib_pickle_across_python_versions
nose.config: INFO: Ignoring files matching ['^\\.', '^_', '^setup\\.py$']
nose.plugins.cover: INFO: Coverage report will include only packages: ['joblib']
________________________________________________________________________________
setup numpy_pickle
________________________________________________________________________________
joblib.test.test_numpy_pickle.test_joblib_pickle_across_python_versions ... > /home/yoh/deb/gits/build-area/joblib-0.10.2/joblib/numpy_pickle_utils.py(203)_read_fileobject()
-> yield _buffered_read_file(lzma.LZMAFile(fileobj, 'rb'))
(Pdb) p fileobj
<open file '/home/yoh/deb/gits/build-area/joblib-0.10.2/joblib/test/data/joblib_0.10.0_pickle_py26_np16.pkl.xz', mode 'rb' at 0x7f161a03dc90>
(Pdb) p lzma.LZMAFile(fileobj, 'rb')
*** TypeError: TypeError('coercing to Unicode: need string or buffer, file found',)
(Pdb) p lzma.__version__
'0.5.3'
```
and I believe it is this lzma -- https://pypi.python.org/pypi/pyliblzma/0.5.3 ;)  so I wondered if we are having the same lzma module used or issue is different (that was on debian testing/stable amd64)

**Comment by aabadie** [comment]
Thanks for reporting @yarikoptic.
I could reproduce this error locally by using python 2.7 and installing pyliblzma package.
The lzma compression was added in joblib because it's part of python standard library starting from version 3.3. This is definitely an issue and requires a fix.

**Comment by aabadie** [comment]
Looking at this more in depth, it seems that the problem comes from the `pyliblzma` package: the LZMAFile cannot deal with file objects. The following example reproduces what happens in the test in python 2.7 with `pyliblzma`:
```python
import lzma
with open('/tmp/test_file.lzma'; 'rb') as f:
    with lzma.LZMAFile(f, 'rb') as fz:
        fz.read()
```
fails with the same message:
```
      1 with open('/tmp/test_file.lzma', 'rb') as f:
----> 2     with lzma.LZMAFile(f, 'rb') as fz:
      3         fz.read()
      4 

TypeError: coercing to Unicode: need string or buffer, file found
```
Whereas the following works:
```python
with lzma.LZMAFile('/tmp/test_file.lzma', 'rb') as fz:
    fz.read()
```

**Comment by aabadie** [comment]
looking at the code [here](https://github.com/joblib/joblib/blob/master/joblib/numpy_pickle.py#L567) I fear joblib won't be able to support lzma compression/decompression with python 2.7 with the current implementation of `pyliblzma` (to me the problem is on their side).

**Comment by yarikoptic** [comment]
thought to suggest smth like
```
-                yield _buffered_read_file(lzma.LZMAFile(fileobj, 'rb'))
+                yield _buffered_read_file(
+                    lzma.LZMAFile(fileobj if PY3_OR_LATER else fileobj.name, 'rb'))
```
but then it boils into 
```
  File "/home/yoh/deb/gits/joblib/joblib/numpy_pickle_utils.py", line 203, in _read_fileobject
    lzma.LZMAFile(fileobj if PY3_OR_LATER else fileobj.name, 'rb'))
  File "/home/yoh/deb/gits/joblib/joblib/numpy_pickle_utils.py", line 108, in _buffered_read_file
    return io.BufferedReader(fobj, buffer_size=_IO_BUFFER_SIZE)
AttributeError: 'lzma.LZMAFile' object has no attribute 'readable'
```
so indeed might be easiest to not support on python2.  decision is fully up to you! ;)

**Comment by aabadie** [comment]
> so indeed might be easiest to not support on python2

I think we'll end up with this 'solution'.
