### ISSUE TITLE
Filesystem compression breaks joblib.test.test_disk.test_disk_used

### ISSUE THREAD

**Issue by lsartran** [joblib/joblib#57]
Hello, I am getting the following error when running nosetests on the latest version (latest commit dated Jan 15th.)

```
======================================================================
FAIL: joblib.test.test_disk.test_disk_used
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/nose-1.2.1-py2.7.egg/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/usr/home/ls/software/joblib/joblib/test/test_disk.py", line 40, in test_disk_used
    nose.tools.assert_true(disk_used(cachedir) >= target_size)
AssertionError: False is not true
    'False is not true' = self._formatMessage('False is not true', "%s is not true" % safe_repr(False))
>>  raise self.failureException('False is not true')


----------------------------------------------------------------------
Ran 299 tests in 2.890s

FAILED (failures=1)
```

/tmp is in a ZFS volume on FreeBSD with on-the-fly transparent compression enabled, so disk_used can be smaller than target_size. It indeed is:

```
[10:14:30] [ls@coyote /tmp]$ dd if=/dev/zero of=test.1M bs=1M count=1
1+0 records in
1+0 records out
1048576 bytes transferred in 0.000609 secs (1721348928 bytes/sec)
[10:14:36] [ls@coyote /tmp]$ ls -al test.1M
-rw-r--r--  1 ls  wheel  1048576 Jan 30 10:14 test.1M
[10:14:39] [ls@coyote /tmp]$ du -k test.1M
1   test.1M
[10:14:50] [ls@coyote /tmp]$ du -Ak test.1M
1024    test.1M
```

I'm unsure about what to suggest, as I don't know what the authors meant to check here:
- to get the apparent size of a file, using stat.st_size is the way to go
- however, to get its actual disk usage (to impose a limit upon how much space the cache can use, for instance) stat.st_blocks is fine, but the assumption test_disk_used makes doesn't hold.

**Comment by amueller** [comment]
can cause test failures on sklearn :-/
https://github.com/scikit-learn/scikit-learn/issues/4127
