### ISSUE TITLE
Error using loky and sphinx-gallery

### ISSUE THREAD

**Issue by glemaitre** [joblib/joblib#606]
I get some strange error when trying to compile the gallery with the example introduced in #605 

### How to reproduce

Note that the example can be run as a standalone script

```python
python examples/parallel_random_state.py
```

However, I get the following crash when running the doc build. Then, within the same terminal, the execution of the example will reproduce the crash.

```python
python setup.py build_sphinx
running build_sphinx
Running Sphinx v1.6.3
loading pickled environment... done
[autosummary] generating autosummary for: CHANGES.rst, README.rst, auto_examples/index.rst, auto_examples/parallel_memmap.rst, auto_examples/parallel_profiling.rst, developing.rst, generated/joblib.Memory.rst, generated/joblib.Parallel.rst, generated/joblib.dump.rst, generated/joblib.hash.rst, generated/joblib.load.rst, index.rst, installing.rst, memory.rst, parallel.rst, parallel_numpy.rst, persistence.rst, why.rst
generating gallery...
Traceback (most recent call last):es... [100%] parallel_random_state.py              
  File "/home/lemaitre/miniconda3/lib/python3.6/site-packages/joblib/externals/loky/process_executor.py", line 352, in _process_worker
    call_item = call_queue.get(block=True, timeout=timeout)
  File "/home/lemaitre/miniconda3/lib/python3.6/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
  File "/home/lemaitre/miniconda3/lib/python3.6/site-packages/joblib/parallel.py", line 141, in __setstate__
    items, self._size = state
ValueError: too many values to unpack (expected 2)
Traceback (most recent call last):
  File "/home/lemaitre/miniconda3/lib/python3.6/site-packages/joblib/externals/loky/process_executor.py", line 352, in _process_worker
    call_item = call_queue.get(block=True, timeout=timeout)
  File "/home/lemaitre/miniconda3/lib/python3.6/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
  File "/home/lemaitre/miniconda3/lib/python3.6/site-packages/joblib/parallel.py", line 141, in __setstate__
    items, self._size = state
ValueError: too many values to unpack (expected 2)
Exception in thread QueueManagerThread:
Traceback (most recent call last):
  File "/home/lemaitre/Documents/code/toolbox/joblib/joblib/externals/loky/_base.py", line 322, in _invoke_callbacks
    callback(self)
  File "/home/lemaitre/Documents/code/toolbox/joblib/joblib/parallel.py", line 227, in __call__
    self.parallel.dispatch_next()
  File "/home/lemaitre/Documents/code/toolbox/joblib/joblib/parallel.py", line 613, in dispatch_next
    if not self.dispatch_one_batch(self._original_iterator):
  File "/home/lemaitre/Documents/code/toolbox/joblib/joblib/parallel.py", line 640, in dispatch_one_batch
    self._dispatch(tasks)
  File "/home/lemaitre/Documents/code/toolbox/joblib/joblib/parallel.py", line 598, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/home/lemaitre/Documents/code/toolbox/joblib/joblib/_parallel_backends.py", line 457, in apply_async
    future = self._workers.submit(SafeFunction(func))
  File "/home/lemaitre/Documents/code/toolbox/joblib/joblib/externals/loky/process_executor.py", line 973, in submit
    raise BrokenProcessPool('A child process terminated abruptly, '
joblib.externals.loky.process_executor.BrokenProcessPool: A child process terminated abruptly, the process pool is not usable anymore

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lemaitre/miniconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/lemaitre/miniconda3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/lemaitre/Documents/code/toolbox/joblib/joblib/externals/loky/process_executor.py", line 568, in _queue_management_worker
    "A process in the process pool was terminated abruptly"
  File "/home/lemaitre/Documents/code/toolbox/joblib/joblib/externals/loky/_base.py", line 533, in set_exception
    self._invoke_callbacks()
  File "/home/lemaitre/Documents/code/toolbox/joblib/joblib/externals/loky/_base.py", line 324, in _invoke_callbacks
    LOGGER.exception('exception calling callback for %r', self)
  File "/home/lemaitre/miniconda3/lib/python3.6/logging/__init__.py", line 1341, in exception
    self.error(msg, *args, exc_info=exc_info, **kwargs)
  File "/home/lemaitre/miniconda3/lib/python3.6/logging/__init__.py", line 1335, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/home/lemaitre/miniconda3/lib/python3.6/logging/__init__.py", line 1442, in _log
    self.handle(record)
  File "/home/lemaitre/miniconda3/lib/python3.6/logging/__init__.py", line 1452, in handle
    self.callHandlers(record)
  File "/home/lemaitre/miniconda3/lib/python3.6/logging/__init__.py", line 1514, in callHandlers
    hdlr.handle(record)
  File "/home/lemaitre/miniconda3/lib/python3.6/logging/__init__.py", line 859, in handle
    rv = self.filter(record)
  File "/home/lemaitre/miniconda3/lib/python3.6/logging/__init__.py", line 718, in filter
    result = f.filter(record)
  File "/home/lemaitre/miniconda3/lib/python3.6/site-packages/Sphinx-1.6.3-py3.6.egg/sphinx/util/logging.py", line 338, in filter
    raise SphinxWarning(record.msg % record.args)
sphinx.errors.SphinxWarning: exception calling callback for <Future at 0x7f3543f7c898 state=finished raised BrokenProcessPool>


Warning, treated as error:
/home/lemaitre/Documents/code/toolbox/joblib/examples/parallel_random_state.py failed to execute correctly: Traceback (most recent call last):
  File "/home/lemaitre/Documents/code/toolbox/joblib/examples/parallel_random_state.py", line 54, in <module>
    stochastic_function)(10) for _ in range(n_vectors))
  File "/home/lemaitre/Documents/code/toolbox/joblib/joblib/parallel.py", line 813, in __call__
    self.retrieve()
  File "/home/lemaitre/Documents/code/toolbox/joblib/joblib/parallel.py", line 714, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/lemaitre/Documents/code/toolbox/joblib/joblib/_parallel_backends.py", line 468, in wrap_future_result
    return future.result(timeout=timeout)
  File "/home/lemaitre/Documents/code/toolbox/joblib/joblib/externals/loky/_base.py", line 431, in result
    return self.__get_result()
  File "/home/lemaitre/Documents/code/toolbox/joblib/joblib/externals/loky/_base.py", line 382, in __get_result
    raise self._exception
joblib.externals.loky.process_executor.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.

```

**Comment by glemaitre** [comment]
Interestingly, it is not happening on the CI.
