### ISSUE TITLE
Regression: TypeError: can't pickle weakref objects

### ISSUE THREAD

**Issue by jlopezpena** [joblib/joblib#629]
In an attempt to solve some impossible to debug deadlocks I was getting with the `sklearn` version of `joblib`, I decided to test with the new dev version and the `loky` backend, however, when running my code it gives me an error:
`TypeError: can't pickle weakref objects`
The error happens with both the `loky` and `multiprocessing` backends (joblib master branch pulled from git earlier today), the same function was "working" (apart from the deadlocks, but that is a separate issue) in the previous version of `joblib`.

Are there any changes that make the code backwards incompatible? I checked the docs, but I didn't find anything useful there. Shouldn't the `cloudpickle` backend work fine with everything that was working before?

**Comment by GaelVaroquaux** [comment]
Can you give us the full traceback, it will help understanding the problem.

Also, ideally, if you have code to reproduce the problem, it would help
fixing it.

**Comment by jlopezpena** [comment]
This is the full traceback:

```
Traceback (most recent call last):
  File "library_search_.py", line 252, in <module>
    run_full_search()
  File "/home/javier/anaconda3/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/javier/anaconda3/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/javier/anaconda3/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/javier/anaconda3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "library_search_.py", line 225, in run_full_search
    verbose=0)
  File "/home/javier/.dropbox-kickdex/Dropbox (Kickdex)/Code/ModelGenerationFramework/model_generation/model_search/search_library.py", line 314, in blended_weight_discard
    raise(e)
  File "/home/javier/.dropbox-kickdex/Dropbox (Kickdex)/Code/ModelGenerationFramework/model_generation/model_search/search_library.py", line 302, in blended_weight_discard
    avg_folds=folds)
  File "/home/javier/.dropbox-kickdex/Dropbox (Kickdex)/Code/ModelGenerationFramework/model_generation/models/blended_models.py", line 223, in _fit_weights
    **kwargs)
  File "/home/javier/.dropbox-kickdex/Dropbox (Kickdex)/Code/ModelGenerationFramework/model_generation/models/blended_models.py", line 204, in _fit_weights_max_score
    **kwargs) for x in seeds]
  File "/home/javier/.dropbox-kickdex/Dropbox (Kickdex)/Code/ModelGenerationFramework/model_generation/models/blended_models.py", line 204, in <listcomp>
    **kwargs) for x in seeds]
  File "/home/javier/.dropbox-kickdex/Dropbox (Kickdex)/Code/ModelGenerationFramework/model_generation/ensemble/weight_optimization.py", line 116, in weight_optimization_iter_
    **kwargs)
  File "/home/javier/.dropbox-kickdex/Dropbox (Kickdex)/Code/ModelGenerationFramework/model_generation/ensemble/hillclimb_optimizer.py", line 150, in hillclimb_optimizer_
    for prediction in prediction_blocks]))
  File "/home/javier/anaconda3/lib/python3.6/site-packages/joblib/parallel.py", line 800, in __call__
    if self.dispatch_one_batch(iterator):
  File "/home/javier/anaconda3/lib/python3.6/site-packages/joblib/parallel.py", line 640, in dispatch_one_batch
    self._dispatch(tasks)
  File "/home/javier/anaconda3/lib/python3.6/site-packages/joblib/parallel.py", line 598, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/home/javier/anaconda3/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 457, in apply_async
    future = self._workers.submit(SafeFunction(func))
  File "/home/javier/anaconda3/lib/python3.6/site-packages/joblib/externals/loky/process_executor.py", line 988, in submit
    self._ensure_executor_running()
  File "/home/javier/anaconda3/lib/python3.6/site-packages/joblib/externals/loky/process_executor.py", line 966, in _ensure_executor_running
    self._adjust_process_count()
  File "/home/javier/anaconda3/lib/python3.6/site-packages/joblib/externals/loky/process_executor.py", line 957, in _adjust_process_count
    p.start()
  File "/home/javier/anaconda3/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/home/javier/anaconda3/lib/python3.6/site-packages/joblib/externals/loky/backend/process.py", line 37, in _Popen
    return Popen(process_obj)
  File "/home/javier/anaconda3/lib/python3.6/site-packages/joblib/externals/loky/backend/popen_loky_posix.py", line 55, in __init__
    self._launch(process_obj)
  File "/home/javier/anaconda3/lib/python3.6/site-packages/joblib/externals/loky/backend/popen_loky_posix.py", line 135, in _launch
    reduction.dump(process_obj, fp)
  File "/home/javier/anaconda3/lib/python3.6/site-packages/joblib/externals/loky/backend/reduction.py", line 154, in dump
    protocol=protocol).dump(obj)
TypeError: can't pickle weakref objects
```

**Comment by jlopezpena** [comment]
Essentially, what is going on is a parallellized version of Caruana's hillclimb algorithm for ensemble selection. I have several hundred (or thousands) of models, for each of them I have an offsample prediction block, and at each iteration I want to select the estimator that brings the biggest improvement to the ensemble score.

The scoring function is a version of multiclass logloss, with a baseline scaling so that a random prediction has score 0 and a perfect prediction has score 1 (Caruana has another paper in which he talks about this "adjusted logloss").

I will try to make a failing example, but it might take a while to decouple it from the rest of our company's code.

**Comment by jlopezpena** [comment]
Digging in this, the error seems to only happen if there are multiple parallel contexts defined.

My process goes like this:

1. Describe a bunch of models
2. Make parallel cross validation predictions for the models  <---- Parallel context 1
3. Based on some argument to my function, decide on optimization function (eg hillclimb) and call it
4. (Inside hillclimb) Parallel evaluate the scoring function in each of the submodels <--- Parallel context 2

In both 2 and 4 I define parallel contexts. If I use the dev `joblib` in BOTH of them, I get the `weakref` error from above, whereas if I only use the new joblib in one of them and I use the `sklearn` version in the other one, everything works just fine. Functions in 2 and 4 are defined in separate modules in my code (2 is a generic "ensemble creation" module, 4 is specific routines for parallel hillclimb).

**Comment by jlopezpena** [comment]
Still digging and trying to reduce the issue into a single-file reproducible example.
In the meantime, I managed to isolate a bit further the issue, which seems to happen the **second** time a parallel backend is used

By simplifying a little the functions I call I managed to get a more informative traceback:

```
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/javier/anaconda3/lib/python3.6/site-packages/joblib/externals/loky/backend/queues.py", line 150, in _feed
    obj, reducers=reducers)
  File "/home/javier/anaconda3/lib/python3.6/site-packages/joblib/externals/loky/backend/reduction.py", line 145, in dumps
    p.dump(obj)
  File "/home/javier/anaconda3/lib/python3.6/site-packages/joblib/parallel.py", line 140, in __getstate__
    for func, args, kwargs in self.items]
  File "/home/javier/anaconda3/lib/python3.6/site-packages/joblib/parallel.py", line 140, in <listcomp>
    for func, args, kwargs in self.items]
  File "/home/javier/anaconda3/lib/python3.6/site-packages/joblib/externals/cloudpickle/cloudpickle.py", line 881, in dumps
    cp.dump(obj)
  File "/home/javier/anaconda3/lib/python3.6/site-packages/joblib/externals/cloudpickle/cloudpickle.py", line 268, in dump
    return Pickler.dump(self, obj)
  File "/home/javier/anaconda3/lib/python3.6/pickle.py", line 409, in dump
    self.save(obj)
  File "/home/javier/anaconda3/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/javier/anaconda3/lib/python3.6/site-packages/joblib/externals/cloudpickle/cloudpickle.py", line 405, in save_function
    self.save_function_tuple(obj)
  File "/home/javier/anaconda3/lib/python3.6/site-packages/joblib/externals/cloudpickle/cloudpickle.py", line 553, in save_function_tuple
    save(state)
  File "/home/javier/anaconda3/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/javier/anaconda3/lib/python3.6/pickle.py", line 821, in save_dict
    self._batch_setitems(obj.items())
  File "/home/javier/anaconda3/lib/python3.6/pickle.py", line 847, in _batch_setitems
    save(v)
  File "/home/javier/anaconda3/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/javier/anaconda3/lib/python3.6/pickle.py", line 821, in save_dict
    self._batch_setitems(obj.items())
  File "/home/javier/anaconda3/lib/python3.6/pickle.py", line 847, in _batch_setitems
    save(v)
  File "/home/javier/anaconda3/lib/python3.6/pickle.py", line 521, in save
    self.save_reduce(obj=obj, *rv)
  File "/home/javier/anaconda3/lib/python3.6/pickle.py", line 634, in save_reduce
    save(state)
  File "/home/javier/anaconda3/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/javier/anaconda3/lib/python3.6/pickle.py", line 821, in save_dict
    self._batch_setitems(obj.items())
  File "/home/javier/anaconda3/lib/python3.6/pickle.py", line 847, in _batch_setitems
    save(v)
  File "/home/javier/anaconda3/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/javier/anaconda3/lib/python3.6/pickle.py", line 781, in save_list
    self._batch_appends(obj)
  File "/home/javier/anaconda3/lib/python3.6/pickle.py", line 808, in _batch_appends
    save(tmp[0])
  File "/home/javier/anaconda3/lib/python3.6/pickle.py", line 521, in save
    self.save_reduce(obj=obj, *rv)
  File "/home/javier/anaconda3/lib/python3.6/pickle.py", line 634, in save_reduce
    save(state)
  File "/home/javier/anaconda3/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/javier/anaconda3/lib/python3.6/pickle.py", line 821, in save_dict
    self._batch_setitems(obj.items())
  File "/home/javier/anaconda3/lib/python3.6/pickle.py", line 847, in _batch_setitems
    save(v)
  File "/home/javier/anaconda3/lib/python3.6/pickle.py", line 496, in save
    rv = reduce(self.proto)
TypeError: can't pickle _thread.RLock objects
```

**Comment by ogrisel** [comment]
The later traceback seems quite different from the previous one though.

**Comment by ogrisel** [comment]
@jlopezpena How to do you use the parallel backend? Using the `with parallel_backend('backend_name'):` syntax or using `Parallel(backend='backend_name')` directly?

Do you nest the parallel calls or do you call them sequentially in the the same main thread?

**Comment by jlopezpena** [comment]
@ogrisel my (simplified) code looks like this:

```
def create_ensemble(X, y, descriptors, scoring='log_loss', avg_folds=10):
    seeds = np.random.randint(4294967296,  # 2 ** 32
                              size=avg_folds)
    weights = [ensemble_weights(
        descriptors=descriptors,
        X=X,
        y=y,
        scoring=scoring,
        seed=x) for x in seeds]
    return np.mean(weights, axis=0)


def ensemble_weights(X, y, model_descriptions, scoring='log_loss'):
    np.random.seed(seed)
    with Parallel(n_jobs=-1) as parallel:
        prediction_blocks = parallel([
            delayed(cross_val_predict_from_desc_)(descriptor, X, y)
            for i, descriptor in enumerate(model_descriptions)])

    opt = hillclimb_optimizer(prediction_blocks, y, scoring)
    return opt['x']


def hillclimb_optimizer(prediction_blocks, y, scoring='log_loss'):
    n = len(prediction_blocks)
    ret_ensemble_ = np.zeros(n)

    initial_score = -np.inf
    scorer = check_scoring(scoring)

    with Parallel(n_jobs=-1) as parallel:
        submodel_scores = pd.Series(parallel(
            [delayed(scorer)(y,
                             prediction)
             for prediction in prediction_blocks]))

    initial_ensemble = get_initial_ensemble_(submodel_scores)
    
    ## ... iterations for the rest of the hillclimb method ...
    ## ...
```

Most versions of the functions are custom wrappers around the `sklearn` functions, so that they work on our `model_description` object (text-based serialization describing a model prior to fitting for easier pickling and persistence on database). I cannot stick to standard `sklearn` because some of our models wrap calls to R code that does not follow the sklearn API.

Looks like some of the issues happen when my list of model descriptors is loaded from a previously (joblib) dumped list, so I am guessing there are some problems unpickling data previously pickled with the earlier version of joblib (weirdly, I don't get any errors unpickling or fitting models, only when running the parallel stuff), re-pickling the model descriptors with the new jobs moved the error slightly (albeit still fail). Due to some urgent job deadline I had to roll back to my environment using only the `sklearn` version and couldn't keep searching here, hopefully will be able to look further into it later this week.

**Comment by ogrisel** [comment]
So indeed the parallel calls happen sequentially. I will try to write scripts to try to reproduce this.

**Comment by ogrisel** [comment]
I can reproduce it as follows:

```python
from joblib import Parallel, delayed
import numpy as np


big_data = np.random.randn(int(1e7))


def func(data, i):
    return data * i


Parallel(n_jobs=2, verbose=1)(delayed(func)(big_data, i) for i in range(20))
Parallel(n_jobs=8, verbose=1)(delayed(func)(big_data, i) for i in range(20))
```

I get the following output:

```
[Parallel(n_jobs=2)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=2)]: Done  20 out of  20 | elapsed:    3.3s finished
Traceback (most recent call last):
  File "/volatile/ogrisel/tmp/joblib_loky_adjust.py", line 13, in <module>
    Parallel(n_jobs=8, verbose=1)(delayed(func)(big_data, i) for i in range(20))
  File "/volatile/ogrisel/code/joblib/joblib/parallel.py", line 834, in __call__
    n_jobs = self._initialize_backend()
  File "/volatile/ogrisel/code/joblib/joblib/parallel.py", line 624, in _initialize_backend
    **self._backend_args)
  File "/volatile/ogrisel/code/joblib/joblib/_parallel_backends.py", line 431, in configure
    n_jobs, **memmappingexecutor_args)
  File "/volatile/ogrisel/code/joblib/joblib/executor.py", line 33, in get_memmapping_executor
    reuse=reuse)
  File "/volatile/ogrisel/code/joblib/joblib/externals/loky/reusable_executor.py", line 119, in get_reusable_executor
    executor._resize(max_workers)
  File "/volatile/ogrisel/code/joblib/joblib/externals/loky/reusable_executor.py", line 150, in _resize
    self._adjust_process_count()
  File "/volatile/ogrisel/code/joblib/joblib/externals/loky/process_executor.py", line 957, in _adjust_process_count
    p.start()
  File "/volatile/ogrisel/miniconda3/envs/joblibdoc/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/volatile/ogrisel/code/joblib/joblib/externals/loky/backend/process.py", line 37, in _Popen
    return Popen(process_obj)
  File "/volatile/ogrisel/code/joblib/joblib/externals/loky/backend/popen_loky_posix.py", line 55, in __init__
    self._launch(process_obj)
  File "/volatile/ogrisel/code/joblib/joblib/externals/loky/backend/popen_loky_posix.py", line 135, in _launch
    reduction.dump(process_obj, fp)
  File "/volatile/ogrisel/code/joblib/joblib/externals/loky/backend/reduction.py", line 154, in dump
    protocol=protocol).dump(obj)
TypeError: can't pickle weakref objects
```

It's probably caused by the new implementation of the auto-memmaping feature. I will investigate.
