### ISSUE TITLE
can't cache decorator with Parallel

### ISSUE THREAD

**Issue by tbenst** [joblib/joblib#666]
Minimal example below:

```python
from joblib import Parallel, delayed, Memory
memory = Memory(cachedir='/tmp/yo')

@memory.cache
def yo(x):
    _yo(x)

def _yo(x):
    print("yo")
    return x

yoc = memory.cache(_yo)

# works
Parallel(n_jobs=6)(delayed(yoc)(i) for i in range(6))

# error
Parallel(n_jobs=6)(delayed(yo)(i) for i in range(6))

Traceback (most recent call last):
  File "test.py", line 18, in <module>
    Parallel(n_jobs=6)(delayed(yo)(i) for i in range(6))
  File "/home/tyler/lib/anaconda3/lib/python3.6/site-packages/joblib/parallel.py", line 779, in __call__
    while self.dispatch_one_batch(iterator):
  File "/home/tyler/lib/anaconda3/lib/python3.6/site-packages/joblib/parallel.py", line 620, in dispatch_one_batch
    tasks = BatchedCalls(itertools.islice(iterator, batch_size))
  File "/home/tyler/lib/anaconda3/lib/python3.6/site-packages/joblib/parallel.py", line 127, in __init__
    self.items = list(iterator_slice)
  File "test.py", line 18, in <genexpr>
    Parallel(n_jobs=6)(delayed(yo)(i) for i in range(6))
  File "/home/tyler/lib/anaconda3/lib/python3.6/site-packages/joblib/parallel.py", line 183, in delayed
    pickle.dumps(function)
_pickle.PicklingError: Can't pickle <function yo at 0x7f43e5b5aea0>: it's not the same object as __main__.yo
```

**Comment by lesteve** [comment]
I believe this has been fixed in master, probably because we are using cloudpickle, closing this one. If you find this is still failing on master, do reopen this issue.
