### ISSUE TITLE
Pickling error from joblib.Parallel()

### ISSUE THREAD

**Issue by aveekchoudhury01** [joblib/joblib#767]
When running a block of code from within Parallel(), it returns the error - 
_pickle.PicklingError: Could not pickle the task to send it to the workers.

Is anyone facing similar issues? Any help appreciated!

Description - Inside the (to be parallelized) function, I am using Spacy's english language model to extract Named Entities from text.  I encounter this error when running the script from command line. If I use interactive program like a jupyter notebook, the call to Parallel() sometimes works fine and sometimes throws the described error, basically not consistent.

The error trace looks like this - 
$ python namedAliases_associatedEntities_v6.py
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Batch computation too fast (0.0770s.) Setting batch_size=4.
joblib.externals.loky.process_executor._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.5/site-packages/joblib/externals/loky/backend/queues.py", line 151, in _feed
    obj, reducers=reducers)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/joblib/externals/loky/backend/reduction.py", line 145, in dumps
    p.dump(obj)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/joblib/parallel.py", line 290, in __getstate__
    for func, args, kwargs in self.items]
  File "/home/ubuntu/.local/lib/python3.5/site-packages/joblib/parallel.py", line 290, in <listcomp>
    for func, args, kwargs in self.items]
  File "/home/ubuntu/.local/lib/python3.5/site-packages/joblib/parallel.py", line 278, in _wrap_non_picklable_objects
    wrapped_obj = CloudpickledObjectWrapper(obj)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/joblib/parallel.py", line 208, in __init__
    self.pickled_obj = dumps(obj)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/joblib/externals/cloudpickle/cloudpickle.py", line 917, in dumps
    cp.dump(obj)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/joblib/externals/cloudpickle/cloudpickle.py", line 268, in dump
    return Pickler.dump(self, obj)
  File "/usr/lib/python3.5/pickle.py", line 408, in dump
    self.save(obj)
  File "/usr/lib/python3.5/pickle.py", line 475, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/ubuntu/.local/lib/python3.5/site-packages/joblib/externals/cloudpickle/cloudpickle.py", line 408, in save_function
    self.save_function_tuple(obj)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/joblib/externals/cloudpickle/cloudpickle.py", line 573, in save_function_tuple
    save(state)
  File "/usr/lib/python3.5/pickle.py", line 475, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/ubuntu/.local/lib/python3.5/site-packages/dill/_dill.py", line 893, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/usr/lib/python3.5/pickle.py", line 810, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.5/pickle.py", line 836, in _batch_setitems
    save(v)
  File "/usr/lib/python3.5/pickle.py", line 475, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/ubuntu/.local/lib/python3.5/site-packages/dill/_dill.py", line 893, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/usr/lib/python3.5/pickle.py", line 810, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.5/pickle.py", line 841, in _batch_setitems
    save(v)
  File "/usr/lib/python3.5/pickle.py", line 475, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/ubuntu/.local/lib/python3.5/site-packages/joblib/externals/cloudpickle/cloudpickle.py", line 408, in save_function
    self.save_function_tuple(obj)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/joblib/externals/cloudpickle/cloudpickle.py", line 573, in save_function_tuple
    save(state)
  File "/usr/lib/python3.5/pickle.py", line 475, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/ubuntu/.local/lib/python3.5/site-packages/dill/_dill.py", line 893, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/usr/lib/python3.5/pickle.py", line 810, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.5/pickle.py", line 836, in _batch_setitems
    save(v)
  File "/usr/lib/python3.5/pickle.py", line 475, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/ubuntu/.local/lib/python3.5/site-packages/dill/_dill.py", line 893, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/usr/lib/python3.5/pickle.py", line 810, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.5/pickle.py", line 836, in _batch_setitems
    save(v)
  File "/usr/lib/python3.5/pickle.py", line 475, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/ubuntu/.local/lib/python3.5/site-packages/joblib/externals/cloudpickle/cloudpickle.py", line 408, in save_function
    self.save_function_tuple(obj)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/joblib/externals/cloudpickle/cloudpickle.py", line 573, in save_function_tuple
    save(state)
  File "/usr/lib/python3.5/pickle.py", line 475, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/ubuntu/.local/lib/python3.5/site-packages/dill/_dill.py", line 893, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/usr/lib/python3.5/pickle.py", line 810, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.5/pickle.py", line 836, in _batch_setitems
    save(v)
  File "/usr/lib/python3.5/pickle.py", line 475, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/ubuntu/.local/lib/python3.5/site-packages/dill/_dill.py", line 893, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/usr/lib/python3.5/pickle.py", line 810, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.5/pickle.py", line 841, in _batch_setitems
    save(v)
  File "/usr/lib/python3.5/pickle.py", line 520, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python3.5/pickle.py", line 592, in save_reduce
    "args[0] from __newobj__ args has the wrong class")
_pickle.PicklingError: args[0] from __newobj__ args has the wrong class
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "namedAliases_associatedEntities_v6.py", line 283, in <module>
    list_of_named_entities = Parallel(n_jobs=-1, verbose=10, backend = 'loky')(map(delayed(processNER), all_articles))
  File "/home/ubuntu/.local/lib/python3.5/site-packages/joblib/parallel.py", line 996, in __call__
    self.retrieve()
  File "/home/ubuntu/.local/lib/python3.5/site-packages/joblib/parallel.py", line 899, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/ubuntu/.local/lib/python3.5/site-packages/joblib/_parallel_backends.py", line 517, in wrap_future_result
    return future.result(timeout=timeout)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/joblib/externals/loky/_base.py", line 431, in result
    return self.__get_result()
  File "/home/ubuntu/.local/lib/python3.5/site-packages/joblib/externals/loky/_base.py", line 382, in __get_result
    raise self._exception
_pickle.PicklingError: Could not pickle the task to send it to the workers.

**Comment by ogrisel** [comment]
The fact that you have the `dill` library in your traceback looks fishy to me. Is dill a dependency of spacy? Have you tried to run your script without dill installed?

Could you please provide a minimal reproduction case that does not depend on private data?

See: http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by dmparker0** [comment]
I'm having a similar issue. With joblib 0.12.1, I have no issues. With joblib 0.12.5, I run into a pickling error:

>joblib.externals.loky.process_executor._RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\site-packages\joblib\externals\loky\backend\queues.py", line 151, in _feed
    obj, reducers=reducers)
  File "C:\Program Files\Python36\lib\site-packages\joblib\externals\loky\backend\reduction.py", line 145, in dumps
    p.dump(obj)
  File "C:\Program Files\Python36\lib\site-packages\joblib\parallel.py", line 290, in __getstate__
    for func, args, kwargs in self.items]
  File "C:\Program Files\Python36\lib\site-packages\joblib\parallel.py", line 290, in <listcomp>
    for func, args, kwargs in self.items]
  File "C:\Program Files\Python36\lib\site-packages\joblib\parallel.py", line 278, in _wrap_non_picklable_objects
    wrapped_obj = CloudpickledObjectWrapper(obj)
  File "C:\Program Files\Python36\lib\site-packages\joblib\parallel.py", line 208, in __init__
    self.pickled_obj = dumps(obj)
  File "C:\Program Files\Python36\lib\site-packages\joblib\externals\cloudpickle\cloudpickle.py", line 918, in dumps
    cp.dump(obj)
  File "C:\Program Files\Python36\lib\site-packages\joblib\externals\cloudpickle\cloudpickle.py", line 268, in dump
    return Pickler.dump(self, obj)
  File "C:\Program Files\Python36\lib\pickle.py", line 409, in dump
    self.save(obj)
  File "C:\Program Files\Python36\lib\pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Program Files\Python36\lib\site-packages\joblib\externals\cloudpickle\cloudpickle.py", line 408, in save_function
    self.save_function_tuple(obj)
  File "C:\Program Files\Python36\lib\site-packages\joblib\externals\cloudpickle\cloudpickle.py", line 573, in save_function_tuple
    save(state)
  File "C:\Program Files\Python36\lib\pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Program Files\Python36\lib\pickle.py", line 821, in save_dict
    self._batch_setitems(obj.items())
  File "C:\Program Files\Python36\lib\pickle.py", line 847, in _batch_setitems
    save(v)
  File "C:\Program Files\Python36\lib\pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Program Files\Python36\lib\pickle.py", line 821, in save_dict
    self._batch_setitems(obj.items())
  File "C:\Program Files\Python36\lib\pickle.py", line 847, in _batch_setitems
    save(v)
  File "C:\Program Files\Python36\lib\pickle.py", line 507, in save
    self.save_global(obj, rv)
  File "C:\Program Files\Python36\lib\site-packages\joblib\externals\cloudpickle\cloudpickle.py", line 668, in save_global
    return Pickler.save_global(self, obj, name=name)
  File "C:\Program Files\Python36\lib\pickle.py", line 927, in save_global
    (obj, module_name, name))
_pickle.PicklingError: Can't pickle typing.Union[typing.List[typing.List[str]], NoneType]: it's not the same object as typing.Union
"""

>The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "r:\Report Scripts\PCSHelper.py", line 70, in <module>
    data = [x for y in Parallel(n_jobs=2)(delayed(getPropDetails)(prop) for prop in props) for x in y]
  File "C:\Program Files\Python36\lib\site-packages\joblib\parallel.py", line 996, in __call__
    self.retrieve()
  File "C:\Program Files\Python36\lib\site-packages\joblib\parallel.py", line 899, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "C:\Program Files\Python36\lib\site-packages\joblib\_parallel_backends.py", line 517, in wrap_future_result
    return future.result(timeout=timeout)
  File "C:\Program Files\Python36\lib\concurrent\futures\_base.py", line 432, in result
    return self.__get_result()
  File "C:\Program Files\Python36\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
_pickle.PicklingError: Could not pickle the task to send it to the workers.

**Comment by ogrisel** [comment]
I think pickling types is broken in Python 3.6. Can you try with Python 3.7?

**Comment by jugovich** [comment]
I have the same issue on rhel 7.  Joblib breaks with PicklingError when sending loaded spacy 'en' model to task.  I tried with both python3.6 and python3.7.  The error can be reproduced using the spacy multiprocessing example script (available on [https://spacy.io/usage/examples](url))

I have the following dependencies
```
numpy==1.15.4
scipy==1.2.0
joblib==0.13.1
spacy==2.0.18
psycopg2-binary==2.7.6.1
SQLAlchemy==1.2.15
configparser==3.5.0
watson_developer_cloud==2.1.0
pandas==0.23
```

Here is the sample script to reproduce the error (note you first must download the 'en_core_small_web_model' file using `python -m spacy download en`
```
#!/usr/bin/env python
# coding: utf8
"""Example of multi-processing with Joblib. Here, we're exporting
part-of-speech-tagged, true-cased, (very roughly) sentence-separated text, with
each "sentence" on a newline, and spaces between tokens. Data is loaded from
the IMDB movie reviews dataset and will be loaded automatically via Thinc's
built-in dataset loader.

Compatible with: spaCy v2.0.0+
"""
from __future__ import print_function, unicode_literals
from toolz import partition_all
from pathlib import Path
from joblib import Parallel, delayed
import thinc.extra.datasets
import plac
import spacy


@plac.annotations(
    output_dir=("Output directory", "positional", None, Path),
    model=("Model name (needs tagger)", "positional", None, str),
    n_jobs=("Number of workers", "option", "n", int),
    batch_size=("Batch-size for each process", "option", "b", int),
    limit=("Limit of entries from the dataset", "option", "l", int))
def main(output_dir, model='en', n_jobs=4, batch_size=1000,
         limit=10000):
    nlp = spacy.load(model)  # load spaCy model
    print("Loaded model '%s'" % model)
    if not output_dir.exists():
        output_dir.mkdir()
    # load and pre-process the IMBD dataset
    print("Loading IMDB data...")
    data, _ = thinc.extra.datasets.imdb()
    texts, _ = zip(*data[-limit:])
    print("Processing texts...")
    partitions = partition_all(batch_size, texts)
    executor = Parallel(n_jobs=n_jobs)
    do = delayed(transform_texts)
    tasks = (do(nlp, i, batch, output_dir)
             for i, batch in enumerate(partitions))
    executor(tasks)


def transform_texts(nlp, batch_id, texts, output_dir):
    print(nlp.pipe_names)
    out_path = Path(output_dir) / ('%d.txt' % batch_id)
    if out_path.exists():  # return None in case same batch is called again
        return None
    print('Processing batch', batch_id)
    with out_path.open('w', encoding='utf8') as f:
        for doc in nlp.pipe(texts):
            f.write(' '.join(represent_word(w) for w in doc if not w.is_space))
            f.write('\n')
    print('Saved {} texts to {}.txt'.format(len(texts), batch_id))


def represent_word(word):
    text = word.text
    # True-case, i.e. try to normalize sentence-initial capitals.
    # Only do this if the lower-cased form is more probable.
    if text.istitle() and is_sent_begin(word) \
       and word.prob < word.doc.vocab[text.lower()].prob:
        text = text.lower()
    return text + '|' + word.tag_


def is_sent_begin(word):
    if word.i == 0:
        return True
    elif word.i >= 2 and word.nbor(-1).text in ('.', '!', '?', '...'):
        return True
    else:
        return False


if __name__ == '__main__':
    plac.call(main)
```

**Comment by jugovich** [comment]
Dig some further digging and this appears to be a spacy issue with pickling and not a joblib issue.  See this issue for reference on the spacy pickling issue: [https://github.com/explosion/spaCy/issues/2962](url)

**Comment by alexander-soare** [comment]
I'm getting this issue too. Worth noting that I'm in a notebook environment and using autoreload:

```
%reload_ext autoreload
%autoreload 2
```

The error seems to be thrown up when I update one of my modules in between cell runs.

**Comment by JohnCHarrington** [comment]
I have a very similar issue trying to run PyMC3 model training with joblib (and I also had dill in the trace). As dmparker said above, I tried using an old version of joblib (0.12.1) and it works fine.
