### ISSUE TITLE
Error when returning certain objects

### ISSUE THREAD

**Issue by khoopes** [joblib/joblib#774]
Joblib is new to me so excuse my ignorance if there is a better way to do this that does not give an error. I have simplified my larger code down to this repeatable issue:

```python

from joblib import Parallel, delayed
import CoolProp

def run_fun(num):
	co2 = CoolProp.AbstractState('HEOS', 'CO2')
	co2.update(CoolProp.PT_INPUTS, 101325, 400+num)
	return co2

if __name__ == '__main__':
	
	number_range = [2,3,4,5,6,7,8]
	
	#################This works####################
	serial_output = []
	for number in number_range:
		serial_output.append(run_fun(number))
	
	print [k.rhomass() for k in serial_output]
	
	#################This doesn't##################	
	parallel_output = Parallel(n_jobs=4, backend="multiprocessing")(map(delayed(run_fun), number_range))
	print [k.rhomass() for k in parallel_output]

```

I think the issue is what I return in my function, if I return k.rhomass() from the function the parallel works just fine. But it does not like getting that coolprop object. I get this error:

```
[1.336555986982784, 1.3332176198250427, 1.3298959970186623, 1.3265909917944818, 1.3233024786744818, 1.3200303334551526, 1.3167744331911175]
Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\Users\khoopes\AppData\Local\Continuum\anaconda2\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Users\khoopes\AppData\Local\Continuum\anaconda2\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Users\khoopes\AppData\Local\Continuum\anaconda2\lib\multiprocessing\pool.py", line 392, in _handle_results
    task = get()
  File "CoolProp\AbstractState.pyx", line 31, in CoolProp.CoolProp.AbstractState.__cinit__ (CoolProp\CoolProp.cpp:11111)
TypeError: __cinit__() takes exactly 2 positional arguments (0 given)

```

Sorry to require CoolProp to recreate this issue, but that is what my other code uses and I wanted to get it as close as possible. I would really like to return the coolprop object.

Any ideas?

**Comment by ogrisel** [comment]
Don't use map, use a generator expression:

```python
parallel_output = Parallel(n_jobs=4, backend="multiprocessing")(
    delayed(run_fun)(i) for i in number_range
)
```

Also, in the latest version of joblib, it is recommended to use the "loky" default backend instead of the old multiprocessing backend (no need to pass the backend argument.

**Comment by khoopes** [comment]
OK. I need to read up on generators.... I still get an error when I use that though. Also, when I switch to loky, by removing the multiprocessing backend. I get this error

```
Traceback (most recent call last):
  File "joblib_test.py", line 22, in <module>
    parallel_output = Parallel(n_jobs=4)(delayed(run_fun)(i) for i in number_range)
  File "C:\Users\khoopes\AppData\Local\Continuum\anaconda2\lib\site-packages\joblib\parallel.py", line 996, in __call__
    self.retrieve()
  File "C:\Users\khoopes\AppData\Local\Continuum\anaconda2\lib\site-packages\joblib\parallel.py", line 899, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "C:\Users\khoopes\AppData\Local\Continuum\anaconda2\lib\site-packages\joblib\_parallel_backends.py", line 517, in wrap_future_result
    return future.result(timeout=timeout)
  File "C:\Users\khoopes\AppData\Local\Continuum\anaconda2\lib\site-packages\joblib\externals\loky\_base.py", line 433, in result
    return self.__get_result()
  File "C:\Users\khoopes\AppData\Local\Continuum\anaconda2\lib\site-packages\joblib\externals\loky\_base.py", line 381, in __get_result
    raise self._exception
TypeError: can't pickle AbstractState objects
```

**Comment by ogrisel** [comment]
joblib cannot work with process-based backends on unpicklable objects in arguments or return values of the function called in parallel.

Either use the threading backend or make your class `AbstractState` picklable by implementing `__getstate__` / `__setstate__` methods (or a `__reduce__` method):  https://docs.python.org/3.7/library/pickle.html#pickling-class-instances
