### ISSUE TITLE
joblib.load("model.pkl")   how can i solve it？

### ISSUE THREAD

**Issue by halxp1** [joblib/joblib#783]
/home/xipuhu/anaconda3/lib/python3.6/site-packages/sklearn/base.py:251: UserWarning: Trying to unpickle estimator TfidfTransformer from version 0.19.1 when using version 0.20.0. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
Traceback (most recent call last):
  File "main_predict.py", line 30, in <module>
    classifier_dict = joblib.load(config.model_save_path + model_name)
  File "/home/xipuhu/anaconda3/lib/python3.6/site-packages/sklearn/externals/joblib/numpy_pickle.py", line 598, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/home/xipuhu/anaconda3/lib/python3.6/site-packages/sklearn/externals/joblib/numpy_pickle.py", line 526, in _unpickle
    obj = unpickler.load()
  File "/home/xipuhu/anaconda3/lib/python3.6/pickle.py", line 1048, in load
    raise EOFError
EOFError

**Comment by halxp1** [comment]
and  my model.pkl  is 870MB size

**Comment by tomMoral** [comment]
Your saved model seems to be invalid.
We need more information to be able to help you.

How did you save your model and what type of model is this?
Also, with which version of `sklearn` did you save your model and with which version did you load it.
