### ISSUE TITLE
Failures occur when internal function is named `process`

### ISSUE THREAD

**Issue by msalib** [joblib/joblib#808]
Try running this test program both with and without --bug. The problem seems to be that joblib's internal objects are colliding with user defined code.

```
import sys
import joblib


USE_BAD_NAME = '--bug' in sys.argv


def proc(x):
    print(x)


def process(x):
    print(x)


def work(x):
    if USE_BAD_NAME:
        process(x)
    else:
        proc(x)


joblib.Parallel(-1)(joblib.delayed(work)(x) for x in range(50))
```

**Comment by tomMoral** [comment]
I can reproduce with the given script. I get the following error:

```python-traceback
$ python main.py --bug
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/tom/Work/prog/joblib/joblib/externals/loky/process_executor.py", line 418, in _process_worker
    r = call_item()
  File "/home/tom/Work/prog/joblib/joblib/externals/loky/process_executor.py", line 272, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/home/tom/Work/prog/joblib/joblib/_parallel_backends.py", line 567, in __call__
    return self.func(*args, **kwargs)
  File "/home/tom/Work/prog/joblib/joblib/parallel.py", line 225, in __call__
    for func, args, kwargs in self.items]
  File "/home/tom/Work/prog/joblib/joblib/parallel.py", line 225, in <listcomp>
    for func, args, kwargs in self.items]
  File "main.py", line 18, in work
    process(x)
TypeError: 'module' object is not callable
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 23, in <module>
    joblib.Parallel(-1)(joblib.delayed(work)(x) for x in range(50))
  File "/home/tom/Work/prog/joblib/joblib/parallel.py", line 930, in __call__
    self.retrieve()
  File "/home/tom/Work/prog/joblib/joblib/parallel.py", line 833, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/tom/Work/prog/joblib/joblib/_parallel_backends.py", line 521, in wrap_future_result
    return future.result(timeout=timeout)
  File "/home/tom/.local/miniconda/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/home/tom/.local/miniconda/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
TypeError: 'module' object is not callable
```

Thanks for reporting this.

**Comment by msalib** [comment]
Thanks for joblib! It makes our lives a lot easier!

**Comment by tomMoral** [comment]
After investigating, it seems that we have an interaction between the module used to launched the new process and the name of the function. It also fails for `util`, `reduction`, `spawn`, `signal` and `pickle`.

This is a regression as it was working previously with `parallel_backend('multiprocessing')`.

It is probably possible to mitigate that by reducing the number of loaded module and using them with extra `_` at the beginning.
