### ISSUE TITLE
joblib.Memory error in unpickling

### ISSUE THREAD

**Issue by amueller** [joblib/joblib#809]
I've been trying to cache results from google bigquery and ran int
```pythontb
WARNING:root:[MemorizedFunc(func=<bound method GithubPython.run of <odyssey.core.bigquery.GithubPython.GithubPython object at 0x7fb32c660d30>>, location=./joblib)]: Exception while loading results for run(('\n'
 '        SELECT\n'
 '            DISTINCT(repo_name)\n'
 '        FROM\n'
 '            sklearn_unique.nov_12_2018\n'
 '        WHERE\n'
 '            (REGEXP_CONTAINS(path,"")) OR (REGEXP_CONTAINS(repo_name,""))\n'
 '        '))
 Traceback (most recent call last):
  File "/home/andy/anaconda3/envs/py37/lib/python3.7/site-packages/joblib/memory.py", line 490, in _cached_call
    verbose=self._verbose)
  File "/home/andy/anaconda3/envs/py37/lib/python3.7/site-packages/joblib/_store_backends.py", line 171, in load_item
    item = numpy_pickle.load(f)
  File "/home/andy/anaconda3/envs/py37/lib/python3.7/site-packages/joblib/numpy_pickle.py", line 588, in load
    obj = _unpickle(fobj)
  File "/home/andy/anaconda3/envs/py37/lib/python3.7/site-packages/joblib/numpy_pickle.py", line 526, in _unpickle
    obj = unpickler.load()
  File "/home/andy/anaconda3/envs/py37/lib/python3.7/pickle.py", line 1085, in load
    dispatch[key[0]](self)
  File "/home/andy/anaconda3/envs/py37/lib/python3.7/site-packages/joblib/numpy_pickle.py", line 339, in load_build
    Unpickler.load_build(self)
  File "/home/andy/anaconda3/envs/py37/lib/python3.7/pickle.py", line 1547, in load_build
    setstate = getattr(inst, "__setstate__", None)
  File "/home/andy/anaconda3/envs/py37/lib/python3.7/site-packages/google/cloud/bigquery/table.py", line 1065, in __getattr__
    value = self._xxx_field_to_index.get(name)
  File "/home/andy/anaconda3/envs/py37/lib/python3.7/site-packages/google/cloud/bigquery/table.py", line 1065, in __getattr__
    value = self._xxx_field_to_index.get(name)
  File "/home/andy/anaconda3/envs/py37/lib/python3.7/site-packages/google/cloud/bigquery/table.py", line 1065, in __getattr__
    value = self._xxx_field_to_index.get(name)
  [Previous line repeated 1475 more times]
RecursionError: maximum recursion depth exceeded while calling a Python object
```

Has anyone seen anything like that? I'll try to get a minimum example

**Comment by GaelVaroquaux** [comment]
> I've been trying to cache results from google bigquery and ran int

Does the object pickle/unpickle with the standard-library pickler?

**Comment by amueller** [comment]
I can ``dump`` and ``load`` the object with joblib.

**Comment by amueller** [comment]
Not using ``Memory.cache`` that is.

**Comment by amueller** [comment]
Or did you mean can I open the ``output.pkl``? That's a joblib file, not a pickle file, right?

**Comment by amueller** [comment]
one of the input args is "self", is that the issue?

**Comment by GaelVaroquaux** [comment]
No, your answer answers my question. I was hoping that the unpickling
routine of the object was broken, but it seems it's not, and the bug is
on our side :).

**Comment by amueller** [comment]
I think the issue is actually the input parameters because I overwrote a method with a pickled version of itself. At least that's my guess.

**Comment by amueller** [comment]
aww that's not actually the case :-/ too bad.

**Comment by amueller** [comment]
```python
@memory.cache
def run_query(query, project):
    from google.cloud import bigquery
    job_config = bigquery.QueryJobConfig()
    client = bigquery.Client(project=project)
    result = client.query(query, job_config=job_config)
    job_config.allowLargeResults = True
    result.__done_timeout = 99999999
    return list(result)
```
this is the trouble maker.

**Comment by amueller** [comment]
The return object is a list of strings btw.

**Comment by amueller** [comment]
all my fault, sorry for wasting your time lol

**Comment by GaelVaroquaux** [comment]
Tell us more (what was the mistake, so that we learn to spot it).

**Comment by amueller** [comment]
Ok basically the return object was a bigquery object that contains lots of weird stuff. Trying to pickle it with pickle resulted in a pickle error that told me not to try and pickle this.
Basically I needed to convert it to something normal (like a pandas dataframe) which was pickle-able.
I guess one point of improvement would be to detect in joblib that this thing can't be pickled and then raise the same error that pickle raises. (it told me "client object can't be pickled").
