### ISSUE TITLE
loky TerminatedWorkerError

### ISSUE THREAD

**Issue by Dtsimpson1** [joblib/joblib#812]
I run a script with the parallel loop in it every 5 minutes to update some work assignments stored in the cloud. This needs to happen in real time so the script is set up in the task scheduler on a windows server. This needs to be a very fault tolerant script because an entire department runs on it.
 
I use Anaconda3 and have gotten this error with version 0.13.0 and 0.12.5 of joblib. 

Probably every other run of this script throws this exception (calling defs removed):
```
  File "C:\Workforce Scripts\MU_Sync.py", line 187, in syncCounty
    Parallel(n_jobs=n_jobs)(delayed(syncWorkOrderId)(workOrderId) for workOrderId in workOrderIds)
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\parallel.py", line 930, in __call__
    self.retrieve()
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\parallel.py", line 833, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\_parallel_backends.py", line 521, in wrap_future_result
    return future.result(timeout=timeout)
  File "C:\ProgramData\Anaconda3\lib\concurrent\futures\_base.py", line 432, in result
    return self.__get_result()
  File "C:\ProgramData\Anaconda3\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\externals\loky\_base.py", line 625, in _invoke_callbacks
    callback(self)
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\parallel.py", line 309, in __call__
    self.parallel.dispatch_next()
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\parallel.py", line 731, in dispatch_next
    if not self.dispatch_one_batch(self._original_iterator):
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\parallel.py", line 759, in dispatch_one_batch
    self._dispatch(tasks)
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\parallel.py", line 716, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\_parallel_backends.py", line 510, in apply_async
    future = self._workers.submit(SafeFunction(func))
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\externals\loky\reusable_executor.py", line 151, in submit
    fn, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\externals\loky\process_executor.py", line 1022, in submit
    raise self._flags.broken
joblib.externals.loky.process_executor.TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.
```

I could not find a reference to this issue anywhere else. Can someone help me figure out what is causing the issue so we can repair it? Let me know what else you need me to attach.

**Comment by tomMoral** [comment]
This is something that has happened with `loky` on appveyor (our closest access to window) but I think it was only due to the load of the machine. From time to time, one of the worker process terminates in an unusual way (No python error) and we have no way to recover from this state. As stated, the most probable cause is a segfault in the called function `syncWorkOrderId`, or a memory problem, where the OS kill the worker for taking to much memory.

It is hard to tell what goes wrong from the traceback you report as we need to see the internals of `syncWorkOrderId` to know what happens. But if it is due to `loky`, it is something needs to be fixed if possible so if you could craft a [minimal reproducing example](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports), it would be awesome!

**Comment by STHSF** [comment]
@tomMoral I have the same problem like @Dtsimpson1, here is my  code
```
class DiscussParser(object):
    def __init__(self):
        self.data_process = DataPressing()
        self.stop_words = load_stop_words()
        _, self.stocks_df = dicts.load_stock_data()

    def cut_process(self, text):
        tokenizer = Tokenizer(self.data_process, self.stop_words)
        text_list = tokenizer.token(text)
        stock_list = self.data_process.find_stocks(text_list, self.stocks_df)
        del tokenizer
        gc.collect()
        return stock_list

    def tmp_func(self, df):
        df['stock_list'] = df['text'].apply(self.cut_process)
        # return df[['xid', 'uid', 'stock_list', 'unix_time', 'information_dic']]
        return df

    def apply_parallel(self, df_grouped, func):
       ret_lst = Parallel(n_jobs=3)(delayed(func)(group) for name, group in df_grouped)

        return pd.concat(ret_lst)

    def run(self, target_df):
        df_grouped = target_df.groupby(target_df.index)
        res = self.apply_parallel(df_grouped, self.tmp_func)
        return res
```
I don't know what's wrong with it

**Comment by STHSF** [comment]
I test this code with small datasets, it has no problem, but when large datasets the problem occurred.

**Comment by eromoe** [comment]
Got similar problem on loky backend 
```
  File "/home/hadoop/miniconda3/envs/py3/lib/python3.6/site-packages/joblib/parallel.py", line 934, in __call__
    self.retrieve()
  File "/home/hadoop/miniconda3/envs/py3/lib/python3.6/site-packages/joblib/parallel.py", line 833, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/hadoop/miniconda3/envs/py3/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 521, in wrap_future_result
    return future.result(timeout=timeout)
  File "/home/hadoop/miniconda3/envs/py3/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/home/hadoop/miniconda3/envs/py3/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
joblib.externals.loky.process_executor.TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker. The exit codes of the workers are {SIGKILL(-9)}
Command exiting with ret '1'

```

**Comment by homwe** [comment]
i have the same error, have you solve the problem?

**Comment by csbrown** [comment]
@tomMoral you say "No python error".  Are you saying that this problem is not caused by a python error in the worker?  I am getting this error and am not sure where to start debugging.  If the error is not in my python code, then that would be useful information.

**Comment by tomMoral** [comment]
@csbrown This error should only be displayed when one of the worker in the `ProcessPoolExecutor` died in an unexpected way. This means that the worker got killed by something that `loky` does not know/control. All python `Error` should be catch by a try except block so it does not seem to come from such "python" error.

The main causes where we have seen this previously were:
- Segfaults in the worker. The worker dies in native code and the process immediately shutdown.
- Too high memory consumption. The worker is killed by the OS because it has a high memory usage.

But other things could cause this. To be able to debug this, I would need to have access to a reproducing example to dissect this. Let me know if I can help.

**Comment by bidhya** [comment]
I am also getting the same error: 
joblib.externals.loky.process_executor.TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.
The exit codes of the workers are {SIGKILL(-9)}

I am certain this is due to memory error because when I reduce the number of workers, the code succeeds. I am assuming this each worker will be allocated more memory (on average), and, hence the code succeeds.

Knowing this my question is How do I avoid this kind of error? Is there some flag I can pass through Parallel/delayed to make workers wait as some memory is released by other workers? 
Or perhaps restart the whole processing sequence (function) for the worker where it failed?

**Comment by JimMcDonough** [comment]
Anyone solved this yet?  I have the same issue.
joblib.externals.loky.process_executor.TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.

**Comment by drfraser** [comment]
I am getting this error (with SIGSEGV (-11)) consistently with this setup:

```>>> import sklearn; sklearn.show_versions()

System:
    python: 3.8.10 (default, May  8 2021, 03:07:44)  [Clang 8.0.0 (clang-800.0.42.1)]
executable: /Volumes/Phil/projects/research/holistic/venv/bin/python
   machine: macOS-10.11.6-x86_64-i386-64bit

Python dependencies:
          pip: 21.1
   setuptools: 41.2.0
      sklearn: 0.24.2
        numpy: 1.21.0
        scipy: 1.6.3
       Cython: 0.29.23
       pandas: 1.2.4
   matplotlib: 3.4.1
       joblib: 1.0.1
threadpoolctl: 2.1.0

Built with OpenMP: False
```
The backend being used is 'loky'
BaggingClassifier (default params & n_jobs=2)
SVC (default params & kernel: linear)
Just one particular set of train/test data (others I am using result in no problems)

If I change these parameters (only one each time) then there are no problems and program finishes correctly:
n_jobs -> 1             
kernel -> rbf 
backend -> threading

If I change the backend to 'multiprocessing', then everything hangs, have to Ctrl-C

I will update this issue with a backtrace from gdb, if I can get that to work. I will also try joblib 0.16.0

Below is the output when I Ctrl-C with backend of multiprocessing, in case it is useful:

Process SpawnPoolWorker-6:
Process SpawnPoolWorker-5:
Traceback (most recent call last):
  File "classify_docs.py", line 333, in <module>
    debug_experiment(args, featSet, experiment, target_col)
  File "classify_docs.py", line 224, in debug_experiment
    res = train_model(experiment.config, experiment.meta, featSet.feature_names,
  File "/Volumes/Phil/projects/research/holistic/src/holistic/models/classify.py", line 224, in train_model
    loop_res = perform_calcs(train_test, seed, clf_cfg, ensemble_cfg, conf['pp'], featnames)
  File "/Volumes/Phil/projects/research/holistic/src/holistic/models/classify.py", line 169, in perform_calcs
    predictions, the_scores = classify(eCLF, clf_cfg['label'], train_test)
  File "/Volumes/Phil/projects/research/holistic/src/holistic/models/classify.py", line 80, in classify
    predictions = CLF.predict(X_test)
  File "/Volumes/Phil/projects/research/holistic/venv/lib/python3.8/site-packages/sklearn/ensemble/_bagging.py", line 677, in predict
    predicted_probabilitiy = self.predict_proba(X)
  File "/Volumes/Phil/projects/research/holistic/venv/lib/python3.8/site-packages/sklearn/ensemble/_bagging.py", line 720, in predict_proba
    all_proba = Parallel(n_jobs=n_jobs, verbose=self.verbose,
  File "/Volumes/Phil/projects/research/holistic/venv/lib/python3.8/site-packages/joblib/parallel.py", line 1054, in __call__
    self.retrieve()
  File "/Volumes/Phil/projects/research/holistic/venv/lib/python3.8/site-packages/joblib/parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/pool.py", line 765, in get
    self.wait(timeout)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/pool.py", line 762, in wait
    self._event.wait(timeout)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 558, in wait
    signaled = self._cond.wait(timeout)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 302, in wait
    waiter.acquire()
KeyboardInterrupt

**Comment by drfraser** [comment]
Here is what I get out of gdb when using 'loky' and n_jobs>1:  I am sure a lack of RAM is not the issue.

  File "/Volumes/Phil/projects/research/holistic/venv/lib/python3.8/site-packages/sklearn/ensemble/_bagging.py", line 677, in predict
    predicted_probabilitiy = self.predict_proba(X)
  File "/Volumes/Phil/projects/research/holistic/venv/lib/python3.8/site-packages/sklearn/ensemble/_bagging.py", line 720, in predict_proba
    all_proba = Parallel(n_jobs=n_jobs, verbose=self.verbose,
  File "/Volumes/Phil/projects/research/holistic/venv/lib/python3.8/site-packages/joblib/parallel.py", line 1054, in __call__
    self.retrieve()
  File "/Volumes/Phil/projects/research/holistic/venv/lib/python3.8/site-packages/joblib/parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/Volumes/Phil/projects/research/holistic/venv/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
joblib.externals.loky.process_executor.TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.

The exit codes of the workers are {SIGSEGV(-11)}
[Inferior 1 (process 83800) exited with code 01]

**Comment by drfraser** [comment]
I patched sklearn's _bagging.py / _parallel_predict_proba()  to use faulthandler to dump tracebacks to a file so that the worker processes that die could output some information.

Fatal Python error: Segmentation fault
Current thread 0x00000001113b6000 (most recent call first):
  File "/Volumes/Phil/projects/research/holistic/venv/lib/python3.8/site-packages/sklearn/svm/_base.py", line 361 in _dense_predict
  File "/Volumes/Phil/projects/research/holistic/venv/lib/python3.8/site-packages/sklearn/svm/_base.py", line 344 in predict
  File "/Volumes/Phil/projects/research/holistic/venv/lib/python3.8/site-packages/sklearn/svm/_base.py", line 624 in predict
  File "/Volumes/Phil/projects/research/holistic/venv/lib/python3.8/site-packages/sklearn/ensemble/_bagging.py", line 145 in _parallel_predict_proba
  File "/Volumes/Phil/projects/research/holistic/venv/lib/python3.8/site-packages/sklearn/utils/fixes.py", line 222 in __call__
  File "/Volumes/Phil/projects/research/holistic/venv/lib/python3.8/site-packages/joblib/parallel.py", line 262 in <listcomp>
  File "/Volumes/Phil/projects/research/holistic/venv/lib/python3.8/site-packages/joblib/parallel.py", line 262 in __call__
  File "/Volumes/Phil/projects/research/holistic/venv/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 595 in __call__
  File "/Volumes/Phil/projects/research/holistic/venv/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py", line 285 in __call__
  File "/Volumes/Phil/projects/research/holistic/venv/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py", line 431 in _process_worker
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 108 in run
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 315 in _bootstrap
  File "/Volumes/Phil/projects/research/holistic/venv/lib/python3.8/site-packages/joblib/externals/loky/backend/popen_loky_posix.py", line 203 in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 87 in _run_code
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 194 in _run_module_as_main


So the fundamental problem looks to be in sklearn's SVM - the train/test data I am using is sparse (I think) so seeing the last line refer to _dense_predict gives me a clue as to what is happening.  I assume the segfault shouldn't happen at all, so this is not an issue with joblib per se, and it (with loky) is working as intended. With multiprocessing, I guess both child processes fall over and thus execution gets suspended.

Hopefully what I've written up helps someone else determine where their segfault is happening and why.

**Comment by LJingnan** [comment]
I solved this problem by setting  max_nbytes=5000(large number), like
`Parallel(n_jobs=n_cpu, max_nbytes=5000)`

**Comment by holderhe** [comment]
> 

same error. realy appreciate if there is a flag to make workers wait as some memory is released by other workers.
