### ISSUE TITLE
Fall back to serial mode does not work in current version

### ISSUE THREAD

**Issue by mhsmith** [joblib/joblib#825]
Android does not have a functioning sem_open implementation, so I receive the following warning as expected:

```
_multiprocessing_helpers.py:38: UserWarning: This platform lacks a functioning sem_open implementation, therefore, the required synchronization primitives needed will not function, see issue 3770..  joblib will operate in serial mode
```

With joblib 0.11, the import still succeeds. But with joblib 0.13.0 it fails, because joblib unconditionally imports loky, which unconditionally imports multiprocessing.synchronize.

Traceback from https://github.com/chaquo/chaquopy/issues/21 (edited for clarity):
```
 File "/android_asset/chaquopy/requirements-common.zip/joblib/__init__.py", line 119, in <module>
    from .parallel import Parallel
  File "/android_asset/chaquopy/requirements-common.zip/joblib/parallel.py", line 33, in <module>
    from .externals import loky
  File "/android_asset/chaquopy/requirements-common.zip/joblib/externals/loky/__init__.py", line 11, in <module>
    from .backend.context import cpu_count
  File "/android_asset/chaquopy/requirements-common.zip/joblib/externals/loky/backend/__init__.py", line 13, in <module>
    from multiprocessing import synchronize
  File "stdlib/multiprocessing/synchronize.py", line 34, in <module>
ImportError: This platform lacks a functioning sem_open implementation, therefore, the required synchronization primitives needed will not function, see issue 3770.

```

**Comment by maxgerhardt** [comment]
This prevents `joblib` from working in a Cygwin shell environment, e.g. in sagemath, where parallelization is really important.

**Comment by mhsmith** [comment]
This workaround will allow the import to complete:

```
import _multiprocessing
_multiprocessing.sem_unlink = None
```

Of course, process-based parallelism will still not work if the underlying platform doesn't support it, so you'll have to use the `parallel_backend` context manager to use thread-based parallelism instead.

**Comment by thebestnom** [comment]
@mhsmith tried the workaround and it didn't work, can you help?

**Comment by mhsmith** [comment]
If you're using Chaquopy, please post:
* Your error message
* What version of Chaquopy and joblib you're using
* If possible, a minimal test case.

If you're using some other platform, then I'm afraid I can't help you - I don't really know much about joblib's internals.

**Comment by thebestnom** [comment]
Well, im using latest joblib (0.14.1) on termux (android) which does not support semaphores, and the error is exact same as yours (I'm guessing you can't help but I'm putting it here anyway for reference for future help)
 `import joblib` is enough
```
/data/data/com.termux/files/home/env/lib/python3.8/site-packages/joblib/_multiprocessing_helpers.py:53: UserWarning: cannot import name 'SemLock' from '_multiprocessing' (/data/data/com.termux/files/usr/lib/python3.8/lib-dynload/_multiprocessing.cpython-38.so).  joblib will operate in serial mode
  warnings.warn('%s.  joblib will operate in serial mode' % (e,))
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/synchronize.py", line 28, in <module>
    from _multiprocessing import SemLock, sem_unlink
ImportError: cannot import name 'SemLock' from '_multiprocessing' (/data/data/com.termux/files/usr/lib/python3.8/lib-dynload/_multiprocessing.cpython-38.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/data/com.termux/files/home/env/lib/python3.8/site-packages/joblib/__init__.py", line 120, in <module>
    from .parallel import Parallel
  File "/data/data/com.termux/files/home/env/lib/python3.8/site-packages/joblib/parallel.py", line 31, in <module>
    from .externals import loky
  File "/data/data/com.termux/files/home/env/lib/python3.8/site-packages/joblib/externals/loky/__init__.py", line 11, in <module>
    from .backend.context import cpu_count
  File "/data/data/com.termux/files/home/env/lib/python3.8/site-packages/joblib/externals/loky/backend/__init__.py", line 13, in <module>
    from multiprocessing import synchronize
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/synchronize.py", line 30, in <module>
    raise ImportError("This platform lacks a functioning sem_open" +
ImportError: This platform lacks a functioning sem_open implementation, therefore, the required synchronization primitives needed will not function, see issue 3770.
```

**Comment by jrgriffiniii** [comment]
Perhaps errors here be handled slightly differently? https://github.com/joblib/joblib/blob/master/joblib/externals/loky/backend/__init__.py#L13

https://github.com/joblib/joblib/blob/master/joblib/externals/loky/backend/__init__.py#L6 leads me to believe that gracefully handling cases where `loky` is kept unused doesn't break any functionality elsewhere.

**Comment by jrgriffiniii** [comment]
I've been experimenting starting with https://github.com/joblib/joblib/compare/master...jrgriffiniii:issues-825-jrgriffiniii-no-sem-support, and I'm basically finding that these classes essentially hard-code the usage of semaphores into this package: https://github.com/joblib/joblib/blob/master/joblib/externals/loky/backend/synchronize.py#L131 and https://github.com/joblib/joblib/blob/master/joblib/externals/loky/backend/synchronize.py#L153

I speculate that there are alternate implementations which could be proposed, but I am unfortunately not the position to offer anything useful there.

**Comment by jrgriffiniii** [comment]
https://github.com/joblib/joblib/pull/999 worked for me with the latest release of `scikit-learn` in an Android environment over termux (the logging is just awful, and I need to improve the PR).

**Comment by mhsmith** [comment]
Chaquopy 8.0.1 now has a workaround for this problem. Process-based parallelism is still unavailable, but joblib can at least be imported, and then you can use the `parallel_backend` context manager to use thread-based parallelism instead.

To upgrade, edit your app's top-level build.gradle file and change the version number of `com.chaquo.python:gradle`.
