### ISSUE TITLE
Error while using n_jobs=-1 with uwsgi

### ISSUE THREAD

**Issue by manishprasadthapliyal** [joblib/joblib#827]
Hi I am using sklearn n_jobs = -1 for multi process training of my model but i am getting below error.

sklearn.externals.joblib.externals.loky.process_executor.TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker. The exit codes of the workers are {EXIT(1), EXIT(1), EXIT(1)}

**Comment by rth** [comment]
As mentionned by @adrinjalali in https://github.com/scikit-learn/scikit-learn/issues/12922

> Could you please also include a minimal and reproducible example for us to better diagnose the problem?

An example that only involves joblib parallel would help.

Support for multiprocessing backend when used in uwsgi was fixed in https://github.com/joblib/joblib/issues/180. Using that backend might solve this issue for you, but fixing this in loky would also be useful (if the issue is confirmed).

Also in the future, if you do open the same issue in different repositories, it's preferable to link them.

**Comment by manishprasadthapliyal** [comment]
I am not using Joblib parallel.
i am using it with GridSearchCV and other sklearn algorithms like LogisticRegression etc.
` gs_clf = GridSearchCV(text_clf, classifier_param, cv = 2, n_jobs=-1)`

`uwsgi --http-socket :9999 --master --workers 4 --threads 1 --wsgi-file main.py --enable-threads`

**Comment by GaelVaroquaux** [comment]
> i am using it with GridSearchCV and other sklearn algorithms like LogisticRegression etc.

All these use internally Joblib parallel.

**Comment by manishprasadthapliyal** [comment]
Sorry to bother again, Is there a way i can use n_jobs=-1 with uWSGI without any error? some other way to run training in multi-processing?

**Comment by neeraj1928** [comment]
are we able to find any solution for this issue. I am also getting similar error but kith a different exit code. Here **sklearn.decomposition.LatentDirichLetAllocation** is used and using n_jobs parallelization is achieved. Also **joblib** is using **locky** as a backend.
Below is the error message which I am getting.
sklearn.externals.joblib.externals.loky.process_executor.TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker. The exit codes of the workers are {SIGKILL(-9)}

**Comment by ogrisel** [comment]
@neeraj1928 are you using uwsgi? If not this is probably an unrelated problem. Please open a dedicated issue with a minimal reproduction example.

**Comment by ogrisel** [comment]
I can reproduce this issue with just uwsgi:

First build uwsgi with clang because it's buggy with recent versions of gcc:

```bash
CC=clang-7 pip install uwsgi
```

Then define a joblib-enabled uswgi implementation in a file named "joblib_application.py" with the following content:

```python
from joblib import Parallel, delayed

def application(env, start_response):
    start_response('200 OK', [('Content-Type','text/html')])
    results = Parallel(n_jobs=-1)(
        delayed(lambda x: x ** 2)(i) for i in range(1000))
````

Finally start the uswgi server:

```
$ uwsgi --http-socket :9999 --master --workers 4 --threads 1 --wsgi-file joblib_application.py --enable-threads
*** Starting uWSGI 2.0.18 (64bit) on [Fri Apr 19 16:11:28 2019] ***
compiled with version: 4.2.1 Compatible Clang 7.0.0 (tags/RELEASE_700/final) on 19 April 2019 14:02:41
os: Linux-4.18.0-17-generic #18~18.04.1-Ubuntu SMP Fri Mar 15 15:27:12 UTC 2019
nodename: ici
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /home/ogrisel/draft
detected binary path: /home/ogrisel/miniconda3/envs/pip/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
your processes number limit is 62329
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :9999 fd 3
Python version: 3.7.3 (default, Mar 27 2019, 22:11:17)  [GCC 7.3.0]
Python main interpreter initialized at 0x1fab450
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 364520 bytes (355 KB) for 4 cores
*** Operational MODE: preforking ***
unable to load configuration from from multiprocessing.semaphore_tracker import main;main(13)
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x1fab450 pid: 15710 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 15710)
spawned uWSGI worker 1 (pid: 15715, cores: 1)
spawned uWSGI worker 2 (pid: 15716, cores: 1)
spawned uWSGI worker 3 (pid: 15717, cores: 1)
spawned uWSGI worker 4 (pid: 15718, cores: 1)
subprocess 15714 exited with code 1
```

Navigating to http://localhost:9999 in your browser should trigger the crash in loky:

```bash
unable to load configuration from from joblib.externals.loky.backend.semaphore_tracker import main; main(6)
Fri Apr 19 16:25:09 2019 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) on request / (ip 127.0.0.1) !!!
/home/ogrisel/miniconda3/envs/pip/lib/python3.7/site-packages/joblib/externals/loky/backend/semaphore_tracker.py:74: UserWarning: semaphore_tracker: process died unexpectedly, relaunching.  Some semaphores might leak.
  warnings.warn('semaphore_tracker: process died unexpectedly, '
/home/ogrisel/miniconda3/envs/pip/bin/uwsgi: unrecognized option '--process-name'
getopt_long() error
unable to load configuration from from joblib.externals.loky.backend.semaphore_tracker import main; main(7)
Fri Apr 19 16:25:09 2019 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) on request / (ip 127.0.0.1) !!!
/home/ogrisel/miniconda3/envs/pip/bin/uwsgi: unrecognized option '--process-name'
getopt_long() error
unable to load configuration from from joblib.externals.loky.backend.semaphore_tracker import main; main(18)
/home/ogrisel/miniconda3/envs/pip/bin/uwsgi: unrecognized option '--process-name'
getopt_long() error
/home/ogrisel/miniconda3/envs/pip/bin/uwsgi: unrecognized option '--process-name'
getopt_long() error
exception calling callback for <Future at 0x7f05008875f8 state=finished raised TerminatedWorkerError>
Traceback (most recent call last):
  File "/home/ogrisel/miniconda3/envs/pip/lib/python3.7/site-packages/joblib/externals/loky/_base.py", line 625, in _invoke_callbacks
    callback(self)
  File "/home/ogrisel/miniconda3/envs/pip/lib/python3.7/site-packages/joblib/parallel.py", line 309, in __call__
    self.parallel.dispatch_next()
  File "/home/ogrisel/miniconda3/envs/pip/lib/python3.7/site-packages/joblib/parallel.py", line 731, in dispatch_next
    if not self.dispatch_one_batch(self._original_iterator):
  File "/home/ogrisel/miniconda3/envs/pip/lib/python3.7/site-packages/joblib/parallel.py", line 759, in dispatch_one_batch
    self._dispatch(tasks)
  File "/home/ogrisel/miniconda3/envs/pip/lib/python3.7/site-packages/joblib/parallel.py", line 716, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/home/ogrisel/miniconda3/envs/pip/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 510, in apply_async
    future = self._workers.submit(SafeFunction(func))
  File "/home/ogrisel/miniconda3/envs/pip/lib/python3.7/site-packages/joblib/externals/loky/reusable_executor.py", line 151, in submit
    fn, *args, **kwargs)
  File "/home/ogrisel/miniconda3/envs/pip/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 1022, in submit
    raise self._flags.broken
joblib.externals.loky.process_executor.TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker. The exit codes of the workers are {EXIT(1), EXIT(1), EXIT(1), EXIT(1)}
Fri Apr 19 16:25:09 2019 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) on request / (ip 127.0.0.1) !!!
/home/ogrisel/miniconda3/envs/pip/lib/python3.7/site-packages/joblib/externals/loky/backend/semaphore_tracker.py:74: UserWarning: semaphore_tracker: process died unexpectedly, relaunching.  Some semaphores might leak.
  warnings.warn('semaphore_tracker: process died unexpectedly, '
unable to load configuration from from joblib.externals.loky.backend.semaphore_tracker import main; main(19)
Fri Apr 19 16:25:09 2019 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) on request / (ip 127.0.0.1) !!!
/home/ogrisel/miniconda3/envs/pip/lib/python3.7/site-packages/joblib/externals/loky/backend/semaphore_tracker.py:74: UserWarning: semaphore_tracker: process died unexpectedly, relaunching.  Some semaphores might leak.
  warnings.warn('semaphore_tracker: process died unexpectedly, '
unable to load configuration from from joblib.externals.loky.backend.semaphore_tracker import main; main(18)
Fri Apr 19 16:25:09 2019 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) on request / (ip 127.0.0.1) !!!
/home/ogrisel/miniconda3/envs/pip/lib/python3.7/site-packages/joblib/externals/loky/backend/semaphore_tracker.py:74: UserWarning: semaphore_tracker: process died unexpectedly, relaunching.  Some semaphores might leak.
  warnings.warn('semaphore_tracker: process died unexpectedly, '
unable to load configuration from from joblib.externals.loky.backend.semaphore_tracker import main; main(7)
Traceback (most recent call last):
  File "joblib_application.py", line 7, in application
    delayed(lambda x: x ** 2)(i) for i in range(1000))
  File "/home/ogrisel/miniconda3/envs/pip/lib/python3.7/site-packages/joblib/parallel.py", line 934, in __call__
    self.retrieve()
  File "/home/ogrisel/miniconda3/envs/pip/lib/python3.7/site-packages/joblib/parallel.py", line 833, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/ogrisel/miniconda3/envs/pip/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 521, in wrap_future_result
    return future.result(timeout=timeout)
  File "/home/ogrisel/miniconda3/envs/pip/lib/python3.7/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/home/ogrisel/miniconda3/envs/pip/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/ogrisel/miniconda3/envs/pip/lib/python3.7/site-packages/joblib/externals/loky/_base.py", line 625, in _invoke_callbacks
    callback(self)
  File "/home/ogrisel/miniconda3/envs/pip/lib/python3.7/site-packages/joblib/parallel.py", line 309, in __call__
    self.parallel.dispatch_next()
  File "/home/ogrisel/miniconda3/envs/pip/lib/python3.7/site-packages/joblib/parallel.py", line 731, in dispatch_next
    if not self.dispatch_one_batch(self._original_iterator):
  File "/home/ogrisel/miniconda3/envs/pip/lib/python3.7/site-packages/joblib/parallel.py", line 759, in dispatch_one_batch
    self._dispatch(tasks)
  File "/home/ogrisel/miniconda3/envs/pip/lib/python3.7/site-packages/joblib/parallel.py", line 716, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/home/ogrisel/miniconda3/envs/pip/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 510, in apply_async
    future = self._workers.submit(SafeFunction(func))
  File "/home/ogrisel/miniconda3/envs/pip/lib/python3.7/site-packages/joblib/externals/loky/reusable_executor.py", line 151, in submit
    fn, *args, **kwargs)
  File "/home/ogrisel/miniconda3/envs/pip/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 1022, in submit
    raise self._flags.broken
joblib.externals.loky.process_executor.TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker. The exit codes of the workers are {EXIT(1), EXIT(1), EXIT(1), EXIT(1)}
[pid: 15717|app: 0|req: 1/1] 127.0.0.1 () {36 vars in 784 bytes} [Fri Apr 19 16:25:09 2019] GET / => generated 0 bytes in 168 msecs (HTTP/1.1 200) 1 headers in 44 bytes (0 switches on core 0)

```

**Comment by ogrisel** [comment]
Reading this message makes me think that we can report the issue upstream with a minimal reproduction example just for loky that does not even depend on joblib.

**Comment by neeraj1928** [comment]
> @neeraj1928 are you using uwsgi? If not this is probably an unrelated problem. Please open a dedicated issue with a minimal reproduction example.

No, I am not using uwsgi. Sure, I'll open a dedicated issue. Thanks

**Comment by ogrisel** [comment]
I opened https://github.com/tomMoral/loky/issues/207 in loky with a minimal reproduction case.
