### ISSUE TITLE
'numpy.ndarray' object has no attribute 'offset' (memmap)

### ISSUE THREAD

**Issue by saimn** [joblib/joblib#839]
Hi,

I get an error, (similar to #161 but with Python 3.7, Numpy 1.16, Joblib 0.13.1), while serializing memmap arrays (traceback below).

This arrays is read with `astropy.io.fits`, which was using `np.memmap` but switch to using `mmap.mmap` directly (https://github.com/astropy/astropy/pull/7597, this may explain why I never encountered this error before). So basically the array is constructed like this:
```
self._mmap = mmap.mmap(self._file.fileno(), 0, access=access_mode, offset=0)
np.ndarray(shape=shape, dtype=dtype, offset=offset, buffer=self._mmap)
```
(https://github.com/astropy/astropy/blob/master/astropy/io/fits/file.py#L309-L334)

And then the array does not have an `.offset` attribute, which is specific to `np.memmap`. 
So I think that it should be safe to check this exception and use 0 as a default value for offset ?

```
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/simon/.pyenv/versions/3.7.2/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 344, in _sendback_result
    exception=exception))
  File "/home/simon/.pyenv/versions/3.7.2/lib/python3.7/site-packages/joblib/externals/loky/backend/queues.py", line 234, in put
    obj = dumps(obj, reducers=self._reducers)
  File "/home/simon/.pyenv/versions/3.7.2/lib/python3.7/site-packages/joblib/externals/loky/backend/reduction.py", line 243, in dumps
    dump(obj, buf, reducers=reducers, protocol=protocol)
  File "/home/simon/.pyenv/versions/3.7.2/lib/python3.7/site-packages/joblib/externals/loky/backend/reduction.py", line 236, in dump
    _LokyPickler(file, reducers=reducers, protocol=protocol).dump(obj)
  File "/home/simon/.pyenv/versions/3.7.2/lib/python3.7/site-packages/joblib/externals/cloudpickle/cloudpickle.py", line 284, in dump
    return Pickler.dump(self, obj)
  File "/home/simon/.pyenv/versions/3.7.2/lib/python3.7/pickle.py", line 437, in dump
    self.save(obj)
  File "/home/simon/.pyenv/versions/3.7.2/lib/python3.7/pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "/home/simon/.pyenv/versions/3.7.2/lib/python3.7/pickle.py", line 662, in save_reduce
    save(state)
  File "/home/simon/.pyenv/versions/3.7.2/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/simon/.pyenv/versions/3.7.2/lib/python3.7/pickle.py", line 856, in save_dict
    self._batch_setitems(obj.items())
  File "/home/simon/.pyenv/versions/3.7.2/lib/python3.7/pickle.py", line 882, in _batch_setitems
    save(v)
  File "/home/simon/.pyenv/versions/3.7.2/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/simon/.pyenv/versions/3.7.2/lib/python3.7/pickle.py", line 816, in save_list
    self._batch_appends(obj)
  File "/home/simon/.pyenv/versions/3.7.2/lib/python3.7/pickle.py", line 843, in _batch_appends
    save(tmp[0])
  File "/home/simon/.pyenv/versions/3.7.2/lib/python3.7/pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "/home/simon/.pyenv/versions/3.7.2/lib/python3.7/pickle.py", line 662, in save_reduce
    save(state)
  File "/home/simon/.pyenv/versions/3.7.2/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/simon/.pyenv/versions/3.7.2/lib/python3.7/pickle.py", line 856, in save_dict
    self._batch_setitems(obj.items())
  File "/home/simon/.pyenv/versions/3.7.2/lib/python3.7/pickle.py", line 882, in _batch_setitems
    save(v)
  File "/home/simon/.pyenv/versions/3.7.2/lib/python3.7/pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "/home/simon/.pyenv/versions/3.7.2/lib/python3.7/pickle.py", line 662, in save_reduce
    save(state)
  File "/home/simon/.pyenv/versions/3.7.2/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/simon/.pyenv/versions/3.7.2/lib/python3.7/pickle.py", line 856, in save_dict
    self._batch_setitems(obj.items())
  File "/home/simon/.pyenv/versions/3.7.2/lib/python3.7/pickle.py", line 882, in _batch_setitems
    save(v)
  File "/home/simon/.pyenv/versions/3.7.2/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/simon/.pyenv/versions/3.7.2/lib/python3.7/pickle.py", line 856, in save_dict
    self._batch_setitems(obj.items())
  File "/home/simon/.pyenv/versions/3.7.2/lib/python3.7/pickle.py", line 882, in _batch_setitems
    save(v)
  File "/home/simon/.pyenv/versions/3.7.2/lib/python3.7/pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "/home/simon/.pyenv/versions/3.7.2/lib/python3.7/pickle.py", line 662, in save_reduce
    save(state)
  File "/home/simon/.pyenv/versions/3.7.2/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/simon/.pyenv/versions/3.7.2/lib/python3.7/pickle.py", line 856, in save_dict
    self._batch_setitems(obj.items())
  File "/home/simon/.pyenv/versions/3.7.2/lib/python3.7/pickle.py", line 882, in _batch_setitems
    save(v)
  File "/home/simon/.pyenv/versions/3.7.2/lib/python3.7/pickle.py", line 510, in save
    rv = reduce(obj)
  File "/home/simon/.pyenv/versions/3.7.2/lib/python3.7/site-packages/joblib/_memmapping_reducer.py", line 304, in __call__
    return _reduce_memmap_backed(a, m)
  File "/home/simon/.pyenv/versions/3.7.2/lib/python3.7/site-packages/joblib/_memmapping_reducer.py", line 218, in _reduce_memmap_backed
    offset += m.offset
AttributeError: 'numpy.ndarray' object has no attribute 'offset'
"""
```

**Comment by saimn** [comment]
There is the same issue with `.mode` and `.filename`, which are also specific to `np.memmap`. Not sure if an array directly using `mmap.mmap` can be supported the same way, since the filename is not available.

**Comment by zaccharieramzi** [comment]
I have the exact same error using also an array read with `astropy.io.fits`.

My current quick-fix is to change the array type to `float32` inplace.
So basically I do something like:
```python
arr = astropy.io.fits.getdata(file_mr)
arr.astype('float32', copy=False)
```

[I saw](https://github.com/joblib/joblib/pull/853#issuecomment-478887822) that you were copying the data each time. If memory is a concern, this could be helpful. However, it will still take time.
