### ISSUE TITLE
joblib not found when Parallel is executed inside a pex

### ISSUE THREAD

**Issue by yetanotherion** [joblib/joblib#849]
Trying to package joblib inside a pex, executing the script
```bash
#!/bin/bash
python3.6 -m venv .
. bin/activate
# gets pip 19.0.3
pip install --upgrade pip
pip install pex
pex joblib -o ./pex
cat <<EOF > test.py
from joblib import Parallel, delayed

def func(k):
    return k

jobs = (delayed(func)(k) for k in range(2))
print(Parallel(n_jobs=2)(jobs))

EOF
deactivate
./pex test.py

```
Raises
```
Traceback (most recent call last):
  ...
  File "test.py", line 7, in <module>
    print(Parallel(n_jobs=2)(jobs))
  File "/Users/j.alberdi/.pex/install/joblib-0.13.2-py2.py3-none-any.whl.71f5159401747e872566d2974ae0d2afcc42332d/joblib-0.13.2-py2.py3-none-any.whl/joblib/parallel.py", line 934, in __call__
    self.retrieve()
  File "/Users/j.alberdi/.pex/install/joblib-0.13.2-py2.py3-none-any.whl.71f5159401747e872566d2974ae0d2afcc42332d/joblib-0.13.2-py2.py3-none-any.whl/joblib/parallel.py", line 833, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/Users/j.alberdi/.pex/install/joblib-0.13.2-py2.py3-none-any.whl.71f5159401747e872566d2974ae0d2afcc42332d/joblib-0.13.2-py2.py3-none-any.whl/joblib/_parallel_backends.py", line 521, in wrap_future_result
    return future.result(timeout=timeout)
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
joblib.externals.loky.process_executor.TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker. The exit codes of the workers are {EXIT(1)}
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'joblib'
```
It can be noticed that 
* `from joblib import Parallel, delayed` does not raise anything
* the execution of the line `Parallel(n_jobs=2)(jobs)` raises the exception

To test the procedure to build a pex, the following test with requests runs fine
```bash
#!/bin/bash
python3.6 -m venv .
. bin/activate
pip install --upgrade pip

pip install pex
pex requests -o ./pex
cat <<EOF > test.py
import requests

print(requests.get("http://www.google.fr"))

EOF
deactivate
./pex test.py
```

```
<Response [200]>
```

Similarly, the script
```bash
#!/bin/bash
# python3.7 works too
python3.6 -m venv .
. bin/activate
pip install --upgrade pip
pip install pex joblib
pex joblib -o ./pex
cat <<EOF > test.py
from joblib import Parallel, delayed

def func(k):
    return k

jobs = (delayed(func)(k) for k in range(2))
print(Parallel(n_jobs=2)(jobs))

EOF
#deactivate
./pex test.py
```
Outputs the expected
```
[0, 1]
```
However
* `pip install joblib` and more importantly
* `#deactivate`

should be removed to ensure the pex could be deployed somewhere else.

Any hints on the root cause would be very welcome.

**Comment by yetanotherion** [comment]
@jsirois found that the bug is in the *loky* backend (the bug is not reproduced using the *multiprocessing* backend).
https://github.com/pantsbuild/pex/issues/675#issuecomment-466075996
>The problem seems to lie here:
https://github.com/joblib/joblib/blob/a99273bb0fe1d77c5e5b1b5512c6a9fa1285a125/joblib/externals/loky/backend/popen_loky_posix.py#L144-L155

>Worker processes are spawned using sys.executable but sys.path is not passed on (e.g. via altering the PYTHONPATH via os.execve - instead os.execv is used). Since a pex alters the sys.path at runtime (on boot) instead of using the standard sys.executable sys.path construction - this leads to the problem you observe of spawned jobs not being able to find the dependencies contained within the original pex.

>If I hand-hack popen_loky_posix.py to `os.environ['PYTHONPATH'] = os.pathsep.join(sys.path)` before calling `fork_exec` in the snippet pointed to above, ie:

>I then get partial success:

What are you thoughts regarding refactoring the way worker processes are spawned, to be able to use the loky backend in a pex? (I'd like to have feedbacks before trying to propose a fix)

**Comment by tomMoral** [comment]
Sorry I just noticed this discussion.

I am currently making some changes in `loky` to better support environment variables and I am planning to switch to `os.execve` in `popen_loky_posix.py`. If I understand correctly, you would like to pass the value of `sys.path` as an environment variable in `PYTHONPATH`?

Also, I noticed that you seem to have issues with named semaphores. I don't know the pex sytem but is it possible that it creates permission issues with the semaphores?

**Comment by jsirois** [comment]
> I am currently making some changes in loky to better support environment variables and I am planning to switch to os.execve in popen_loky_posix.py. If I understand correctly, you would like to pass the value of sys.path as an environment variable in PYTHONPATH?

Exactly.

For example, in `multiprocessing` when `spawn` mode is used the `sys.path` is passed in a pickle and re-established from it here: https://github.com/python/cpython/blob/9ffca670ed4df42eb256e7144619a9d3a830e7c0/Lib/multiprocessing/spawn.py#L218-L219 Passing `sys.path` via `PYTHONPATH` in `popen_loky_posix.py` would be similar in spirit.

**Comment by goyalankit** [comment]
Is there any update on this issue? We are hitting the same issue with https://github.com/linkedin/shiv which works similarly to pex. Curious if there any workarounds?

**Comment by thundergolfer** [comment]
We're also experiencing this issue with https://github.com/google/subpar which is similar to both Pex and Linkedin/Shiv.

**Comment by ptuls** [comment]
Has there been an update on this issue?

**Comment by tayrinedias** [comment]
Hi, is there any update on this issue? I am trying to run BERTopic and HDBSCAN and I have been running into this issue.

Code:

`umap_model = UMAP(n_neighbors=15,n_components=5,min_dist=0.0,metric='cosine',random_state=100,low_memory=True)`

Initiate BERTopic
`topic_model = BERTopic(umap_model=umap_model, language="english", calculate_probabilities=True)`

Run BERTopic model
```
dfred = df[0:20000]
topics, probabilities = topic_model.fit_transform(dfred['text'])
```

Error:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'loky'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'joblib'
/Users/x/miniconda3/envs/spyderenv/bin/python: Error while finding module specification for 'loky.backend.popen_loky_posix' (ModuleNotFoundError: No module named 'loky')
/Users/x/miniconda3/envs/spyderenv/bin/python: Error while finding module specification for 'loky.backend.popen_loky_posix' (ModuleNotFoundError: No module named 'loky')
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'loky'
/Users/x/miniconda3/envs/spyderenv/bin/python: Error while finding module specification for 'loky.backend.popen_loky_posix' (ModuleNotFoundError: No module named 'loky')
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'loky'
Traceback (most recent call last):

  Cell In[43], line 3
    topics, probabilities = topic_model.fit_transform(dfred['text'])

  File ~/miniconda3/envs/spyderenv/lib/python3.9/site-packages/bertopic/_bertopic.py:359 in fit_transform
    documents, probabilities = self._cluster_embeddings(umap_embeddings, documents, y=y)

  File ~/miniconda3/envs/spyderenv/lib/python3.9/site-packages/bertopic/_bertopic.py:2903 in _cluster_embeddings
    self.hdbscan_model.fit(umap_embeddings, y=y)

  File ~/miniconda3/envs/spyderenv/lib/python3.9/site-packages/hdbscan/hdbscan_.py:1190 in fit
    ) = hdbscan(clean_data, **kwargs)

  File ~/miniconda3/envs/spyderenv/lib/python3.9/site-packages/hdbscan/hdbscan_.py:822 in hdbscan
    (single_linkage_tree, result_min_span_tree) = memory.cache(

  File ~/miniconda3/envs/spyderenv/lib/python3.9/site-packages/joblib/memory.py:349 in __call__
    return self.func(*args, **kwargs)

  File ~/miniconda3/envs/spyderenv/lib/python3.9/site-packages/hdbscan/hdbscan_.py:325 in _hdbscan_boruvka_kdtree
    alg = KDTreeBoruvkaAlgorithm(

  File hdbscan/_hdbscan_boruvka.pyx:392 in hdbscan._hdbscan_boruvka.KDTreeBoruvkaAlgorithm.__init__

  File hdbscan/_hdbscan_boruvka.pyx:426 in hdbscan._hdbscan_boruvka.KDTreeBoruvkaAlgorithm._compute_bounds

  File ~/miniconda3/envs/spyderenv/lib/python3.9/site-packages/joblib/parallel.py:1098 in __call__
    self.retrieve()

  File ~/miniconda3/envs/spyderenv/lib/python3.9/site-packages/joblib/parallel.py:975 in retrieve
    self._output.extend(job.get(timeout=self.timeout))

  File ~/miniconda3/envs/spyderenv/lib/python3.9/site-packages/joblib/_parallel_backends.py:567 in wrap_future_result
    return future.result(timeout=timeout)

  File ~/miniconda3/envs/spyderenv/lib/python3.9/concurrent/futures/_base.py:446 in result
    return self.__get_result()

  File ~/miniconda3/envs/spyderenv/lib/python3.9/concurrent/futures/_base.py:391 in __get_result
    raise self._exception

TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.

The exit codes of the workers are {EXIT(1)}

**Comment by jsirois** [comment]
Circling back to the OP, Pex grew a `--venv` execution mode a few years ago and that solves the problem it had with this library. I've updated https://github.com/pantsbuild/pex/issues/675 to reflect this.
