### ISSUE TITLE
Could not pickle the task to send it to the workers.

### ISSUE THREAD

**Issue by sngoel** [joblib/joblib#867]
I tried using this specific chunk of code and ran into the following error. I have tried looking up a way to fix it and can't seem to figure it out. 

`param_grid = dict(criterion = ['gini', 'entropy'],
                  max_depth = max_depth,
                  max_features = ['auto', 'sqrt', 'log2', None],
                  min_impurity_decrease = [0.00001, 0.0001, 0.001, 0.01, 0.1],
                  min_samples_split = min_samples_split,
                  min_samples_leaf = min_samples_leaf)

print('DecisionTree Classifier')
dtc_grid_search = GridSearchCV(dtc, param_grid, scoring = 'accuracy', n_jobs = -1, cv = kfold, verbose = 1)
dtc_grid_result = dtc_grid_search.fit(X, Y)`

The Code was working when I had this param_grid as far as I remember:
`param_grid = dict(max_depth = [2, 5, 10, 20, 30],,
                               min_samples_split = [2, 4, 6, 8, 10],
                               min_samples_leaf = [0.10, 0.25, 0.50, 1, 2, 4])`

`---------------------------------------------------------------------------
_RemoteTraceback                          Traceback (most recent call last)
_RemoteTraceback: 
"""
Traceback (most recent call last):
  File "D:\Anaconda3\lib\site-packages\sklearn\externals\joblib\externals\loky\backend\queues.py", line 150, in _feed
    obj_ = dumps(obj, reducers=reducers)
  File "D:\Anaconda3\lib\site-packages\sklearn\externals\joblib\externals\loky\backend\reduction.py", line 243, in dumps
    dump(obj, buf, reducers=reducers, protocol=protocol)
  File "D:\Anaconda3\lib\site-packages\sklearn\externals\joblib\externals\loky\backend\reduction.py", line 236, in dump
    _LokyPickler(file, reducers=reducers, protocol=protocol).dump(obj)
  File "D:\Anaconda3\lib\site-packages\sklearn\externals\joblib\externals\cloudpickle\cloudpickle.py", line 284, in dump
    return Pickler.dump(self, obj)
  File "D:\Anaconda3\lib\pickle.py", line 437, in dump
    self.save(obj)
  File "D:\Anaconda3\lib\pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "D:\Anaconda3\lib\pickle.py", line 662, in save_reduce
    save(state)
  File "D:\Anaconda3\lib\pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "D:\Anaconda3\lib\site-packages\dill\_dill.py", line 902, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "D:\Anaconda3\lib\pickle.py", line 856, in save_dict
    self._batch_setitems(obj.items())
  File "D:\Anaconda3\lib\pickle.py", line 882, in _batch_setitems
    save(v)
  File "D:\Anaconda3\lib\pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "D:\Anaconda3\lib\pickle.py", line 662, in save_reduce
    save(state)
  File "D:\Anaconda3\lib\pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "D:\Anaconda3\lib\site-packages\dill\_dill.py", line 902, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "D:\Anaconda3\lib\pickle.py", line 856, in save_dict
    self._batch_setitems(obj.items())
  File "D:\Anaconda3\lib\pickle.py", line 887, in _batch_setitems
    save(v)
  File "D:\Anaconda3\lib\pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "D:\Anaconda3\lib\pickle.py", line 662, in save_reduce
    save(state)
  File "D:\Anaconda3\lib\pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "D:\Anaconda3\lib\site-packages\dill\_dill.py", line 902, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "D:\Anaconda3\lib\pickle.py", line 856, in save_dict
    self._batch_setitems(obj.items())
  File "D:\Anaconda3\lib\pickle.py", line 882, in _batch_setitems
    save(v)
  File "D:\Anaconda3\lib\pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "D:\Anaconda3\lib\pickle.py", line 816, in save_list
    self._batch_appends(obj)
  File "D:\Anaconda3\lib\pickle.py", line 843, in _batch_appends
    save(tmp[0])
  File "D:\Anaconda3\lib\pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "D:\Anaconda3\lib\pickle.py", line 771, in save_tuple
    save(element)
  File "D:\Anaconda3\lib\pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "D:\Anaconda3\lib\pickle.py", line 771, in save_tuple
    save(element)
  File "D:\Anaconda3\lib\pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "D:\Anaconda3\lib\pickle.py", line 662, in save_reduce
    save(state)
  File "D:\Anaconda3\lib\pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "D:\Anaconda3\lib\site-packages\dill\_dill.py", line 902, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "D:\Anaconda3\lib\pickle.py", line 856, in save_dict
    self._batch_setitems(obj.items())
  File "D:\Anaconda3\lib\pickle.py", line 882, in _batch_setitems
    save(v)
  File "D:\Anaconda3\lib\pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "D:\Anaconda3\lib\pickle.py", line 662, in save_reduce
    save(state)
  File "D:\Anaconda3\lib\pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "D:\Anaconda3\lib\pickle.py", line 786, in save_tuple
    save(element)
  File "D:\Anaconda3\lib\pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "D:\Anaconda3\lib\pickle.py", line 816, in save_list
    self._batch_appends(obj)
  File "D:\Anaconda3\lib\pickle.py", line 843, in _batch_appends
    save(tmp[0])
  File "D:\Anaconda3\lib\pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "D:\Anaconda3\lib\pickle.py", line 638, in save_reduce
    save(args)
  File "D:\Anaconda3\lib\pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "D:\Anaconda3\lib\pickle.py", line 771, in save_tuple
    save(element)
  File "D:\Anaconda3\lib\pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "D:\Anaconda3\lib\site-packages\dill\_dill.py", line 902, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "D:\Anaconda3\lib\pickle.py", line 856, in save_dict
    self._batch_setitems(obj.items())
  File "D:\Anaconda3\lib\pickle.py", line 882, in _batch_setitems
    save(v)
  File "D:\Anaconda3\lib\pickle.py", line 510, in save
    rv = reduce(obj)
  File "D:\Anaconda3\lib\site-packages\sklearn\externals\joblib\_memmapping_reducer.py", line 339, in __call__
    for dumped_filename in dump(a, filename):
  File "D:\Anaconda3\lib\site-packages\sklearn\externals\joblib\numpy_pickle.py", line 502, in dump
    NumpyPickler(f, protocol=protocol).dump(value)
  File "D:\Anaconda3\lib\pickle.py", line 437, in dump
    self.save(obj)
  File "D:\Anaconda3\lib\site-packages\sklearn\externals\joblib\numpy_pickle.py", line 289, in save
    wrapper.write_array(obj, self)
  File "D:\Anaconda3\lib\site-packages\sklearn\externals\joblib\numpy_pickle.py", line 104, in write_array
    pickler.file_handle.write(chunk.tostring('C'))
OSError: [Errno 28] No space left on device
"""

The above exception was the direct cause of the following exception:

PicklingError                             Traceback (most recent call last)
<ipython-input-8-9704539d1262> in <module>
     12 print('DecisionTree Classifier')
     13 dtc_grid_search = GridSearchCV(dtc, param_grid, scoring = 'accuracy', n_jobs = -1, cv = kfold, verbose = 1)
---> 14 dtc_grid_result = dtc_grid_search.fit(X, Y)
     15 dtc_predict = dtc_grid_search.predict(X)
     16 dtc_predict_proba = pd.DataFrame(dtc_grid_search.predict_proba(X))

D:\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py in fit(self, X, y, groups, **fit_params)
    720                 return results_container[0]
    721 
--> 722             self._run_search(evaluate_candidates)
    723 
    724         results = results_container[0]

D:\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py in _run_search(self, evaluate_candidates)
   1189     def _run_search(self, evaluate_candidates):
   1190         """Search all candidates in param_grid"""
-> 1191         evaluate_candidates(ParameterGrid(self.param_grid))
   1192 
   1193 

D:\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py in evaluate_candidates(candidate_params)
    709                                for parameters, (train, test)
    710                                in product(candidate_params,
--> 711                                           cv.split(X, y, groups)))
    712 
    713                 all_candidate_params.extend(candidate_params)

D:\Anaconda3\lib\site-packages\sklearn\externals\joblib\parallel.py in __call__(self, iterable)
    928 
    929             with self._backend.retrieval_context():
--> 930                 self.retrieve()
    931             # Make sure that we get a last message telling us we are done
    932             elapsed_time = time.time() - self._start_time

D:\Anaconda3\lib\site-packages\sklearn\externals\joblib\parallel.py in retrieve(self)
    831             try:
    832                 if getattr(self._backend, 'supports_timeout', False):
--> 833                     self._output.extend(job.get(timeout=self.timeout))
    834                 else:
    835                     self._output.extend(job.get())

D:\Anaconda3\lib\site-packages\sklearn\externals\joblib\_parallel_backends.py in wrap_future_result(future, timeout)
    519         AsyncResults.get from multiprocessing."""
    520         try:
--> 521             return future.result(timeout=timeout)
    522         except LokyTimeoutError:
    523             raise TimeoutError()

D:\Anaconda3\lib\concurrent\futures\_base.py in result(self, timeout)
    423                 raise CancelledError()
    424             elif self._state == FINISHED:
--> 425                 return self.__get_result()
    426 
    427             self._condition.wait(timeout)

D:\Anaconda3\lib\concurrent\futures\_base.py in __get_result(self)
    382     def __get_result(self):
    383         if self._exception:
--> 384             raise self._exception
    385         else:
    386             return self._result`

**Comment by GaelVaroquaux** [comment]
> File "D:\Anaconda3\lib\site-packages\sklearn\externals\joblib\numpy_pickle.py",
> line 104, in write_array
> pickler.file_handle.write(chunk.tostring('C'))
> OSError: [Errno 28] No space left on device

I think that your problem lies here: you do not have enough space on the
disk to store intermediate results.

**Comment by sngoel** [comment]
@GaelVaroquaux is there a way to calculate how much disk space is required and if not a way to change the drive for storing those intermediate results
