### ISSUE TITLE
worker stopping due to "timeout or by a memory leak.", 

### ISSUE THREAD

**Issue by Krzysiaczek99** [joblib/joblib#869]
In my system when i run latest joblib '0.13.2' worker sometimes stop to work - see below

```
/usr/anaconda3/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py:706: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  "timeout or by a memory leak.", UserWarning

```
and additional information

```
Exception in thread QueueFeederThread:
Traceback (most recent call last):
  File "/usr/anaconda3/lib/python3.7/site-packages/joblib/externals/loky/backend/queues.py", line 150, in _feed
    obj_ = dumps(obj, reducers=reducers)
  File "/usr/anaconda3/lib/python3.7/site-packages/joblib/externals/loky/backend/reduction.py", line 243, in dumps
    dump(obj, buf, reducers=reducers, protocol=protocol)
  File "/usr/anaconda3/lib/python3.7/site-packages/joblib/externals/loky/backend/reduction.py", line 236, in dump
    _LokyPickler(file, reducers=reducers, protocol=protocol).dump(obj)
  File "/usr/anaconda3/lib/python3.7/site-packages/joblib/externals/cloudpickle/cloudpickle.py", line 267, in dump
    return Pickler.dump(self, obj)
  File "/usr/anaconda3/lib/python3.7/pickle.py", line 437, in dump
    self.save(obj)
  File "/usr/anaconda3/lib/python3.7/pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/anaconda3/lib/python3.7/pickle.py", line 662, in save_reduce
    save(state)
  File "/usr/anaconda3/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/anaconda3/lib/python3.7/pickle.py", line 856, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/anaconda3/lib/python3.7/pickle.py", line 882, in _batch_setitems
    save(v)
  File "/usr/anaconda3/lib/python3.7/pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/anaconda3/lib/python3.7/pickle.py", line 662, in save_reduce
    save(state)
  File "/usr/anaconda3/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/anaconda3/lib/python3.7/pickle.py", line 856, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/anaconda3/lib/python3.7/pickle.py", line 887, in _batch_setitems
    save(v)
  File "/usr/anaconda3/lib/python3.7/pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/anaconda3/lib/python3.7/pickle.py", line 662, in save_reduce
    save(state)
  File "/usr/anaconda3/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/anaconda3/lib/python3.7/pickle.py", line 856, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/anaconda3/lib/python3.7/pickle.py", line 882, in _batch_setitems
    save(v)
  File "/usr/anaconda3/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/anaconda3/lib/python3.7/pickle.py", line 816, in save_list
    self._batch_appends(obj)
  File "/usr/anaconda3/lib/python3.7/pickle.py", line 843, in _batch_appends
    save(tmp[0])
  File "/usr/anaconda3/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/anaconda3/lib/python3.7/pickle.py", line 771, in save_tuple
    save(element)
  File "/usr/anaconda3/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/anaconda3/lib/python3.7/site-packages/joblib/externals/cloudpickle/cloudpickle.py", line 395, in save_function
    self.save_function_tuple(obj)
  File "/usr/anaconda3/lib/python3.7/site-packages/joblib/externals/cloudpickle/cloudpickle.py", line 594, in save_function_tuple
    save(state)
  File "/usr/anaconda3/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/anaconda3/lib/python3.7/pickle.py", line 856, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/anaconda3/lib/python3.7/pickle.py", line 882, in _batch_setitems
    save(v)
  File "/usr/anaconda3/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/anaconda3/lib/python3.7/pickle.py", line 856, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/anaconda3/lib/python3.7/pickle.py", line 882, in _batch_setitems
    save(v)
  File "/usr/anaconda3/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/anaconda3/lib/python3.7/pickle.py", line 856, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/anaconda3/lib/python3.7/pickle.py", line 882, in _batch_setitems
    save(v)
  File "/usr/anaconda3/lib/python3.7/pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/anaconda3/lib/python3.7/pickle.py", line 662, in save_reduce
    save(state)
  File "/usr/anaconda3/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/anaconda3/lib/python3.7/pickle.py", line 856, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/anaconda3/lib/python3.7/pickle.py", line 882, in _batch_setitems
    save(v)
  File "/usr/anaconda3/lib/python3.7/pickle.py", line 510, in save
    rv = reduce(obj)
  File "/usr/anaconda3/lib/python3.7/site-packages/joblib/_memmapping_reducer.py", line 340, in __call__
    os.chmod(dumped_filename, FILE_PERMISSIONS)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/shm/joblib_memmapping_folder_23182_2390848912/23182-140373532612424-8910857d38334ce3b2f3d6b5942addf4.pkl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/anaconda3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/anaconda3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/anaconda3/lib/python3.7/site-packages/joblib/externals/loky/backend/queues.py", line 175, in _feed
    onerror(e, obj)
  File "/usr/anaconda3/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 310, in _on_queue_feeder_error
    self.thread_wakeup.wakeup()
  File "/usr/anaconda3/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 155, in wakeup
    self._writer.send_bytes(b"")
  File "/usr/anaconda3/lib/python3.7/multiprocessing/connection.py", line 183, in send_bytes
    self._check_closed()
  File "/usr/anaconda3/lib/python3.7/multiprocessing/connection.py", line 136, in _check_closed
    raise OSError("handle is closed")
OSError: handle is closed
```

**Comment by ogrisel** [comment]
Note: we need a loky release + revendor or unvendor loky to get this actually fixed in joblib.
