### ISSUE TITLE
Error with GridSearchCV with n_jobs>1 on MacOS

### ISSUE THREAD

**Issue by GiuseppeLaurenza** [joblib/joblib#908]
#### Description
Using GridSearchCV with Jupiter notebook cause  a TerminatedWorkerError and no result.
```python
from sklearn import datasets
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier

digits = datasets.load_digits()
n_samples = len(digits.images)
X = digits.images.reshape((n_samples, -1))
y = digits.target
max_depth = list(range(10,30,10))
max_depth.append(None)
rf_params = [{"max_depth": max_depth},
             {"min_samples_split":list(range(10,30,10))},
             {"min_samples_leaf":list(range(1,2))},
             {"max_features":["sqrt","log2"]},  # edited by @ogrisel to remove the now invalid "auto" option
             {"bootstrap":[True, False]}]

scoring = ['accuracy', 'precision_macro']
clf = GridSearchCV(RandomForestClassifier(), rf_params, scoring=scoring, refit='accuracy', cv=5, n_jobs=2)
clf.fit(X, y)
```

in the console of Jupiter I found this error
```python
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'joblib'
/Users/giuseppe/.pyenv/versions/jupyter3/bin/python: Error while finding module specification for 'joblib.externals.loky.backend.popen_loky_posix' (ModuleNotFoundError: No module named 'joblib')
/Users/giuseppe/.pyenv/versions/jupyter3/bin/python: Error while finding module specification for 'joblib.externals.loky.backend.popen_loky_posix' (ModuleNotFoundError: No module named 'joblib')
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'joblib'
```
Looking at #849  I understood that there are some problem with "Loki" backend, so I tried to change the backend for the scikit-learn library using their funciton

```python
    parallel_backend('threading'):
```
and now the code works. So the bug is related to "Loki" implementation on macOS

**Comment by ogrisel** [comment]
Unfortunately I cannot reproduce this problem.

**Comment by lesteve** [comment]
Let's close this one. If someone manages to reproduce, please share a stand-alone snippet, without one, there is not much we can do ...
