### ISSUE TITLE
Joblib fails at importing dataframe, only imports header

### ISSUE THREAD

**Issue by tigerhawkvok** [joblib/joblib#918]
Easy to reproduce:

```python
>>> fn = "trainingDataStash-5.pkl"
>>> import joblib
>>> df = joblib.load(fn)
>>> df.head()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'numpy.ndarray' object has no attribute 'head'
>>> from sklearn.externals import joblib
>>> df = joblib.load(fn)
>>> df.head()
# Prints out dataframe
```

The version from `sklearn.externals` returns `joblib.__version__` of `'0.11'`; the native version returns `'0.13.2'`.

**Comment by pierreglaser** [comment]
I can't reproduce because I don't have your pickle file `"trainingDataStash-5.pkl"`. Can you also provide the steps to create it ?

**Comment by tigerhawkvok** [comment]
Here's a sample:

```python
>>> import numpy as np
>>> import pandas as pd
>>> df = pd.DataFrame([{"Column1": 1.1, "Column2": 1.2, "Column3": np.float32(1.3)}, {"Column1": 2.1, "Column2": 2.2, "Column3": np.float32(2.3)}])
>>> df.head()
   Column1  Column2  Column3
0      1.1      1.2      1.3
1      2.1      2.2      2.3
>>> joblib.__version__
'0.11'
>>> joblib.dump(df, "testData.pkl")
['testData.pkl']
>>> dftest = joblib.load("testData.pkl"); dftest.head()
   Column1  Column2  Column3
0      1.1      1.2      1.3
1      2.1      2.2      2.3
>>> import joblib; joblib.__version__
'0.13.2'
>>> dftest = joblib.load("testData.pkl"); dftest.head()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'numpy.ndarray' object has no attribute 'head'
```

[testData.zip](https://github.com/joblib/joblib/files/3448216/testData.zip)

**Comment by tigerhawkvok** [comment]
Checking in @pierreglaser -- were you able to repro with my test case?

**Comment by GaelVaroquaux** [comment]
If I am not wrong, you are saving with one version of joblib and loading with another. This is not expected to work.

I believe that we can close this issue.

Best,

**Comment by tigerhawkvok** [comment]
They're different minor versions @GaelVaroquaux -- a major behaviour like "loading" for a module whose purpose is dumping and loading data should not break across minor versions. This is [part and parcel of semantic versioning](https://semver.org):

>Given a version number MAJOR.MINOR.PATCH, increment the:
>
>MAJOR version when you make incompatible API changes,
>MINOR version when you add functionality in a backwards compatible manner, and
>PATCH version when you make backwards compatible bug fixes.
>Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.

If it's not expected to work, Joblib should not be on major version `0` anymore, and should increment the major version every time it's not expected to work anymore.

**Comment by GaelVaroquaux** [comment]
The semantics of version 0.X is that backward compatibility is not
enforced.

In addition, persistence with joblib dump / load is meant for internal
persistence and has no strong compatibility contract. It is an extension
of the pickle protocol, and comes with the same limitations.
