### ISSUE TITLE
Code using dynamically crafted module fail  (parallel)

### ISSUE THREAD

**Issue by huitredelombre** [joblib/joblib#921]
Hi, 

I am parsing some users source and creating an other module with it. In this crafted module lie the definition of some functions that workers uses. I don't know how exactly work Joblib, but I don't understand why the falling thread (the one than un-serialize) cant import the modules while the original thread can (I imagined that all threads are just forked process). 

Here is the pdb session that show the problem:
```(Pdb) l
170  	            sizeBatch=size//nbCores
171  	            l=[i*sizeBatch for i in range (nbCores)]
172  	            listOfBatch= [(rows[i:i+sizeBatch], fetchResult[i:i+sizeBatch]) for i in l]
173  	
174  	            breakpoint()
175  ->	            result=Parallel(n_jobs=-1, verbose=51, batch_size=size//nbCores)(delayed(self._transformRows)(batch[0], batch[1]) for batch in listOfBatch)

(Pdb) interact
*interactive*
>>> import userTransformModulePreparsed
>>> 
now exiting InteractiveConsole...
(Pdb) c
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done   4 tasks      | elapsed:    0.7s
A probleme ocurred while migrating:


joblib.externals.loky.process_executor._RemoteTraceback: 
'''
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 391, in _process_worker
    call_item = call_queue.get(block=True, timeout=timeout)
  File "/usr/local/lib/python3.7/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
ModuleNotFoundError: No module named 'userTransformModulePreparsed'
'''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/osboxes/stage/inspireDataBase2/migrations/src/session/session.py", line 217, in applyTransforms
    recuperatedRows=self.applyCurrentTransformWhileMonitoringMemory(batchSize)
  File "/home/osboxes/stage/inspireDataBase2/migrations/src/session/session.py", line 125, in applyCurrentTransformWhileMonitoringMemory
    memUsage, trueReturn =memory_profiler.memory_usage(memoryUsageTuple, max_usage=True, retval=True, backend='psutil', interval=0)
  File "/usr/local/lib/python3.7/site-packages/memory_profiler.py", line 336, in memory_usage
    returned = f(*args, **kw)
  File "/home/osboxes/stage/inspireDataBase2/migrations/src/session/session.py", line 163, in applyCurrentTransform
    retTuple=currentSessionTransform.intermediaryTransform.apply(currentSessionTransform.savedData, Session.entryExplorer, Session.outModifier, precedentTransform)
  File "/home/osboxes/stage/inspireDataBase2/migrations/src/transforms/transform.py", line 111, in apply
    resultingRows, deletedRows, numberOfDeletes= self.transformRows(rows, fetchResult, useThreads )
  File "/home/osboxes/stage/inspireDataBase2/migrations/src/transforms/transform.py", line 175, in transformRows
    result=Parallel(n_jobs=-1, verbose=51, batch_size=size//nbCores)(delayed(self._transformRows)(batch[0], batch[1]) for batch in listOfBatch)
  File "/usr/local/lib/python3.7/site-packages/joblib/parallel.py", line 934, in __call__
    self.retrieve()
  File "/usr/local/lib/python3.7/site-packages/joblib/parallel.py", line 833, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/usr/local/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 521, in wrap_future_result
    return future.result(timeout=timeout)
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
joblib.externals.loky.process_executor.BrokenProcessPool: A task has failed to un-serialize. Please ensure that the arguments of the function are all picklable.
```
I am looking for a workaround for this problem. For now I think I am just gonna put the crafted module on the file system before using the parallel call, but I would prefer another solution if this is possible.

**Comment by huitredelombre** [comment]
I just checked and the problem is that in the multiprocessing code, the original thread sys.modules had been lost.

**Comment by pierreglaser** [comment]
Indeed. Here is a reproducer:
```python
import sys
import types

from joblib import Parallel, delayed


mod = types.ModuleType("mod")
sys.modules["mod"] = mod


def f():
    import mod


if __name__ == "__main__":
    print(Parallel(n_jobs=2)(delayed(f)() for i in range(2)))
```

The tricky thing here is the `import` statement hiding a dynamically created module. Is there such a
pattern in your code?

**Comment by hugoboum** [comment]
I have the same problem. I have a algo.py with functions using joblib Parallel and Delayed , including a function calling such functions.
The only solution mentionned above is to manually paste the algo.py in sites-packages folder.
Switching to backend='multiprocessing' has the code running forever for me
