### ISSUE TITLE
Pickling error and possible interference with CloudStack - malformed API call

### ISSUE THREAD

**Issue by 1605200517** [joblib/joblib#949]
For some reason, after execution context of joblib, call to CloudStack in another place gets malformed.

What I am trying to achieve (Python 3.6.8, Ubuntu Linux 18.04.3 LTS):
- for a report, find a set of VM templates (represented by key-value property set dictionaries)
- enrich it by counting corresponding VMs.
What is strange, the problem comes already alone from the parallel looping through the template data.

Relevant code - works well (but not fast enough that's why I'm here) if I uncomment the line with the call to `Parallel`:

```
class Report():
...
    def processInput(self,tpl):
        return tpl  # do nothing for the sake of the example, otherwise enrich data

def makeReport(self, ..)
...
template_assets = CloudmonkeyAsyncBatch(self.cs, profile=profile).query(command=apisearch % keyword)['template']
            print("INFO: process %s templates for filter=%s" % (len(template_assets), keyword))
            template_assets = Parallel(n_jobs=self.num_cores)(delayed(self.processInput)(i) for i in inputs)
            print("AFTER PARALLEL")
            pprint.pprint(template_assets)
            for tpl in template_assets:
                pprint.pprint(tpl)
```
Error output:
```
============================================================================================================= FAILURES ==============================================================================================================
__________________________________________________________________________________________________ TestTemplate.test_find_garbage ___________________________________________________________________________________________________
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/username/.virtualenvs/apache-cs-extensions/lib/python3.6/site-packages/joblib/externals/loky/backend/queues.py", line 150, in _feed
    obj_ = dumps(obj, reducers=reducers)
  File "/home/username/.virtualenvs/apache-cs-extensions/lib/python3.6/site-packages/joblib/externals/loky/backend/reduction.py", line 247, in dumps
    dump(obj, buf, reducers=reducers, protocol=protocol)
  File "/home/username/.virtualenvs/apache-cs-extensions/lib/python3.6/site-packages/joblib/externals/loky/backend/reduction.py", line 240, in dump
    _LokyPickler(file, reducers=reducers, protocol=protocol).dump(obj)
  File "/home/username/.virtualenvs/apache-cs-extensions/lib/python3.6/site-packages/joblib/externals/cloudpickle/cloudpickle.py", line 482, in dump
    return Pickler.dump(self, obj)
  File "/usr/lib/python3.6/pickle.py", line 409, in dump
    self.save(obj)
  File "/usr/lib/python3.6/pickle.py", line 521, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python3.6/pickle.py", line 634, in save_reduce
    save(state)
  File "/usr/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.6/pickle.py", line 821, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.6/pickle.py", line 847, in _batch_setitems
    save(v)
  File "/usr/lib/python3.6/pickle.py", line 521, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python3.6/pickle.py", line 634, in save_reduce
    save(state)
  File "/usr/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.6/pickle.py", line 821, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.6/pickle.py", line 852, in _batch_setitems
    save(v)
  File "/usr/lib/python3.6/pickle.py", line 521, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python3.6/pickle.py", line 634, in save_reduce
    save(state)
  File "/usr/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.6/pickle.py", line 821, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.6/pickle.py", line 847, in _batch_setitems
    save(v)
  File "/usr/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.6/pickle.py", line 781, in save_list
    self._batch_appends(obj)
  File "/usr/lib/python3.6/pickle.py", line 808, in _batch_appends
    save(tmp[0])
  File "/usr/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.6/pickle.py", line 736, in save_tuple
    save(element)
  File "/usr/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/username/.virtualenvs/apache-cs-extensions/lib/python3.6/site-packages/joblib/externals/cloudpickle/cloudpickle.py", line 890, in save_instancemethod
    self.save_reduce(types.MethodType, (obj.__func__, obj.__self__), obj=obj)
  File "/usr/lib/python3.6/pickle.py", line 610, in save_reduce
    save(args)
  File "/usr/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.6/pickle.py", line 736, in save_tuple
    save(element)
  File "/usr/lib/python3.6/pickle.py", line 521, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python3.6/pickle.py", line 634, in save_reduce
    save(state)
  File "/usr/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.6/pickle.py", line 821, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.6/pickle.py", line 847, in _batch_setitems
    save(v)
  File "/usr/lib/python3.6/pickle.py", line 496, in save
    rv = reduce(self.proto)
  File "/home/username/.virtualenvs/apache-cs-extensions/lib/python3.6/site-packages/cs/client.py", line 213, in handler
    return self._request(command, **kwargs)
  File "/home/username/.virtualenvs/apache-cs-extensions/lib/python3.6/site-packages/cs/client.py", line 295, in _request
    data = self._response_value(response, json)
  File "/home/username/.virtualenvs/apache-cs-extensions/lib/python3.6/site-packages/cs/client.py", line 360, in _response_value
    response=response)
cs.client.CloudStackApiException: HTTP 432 response from CloudStack.
cserrorcode 9999: The user is not allowed to request the API command or the API command does not exist
"""

The above exception was the direct cause of the following exception:

self = <tests.test_template_report.TestTemplate testMethod=test_find_garbage>

    def test_find_garbage(self):
    
        # osfilter = ["debian", "centos", "coreos", "ubuntu"]
        osfilter = ["debian10"]
        apisearch = "list templates templatefilter=all isfeatured=false ispublic=true keyword=%s"
    
        filename = "templates-" + random_tag() + ".csv"
>       self.TR.makeReport(osfilter=osfilter, apisearch=apisearch, csv=filename)

tests/test_template_report.py:28: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
csextensions/helpers/template_usage_report.py:48: in makeReport
    template_assets = Parallel(n_jobs=self.num_cores)(delayed(self.processInput)(i) for i in inputs)
../../../.virtualenvs/apache-cs-extensions/lib/python3.6/site-packages/joblib/parallel.py:1016: in __call__
    self.retrieve()
../../../.virtualenvs/apache-cs-extensions/lib/python3.6/site-packages/joblib/parallel.py:908: in retrieve
    self._output.extend(job.get(timeout=self.timeout))
../../../.virtualenvs/apache-cs-extensions/lib/python3.6/site-packages/joblib/_parallel_backends.py:554: in wrap_future_result
    return future.result(timeout=timeout)
/usr/lib/python3.6/concurrent/futures/_base.py:432: in result
    return self.__get_result()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <Future at 0x7fb7d6360550 state=finished raised PicklingError>

    def __get_result(self):
        if self._exception:
>           raise self._exception
E           _pickle.PicklingError: Could not pickle the task to send it to the workers.

/usr/lib/python3.6/concurrent/futures/_base.py:384: PicklingError
```
If I just take out the line with the call to Parallel, the output is the following:

```
..
INFO: process 30 templates for filter=debian10
AFTER PARALLEL
[{'account': ..... # collected template data

```

**Comment by ogrisel** [comment]
The error message is "cserrorcode 9999: The user is not allowed to request the API command or the API command does not exist".

You probably need to pass the right credentials to connect to the HTTP service from the worker process. Maybe that would require to re-authenticate from each parallel call.

However I find it weird that you have an object that requires to do HTTP requests when pickling. It sounds like a weird design.

If the goal to to execute several calls to the service at a time, you don't really need to use subprocesses if the code that you want to execute is thread-safe. Just use `Parallel(n_jobs=4, backend="threading")(...)` to use threads instead of subprocesses. This way you won't have to pickle anything anymore.
